### ISSUE TITLE
Improvements required in delegate search results

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-sdk#1180]
### Actual behaviour
For the `/api/delegates/search` endpoint, the result is an array whose members are alphabetically sorted based on username. for example, if you search for `lisk` with this query:
```
/api/delegates/search?q=lisk
```
you receive an array starting with a delegate object with username `amazinglisk.com` but vividly the closest result is `liska` which starts with the given substring and has the minimum length of suffix.

The above result is retrieved from testnet explorer.

And it's far worst when you search for `zen` which is an already existing delegate (in mainnet) but the first item in result list is `mauroverdekizen`. because alphabetically it's before `zen`.

### The problem
Taking the above behaviour, every client should implement the logic to refine the response to get the intended result.

### Expected behaviour
The result must be sorted based on the degree of similarity of usernames with the given query string. [string-similarity](https://www.npmjs.com/package/string-similarity) is one of the libraries performing such a job.

### Core version
v0.9.x (presently running on testnet and mainnet)

**Comment by shuse2** [comment]
Closing because extending the HTTP API should be done in the custom module / plugin.
