### ISSUE TITLE
Proper and consistent behaviour of collection count around different API endpoints

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#1461]
Currently there is inconsistency among different endpoints to provided collection count. To do more thinking on this topic I am listing use cases for such counts; 

### Total Collection Count 
Entity |  Current Usage | Probable Use Case  | Implemented 
--- | --- | --- | ---
Transactions | No | No | No
Blocks | No |  No | No
Delegates | Explorer  to show active and on standby delegates |  No | No
Accounts | No |  No | No
Votes | No |  No | No
Voters | No |  No | No

### Filtered Collection Count
Entity |  Current Usage | Probable Use Case | Implemented 
--- | --- | --- | ---
Transaction | Explorer / Nano (to show total incoming and outgoing transactions) | Wallet / Exchanges  / Third-party apps | Yes
Blocks | Explorer | Pagination | No
Delegates | No | Pagination | No
Accounts | No | Pagination | No
Votes | Explorer | Pagination | No
Voters | Explorer | Pagination | No

As per above summary, the most common use case is the pagination. Which can be implemented without total count with Previous<>Next approach. 

We need to think/discuss/brainstorm on this topic further to come up with consistent approach of providing count of collection. 

1. Either we implement it across all collections
2. Or remove it from existing implementations

**Comment by nazarhussain** [comment]
One way for implementation is to provide Estimated Count

https://github.com/LiskHQ/lisk/pull/1436#issuecomment-361650085

**IT DON'T PROVIDE ACCURATE DATA BUT CAN BE A WORKAROUND TO PROBLEM**

**Comment by nazarhussain** [comment]
@diego-G @karmacoma @willclarktech @slaweet @reyraa Please add/update the issue your feedback to this issue.

**Comment by willclarktech** [comment]
Also @Tosch110

**Comment by Tosch110** [comment]
I am totally in favor of having counts together in the API response for all the cases you have listed. It helps on many levels, finding out how to handle the data that is received. I like the accurate count more than the estimated, even though it requires more time. I think a viable option is to have a default with serving the count on the response but you can turn it off with a variable like `&count=false` depending what the default would be.

**Comment by willclarktech** [comment]
Alternatively, we could provide no count by default, a fast but inaccurate count with `count=true` and a slow but accurate count with `count=true&accurateCount=true` or something like that.

**Comment by slaweet** [comment]
I'd vote for no counts by default and enabling them with `count=true`, to be fast by default. But the other way (counts on by default) is fine, too.

**Comment by diego-G** [comment]
I add @MichalTuleja to the discussion.

**Comment by lsilvs** [comment]
I like the idea of having no count by default and using `count=true` to get the count value but in this case (using `count=true`) I reckon it should return the accurate count. If one wants to get an inaccurate count for performance reasons use `inaccurateCount=true` instead.

**Comment by shuse2** [comment]
Closing this in favor of #5213
