### ISSUE TITLE
Refactor tests to use chai-as-promised

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-sdk#1558]
### Expected behavior

After closing #1553 we can use chai-as-promised in tests involving promises. Tests which were written prior to including chai-as-promised should be rewritten to make use of this library for cleaner assertions.

### Actual behavior

All existing tests do not use chai-as-promised.

### Which version(s) does this affect? (Environment, OS, etc...)

1.0.0

**Comment by MaciejBaj** [comment]
It will demand a lot of code changes. The idea will be reconsidered after all of the scheduled to move modules will already be extracted from Lisk Core to Lisk Elements. Suspended for now.

**Comment by shuse2** [comment]
Closing since we are moving the Jest, this issue is no longer valid
