### ISSUE TITLE
Equalise to bytea type all the parameters related to publicKey

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk-sdk#1694]
### Expected behavior

All the references to publicKey presented in the database should be stored as the same data type `bytea`.

### Actual behavior

Some of them are as `bytea` , some others are as `varchar(64)`.

### Which version(s) does this affect? (Environment, OS, etc...)
`1.1.0` ?

**Comment by SargeKhan** [comment]
In database, the storage of public keys is as follow:

| Tables | Column name | Data type |
| --- | --- | --- |
| blocks | generatorPublicKey | bytea |
| blocks_list | generatorPublicKey | text |
| forks_stat | delegatePublicKey | bytea |
| full_blocks_list | b_generatorPublicKey | text |
| full_blocks_list | t_senderPublicKey | text |
| full_blocks_list | s_publicKey | text |
| full_blocks_list | m_keysgroup | text |
| full_blocks_list | t_requesterPublicKey | text |
| mem_accounts | publicKey | bytea |
| mem_accounts | secondPublicKey | bytea |
| mem_rounds | delegate (?) | character varying (64) |
| mem_rounds_snapshot | delegate (?) | character varying (64) |
| mem_votes | publicKey | bytea |
| round_rewards | publicKey | bytea |
| signatures | publicKey | bytea |
| trs | senderPublicKey | bytea |
| trs | requesterPublicKey | bytea |
| trs_list | t_senderPublicKey | bytea |
| trs_list | t_recipientPublicKey | bytea |
| votes | votes (Array of votes) | text |

**Comment by SargeKhan** [comment]
@diego-G, can you list the public keys which are stored as varchar(64)?

**Comment by 4miners** [comment]
Closed in favor of https://github.com/LiskHQ/lisk/issues/2314.

**Comment by diego-G** [comment]
Postponed until https://github.com/LiskHQ/lisk/milestone/35 is implemented.

**Comment by shuse2** [comment]
This is no longer relevant after https://github.com/LiskHQ/lips/blob/master/proposals/lip-0027.md
