### ISSUE TITLE
Refactoring Callbacks

### ISSUE THREAD

**Issue by vitaly-t** [LiskHQ/lisk-sdk#1760]
This is to be the parent task for replacing callback logic with promise chains, as well as getting rid of the async module entirely. 

Sub-tasks cannot be listed here beforehand, as they should be based on the scope of changes that will layer callbacks out, with the sanity check approach, as explained below.  

# Sanity Check

In order to avoid composite logic changes, each PR should contain refactoring functions on one level only, i.e. within the same PR you can only refactor functions that do not use other callback functions that need to be refactored also.

This approach enforces that you start with the functions that have no dependency, walking up their dependencies in PR-s that will follow, till no callbacks left on any level.    

# Justification

* Make the code logic consistent, more readable and easier to maintain.
* Make business logic compatible with the promise-based logic of the database layer.
* Make the code compatible with ES6/ES7 native async standards.

**Comment by shuse2** [comment]
As of lisk-sdk/2.2.0, we have removed all callback style from the source code.
We still have callbacks in the tests, but they will be gradually removed while we move to Jest
