### ISSUE TITLE
Reduce the 10sec window a delegate is allowed to forge a block

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk-sdk#1962]
### Expected behavior
Right now, a delegate has a 10sec window to forge his block. that could allow him to forge a block in the last 10ms and broadcast it. Because of the propagation delay in the network, it is most likely that the next forger didn't receive that block yet. That means the next forger forges on the wrong block which will cause a fork. My idea is to reduce the window a forger can forge a block to maybe 5 seconds (or even 3 seconds). This would mean that the block has at least 5 seconds (or 7 seconds) to propagate in the network, before the next delegate forges on it. I assume that would make the network a bit more stable

### Actual behavior
A delegate has 10 seconds to forge the block. If he does it in the last possible moment, there is not enough time to propagate the block in the complete network

### Which version(s) does this affect? (Environment, OS, etc...)
probably every version.

**Comment by webmaster128** [comment]
Thanks Simon for bringing this up! I support the idea.

But let's see what t helps: a malicious forger can always create a block early and send it into the network with a delay such that the trouble you mentioned occurs but the delegate cannot be blamed. However, if a delegate is prevented from forging (e.g. by high system load or by lack of broadhash consensus) this can help to avoid late forging.

**Comment by SargeKhan** [comment]
Hey @simonmorgenthaler, thanks for your input, but I agree with @webmaster128 that this does not solve the real problem. A malicious delegate would still be able to forge block early but broadcast it with a delay causing the next delegate to forge a block with a different previous ID (Or just change application time to match whichever slot it wants). When it comes to problems related to a huge number of transactions and propagation delays, we are actively benchmarking application performance, and looking into academic papers to figure out an elegant solution.

**Comment by shuse2** [comment]
This issue requires protocol change. Also, mostly solved with the BFT implementation https://github.com/LiskHQ/lisk-sdk/issues/3555.
For further discussion, please go to https://research.lisk.io/
