### ISSUE TITLE
Add community provided seed nodes

### ISSUE THREAD

**Issue by hendrikhofstadt** [LiskHQ/lisk-sdk#2000]
### Expected behavior
Lisk Core config should also contain nodes operated by independent instances to guarantee decentralization and prevent a attack in which seed nodes only supply selected peers to fork the network.

### Actual behavior
Lisk Core config only contains seed nodes operated by LiskHQ.

**Comment by webmaster128** [comment]
Is it possible to use domains in the peers.list? I guess it is much easier for a community member to provide long term support of a domain than an ip address.

**Comment by jondubois** [comment]
@webmaster128 Support for domain names in the peers list (config file) was only added in v1.2; so in the meantime we should stick to IPv4 addresses.

The PR is here: https://github.com/LiskHQ/lisk/pull/2325

**Comment by shuse2** [comment]
Closing because seed node is a config, and SDK does not hold the config anymore
