### ISSUE TITLE
Block is always created with the timestamp value of first second of the slot

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk-sdk#2081]
### Expected behavior
Block should be created with the actual timestamp value of the machine.
### Actual behavior
Block is created with timestamp value based on slot window, which means that every node will create a block with timestamp value equal to slotWindow * 10. When it should be: slotWindow * 10 + secondsPassedWithinCurrentSlot. This will give us more information about when the block is actually forged and broadcasted to the network, which nodes are forging on time, which nodes are performing too much work and so on and so forth.
### Steps to reproduce
N/A
### Which version(s) does this affect? (Environment, OS, etc...)
*

**Comment by willclarktech** [comment]
Could this aid fingerprinting of delegates?

**Comment by nazarhussain** [comment]
I like the idea but I believe `timestamp` of the block is when block forging started. Not when block was finalized. 

https://github.com/LiskHQ/lisk/blob/76b0265d8ce4f11f544779f145855953aa9a05da/modules/blocks/process.js#L529-L531

https://github.com/LiskHQ/lisk/blob/76b0265d8ce4f11f544779f145855953aa9a05da/modules/delegates.js#L204-L208

So even if you update this implementation 

https://github.com/LiskHQ/lisk/blob/76b0265d8ce4f11f544779f145855953aa9a05da/helpers/slots.js#L115-L117

I think it will be roughly between 0-1 always.

**Comment by 4miners** [comment]
Please be aware that changing current behavior will result with potential increase of fork ratio when delegate double-forge and other issues.

**Comment by SargeKhan** [comment]
I agree with @4miners, we should delay this to after 1.0.0.

**Comment by shuse2** [comment]
Closing this issue since this is no longer valid
