### ISSUE TITLE
Upgrade Swagger 2.0 to Open API Specification 3.0

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#2146]
### Expected behavior
The latest version of swagger is renamed to `OAS3`. It have plenty of improvements that we can utilized. Specially the multi server definition. 

### Actual behavior
We are using Swagger 2.0 currently. Which is kind of near to obsolete. 

### Steps to Develop 
1. We are using `swagger-node-runner` which does not support OAS3
2. Either we fork and upgrade `swagger-node-runner` to support OAS3
3. Or instead the package `sway` package directory, which is the dependency of `swagger-node-runner` right now. 
4. Upgrade the swagger specification we currently have in `swagger.yml`
5. Update the functional tests (if any change made in endpoints) 

### Which version(s) does this affect? (Environment, OS, etc...)
`1.0.0`

**Comment by nazarhussain** [comment]
@MaciejBaj An underlaying core library still don't support OAS3. So we should wait a bit further to see if its updated, then we will port our APIs.

**Comment by nazarhussain** [comment]
Un-assigning from myself. We will revisit this issue in coming releases and then assign available resource.

**Comment by shuse2** [comment]
Closing this in favor of #5213 , we will not use swagger runner , but the swagger.yaml will be used for documentation purpose.
