### ISSUE TITLE
Why is mem_round flushed twice while finishing a round

### ISSUE THREAD

**Issue by sqfasd** [LiskHQ/lisk-sdk#216]
https://github.com/LiskHQ/lisk/blob/development/modules/round.js#L136
https://github.com/LiskHQ/lisk/blob/development/modules/round.js#L137

```
return this.updateVotes()
            .then(this.updateMissedBlocks)
            .then(this.flushRound)
            .then(this.applyRound)
            .then(this.updateVotes)
            .then(this.flushRound)
            .then(function () {
                private.ticking = false;
                return t;
            });
```

I think the later updateVotes and flushRound can be removed.

**Comment by karmacoma** [comment]
The current procedure is as follows:

- Update votes (from account balances)
- Update delegates which have missed blocks
- Flush the round
- Apply fees, rewards to eligible delegates
- Update votes (from account balances) - _i.e. changed by fees, rewards_
- Flush the round

Which could be changed to something like:

- Update delegates which have missed blocks
- Apply fees, rewards to eligible delegates
- Update votes (from account balances)
- Flush the round

Requires further implementation and testing.

**Comment by karmacoma** [comment]
Should be resolved after: https://github.com/LiskHQ/lisk/issues/543 is closed.

**Comment by karmacoma** [comment]
Closed by: https://github.com/LiskHQ/lisk/pull/597

**Comment by 4miners** [comment]
Need recheck because #597 is reverted.

**Comment by diego-G** [comment]
Should be done after https://github.com/LiskHQ/lisk/issues/1303

**Comment by MaciejBaj** [comment]
Re-opened as the fix was inverted as part of #2420.

**Comment by MaciejBaj** [comment]
Can only be solved after https://github.com/LiskHQ/lisk/issues/2423 is done, which is waiting for the next hard fork as breaking. Suspended for now.

**Comment by shuse2** [comment]
This will be addressed with part of the BFT implementation https://github.com/LiskHQ/lisk-sdk/issues/3555
