### ISSUE TITLE
/api/node/status delegate count

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-sdk#2353]
Is it possible that current delegate count will be added to this endpoint?

**Comment by 4miners** [comment]
We will consider it. For now, to get delegates count you can use `/api/delegates?sort=rank:desc&limit=1` endpoint. Rank of this delegate is equal to total count.

**Comment by shuse2** [comment]
Closing because extending the HTTP API should be done in the custom module / plugin.
