### ISSUE TITLE
Increase limit of transaction pool

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-sdk#2354]
1. Why current limit of transaction pool is limited to only something around 1-1.5k transactions ? I think it should easily be fine to set it to 50-100k, so no transaction will be missed.
2. Is that possible that transaction which received error "Transaction pool is full" has been processed ? I noticed that it can happen and it shouldn't.

**Comment by shuse2** [comment]
With #4841 , we reimplemented the transaction pool. Current default is 4096, but we will change according to the benchmark we do in #4860
