### ISSUE TITLE
Inconsitency with timestamps in API parameters

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk-sdk#2486]
### Expected behavior
API parameters containing timestamps should be consistent across all API endpoints.
### Actual behavior
We have inconsistency with those parameters. Swagger definitions describe `fromTimestamp` and `toTimestamp` as Unix timestamps here:
https://github.com/LiskHQ/lisk/blob/01dc88cc34cc20d88658f6ed8fb4ef827658c868/schema/swagger.yml#L1172-L1183
Also `timestamp` parameter for `transactions` endpoint is described as Unix timestamp here:
https://github.com/LiskHQ/lisk/blob/01dc88cc34cc20d88658f6ed8fb4ef827658c868/schema/swagger.yml#L1258-L1263
This is only true for `/delegates/{address}/forging_statistics` endpoint. For other endpoints (`blocks`, `transactions`) those parameters are accepting Lisk Timestamp format and not Unix timestamp, as described here:
https://github.com/LiskHQ/lisk/blob/01dc88cc34cc20d88658f6ed8fb4ef827658c868/schema/swagger.yml#L46-L50

My recommendation is fixing the descriptions and make `fromTimestamp` and `toTimestamp` of `forging_statistics` accept Lisk Timestamp format. We can add `fromUnixTimestamp` and `toUnixTimestamp` for accepting timestamps in Unix format. This will change the API behavior, so fix should go with the major version.
### Steps to reproduce
N/A
### Which version(s) does this affect? (Environment, OS, etc...)
`>= 1.0.0`

**Comment by 5an1ty** [comment]
Seems like forging_statistics doesn't even takes unix timestamps. It takes JS timestamps. (ms since epoch)

**Comment by MaciejBaj** [comment]
As pointed by @4miners, the change would break the public API. Suspended for now.

**Comment by shuse2** [comment]
Closing this in favor of #5213
