### ISSUE TITLE
Update the schema validation library for better performance

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#2546]
Currently Lisk Core system is heavily relying on schema validation, and is using `json-schema` to define the schema for different components. 

On the implementation side we are using `z-schema` implementation which is found to be very slow compared to these benchmarks. 

https://github.com/ebdrup/json-schema-benchmark

We should consider migrating the `z-schema` to `djv` which is found to be more performant. But first we should check compatibility of our custom formats with `djv`.

### Which version(s) does this affect? (Environment, OS, etc...)
All

**Comment by yatki** [comment]
I would go with ajv library since we are using it in lisk-elements and it also has more userbase with more than 1M+ downloads per week.

**Comment by pablitovicente** [comment]
@nazarhussain 

We depend on sway that currently only supports Z-Schema there is a pull request (check 471, in https://github.com/apigee-127/swagger-tools/pulls) that is not accepted yet - and seems it would not be - for supporting alternative validators only for the request's body. 

Compatibility: 

For using the same library across the Lisk project I did research on `ajv` as suggested previously. Custom formats are defined in a similar way than in Z-schema and it's not a drop-in replacement but compatibility seems pretty good.

Docs for `ajv` can be found in: https://ajv.js.org/#api

**Comment by shuse2** [comment]
For this, we have created @liskhq/lisk-validator, which is wrapper of Ajv with custom format for lisk protocol, so let's put use this library across product

**Comment by shuse2** [comment]
Superseded by #3278
