### ISSUE TITLE
Add an API endpoint to get the balance of an account at a specific unix timestamp

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk-sdk#2559]
### Expected behavior
It would be useful to get the balance of an account at a specific timestamp in the past.
The existing api endpoint `/accounts` could be extended by an additional optional argument `atTimestamp` (or similar)

### Actual behavior
Now it's only possible to get the current balance with `/accounts?address=5726759782318848681L`. To figure out the balance at a time in the past, you have to track all transactions on this account since the beginning and also consider forging rewards and fees if it is a delegate account.

### Steps to reproduce
call `/accounts?address=5726759782318848681L` and try to figure out what it's balance was on 31st of December 2017

### Which version(s) does this affect? (Environment, OS, etc...)
All core versions

**Comment by shuse2** [comment]
Closing this issue since no active plan right now
