### ISSUE TITLE
Remove obsolete code from logic/account

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk-sdk#2708]
### Expected behavior
Especially since https://github.com/LiskHQ/lisk/issues/2620 is closed, logic/account.js contains obsolete code. 

The overall role of logic/account.js is different than the majority of other files within the `logic` directory, which are responsible for validating and processing the transaction of different types. Accounts are stored in additional database tables and aren't going through verify, validate, objectNormalize, apply steps. That's why:

- `objectNormalize` (https://github.com/LiskHQ/lisk/blob/development/logic/account.js#L153) function is not used anywhere and can be removed. 
- `account.schema` (https://github.com/LiskHQ/lisk/blob/development/logic/account.js#L829) can be removed and the fields of accounts get from database can be found in `entities/account.js`. It will be useful especially after planned TypeScript migration.

### Which version(s) does this affect? (Environment, OS, etc...)
`*`

**Comment by shuse2** [comment]
Superseded by #3729
