### ISSUE TITLE
Misleading "delegates_unique" constraint on delegates table

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk-sdk#2746]
### Expected behavior
One way of solving the issue, the simpler one is to rename the SQL query used for counting duplicated entries in delegates table (`sql.countDuplicatedDelegates`) accordingly of what it does - checking if the same transaction adds the same delegates usernames. 

The second, more challenging way is to reconsider the purpose of `delegates_unique` constaint. It doesn't prevent of adding duplicated delegates username entries.

### Actual behavior
Current `unique_delegates` constaint (`ALTER TABLE delegates ADD CONSTRAINT delegates_unique UNIQUE ("username", "transactionId");` is misleading and classifies an entry to `delegates` table as duplicated when the same transactionId resolves to the same delegates username. As a result, the name of the corresponding SQL query of counting duplicated entry is also misleading `sql.countDuplicatedDelegates`. 

It is possible then to have duplicated delegates usernames introduced by different transactions. 

### Which version(s) does this affect? (Environment, OS, etc...)
"*"

**Comment by shuse2** [comment]
We no longer have delegates table, and mem_accounts2delegate does not have this constraints.
