### ISSUE TITLE
Move Lisk-specific transaction types to application-level

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#2780]
### Expected behavior
The `chain` module should only have standard transactions required to run the DPOS system, register the second signature and multisignature accounts:
- type 0
- type 1
- type 2
- type 3
- type 4

All other transaction types i.e. "dapp registration", "dapp in-transfer", dapp out-transfer" are specific only for the Lisk blockchain application platform, therefore should be elevated to the application-level (`lisk/src`). 
- type 5
- type 6
- type 7

Unit Test needs to be implemented, too

### Actual behavior
Currently, all transaction types are part of the `chain` module.

**Comment by MaciejBaj** [comment]
Re-opening, the transactions type 5,6,7 should be in the application-level

**Comment by shuse2** [comment]
DappRegistration needs to be duplicated for now to avoid major release
