### ISSUE TITLE
Limit log history to a certain amount of days

### ISSUE THREAD

**Issue by Korben3** [LiskHQ/lisk-sdk#2790]
Feature request: Limit log history to a certain amount of days

### Expected behavior

lisk.log "should" only store a log of the last n days.

### Actual behavior

By default and left alone, lisk.log grows infinitely. 

### Steps to reproduce

Install and run core, set fileLogLevel to debug and leave the server alone until hard drive is full.

### Reason for request

Several users running core reported that their server logs quickly fill up the hard drive. Which will cause the node to go offline. 

Example:
![image](https://user-images.githubusercontent.com/42899281/51801004-6c2e5700-2238-11e9-8baf-1436af50fd08.png)

There is a solution using logrotate, but the solution to this issue could be greatly simplified for the user by expanding config with the option: logFileHistoryLength.

Example:
![image](https://user-images.githubusercontent.com/42899281/51801210-055e6d00-223b-11e9-8f9b-5dd070793153.png)

**Comment by MaciejBaj** [comment]
Thanks for the idea, @Nazgolze @4miners @fchavant what do you think?

**Comment by shuse2** [comment]
Closing because log rotation should be done at server management level
