### ISSUE TITLE
Storage basic support for virtual fields

### ISSUE THREAD

**Issue by pablitovicente** [LiskHQ/lisk-sdk#2793]
### Expected behavior

It should be possible for Storage Entities to sort by virtual columns (i.e. columns that do not exists in the schema but are the result of calculations between schema columns) and at the same time validate the passed in options

### Actual behavior

This type of columns are supported by Storage Entities but skipping the options validations

### Steps to reproduce

Try to execute GET http://0.0.0.0:4000/api/delegates/?sort=productivity:asc by modifying _getResults in the Accounts Entity making it validate options by calling `this.validateOptions(options);` on that method.

`mocha test/functional/http/get/delegates.js` fails with said changes

### Which version(s) does this affect? (Environment, OS, etc...)

- 1.5.0

**Comment by lsilvs** [comment]
For now it can be achieved by using `addField` like this:
https://github.com/LiskHQ/lisk/commit/1a2ce95efe7a840716586ed789622fbeeb89f31f#diff-bc70035312bfb85210cc0b649605ae8a

**Comment by pablitovicente** [comment]
> For now it can be achieved by using `addField` like this:
> [1a2ce95#diff-bc70035312bfb85210cc0b649605ae8a](https://github.com/LiskHQ/lisk/commit/1a2ce95efe7a840716586ed789622fbeeb89f31f#diff-bc70035312bfb85210cc0b649605ae8a)

The only issue I see with this is that if the behaviour of `addFiled` is changed we don't have a way for ensuring

**Comment by shuse2** [comment]
Closing this for now since we are not planning to extend storage feature now
