### ISSUE TITLE
Implement Max Transaction Fee

### ISSUE THREAD

**Issue by Korben3** [LiskHQ/lisk-sdk#2915]
Feature request: Implement max transaction fee during the "Network Economics" phase.

Proposal:
Looking at a recent event where a transaction was made on another blockchain with a fee larger than was intended by the user. And seeing how future dynamic fees in lisk will allow the user to set their own fee (above the minimum required). I recommend implementing a maximum tx fee of for instance 2 lisk for type 0 transactions. This could be part of the protocol "Replace static fees with dynamic fee system".

Examples of fees gone wrong:
On Feb-19-2019 a transaction was made on the Ethereum blockchain with a fee of 2,100 Ether. Many times higher than required. This resulted in the loss of $308,679 for the user.

In June 2018, Ripple implemented a maximum transaction fee after a user mistakenly burned 100000 XRP in tx fees.

Solution:
Check if the fee for a type 0 transaction is <2 lsk, otherwise prevent the tx from being broadcasted.

**Comment by anagamidev** [comment]
Yeah, I suggest to introduce constraint that transaction size should be greater then fee. It will prevent such mistakes :D

**Comment by stellardynamic** [comment]
> Yeah, I suggest to introduce constraint that transaction size should be greater then fee. It will prevent such mistakes :D

This would create a situation where you could not send a transaction lower than the fee. Sometimes transactions are sent to transact data instead of value in a system like ours and they will want to be able to send one Beddow (Smallest unit in LSK) + Fee transactions to write to the blockchain.

**Comment by shuse2** [comment]
This would require change in protocol.
For protocol related discussion, please go to https://research.lisk.io/
