### ISSUE TITLE
Remove hardcoded 101 and use properties constants.js instead

### ISSUE THREAD

**Issue by michielmulders** [LiskHQ/lisk-sdk#2922]
### Expected behavior
Multiple pieces of code have `101` as `ACTIVE_DELEGATES` constant hardcoded which impacts the calculation of fees et al.

### Steps to reproduce
Change `default/constants.js` or add it to `devnet` `constants.js` to overwrite the default constants.
Tested this with 10 nodes network via `pm2`.

### Problem
Codebase contains too many hardcoded `101` amounts for `ACTIVE_DELEGATES`.
Most important ones: 
- `storage/sql/migrations/updates/20170321001337_create_rounds_fees_table.sql`
- `storage/sql/migrations/updates/20180205000003_create_rounds_rewards_table.sql`
- `framework/src/modules/chain/helpers` -> `delegatesList()` -> `obj.limit = 101` hardcoded.

### Solution
Replace all `101` occurrences with a dynamic `ACTIVE_DELEGATES` constant imported preferably from `global.constants` or `default/constants.js`.

**Comment by michielmulders** [comment]
Comment from sprint meeting: What about hardcoded `101` inside of migration `.sql` files?
We cannot pass constants to this file, for other `.sql` files from entities we can.

On the other side, we don't need to update old migrations or we can remove the `101` limit and make it flexible.

**Comment by michielmulders** [comment]
- `elements/lisk-transactions/src/3_vote_transaction.ts:30` -> We can find `const MAX_VOTE_PER_ACCOUNT = 101;` This is tricky as this is part of elements and we can not flexibily configure this. `101` is part of the protocol but is also configurable which gives this weird situation. In this file, it is correct we can only cast 101 votes for delegates if there are 101 delegates. However, the number of active delegates is configurable so in case you increase or decrease, this number in vote transaction should also be dynamic with the number you set.

**Comment by michielmulders** [comment]
- `elements/lisk-api-client/src/resources/delegates.ts:41` -> Here we try to get the standby delegates for the api client. Offset is set to `101` but should be dynamic, again, it's not possible to dynamically set.

**Comment by michielmulders** [comment]
- `framework/src/modules/chain/migrations/sql/20170319001337_create_indexes.sql:38` -> `CREATE INDEX IF NOT EXISTS "blocks_rounds" ON "blocks" ((CEIL(height / 101::float)::int));` Hard coded 101 in sql file. It's an index for `block_rounds` -> not sure if it is in use still.

**Comment by michielmulders** [comment]
Other potentially affected places:
- `framework/src/modules/chain/migrations/sql/20170321001337_create_rounds_fees_table.sql`
- `framework/src/modules/chain/migrations/sql/20180205000003_create_rounds_rewards_table.sql`
- `framework/src/modules/chain/migrations/sql/20180205000004_apply_round_exception_mainnet.sql`
- `framework/src/modules/chain/rounds/rounds.js:103` -> Establish if the round is finished by checking if the height is equal to 101.
- `framework/src/modules/http_api/schema/swagger.yml` -> Swagger query to retrieve all delegate s has a range set for the `limit` option between 1 and 101.
- `framework/test/jest/integration/specs/modules/chain/app.spec.js` -> Non dymanic tests: looking for 101 (and many more Jest tests related to rounds that need to be implemented check explicitly for 101.
- ---`framework/test/mocha/common/integration/sql/queries_helper.js` and many more places!

Note: We do have a constants, and it is configurable, so in SDK we can pass this dynamic `active_delegates` variable to all functions that require it: `framework/test/jest/integration/utils/configs/config_constants.js`

**Comment by shuse2** [comment]
As of now, there is no hardcoded `101` in the framework chain-module including the query.
Only case in the query is migration, and the table doesn't exist anymore
