### ISSUE TITLE
Application should not start without valid blockchain state

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#2923]
### Expected behavior
The application shouldn't start if the desired blockchain state is not present.
### Actual behavior
The application works even If the database doesn't have required blockchain state(`mem_accounts` in this case)
### Steps to reproduce
1) Start testnet node with snapshot
2) Stop and delete all records from `mem_accounts`
3) Start the application and it works fine without any error.

**Comment by ManuGowda** [comment]
The function called loadBlockchain - even if it fails it continues to start.

**Comment by limiaspasdaniel** [comment]
Just double checked. When the application detects truncated mem tables it resets them and applies the blocks gain. After that, the application continues loading as expected.

Closing.
