### ISSUE TITLE
Refactor Transaction constructor to match specific transaction types consturctor definitions

### ISSUE THREAD

**Issue by limiaspasdaniel** [LiskHQ/lisk-sdk#2926]
### Expected behavior
Transaction.js should present the same constructor definition as the refactored constructor structure on specific transaction types introduced on #2844:
```
constructor({components: {logger, storage, system}, schema})
```

### Actual behavior
Transaction.js presents a non-consistent constructor definition with the new one
https://github.com/LiskHQ/lisk/blob/12e0fdc632fc95aa7a2d25374bad92c5927d4902/framework/src/modules/chain/logic/transaction.js#L50
### Which version(s) does this affect? (Environment, OS, etc...)
1.6

**Comment by shuse2** [comment]
Closing this because `logic/transactions` is replaced by `elements/lisk-transactions`
