### ISSUE TITLE
Remove unwanted old database functions

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#2954]
### Expected behavior
Remove unwanted old database related logic which is no longer required after storage changes.
### Actual behavior
There are few old database logic functions such as
https://github.com/LiskHQ/lisk/blob/ebfc1349419c6263c26b6c6d59cff7b97223e90f/framework/src/modules/chain/logic/transaction.js#L1221
### Which version(s) does this affect? (Environment, OS, etc...)

**Grooming Meeting Notes**
Remove dbRead and storageRead and put it in other blocks logic related file or merge the code.

**Comment by lsilvs** [comment]
It can only be done after https://github.com/LiskHQ/lisk/issues/2424 as `modules.blocks.process.loadBlocksFromPeer` still uses it.

REF.: https://github.com/LiskHQ/lisk/issues/2424#issuecomment-467018480
