### ISSUE TITLE
Add network test scenario to cover broadhash and consensus updates

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#2956]
### Expected behavior
The broadhash should keep changing constantly while the network is moving and delegates are forging.
### Actual behavior
Currently, there are no tests which cover the functionality of broadhash update, if there is a network with the same node version and `101` delegates forging, the height keeps changing constantly, however, the broadhash doesn't change. Since all the nodes have the same broadhash the network continues to work fine even though it's invalid.

**Comment by shuse2** [comment]
Closing this since broadhash is not used in the protocol anymore
