### ISSUE TITLE
Move BlockReward logic to System component

### ISSUE THREAD

**Issue by limiaspasdaniel** [LiskHQ/lisk-sdk#2990]
### Expected behavior
Block reward logic can be moved to System component so other modules can directly use its logic
### Actual behavior
Block reward is currently present in Chain module but it only contains static computation out of constants.

Having the Block Reward logic in Chain module means other modules need to use the channel to request data from it while this could be requested directly from System component.

**Comment by shuse2** [comment]
I think block reward is strictly the logic of chain module 😕

**Comment by diego-G** [comment]
@shuse2 what do you think about extending the system component on chain?

**Comment by shuse2** [comment]
I think block reward is specific to blockchain, and not relating to application or system, so I think it should just be in chain, and if someone else needs reward info, they should ask chain

**Comment by shuse2** [comment]
Closing this because block reward needs to be in the chain module
