### ISSUE TITLE
Group loaderLoaded and loaderSynced actions on Chain module

### ISSUE THREAD

**Issue by limiaspasdaniel** [LiskHQ/lisk-sdk#2993]
### Expected behavior
`loaderLoaded` and `loaderSynced` actions can be grouped together.
There are many ways to do it.
Please refer to the following discussions for more information:
https://github.com/LiskHQ/lisk/pull/2982#discussion_r260464016
https://github.com/LiskHQ/lisk/pull/2982#discussion_r260464608
https://github.com/LiskHQ/lisk/pull/2982#discussion_r260464981
### Actual behavior
`loaderLoaded` and `loaderSynced` are separate actions that are not grouped together.

**Comment by shuse2** [comment]
`loaderLoaded` and `loaderSynced` no longer exists
