### ISSUE TITLE
Rename chain/modules/ folder to chain/submodules/

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk-sdk#3030]
### Expected behavior

Structure is clear and not redundant.

### Actual behavior

The structure of internal modules is redundant and confusing with the general modules located in `framework/src/`

### Which version(s) does this affect? (Environment, OS, etc...)
`1.6.0`

**Comment by diego-G** [comment]
The solution didn't fully cover all cases. We forgot to rename the private variables referring the submodules. For reference:
https://github.com/LiskHQ/lisk/blob/381c91af4726174ae35d49f7f8ad79b5342d8b7e/framework/src/modules/chain/submodules/rounds.js#L28

**Comment by shuse2** [comment]
Superseded by #3616
