### ISSUE TITLE
Uniformise constructors from chain logics

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk-sdk#3072]
### Expected behavior

Every logic is loaded through the same fashion.

### Actual behavior

Only the logic related to transactions are loaded using spread operators and destructuring pattern.

Antipattern : https://github.com/LiskHQ/lisk/blob/381c91af4726174ae35d49f7f8ad79b5342d8b7e/framework/src/modules/chain/logic/account.js#L50

Pattern to follow :
https://github.com/LiskHQ/lisk/blob/381c91af4726174ae35d49f7f8ad79b5342d8b7e/framework/src/modules/chain/logic/transfer.js#L43

**Comment by shuse2** [comment]
Superseded by #3616
