### ISSUE TITLE
Add a new sorting method to the Transactions endpoint

### ISSUE THREAD

**Issue by Korben3** [LiskHQ/lisk-sdk#3095]
### Add a new sorting method

Sorting by timestamp descending does not always show the latest transactions broadcasted to the blockchain.

For example:
`https://testnet.lisk.io/api/transactions?limit=10&offset=0&sort=timestamp%3Adesc`

should show the latest transactions. But since it's easy to fake a timestamp, for instance by changing the computers clock back a few days and then performing a transaction, this sorting method isn't the most reliable.

I recommend adding sorting by **Height** to the available options, since this might be a more reliable method to discover the latest transactions. 

Adding the following options:

_height:asc
height:desc_

**Comment by lsilvs** [comment]
Related issue: https://github.com/LiskHQ/lisk/issues/1891

**Comment by shuse2** [comment]
Closing because extending the HTTP API should be done at the custom module/plugin level.
