### ISSUE TITLE
Fix randomly failing tests 

### ISSUE THREAD

**Issue by limiaspasdaniel** [LiskHQ/lisk-sdk#3096]
### Expected behavior
No tests should fail
### Actual behavior
Currently, a series of failures when running tests appear inconsistently and as a consequence they slow down PR review and development.
Those failures are mostly related to the environment where they are being executed (Jenkins), as most of them present no failures in local environment.

**Functional WS tests:**
- [ ] `Exceeded time limit to wait for confirmations`: it happens randomly. See [here](https://jenkins.lisk.io/job/lisk-core/view/change-requests/job/PR-3057/
)

**Unit tests**
- [x] #3131 `Cache Disabled`: it happens randomly too and it´s probably due to Cache tests not being atomic and disabling or enabling cache get overlapped. See [here](https://jenkins.lisk.io/job/lisk-core/view/change-requests/job/PR-3046/)
- [ ] `Uncaught TypeError: Cannot read property 'height' of undefined` https://github.com/LiskHQ/lisk/blob/949b41e80eb30992385f90b5b59bf7006b388a73/framework/test/mocha/unit/modules/chain/submodules/loader.js#L488
- [ ] `BatchError: deadlock detected` https://github.com/LiskHQ/lisk/blob/f0d132869df23642e0300a2c30bb2817ad07db12/framework/test/mocha/unit/modules/chain/components/storage/entitites/transaction.js#L75
- [ ] #XXXX Remove usage of [test/mocha/common/application.js](https://github.com/LiskHQ/lisk/blob/development/framework/test/mocha/common/application.js) across unit tests
- [ ] #XXXX Remove usage of [test/mocha/common/modules_loader.js](https://github.com/LiskHQ/lisk/blob/development/framework/test/mocha/common/modules_loader.js) across unit tests

**Integration tests**
- [ ] #3240 Mocha integration test suite execution does not finish properly
- [ ] #XXXX  Replace usage of [test/mocha/common/application.js](https://github.com/LiskHQ/lisk/blob/development/framework/test/mocha/common/application.js) across integration tests

Note: I will be adding more as soon as I collect them. 
### Steps to reproduce
Run all tests
### Which version(s) does this affect? (Environment, OS, etc...)
`*`

**Comment by shuse2** [comment]
Closing this issue because unit, integration and functional tests are stable now
