### ISSUE TITLE
Missing ability to register new actions/events after a channel is created

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk-sdk#3097]
### Expected behavior

It doesn't exist the possibility to register/add new actions or events to a channel if this one was already created. 

### Actual behavior

Application state participates in the general channel as a single source of truth. It means modules dispatch its state, subscribe to changes & need the possibility to invoke to request the state. Then Application state needs the channel in 3 ways:
- to receive dispatch actions
- to publish information to passive subscribers
- but also to offer its state in a reactive way through a getter

For reference: https://github.com/LiskHQ/lisk/issues/3036

### Which version(s) does this affect? (Environment, OS, etc...)
`+1.6`

**Comment by nazarhussain** [comment]
Events/Actions are defined as part of module definition, not the channels. And what you are suggesting is to redefine module definition runtime, which should not happen in any case.
