### ISSUE TITLE
Move api related cache handler to httpApi module

### ISSUE THREAD

**Issue by lsilvs** [LiskHQ/lisk-sdk#3111]
### Expected behavior
Expect to httpApi module to handle its own cache action

### Actual behavior
Currently, Chain module is responsible to clear httpApi module.
See: https://github.com/LiskHQ/lisk/blob/2e4b36f5843af15017744a2cb173c64b9998e286/framework/src/modules/chain/submodules/blocks.js#L245

### Which version(s) does this affect? (Environment, OS, etc...)
1.6

**Comment by lsilvs** [comment]
Have this https://github.com/LiskHQ/lisk/issues/2403 in mind when moving the clear cache to httpApi module

**Comment by pablitovicente** [comment]
Will be fixed by #3513

**Comment by shuse2** [comment]
Superseded by #3513
