### ISSUE TITLE
Reduce rebuild time by using PostgreSQL custom dump format

### ISSUE THREAD

**Issue by hendrikhofstadt** [LiskHQ/lisk-sdk#3112]
Currently the snapshot function is dumping the database to pure SQL and then gzipping.

The PostgreSQL tool `pg_dump` also supports a custom format (`-Fc`) which is compressed by default and that can be restored utilizing multiple threads using `pg_restore` with the `- j <Threads>` argument.

Snapshotting:
https://github.com/LiskHQ/lisk-scripts/blob/1bb2a9245e1b6a0d09bd96c8c811a025a24c6b98/packaged/lisk_snapshot.sh#L208

would become 
```
pg_dump -Fc "$TARGET_DB_NAME" -f "$BACKUP_FULLPATH"
``` 

Restoring:
https://github.com/LiskHQ/lisk-scripts/blob/1bb2a9245e1b6a0d09bd96c8c811a025a24c6b98/packaged/lisk.sh#L149

would become 
```
if ! gunzip -fcq  | pg_restore -Fc -j <numcpu*2> -U "$DB_USER" -d "$DB_NAME" "$DB_SNAPSHOT" >> "$SH_LOG_FILE" 2>&1; then
``` 

The format is incompatible with the old one but rebuild speed went down by ~50% in my tests.

I'd be happy to discuss whether this could be worth the breaking change in favor of faster node rebuilding

**Comment by shuse2** [comment]
It has been handled in https://github.com/LiskHQ/lisk-core
