### ISSUE TITLE
Integration test `ChildProcessChannel` class and `InMemoryChannel` class

### ISSUE THREAD

**Issue by lsilvs** [LiskHQ/lisk-sdk#3118]
### Expected behavior

The `ChildProcessChannel` class and `InMemoryChannel` class should be covered by integration tests.

### Actual behavior

There is no such test coverage.

## Acceptance Criteria

- ~~Add Integration tests for InMemoryChannel #3186~~
- Add Integration tests for ChildProcessChannel

### Additional Information
#3674 needs to be addressed to write the integration test

**Comment by yatki** [comment]
Blocked by #3674

**Comment by yatki** [comment]
All work done on #3675 will be kept in https://github.com/LiskHQ/lisk-sdk/tree/3118-integration-test-ChildProcessChannel branch. So when issue #3674 was resolved, maybe we can reuse some of the code here. @lsilvs
