### ISSUE TITLE
Rename -s/--snapshot cli parameter

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk-sdk#3119]
### Expected behavior
Since https://github.com/LiskHQ/lisk/issues/3109 this option is no longer used for snapshotting purposes:
https://github.com/LiskHQ/lisk/blob/2e4b36f5843af15017744a2cb173c64b9998e286/framework/src/modules/chain/helpers/config.js#L73
It should be renamed to `-v`/-`--verify` (maybe not because `-v` is usually used for `--version`) or `-r`/`--rebuild`, etc. Also the documentation needs to be updated in the relevant places.
### Actual behavior
The parameter name (`-s`/`--snapshot`) not reflecting its purpose.
### Steps to reproduce
N/A
### Which version(s) does this affect? (Environment, OS, etc...)
`>1.5.0`

**Comment by MaciejBaj** [comment]
`r/ --rebuild` sounds good.

**Comment by MaciejBaj** [comment]
Removing the `-s/ --snapshot` parameter can break the tools relying on this param. Therefore, this issue should be moved to Lisk Core 2.0.0, together with other breaking changes (i.e. #3104).
