### ISSUE TITLE
Benchmark the framework parameters to suggest its values

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk-sdk#3151]
### Expected behavior
For all of the exposed parameters by `chain` module suggest the minimum and maximum values. Design the best-fitting benchmarking methods for:
- REWARDS
   - MILESTONES
   - OFFSET (Start rewards at first block of the second round)
   - DISTANCE (Distance between each milestone)
- MAX_TRANSACTIONS_PER_BLOCK
- EPOCH_TIME
- BLOCK_TIME (currently defined in slots.interval)

### Which version(s) does this affect? (Environment, OS, etc...)
`1.6.0`

**Comment by nazarhussain** [comment]
@MaciejBaj @shuse2 

Had tested following constants or genesis configurations and these works well.

**EPOCH_TIME**
- Changed it to "2009-06-15T13:45:30Z"
- Started the app
- Call `curl localhost:4000/api/blocks`
- The timestamp of the firs block returned `311214370`
- If you test the value by `moment.unix(moment("2009-06-15T13:45:30Z").unix()+ 311214370).format()` 
- It returns the `2019-04-26T16:11:40+02:00` clock time which is the accurately correct for that block.

**Comment by nazarhussain** [comment]
To benchmark the right min/max range for `MAX_TRANSACTIONS_PER_BLOCK` and `BLOCK_TIME` is very difficult for the reason that both are co-related to each other. As well different physical parameters can effect the performance as well. 

I suggest to do this after benchmarking of the new transaction processing.

**Comment by MaciejBaj** [comment]
We should be able to give "healthy" suggestions on the value ranges.

**Comment by pablitovicente** [comment]
Limits on values for BLOCK_TIME and MAX_TRANSACTIONS_PER_BLOCK (these values were obtained by trying against a single node (node specs: 1GB Ram, 1CPU core, 25 GB HDD and later confirmed against a network consisting of 50 nodes distributed in 10 different regions) it’s important to note that these values do not represent limits in the SDK but recommended values for the current defaults for other configuration properties and objects configurations used by the SDK and lisk-core. 


| BLOCK_TIME | MAX_TRANSACTIONS_PER_BLOCK| 
| -------------| ------------------------------------| 
| 2 | 25| 
| 4 | 50| 
| 6 | 75| 
| 8 | 110| 
| 10 | 150| 


- With all this configurations blocks were generated correctly, on time and filling all blocks with the configured number of transactions. 

- We construct the TransactionPool object using some default limits that impact the behaviour of transactions per block; for example we’re using `releaseLimit` for setting the value of `bundleLimit` which by default is 25 so this makes the transaction pool to move transactions between jobs slower (if we set this value higher we can move more transactions per job for example maybe this value should be the same as MAX_TRANSACTIONS_PER_BLOCK)
- We should investigate what values will be best for _receivedTransactionsProcessingInterval, _validatedTransactionsProcessingInterval and _verifiedTransactionsProcessingInterval as they command the interval for the transaction pool timers and there’s some interaction between this timers and BLOCK_TIME (I think that tuning this values could potentially improve the current values noted above )
- By increasing the value of `bundleLimit` to 1000 I was able to get reliable results with up to 400 transactions per block (with 10 seconds blocks) although hitting PSQL pretty hard.
- During the tests the memory usage was in the 300 MB limit  and cpu usage around 40% when using 10 seconds block time and 150 transactions per block. 
- PSQL seems to be our biggest show stopper to go faster than 400 transactions every 10 seconds.
- As a side note a 400 transfer transactions block is 200KB when stringified (this value might be of interest for P2P) 


### How the tests were performed? 

- BLOCK_TIME was set to 1 and MAX_TRANSACTIONS_PER_BLOCK to 25 and then the values were incremented checking that the blocks generated were correct (all possible tx filled, correct block time) for each change of one of the values 5000 transactions were sent to the node. 
- After this initial values were established I tested the configuration of BLOCK_TIME=10 and MAX_TRANSACTIONS_PER_BLOCK=150 using the QA tools for deploying a 50 nodes network. All tests passed successfully. 
- The script used for sending the transactions can be found in https://gist.github.com/pablitovicente/99f663e5e59980cd1abde1996a5c0c8a
