### ISSUE TITLE
Change the API response to return an array of errors

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk-sdk#3152]
### Expected behavior
The API response should return all the errors encountered when processing a request. Therefore, the structure of the API response should be:
```
{
   "code": 404,
   "error": [{
      message: "<ERROR_MESSAGE>"
   },
   {
      ...
   }]
}
```
### Actual behavior
The structure of API response in case of an error is not very extensible. It contains only one property with the name `message` which is of type string. In cases where there are multiple errors, it is impossible to return all the errors in this format. The current structure of the API response in case of an error is as follow:
```
{
   "code": 404,
   "message": "<ERROR_MESSAGE>"
}
```
 
### Which version(s) does this affect? (Environment, OS, etc...)
1.7

**Comment by pablitovicente** [comment]
We should also check `processUnconfirmedTransaction()` in transaction pool as it's only returning one error

**Comment by pablitovicente** [comment]
We should fix any tests tagged with `[feature/improve_transactions_processing_efficiency]` on this PR or if scope goes to much up then we should split in different issue blocked by this one

**Comment by mitsujutsu** [comment]
> We should also check `processUnconfirmedTransaction()` in transaction pool 

Yes that's fixed in the branch I'm working on. I am in the process of updating tests.

**Comment by pablitovicente** [comment]
@mitsujutsu be aware that PR #3268 fixes integration and some unit tests so you should check that branch (is about to be merged tough)

**Comment by mitsujutsu** [comment]
@pablitovicente Ok I am currently working on functional tests so that should not be an issue.
