### ISSUE TITLE
Integrate constants.js into chain-specific configuration

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk-sdk#3159]
### Expected behavior
Integrate constants.js into the [configuration of "chain" module](https://github.com/LiskHQ/lisk/blob/2976-distributed-env-variables/framework/src/modules/chain/defaults/config.js). Eventually, there will be only one configuration, specific for the network. 

The good place for the network specific constants is "chain" module, as it's the "chain" module that is responsible for validating and adapting the blockchain behaviour. 

For every entry of constants.js introduce the validation confirming into the `Ajv` standard:

```
activeDelegates: {
 type: 'integer',
 minimum: 1,
 maximum: 101,
 default: 101,
},
```
Introduce the acceptable minimum and maximum values gradually, basing on the proper benchmarkin #3151.

### Actual behavior
The network configuration is now contained in `constants.js` file, different for each network. 

### Which version(s) does this affect? (Environment, OS, etc...)
`*`

**Comment by shuse2** [comment]
Closed by #3275
