### ISSUE TITLE
Create new package.json in application-level

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk-sdk#3172]
### Expected behavior
Split the `/package.json` two packages - one on the application-level, the second one on the framework-level. 

`version`, `minVersion`, `protocolVersion` belong to the application-level package.json and should be passed directly from the package.json file into the framework configuration in `src/` folder. 

Split `dependencies` and `devDependencies` accordingly. 

### Actual behavior
The application-level entry file `src/index.js` defines the variable:
```
const packageInfo = {
	version: packageJSON.version,
	minVersion: packageJSON.lisk.minVersion,
	protocolVersion: packageJSON.lisk.protocolVersion,
};
```

### Which version(s) does this affect? (Environment, OS, etc...)
`1.6.0`

**Comment by shuse2** [comment]
Completed with the product merge.
