### ISSUE TITLE
Application don't cleanup when exit running npm start

### ISSUE THREAD

**Issue by lsilvs** [LiskHQ/lisk-sdk#3210]
### Expected behavior
I expect the application to do the cleanup when running with `npm start`

### Actual behavior
When starting the application with `node src/index.js`, it properly does the cleanup when it exits.
But when starting the application with `npm start`, it doesn't.

### Steps to reproduce
Starting the application with `npm start`.
Exit the application with `ctrl + C`

### Which version(s) does this affect? (Environment, OS, etc...)
1.6

**Comment by shuse2** [comment]
Application is no longer started with `npm start` so this would not be a problem
