### ISSUE TITLE
PM2 does not show CPU and Memory usage when using `npm start`

### ISSUE THREAD

**Issue by lsilvs** [LiskHQ/lisk-sdk#3221]
### Expected behavior
I expect to be able to start PM2 with `pm2 start npm -- start -- -n testnet` and have CPU and memory usage properly displayed with `pm2 monit`

### Actual behavior
When PM2 starts the application using `npm start` it forks the application and its monitoring tool looks for npm pid instead of application pid.

### Steps to reproduce
`pm2 start npm -- start -- -n testnet`
`pm2 monit`

### Which version(s) does this affect? (Environment, OS, etc...)
1.6

**Comment by lsilvs** [comment]
REF.: https://github.com/LiskHQ/lisk/issues/3215

**Comment by shuse2** [comment]
Application is no longer started with `npm start` so this would not be a problem
