### ISSUE TITLE
Provide ability to extend state with custom properties

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk-sdk#3222]
### Expected behavior

Create a method to extend the application state with custom properties without overwriting the existing ones.

```js
state = { 
 modules: { 
   unicorns: 'xx', 
   zebras: 'yy' ,
  }
}
```

### Actual behavior
> 
> let state = {
... modules: {
..... unicorns: 'xx'
..... }}
> 
> newExtensionForState = {
... modules: {
..... zebras: 'yy'}}
{ modules: { zebras: 'yy' } }
>
> Object.assign(state, newExtensionForState)
{ modules: { zebras: 'yy' } }
> 
> 
> state
{ modules: { zebras: 'yy' } }

### Which version(s) does this affect? (Environment, OS, etc...)
`1.7`

**Comment by shuse2** [comment]
Closing because P2P network feature is not exposed now
