### ISSUE TITLE
Revise list of actions in the chain module

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#3230]
### Expected behavior
There must be unique and limited list of actions for the chain module. We must revisit all the actions and see how much we can optimize. 

### Actual behavior

Some actions got redundant in behaviour and some of which are not used. 

### Which version(s) does this affect? (Environment, OS, etc...)
1.7

**Comment by nazarhussain** [comment]
Already identified list of actions to removed: 

https://github.com/LiskHQ/lisk/pull/2937#discussion_r270744992
1. getLastConsensus 
2. loaderLoaded
3. loaderSyncing
4. loaderLoaded
5. getForgersKeyPairs
6. getForgersPublicKeys

**Comment by limiaspasdaniel** [comment]
The following actions are no longer available in `development` branch:
`getLastConsensus` 
`loaderLoaded`
`loaderSyncing`
`loaderLoaded`
`getForgersKeyPairs`

The only one available from the initial list is `getForgersPublicKeys`, but I am not sure why it's meant to be removed. @nazarhussain could you elaborate?
