### ISSUE TITLE
Correct use of rejects across Jest test suite

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk-sdk#3262]
### Expected behavior

https://github.com/LiskHQ/lisk/pull/3247/commits/ed10f642cd7bb601123859c2dd07272e60a07d6c

### Actual behavior
We don't always write `await` when using `rejects`.
https://github.com/LiskHQ/lisk/blob/390a9e6f9f614ab49d8c4cee055726da6c3cd110/framework/test/jest/specs/unit/controller/bus.spec.js#L63

### Steps to reproduce

We receive false positives after changing the above to
```
	// Act && Assert
	expect(
	     bus.registerChannel(moduleAlias, [], actions)
	).rejects.toBeInstanceOf('###### ---> MYERROR###');
```

### Which version(s) does this affect? (Environment, OS, etc...)
`1.6`

**Comment by shuse2** [comment]
This issue have been resolved while moving to jest, and now eslint rule is on place
