### ISSUE TITLE
Allow some modules to publish any event

### ISSUE THREAD

**Issue by jondubois** [LiskHQ/lisk-sdk#3263]
### Expected behavior

Sometimes a module may want to publish events which it only knows at runtime.
For example, the Network module should be able to publish any kind of event on the node (depending on messages it receives from the network).

### Actual behavior

Currently, the module needs to specify the complete list of events that it exposes during boot. This can be useful in terms of imposing constraints for some modules but it's too restrictive for modules like the network module. There should be a way for a module to specify that it can publish any event (maybe a wildcard `'*'`?).

In the `feature/create_network_module` branch, the constraint was disabled completely so that any module can publish any event.

**Comment by diego-G** [comment]
@shuse2 @jondubois possibly duplication of https://github.com/LiskHQ/lisk/issues/3097

**Comment by shuse2** [comment]
Related to this https://github.com/LiskHQ/lisk-sdk/pull/3465#discussion_r279243590
It has to be re-restricted with the above possibility and security.

Also, affects #3154

**Comment by nazarhussain** [comment]
Any module can invoke action or subscribe to events of others, but in any case it should not be able to publish events of others, by impersonating or any other case.

**Comment by jondubois** [comment]
@nazarhussain Even with custom events, modules cannot impersonate each other because the prefix of each event will still contain the module name (e.g. the `postBlock` event published by the `chain` module is `chain:postBlock`). I agree with this aspect completely.

If the Network module publishes an event which originates from a Chain module which running on a remote peer, it might look like `network:chain:postBlock`. In this case, we still know that it's the network module which is publishing the event.

>> When you are not defining the events first, then how subscribers aware of those and use those?

Module developers need to read a module's documentation to find out what the payload of each event will look like; so they can also find out what events are available on the module from the same documentation.

On the pub/sub implementation side, there is no need to specify or restrict what channels a module can publish to. You can have dynamic channels where any client can subscribe or publish to any channel (whether it exists or not) - This is the approach used by Redis, SocketCluster, Faye, and most pub/sub systems and pub/sub SaaS services. The principle of creating channels/topics statically (from the beginning) is more related to Message Queues; systems like RabbitMQ, NSQ, MQTT and Kafka. But MQs are not suitable for our use case; they are too heavy; especially for cross-process communication on the same node.

**Comment by jondubois** [comment]
Some possible approaches (this may change):

Subscribing to a remote event (from a remote module on a peer):

```js
// Subscribe to the postBlock event from a remote chain module
channel.subscribe('network:chain:postBlock', handlerFunction);

// Do not allow subscribing to all remote events on all modules.
// force the user to subscribe to specific events on specific remote modules.
```

OR

```js
// Subscribe to the postBlock event from a remote chain module
channel.subscribe('network:receive:chain:postBlock', handlerFunction);

// Subscribe to all remote events from all remote modules
channel.subscribe('network:receive', handlerFunction);
```

OR

```js
// Subscribe to the postBlock event from a remote chain module
channel.subscribe('network:receive::chain:postBlock', handlerFunction);

// Subscribe to all remote events from all remote modules
channel.subscribe('network:receive', handlerFunction);
```

OR

```js
// Subscribe to the postBlock event from a remote chain module
channel.subscribe('network:receive/chain:postBlock', handlerFunction);

// Subscribe to all remote events from all remote modules
channel.subscribe('network:receive', handlerFunction);
```

Publishing remote event to a peer:

```js
channel.invoke('network:publish', {
  event: 'chain:postBlock',
  data: {}
});
```

**Comment by shuse2** [comment]
With #5603 , this is no longer relevant
