### ISSUE TITLE
Restructure jest folder

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#3282]
### Expected behavior
We should be able to run the test files in any IDE or command line without knowing or setting special configuration. 

### Actual behavior

Right command lines failed to run jest tests. If you run `npx jest my_test_file.spec.js` it fails because some of the configuration for jest is compulsory to specify.  Same happens with any IDE. 

Jest is able to detect any `jest.config.js` in directory hierarchy automatically. So its preferable to move `unit`, `functional` and `integration` config files to specific test directories rather than managing separate directory of config. 

### Steps to reproduce

We must be able to run 

```
npx jest framework/test/jest/specs/unit/controller/application.spec.js
```

### Which version(s) does this affect? (Environment, OS, etc...)
1.7

**Comment by yatki** [comment]
Unfortunately jest cli doesn't find the jest.config.js automatically. WebStorm was detecting it automatically.

However, I've restructured the folder structure to still allow WebStorm and other IDEs to detect jest.config.js automatically. 

We will continue to use npm commands as before.
