### ISSUE TITLE
Transaction timestamps should be checked against slotNumber

### ISSUE THREAD

**Issue by mitsujutsu** [LiskHQ/lisk-sdk#3297]
### Expected behavior

Transaction time stamps should be checked against `slots.getSlotNumber` for validity.

### Actual behavior

In current `feature/improve_transaction_efficiency` branch, transaction time stamp is not checked.

relevant development branch code in `logic/transaction`: line 697

```
if (slots.getSlotNumber(transaction.timestamp) > slots.getSlotNumber()) {      
return setImmediate(
				cb,
				'Invalid transaction timestamp. Timestamp is in the future'
);                
```
### Which version(s) does this affect? (Environment, OS, etc...)
1.7.0

**Comment by shuse2** [comment]
Closed by #3287
