### ISSUE TITLE
Promisified dns lookup returns inconsistant results

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#3303]
### Expected behavior
Create a new promise and avoid `util.promisify`

### Actual behavior
`Promisifying` `dns.lookup` works inconsistantly.
`const { address } = await lookupPromise(peer, { family: 4 });` is giving inconsistant results, root cause couldn't be found.

**Comment by shuse2** [comment]
Sincee dnsPromise is still experimental feature, we should wait to use them
