### ISSUE TITLE
Issues with Next Forging Turn (/api/delegates/forgers)

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk-sdk#3304]
### Expected behavior
The api call /delegates/forgers should return always the correct order (ordered by 'nextSlot') of the current delegates list, to get a consistent value when a delegate will forge its next block

### Actual behavior
The api call /delegates/forgers returns inconsistent values. It is not ordered by 'nextSlot'. Well, sometimes it seems to be ordered correctly, but not always.

### Steps to reproduce
call /delegates/forgers multiple times and compare the returned list

### Which version(s) does this affect? (Environment, OS, etc...)
1.6.0-rc.3

**Comment by ManuGowda** [comment]
@michielmulders please ensure you add the rite tests covering the issue raised, currently we do not have any tests to identify the issues raised, thanks.

**Comment by michielmulders** [comment]
@simonmorgenthaler Thanks a lot for reporting the bug. The custom sort function was indeed not behaving as expected. PR with tests covering this behavior will be created later today. Happy days! :)
