### ISSUE TITLE
Expose a sample Genesis Block from Framework

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#3308]
### Expected behavior

SDK user must be able to start the blockchain application with the minimum code required. 

```js
const {Application, sampleGenesisBlock } = require('lisk-framework');

const app = new Application('myApp', sampleGenesisBlock);

app.run().then(console.info).catch(console.error);
```

To make this possible we should expose one genesis block as part of the framework, which everyone can start with easily. 

### Actual behavior

Right now the genesis block is the required data field to start any application. And we are not shipping any sample genesis block for user. So he had to go to one extra step to first create a genesis block to start any application. 

### Which version(s) does this affect? (Environment, OS, etc...)
1.7

**Comment by sdrpa** [comment]
A sample code on how to generate a genesis block would be great, so that users can customise/modify it to their needs.
