### ISSUE TITLE
Move exceptions.js file to be part of config.json to simplify config structure

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#3309]
### Expected behavior

There should be only one configuration file for one network. 

### Actual behavior

Right now we have one file `exceptions.js` for each network, which actually is part of configurations at key `modules.chain.exceptions`. Using the following code; 

https://github.com/LiskHQ/lisk/blob/c75591a52864d408828c29d410859902c5bffd13/src/index.js#L79

To avoid any confusion we should merge the exception file into actual `config.json` for each network and remove the above code line. This will simplify the config structure and help to understand it easily that exceptions are actually options for chain module. 

### Which version(s) does this affect? (Environment, OS, etc...)

1.7

**Comment by pablitovicente** [comment]
@SargeKhan is working in exceptions now @nazarhussain so you might want to check with him before going ahead with this one

**Comment by nazarhussain** [comment]
The change here has no relation to how we process the exceptions. Its just the matter of keeping a separate file.

**Comment by nazarhussain** [comment]
Although the change was straight forward but just noticed one edge case. The exceptions file is a `js` file and config file is `json` file. In exceptions file we have some keys as integers while in JSON we can't have keys as integers. 

So if we move the exceptions to config file, we have to update the usage of exceptions accordingly.

**Comment by nazarhussain** [comment]
@shuse2  There are a lot of comments in the exception files

https://github.com/LiskHQ/lisk-sdk/blob/265f1cf934d87000248ef572157c668041bf6543/lisk/config/mainnet/exceptions.js#L22-L25

And these are useful for our reference. If I move exceptions to `config.json` we have to remove these comments, as JSON files don't allow comments. On the other hand I don't see it right to convert `config.json` to a script file. It behaves same for the NodeJS environment, but not compatible for other utilities and linux command lines e.g. `cat config.json | jq .`. Its a data file and should remain as data file. 

So what direction we should now? 

1. Move the exceptions to config.json file and remove the comments?
2. Keep the exceptions file as it is?

@MaciejBaj The issue was intended by your directions to have only one config file for each network. So your opinion is also required on it.

**Comment by shuse2** [comment]
After discussion, we will convert it to JSON, but document the details in README
