### ISSUE TITLE
Fix piping transaction:create:second-passphrase to transaction:broadcast error

### ISSUE THREAD

**Issue by mitsuaki-u** [LiskHQ/lisk-sdk#3316]
### Description

Since v2.0 `lisk transaction:create:second-passphrase --passphrase="pass:first pass" --second-passphrase="pass:second pass" | lisk transaction:broadcast` returns inconsitent results (sometimes `No Transaction was provided).  

### Steps to Reproduce

1. npm i lisk-commander@v2.0.0
2. lisk transaction:create:second-passphrase --passphrase="pass:xxx" --second-passphrase="pass:xxx" | lisk transaction:broadcast

**Expected behavior:** 

It should pipe transaction to broadcast

**Actual behavior:** 

Not piped

**Reproduces how often:**  90%

### Versions
v2.0.0

**Comment by S3x0r** [comment]
Stop playing and drinking coffee, get rid of dependence, do it your way and fix it eventually

**Comment by shuse2** [comment]
Closing since second passphrase has been removed
