### ISSUE TITLE
Shows MaxListenersExceeded warning in tests when adding event listener on process

### ISSUE THREAD

**Issue by mitsuaki-u** [LiskHQ/lisk-sdk#3320]
### Description

When adding event listener (to handle errors) directly on process or process.stdin/stdout in `/src/base.js`, mocha tests show warning: 

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 
11 error listeners added. 
Use emitter.setMaxListeners() to increase limit 
```

Possibly related to https://github.com/mochajs/mocha/issues/117

**Reproduces how often:**
Always

### Versions

2.0-

**Comment by shuse2** [comment]
Closing because currently it does not appear
