### ISSUE TITLE
Second attempt at second signature registration message is not precise enough

### ISSUE THREAD

**Issue by pablitovicente** [LiskHQ/lisk-sdk#3327]
### Expected behavior

For 1.6 an attempt at registering a second signature a second time would yield `sender already has second signature enabled`

### Actual behavior

Attempting to register a second signature a second time yields `Transaction: <transactionID here> failed at .signSignature: Missing signSignature`

### Steps to reproduce

Try to register a 2nd signature a second time

### Which version(s) does this affect? (Environment, OS, etc...)
`feature/improve_transaction_processing_efficiency`

**Comment by michielmulders** [comment]
Issue will be closed, read below why...

[Snippet](https://gist.github.com/michielmulders/79d7d99ac077720c2544c6fd62068201) used for testing.
Or, use integration tests for `second signature`:
```bash
npm run mocha:integration --prefix ./framework test/mocha/integration/transactions/1_second_signature/1_1_second_signature.js
```

The reported issue here is not really incorrect. 

Assume the user has already registered a second pass, and tries to register this pass again.
In the old logic, all checks for different transaction types were being applied in one file.

The new logic proposed by the feature branch `improve_transaction_processing_efficiency` uses a first line of basic transaction checks you can find at `elements/lisk-transactions/src/base_transaction.ts:275` (`apply` function).

Next, the `applyAsset` function at line `290` checks if the user has already registered a second pass, if yes, it adds a new (correct) error object to the list. This is the result when trying to register a second pass twice on the feature branch.

![second signature feature](https://i.ibb.co/ctbQC4c/image.png)

When we try the same on `development` or `1.6.0`, we get the following.
![second signature development](https://i.ibb.co/sgqBMck/image-1.png)

**Why does the feature branch add this extra error?**
First, we perform normal checks. One of these checks verifies if the sender account has a second pass enabled for this account. If yes, it expects a `signSignature` field to be present on the transaction. However, the user is trying to register a second pass again, so it expects a signSignature but doesn't get this. In short, the corrects errors are thrown.

**Possible fix we came up with?**
Switching the validation logic -> avoid
Add a check for this edge case and remove the first error from the `errors` array -> not improving code quality

_Open for further discussion._

**Comment by mitsujutsu** [comment]
@michielmulders I concur

**Comment by shuse2** [comment]
Also, we have changed to return all the errors, so I think it's good.
Closing this issue
