### ISSUE TITLE
Add missing unit test for transactions library

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#3331]
### Expected behavior
All the newly created function should be covered by the unit test.
Also, all of the transaction above type 8 have to use the protocol spec to ensure the validity

### Actual behavior
There are missing unit tests

### Which version(s) does this affect? (Environment, OS, etc...)
2.1.0-alpha.2

**Comment by pablitovicente** [comment]
At least type 9, 10 and 11 are not using the protocol spec fixtures so need to update those.

**Comment by pablitovicente** [comment]
We are going to change transaction type 11 in the coming months so we're not going to update to protocol-specs scenarios in this iteration.
