### ISSUE TITLE
Update peer discovery messages in response to fetching peers list

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#3333]
### Description

Update method that selects and returns its peer list in response to `list` rpc call that will be renamed to `getPeers`. As of now, it selects 100 peers and returns it. But according to , it should be implemented as per below.

`getPeers` RPC is used to query a connected peer for a list of known IP addresses of Lisk nodes. In response, the peer sends a message containing up to 1000 IP addresses. 
The IP addresses are selected as follows:

- Let `n` be a random number in the interval,` n = [min(1000, #known peers *0.25), min(1000, #known peers*0.5)]`
- where known peers are any peers in the `triedPeers` or `newPeers` collection

- `select max(n,min(100, #known peers))` addresses at random from all known peers, i.e., peers in the `triedPeers` or `newPeers` collection

- The list returned is shuffled for security reasons

Note: IP address of peers that declared that their IP address should not be advertised (see advertiseAddress flag defined in the next subsection) are never returned.

**Comment by shuse2** [comment]
It should not remove the current Endpoint `list`, but it should add `getPeers` endpoint
