### ISSUE TITLE
Enforce limits on the size of inbound messages/requests in P2P

### ISSUE THREAD

**Issue by jondubois** [LiskHQ/lisk-sdk#3335]
### Expected behavior

Messages and requests which are too large should be rejected to prevent DoS against nodes. Ideally, this value should be configurable.

This is particularly important when dealing with peer info. Right now there is no limit as to how big the custom `options` object in `P2PDiscoveredPeerInfo` can be; so peers could just spam us with lots of data inside the options object to fill up our memory (since we keep a list of `P2PDiscoveredPeerInfo`).

### Actual behavior

There is no size limit on messages and requests.

**Comment by diego-G** [comment]
Solution does not work after merge development into last state of 2.3 version.
