### ISSUE TITLE
Managing fixed white black lists of peers from configuration

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#3339]
### Description

In Phase 2 of lisk-p2p from [LIP0004](https://github.com/LiskHQ/lips/blob/master/proposals/lip-0004.md), we will have different peers list that user can set in the configuration when a node starts. This will include the following types of peer's lists:
- **Blacklist Peer** : 
  - [X] If a peer is blacklisted, then no incoming or outgoing connection is ever established to that peer
  - [x] preference above all 8267deae671eb69073ba3389f3288ef09c4dc717 65773121f78417cbaa8512d6c1a02f0811b47583

- **Fixedlist Peer** : 
  - [x] a permanent outgoing connection is established to that peer (if an incoming connection does not already exist) e2109230b8dec7ae83912a56e4c531c4b34e0100
  - [x] ~no subject to shuffle~ -> to be addressed by #3347
  - [x] ~triggers reconnect if error (using `exponential backoff` functionality from SocketCluster)~ Not needed
  - [x] ~manually removing from the configuration if connection failures after agreed period~ Not wanted
  - [x] 4 at most 1edabab3db7282b21595d381e699dc3f486f1a99
  - [x] users should be discouraged from declaring fixed peers 97527f4689defc1033ada44ac2c7d99331d6b596
  - [x] ~exclusively connect to fixed peers + `advertiseAddress=false` + no shuffling (**exchanges optional feature**)~ -> to be addressed by #3661
  - [x] preference over _whitelisted_ attribute 65773121f78417cbaa8512d6c1a02f0811b47583

- **Whitelist Peer** : a whitelisted peer is treated the same way as a normal peer with some exceptions
  - [x] add to the triedPeers collection at the beginning a3dfb046778f184843b201fcb184328e3724e0f8
  - [x] never removed from the triedPeers collection 1726f47d293b5f6517cae1f939803ba621c02ab5
  - [x] never banned by the banning mechanism 483074b5fbc35d04f12c38e60bd72b1342df1c03
  - [x] incoming connection from a whitelisted peer is never evicted and has precedence over any other (even over an existing one)
  - [x] users should be warned in the configuration file to only declare trustworthy peers 97527f4689defc1033ada44ac2c7d99331d6b596

**Comment by diego-G** [comment]
We underestimated the complex of the issue. Next time we should create the checklist before estimating the points and decide how to tackle it. Ideally we should have fragmented it into several issues.
