### ISSUE TITLE
Redundant rules in tslint.json and missing comments

### ISSUE THREAD

**Issue by yatki** [LiskHQ/lisk-sdk#3341]
### Expected behavior
To have the tslint.json file as clean and small as possible. Also having comments to explain why some certain rules were edited.

### Actual behavior
Right now we have some redundant rules like `no-delete`, `no-let` which are enabled by default. https://github.com/LiskHQ/lisk-elements/blob/development/tslint.json#L13 

Also tslint.json file is a [JSON5](https://json5.org/) file so we can add comments to clarify why we are disabling some of the rules. Because in time, even the developer who disables the rules forgets why..

**Comment by shuse2** [comment]
Closing this since it has been cleaned up for now
