### ISSUE TITLE
Update peer selection (for connection) mechanism for selection of multiple peers

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#3346]
### Description

According to [LIP0004](https://github.com/LiskHQ/lips/blob/master/proposals/lip-0004.md), Update peer selection mechanism based on `newPeers` and `triedPeers` list and consider fixedlist and blacklist peers while selecting any peer. 
Also, peer selection must take banned peers into account while selecting peers.

**Comment by jondubois** [comment]
This line of the LIP is particularly relevant to this issue: `Select a peer from collection triedPeers with probability r and a peer from the collection newPeers with probability 1-r. The peer in each of the collections is selected uniformly at random.`
