### ISSUE TITLE
Add feature to disconnect peers as part of shuffling algorithm

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#3347]
### Description

In lisk-p2p phase2 from [LIP0004](https://github.com/LiskHQ/lips/blob/master/proposals/lip-0004.md), we are going to implement peer shuffling on outgoing connections. 

Over the course of 30 blocks (approximately 5 minutes), one outgoing connection is chosen uniformly at random and terminated at a random time during the interval of 30 blocks.

We need to consider fixed and black peers list here to make sure we don't connect with `blacklist` peer and we don't drop connection with `fixedlist` peer.

**Comment by jondubois** [comment]
Based on a few discussions with @diego-G, it was decided to separate peer managements into three concerns:

- Populating the connected peer list up to a desired size.
- Removing (and disconnecting) peers from the connected peer list (e.g. as part of banning, shuffling or failed internet connection).
- Preventing invalid peers from connecting.
