### ISSUE TITLE
Add browser field in package.json

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#3348]
### Description
Browser field should be re-introduced in the `package.json`

With the correct setup, `browserify` reads the browser field and it fails, but with `--no-browser-field, --no-bf`, it doesn't replace the node variable correct.

related: https://github.com/browserify/browserify/pull/1826

#### Remarks
- Check in browser
- Check in Lisk-Hub
- Check in Lisk-Mobile

**Comment by JesusTheHun** [comment]
Is this issue status up to date ?

**Comment by shuse2** [comment]
The referred PR in the browserify is not merged yet, so I asked the question there as well.
In the mean time, in which environment are you having the problem with? @JesusTheHun
