### ISSUE TITLE
Clean up the "cleanup" method in chain module

### ISSUE THREAD

**Issue by yatki** [LiskHQ/lisk-sdk#3368]
### Expected behavior
We should make use of the `code` variable after defining it or get rid of it, if it's not needed.
### Actual behavior
code argument provided to `cleanup` method were never used in the method after it's defined.

https://github.com/LiskHQ/lisk-sdk/blob/45eaf5ce75179c35a12068b2987acb66d3cd8164/framework/src/modules/chain/chain.js#L288-L297

**Comment by ishantiw** [comment]
@nazarhussain What is the purpose of `code` field [chain.js#L288-L297](https://github.com/LiskHQ/lisk-sdk/blob/45eaf5ce75179c35a12068b2987acb66d3cd8164/framework/src/modules/chain/chain.js#L288-L297), I see we are just assigning value to incoming code in the `cleanUp(code, error)` method of modules but we are not using it anywhere. Maybe we can simply use `cleanUp(error)`?
