### ISSUE TITLE
Move network tests from framework to lisk-core

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#3374]
### Expected behavior
Move required `network` tests from https://github.com/LiskHQ/lisk-sdk/tree/development/framework/test/mocha/network to https://github.com/LiskHQ/lisk-core/tree/master/qa
### Actual behavior
The `network` tests under `framework` are not relevant to `SDK` anymore.

**Comment by shuse2** [comment]
We have decided to keep the network test in the framework level
