### ISSUE TITLE
Vote transaction was not checking for null username value 

### ISSUE THREAD

**Issue by mitsujutsu** [LiskHQ/lisk-sdk#3377]
### Expected behavior

For type 3 vote transaction in `elements`, `apply` stage should disallow voting for non-delegates. 

### Actual behavior

`apply` was checking for `undefined` and `empty string` but not `null`.

### Steps to reproduce

Run functional test for `POST` `/3.votes`

**Comment by shuse2** [comment]
Closed by #3287
