### ISSUE TITLE
Use the matcher pattern for the module replacement

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk-sdk#3390]
### Expected behavior

For implementing the protocol change, there will be the [matcher design pattern](https://github.com/LiskHQ/lisk-sdk/issues/3251) used to disable transaction types (for now types 6 and 7).

It is possible to expand this idea further and introduce for replacing the modules in runtime.

The [application state](#3036) is already implemented - the matcher condition can rely on the height or any other property from the global state of the application while a module is being replaced. For the duration of the module replacement, the whole application should halt and the global state of the application cannot change.

Consider the following example as a final result of the implementation:
```
const ChainModuleV2 = require('lisk-chain@2.0.0');
const ChainModuleV1 = require('lisk-chain@1.0.0');

this.registerModule(ChainModuleV1, matcher: appState => height =< 1000);
this.registerModule(ChainModuleV2, matcher: appState => height > 1000);
```  
### Which version(s) does this affect? (Environment, OS, etc...)
`*`

**Comment by shuse2** [comment]
This issue will be handled through the block processor which will be exposed in the future.
Therefore, Im closing this issue in favour of #4140
