### ISSUE TITLE
Reduce the technical debt

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk-sdk#3394]
Reduce the technical debt by fulfilling the following steps:
- Remove unnecessary project dependencies #3392 
- Make unit and functional tests atomic by rewriting them to Jest #3393 
- Improve network test to be fast and stable #3389

### Which version(s) does this affect? (Environment, OS, etc...)
`2.1.0`

**Comment by shuse2** [comment]
Closing this as 2.2 issues are all closed.
As of 2.2,
- Remove unnecessary project dependencies #3392
- All tests are stable in most of the cases
- cleared out the separation of concerns except rounds
