### ISSUE TITLE
Ignore typescript projects from eslint

### ISSUE THREAD

**Issue by limiaspasdaniel** [LiskHQ/lisk-sdk#3411]
### Expected behavior
It shouldn't
### Actual behavior
Eslint is taking in account transpiled files under `dist` folders
### Steps to reproduce
For example, go to `elements/lisk-transactions/dist-node` or `dist-browser` 
### Which version(s) does this affect? (Environment, OS, etc...)
`development`

**Comment by pablitovicente** [comment]
I can't reproduce this. Please add more notes for it to be worked on.

**Comment by shuse2** [comment]
I also double checked, and it's not reproducible. Therefore, closing this issue.
