### ISSUE TITLE
npx mocha doesn't use mocha.opts file

### ISSUE THREAD

**Issue by limiaspasdaniel** [LiskHQ/lisk-sdk#3413]
### Expected behavior
It should
### Actual behavior
When running `npx mocha pathToTests` it seems Mocha is not using the mocha.opts file which requires to run `setup.js` in order to load for example global constants used by the tests.
### Steps to reproduce
Try to run `npx mocha framework/test/mocha/integration/blocks/process/process.js`
### Which version(s) does this affect? (Environment, OS, etc...)
`development`

**Comment by limiaspasdaniel** [comment]
Also mocha.opts's set a wrong path for the --require path, it should be: `framework/test/mocha/setup.js`

**Comment by shuse2** [comment]
I think from the `framework` project prospective, `test/mocha/setup.js` is correct, and if we pass the `--opts=test/mocha/mocha.opts` it's working fine.
However, we need to investigate why npx mocha is not reading the `mocha.opts` correctly...

**Comment by limiaspasdaniel** [comment]
@shuse2 you're right. I think that if mocka.opts is located in the root folder, it works.
