### ISSUE TITLE
`init_transaction` module not extensible to custom transactions

### ISSUE THREAD

**Issue by mitsujutsu** [LiskHQ/lisk-sdk#3429]
### Expected behavior

`logic/init_transaction` module should be extensible to accommodate for new custom transaction types created by sdk user.

### Actual behavior

`logic/init_transaction` module directly maps known transaction `type`s to raw db format. 

See issue #2424 

### Which version(s) does this affect? (Environment, OS, etc...)
1.7

**Comment by limiaspasdaniel** [comment]
Also `elements/lisk-transactions/src/utils/validation/schema.ts:111` is setting the maximum value for BaseTransaction `type` to be 7. This constraint needs to be removed so we can register custom transactions with a `type > 7`
