### ISSUE TITLE
Fix the update_config.js to point the right version of release for 2.0.0

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#3432]
### Expected behavior

In release planned as 2.0 we made a lot of changes to configuration structure. So the `udpate_config.js` must work with that version and make the right changes to user specific custom configuration. 

### Actual behavior

The change were initially planned for 1.6 but later move to next release so the traces are still pointing to the old version. 

https://github.com/LiskHQ/lisk-sdk/blob/7c9d9e93761a2dd1eb24f8228f83ed370a005092/lisk/scripts/update_config.js#L254

### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0

**Comment by shuse2** [comment]
Superseded by #3478
