### ISSUE TITLE
Misleading name for class contained in`init_transaction.js`

### ISSUE THREAD

**Issue by limiaspasdaniel** [LiskHQ/lisk-sdk#3447]
### Expected behavior
Use a better name for the class and rename the file so it matches class name.
### Actual behavior
`init_transaction.js` holds an ES6 class named `Transaction` which doesn't match the file name. Also the purspose of the class is to instantiate **other** transactions implementations. We could name this class then as `TransactionsInitializer` or some similar name that describes the class functionality in a clearer way. Variables used across the codebase that hold the `require` of the file are also misleadingly named `initTransaction`
### Which version(s) does this affect? (Environment, OS, etc...)
`development`

**Comment by shuse2** [comment]
Superseded by #3616
