### ISSUE TITLE
Remove migrations applyRunTime implementation

### ISSUE THREAD

**Issue by lsilvs** [LiskHQ/lisk-sdk#3452]
Since `feature/improve_transactions_processing_efficiency` implementation, `storage.entities.Migration.applyRunTime()` is not used anymore but the implementation is still present and should be removed.

### Steps to reproduce
Check `framework/src/modules/chain/components/storage/entities/migration.js`

### Which version(s) does this affect? (Environment, OS, etc...)
development

**Comment by pablitovicente** [comment]
Done in #3463

**Comment by pablitovicente** [comment]
Closing as #3483 has been merged.
