### ISSUE TITLE
how can i fork the lisk?

### ISSUE THREAD

**Issue by sukeerthi117** [LiskHQ/lisk-sdk#3469]
Hi,
i want to fork lisk  to create my own blaockchain and cryptocurrency.Can u help me with the steps to fork the lisk?

Thank you.

**Comment by shuse2** [comment]
Lisk SDK alpha is published. Please follow the documentation https://lisk.io/sdk.
If you need further help, join our gitter channel https://gitter.im/LiskHQ/lisk-sdk
