### ISSUE TITLE
Passing ENV var via CLI does not work to modify app behavior

### ISSUE THREAD

**Issue by michielmulders** [LiskHQ/lisk-sdk#3475]
### Expected behavior
Should accept ENV var to modify app behavior.

### Actual behavior
Schema validation error:
```js
[ { keyword: 'type',
       dataPath: '.modules.http_api.httpPort',
       schemaPath:
        '#/properties/modules/properties/http_api/properties/httpPort/type',
       params: [Object],
       message: 'should be integer' } ] }
```
--> Probably CLI passing args as string and not converting them to specified type.

Also, `--http-port` option does not work as this gets converted to `--httpPort`. 
Starting application with `node lisk/src/index.js --httpPort 3000 | npx bunyan` does work.

### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0

**Comment by michielmulders** [comment]
```
{ _: [],
  'http-port': 3000,
  httpPort: 3000,
  '$0': 'lisk/src/index.js' }
Invalid command line arguments specified:  http-port
Set {
  'log',
  'l',
  'database',
  'd',
  'redis',
  'r',
  'snapshot',
  's',
  'port',
  'p',
  'address',
  'a',
  'peers',
  'x',
  'httpPort',
  'h',
  'network',
  'n',
  'config',
  'c' }
```

**Comment by nazarhussain** [comment]
@michaellightcurve Having camelcase naming for the command line arguments is against the Linux convention. We should match both formats while matching, but only allow `-` formats in the command line arguments.

**Comment by nazarhussain** [comment]
Replace the line: 

 https://github.com/LiskHQ/lisk-sdk/blob/3492bd749b40e3c2c5d615bd1e5e633d7da2b811/framework/src/controller/configurator/configurator.js#L113

```js
// Yarg is keeping two arguments in case passed in long format
// Example --http-port, will parse as "httpPort" and "http-port"
// So we also have to keep both values to check any invalid command line argument
this.listOfArgs.add(_.camelCase(arg));
this.listOfArgs.add(arg.replace(/(^--)(.*)/, '$2'));```
