### ISSUE TITLE
Add information about slot to blocks

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk-sdk#348]
Will be usefull to store information about slot number under which block was generated. Database table `blocks` should be extended with `slot` column. Also all endpoints (or at least API ones) should return it.

**Comment by 4miners** [comment]
There can be issue with running simple `UPDATE` on `blocks` - that will take very long time... Another approach should be taken.

**Comment by shuse2** [comment]
Closing due to no active discussion
