### ISSUE TITLE
Solve toJson usage

### ISSUE THREAD

**Issue by michielmulders** [LiskHQ/lisk-sdk#3500]
### Expected behavior
`toJson` should be `toJSON`

### Actual behavior
Ref: https://github.com/LiskHQ/lisk-sdk/pull/3499#discussion_r280707448

**Comment by pablitovicente** [comment]
@michaellightcurve  We should also consider renaming the method to something like `getMessage` as it's not actually returning JSON but the `message` property from an `Error` instance.
