### ISSUE TITLE
API doesn't allow transactions with type higher than 7

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk-sdk#3515]
### Expected behavior
API endpoint `api/transactions` returns transactions with no limit to its type.
### Actual behaviour
API endpoint `api/transactions` returns an error:
``
{"message":"Validation errors","errors":[{"code":"INVALID_REQUEST_PARAMETER","message":"Invalid parameter (type): Value failed JSON Schema validation","in":"query","name":"type","errors":[{"code":"MAXIMUM","message":"Value 9 is greater than maximum 7","path":[]}]}]}
``

### Which version(s) does this affect? (Environment, OS, etc...)
`*`

**Comment by limiaspasdaniel** [comment]
Related: https://github.com/LiskHQ/lisk-sdk/issues/3429#issuecomment-486704853
