### ISSUE TITLE
Test commander core commands

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#3516]
### Expected behavior
Should be able to install commander on Linux and MacOS (Fresh machines)

Note: Try all the possible options for each command
## Linux
- [x] lisk core --help
- [x] lisk core:install
- [x] lisk core:start
- [x] lisk core:stop
~- [ ] lisk core:upgrade~
- [x] lisk core:logs
- [x] lisk core:uninstall

## NPM
- [x] lisk core --help
- [x] lisk core:install
- [x] lisk core:start
- [x] lisk core:stop
~- [ ] lisk core:upgrade~
- [x] lisk core:logs
- [x] lisk core:uninstall

## MacOS
- [ ] lisk core --help
- [ ] lisk core:install
- [ ] lisk core:start
- [ ] lisk core:stop
~- [ ] lisk core:upgrade~
- [ ] lisk core:logs
- [ ] lisk core:uninstall

Note: Upgrade command cannot be used as the commander supports upgrade for Lisk Core version > 2.0.0

**Comment by michielmulders** [comment]
<img width="1666" alt="Screenshot 2019-05-16 at 11 01 17" src="https://user-images.githubusercontent.com/26482710/57841042-233fe580-77ca-11e9-97e1-e7d1ac3d183e.png">

**Comment by michielmulders** [comment]
![Screenshot 2019-05-21 at 12 32 54](https://user-images.githubusercontent.com/26482710/58089286-a8f5d380-7bc4-11e9-8169-e06e7ac67391.png)

**Comment by michielmulders** [comment]
![Screenshot 2019-05-21 at 13 52 44](https://user-images.githubusercontent.com/26482710/58093873-bc5a6c00-7bcf-11e9-9175-e32090f6ec91.png)
When using `lisk core:stop mainnet-03`, I checked the logs and found the following output. @ManuGowda

**Comment by michielmulders** [comment]
Tested:
- Try uninstall non-existing `NAME` -> ✅
- Install with below command for mainnet and testnet using snapshot ->  ✅
- `--no-snapshot` option -> In progress

Note: The `--no-start` option can only be used for default installation of latest with `lisk core:install lisk-mainnet` which fetches the latest official release. For `--release-url`, Lisk core does not start by default.

Tested `2.0.0-alpha.9` version with `lisk core:install --network=testnet --release-url=https://lisk-releases.ams3.digitaloceanspaces.com/lisk-core/lisk-2.0.0-alpha.9-5ed4cbe-Linux-x86_64.tar.gz testnet-01`

**Comment by michielmulders** [comment]
Tested for Lisk Commander `npm` from [our repository](https://npm.lisk.io/#/detail/lisk-commander):
- All checks completed ✅

Tested on Mac with [Darwin build](https://jenkins.lisk.io/job/lisk-qa/job/lisk-commander-build-tag-private/):
- All checks completed ✅

_DO droplet destroyed._
