### ISSUE TITLE
Enable log rotation with bunyan

### ISSUE THREAD

**Issue by Tschakki** [LiskHQ/lisk-sdk#3519]
### Expected behavior

The built-in log rotation of Bunyan should be enabled by default with reasonable values.

The log rotation should be configurable inside of `config.json` or with `ENV` variables.

### Actual behavior

Log rotation has to be manually and separately set up as post-installation step of Lisk Core.

### Which version(s) does this affect? (Environment, OS, etc...)
v1.6.0

**Comment by shuse2** [comment]
Closing because log rotation should be done at server management level
