### ISSUE TITLE
Refine the application config JSON structure 

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#3520]
Creating application with Lisk SDK should be easy and with the shortest possible code. 

To create an application we can pass set of configuration to the constructor. 

```js
const app = new Application(genesisBlock, config); 
```

The current implementation suggest for following structure for the configuration. 

```js
{
   app: {
      label: 'myApp',
      version: '1.0.0',
      genesisConfig: {}
   },
   modules: {},
   components: {},
}
```

This makes it less intuitive for user to relate and pass the configuration of application and the structure logically takes the application with the same levels of modules. So to just change the label of the application. 

```js
const app = new Application(genesisBlock, { app: { label: 'myApp' } }); 
```

We suggest to change the structure of JSON param so that application level configuration get flattered and appear on top level. 

```js
const app = new Application(genesisBlock, { label: 'myApp' }); 
```

After the change the configuration would be look like: 

```js
{
   label: 'myApp',
   version: '1.0.0',
   genesisConfig: {}
   modules: {},
   components: {},
}
```

### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0

**Comment by shuse2** [comment]
Also with this issue, unnecessary exposed config params below should be removed
* app.buildVersion (this is not framework property)
* app.lastCommitId (this is not framework property)
* app.minVersion (this is no longer used)
* app.node.broadcasts (this should not be configurable, and changing this causes p2p banning)
* app.network.populatorInterval (This is too low level)
* app.network.outboundShuffleInterval (This is too low level)

Also,
* app.node.forging can be .forging
* app.node.rebuildUptoRound can be .rebuildUotoRound
