### ISSUE TITLE
Move fee as static property of the transaction implementation

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#3521]
### Expected behavior

With every custom transaction we should be able to specify some distinct fee for it. And that should not involve passing any configuration at application level. 

```js
class CustomTransaction extends BaseTransaction {
   static meta = {fee: 100000}
}
```

That will be accessible through `CustomTransaction.meta.fee` in element and in framework where ever required. 

### Actual behavior

Currently transaction fee is defined as constants in the `transactions` element as well as `framework` constants. Which makes it impossible to create and register new transaction. 

### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0

**Comment by nazarhussain** [comment]
We also look into this endpoint, either to remove the constants or somehow return the fee of custom registered transactions. 

https://github.com/LiskHQ/lisk-sdk/blob/86db5cabc562214958d8d1487fb99ddd4ee24903/framework/src/modules/http_api/controllers/node.js#L85-L93

**Comment by shuse2** [comment]
Superseded by #3860
