### ISSUE TITLE
Refactor redundant code in Account submodule/logic

### ISSUE THREAD

**Issue by lsilvs** [LiskHQ/lisk-sdk#3524]
### Expected behavior
Expect to call storage call whenever possible inside Chain module in order to clean up Account submodules/logic.

### Actual behavior
A lot of functions in Account submodules/logic can be replaced by storage call directly making the code cleaner and more readable.

### Which version(s) does this affect? (Environment, OS, etc...)
2.0

**Comment by SargeKhan** [comment]
The transactions module declares many functions which are just wrapper functions for transaction pool. I think these functions can be removed as well. Furthermore, the transactions module declares function getPooledTransactions whose definition uses unnecessary dynamic function calls. This function is difficult to understand and hard on the eye. Thus, it should be refactored as well.
