### ISSUE TITLE
Improve the logger name for JSON logger

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#3532]
### Expected behavior

Every logger entry should be easily identifiable to which module in the framework it belongs to. 

### Actual behavior

Right now every log entry have a name `lisk-framework`, which is less intuitive while debugging in the logs. 

```
{
  "name": "lisk-framework",
  "hostname": "Nazars-MacBook-Pro.local",
  "pid": 44216,
  "level": 30,
  "msg": "Releasing enqueued broadcasts",
  "time": "2019-05-07T08:47:57.530Z",
  "src": {
    "file": "/Users/nazar/Hub/Lightcurve/Lisk/dev/lisk-sdk/framework/src/modules/chain/logic/broadcaster.js",
    "line": 245,
    "func": "releaseQueue"
  },
  "v": 0
}
```

```
{
  "name": "lisk-framework",
  "hostname": "Nazars-MacBook-Pro.local",
  "pid": 44553,
  "level": 30,
  "msg": "Loading module lisk-framework-chain:0.1.0 with alias \"chain\"",
  "time": "2019-05-07T08:55:54.538Z",
  "src": {
    "file": "/Users/nazar/Hub/Lightcurve/Lisk/dev/lisk-sdk/framework/src/controller/controller.js",
    "line": 219,
    "func": "_loadInMemoryModule"
  },
  "v": 0
}
```

As you look into both entries, both shows the name 'lisk-framework`, it would be nice if we can have different names of logger for different chunks of the application. 

### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0

**Comment by nazarhussain** [comment]
We can use different names for log entries or use the concept of child loggers. I would prefer name as we explicitly create logger in each module.

**Comment by ManuGowda** [comment]
![photo_2019-06-04 09 27 19](https://user-images.githubusercontent.com/6449871/58859822-056bef00-86ab-11e9-80c2-542b8883b9e5.jpeg)
The above diagram was a record of Improve logger discussion between Me and Shu. The conclusion out of the meeting was that we should have a standard logging format for `success` and `error` for `lisk-framework` logs. 
Each module should have its own `child` logger, which can be helpful for further log separation and analysis. The main `info` logs from `chain` module should have logs related to `forging a block(success/ failure with reason)`, `receiving block(success/ failure with reason)`, `syncing (success/ failure with reason)`, `received transactions/signatures(success/ failure with reason)`.
Majority of the `p2p` and `http` module logs need not be at `info` level, it should be at `debug` and `trace` level depending on the severity.

**Comment by michielmulders** [comment]
Notes:
Logger per module with a different name.
