### ISSUE TITLE
API node/status - invalid networkHeight

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk-sdk#3533]
### Expected behavior
`networkHeight` should be always correct.
### Actual behavior
`networkHeight` is incorrect (for about 1 second) when API called just after forging a block.

<img width="613" alt="Screen Shot 2019-05-07 at 11 26 09" src="https://user-images.githubusercontent.com/22824146/57289383-89868300-70bb-11e9-88f9-8ed37d383409.png">

### Steps to reproduce
Tested on a network with 10 nodes, all of them are on the same height and moving forward, the cache was disabled.
Call API endpoint http://lon1-foonet-000.liskdev.net:4000/api/node/status frequently and observe the results.
### Which version(s) does this affect? (Environment, OS, etc...)
`2.0.0-alpha.0`

**Comment by ManuGowda** [comment]
This issue is fixed and verified in `alpha.8` tag
<img width="835" alt="Screen Shot 2019-05-20 at 11 41 12" src="https://user-images.githubusercontent.com/6449871/58012186-36b5be00-7af4-11e9-90d0-130e4d680af5.png">
