### ISSUE TITLE
Avoid using helpers from underlying library instead use the adapter 

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#3548]
### Expected behavior

We should avoid using helper or functions from any underlying library in general if we have a wrapper for it. We are wrapping the pgp library with `pgpAdapter` in our storage component, so we should avoid using directly any helper. 

Either the logic should be executed by a specific SQL file or the functionality should be wrapped in the `pgpAdapter`. 

### Actual behavior

There are couple of such usage in the tests. 

https://github.com/LiskHQ/lisk-sdk/blob/eedad04d2e8e6726f337db73a83f38dfcbec1e91/framework/test/mocha/integration/blocks/process/process.js#L93

https://github.com/LiskHQ/lisk-sdk/blob/eedad04d2e8e6726f337db73a83f38dfcbec1e91/framework/test/mocha/integration/blocks/process/process.js#L99

### Which version(s) does this affect? (Environment, OS, etc...)
Not specific

**Comment by shuse2** [comment]
Closing this in favor of https://github.com/LiskHQ/lisk-sdk/issues/5238
