### ISSUE TITLE
Improve the use of actions meta information in the network module

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#3553]
### Expected behavior

Currently we can define `actions` as an object. 

```
{
   handler: () => {},
   prop1: true, 
   prop2: 'val'
}
```
Where an action can have different meta information specified along with the handler. We need to provide an alternative way to access all this information in any module. So modules can use this information based on their own business logic. 

### Actual behavior

Currenlty `network` module expect to have `public: true` for actions which are allowed to be executed on network. For such a specific implementation only for network module, we exposed a method in `invokePublic` on all channels, which is unnecessary and not extensible implementation for future use cases.  

### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0

**Comment by nazarhussain** [comment]
https://github.com/LiskHQ/lisk-sdk/pull/3530#discussion_r282068272

**Comment by shuse2** [comment]
Related to #3358

**Comment by shuse2** [comment]
Application structure has changed and the network related communication is not done through action.
Therefore, this issue is not applicable anymore
