### ISSUE TITLE
The received time of the most recent block in the blockchain should be maintained

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk-sdk#3557]
### Expected behavior
"Introduce BFT consensus protocol" dictates that every node should maintain the time it received the most recent block.

Maintain in blocks state.
### Actual behavior
The node does not maintain the time at which block is received from the network.
### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0

**Comment by sridharmeganathan** [comment]
@limiaspasdaniel will do the analysis before the next sprint grooming meeting.

**Comment by limiaspasdaniel** [comment]
After having a discussion with @SargeKhan , in the new BFT scenario we need to consider the further points:

In LIP-004 we need to check if the last block APPLIED was RECEIVED in its designated time slot. By RECEIVED meaning only blocks received passively from the network in `receiveBlockFromNetwork` function.

This  check is only part of the fork choice rules that are triggered ONLY by this function in `blocks/blocks.js`

I conclude that:

- We can rename the attribute to a more meaningful description
- We don't need to expose it anymore
- It needs to reflect the time the last block applied was received. If the last block received didn't successfully apply we DO NOT need to update this attribute
- `isStale()` method that triggers the old SYNC mechanism is not used anymore in BFT.
- To keep the compatibility we can leave `this._lastReceipt` to be updated and retrieved the same way as before, so basically don't touch it on the PR. This way legacy function `isStale()` can still check this_lastReceipt` which will be updated no matter a block received is applied or not, the same way as it is right now.


```javascript
// blocks/blocks.js
class Blocks {

	constructor() {
		this._lastReceivedAndAppliedBlock = {
			receivedTime: null,
			id: null
		}
		this._lastReceipt; // For compatibility purposes.
	}

	receiveBlockFromNetwork(block) {
		const receivedTime = Math.floor(Date.now() / 1000);
		this._lastReceipt = receivedTime; // For compatibility purposes.
		// ... Do stuff

		// Fork choice rules access ._lastReceivedTimeOfApplied and _lastReceivedAndAppliedId
		// to check if the last block applied was received in the correct timeslot.
		// CASE 4 (fork_choice_rule.js#isTieBreak)
		if (forkChoiceRules.isTieBreak({ this.slots, this._lastBlock, block, receivedTime, this._lastReceivedAndAppliedBlock})) {
			return handleTieBreak(stuff);
		}

		try {
			this.blocksProcess.processBlock(block);
		} catch {
			throw...
		}

		// Block was applied successfully
		this._lastReceivedAndAppliedBlock.receivedTime = receivedTime;
		this._lastReceivedAndAppliedBlock.id = block.id;
	}
}
```
