### ISSUE TITLE
Add way to retarget specific peers on the network to account for the new LIP advertising feature

### ISSUE THREAD

**Issue by jondubois** [LiskHQ/lisk-sdk#3565]
### Expected behavior

In order to support the block/transaction advertising feature, there needs to be a mechanism for sending a request/message back to a specific peer (I.e. a peer which sent us an advertisement). This may require either adding a mechanism to bypass the default P2P routing algorithm.

### Actual behavior

The core P2P API does not currently support a mechanism for sending a message to a specific peer; the routing is handled internally by the P2P library with no way to bypass the routing algorithm.

**Comment by benfavre** [comment]
Has anyone suggested migrating to support libp2p yet ?

**Comment by shuse2** [comment]
We currently have our own p2p library package called `lisk-p2p`, and we are trying to implement our own P2P protocol, which is described in [LIP 0004](https://github.com/LiskHQ/lips/blob/master/proposals/lip-0004.md).
