### ISSUE TITLE
Unify Endianness of Transactions and Blocks signature

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk-sdk#3566]
### Expected behavior
There is no reason to use different Endianness (sometimes Little, sometimes Big Endian) while calculating or verifying the signature for transactions and blocks.

Suggestion: Decide on Big Endian and apply consistently. 

The rules for generating transactions signature are nice to have from the perspective of developers creating new transaction types and implementing `getBytes` functions for them.

### Actual behavior

Bytes | Property | Endianness | Note
-- | -- | -- | --
TRANSACTION
1 | type (int) | BE | No difference for 1 byte
4 | timestamp (int) | LE | Buffer.writeIntLE
32 | senderPublicKey | BE | Buffer.from
8 | recipientId | BE | BigNum(’12324’).toBuffer({ 8 endian: 'big' })
8 | amount | LE | BigNum(amount).toBuffer({ size: 8 endian: ‘little’ })
BLOCK
4 | version (int) | LE | byteBuffer.writeInt
4 | timestamp (int) | LE | byteBuffer.writeInt
8 | previousBlockfor loop | BE |  
4 | numOfTransactions (int) | LE | byteBuffer.writeInt
8 | totalAmount (long) | LE | byteBuffer.writeLong
8 | totalFee (long) | LE | byteBuffer.writeLong
8 | reward (long) | LE | byteBuffer.writeLong
4 | payloadngth (int) | LE | byteBuffer.writeInt
32 | payloadHash | BE | for loop
32 | generatorPublicKey | BE | for loop
64 | blockSignature or unused | BE | for loop

There is also `byteBuffer.flip();` at the end of Block's bytes generation.

### Which version(s) does this affect? (Environment, OS, etc...)
`*`

**Comment by shuse2** [comment]
This issue is no longer relevant after https://github.com/LiskHQ/lips/blob/master/proposals/lip-0027.md
