### ISSUE TITLE
Implement steps pertaining to BFT consensus protocol introduced block processing mechanism

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk-sdk#3570]
### Expected behavior
Two new steps are introduced in the block processing to maintain BFT consensus protocol in the LIP. These steps should be implemented in the block processing.
### Actual behavior
The block processing does not include these changes in the current implementation. 
### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0

**Comment by shuse2** [comment]
Closing superseded by #4043
