### ISSUE TITLE
Implement steps pertaining to BFT consensus protocol introduced in block reverting mechanism

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk-sdk#3571]
### Expected behavior
BFT consensus protocol introduces new verification and processing steps for maintaining consensus in block reverting mechanism. These steps should be implemented.

### Actual behavior
The block reverting mechanism does not include these changes in the current implementation.

### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0

Task

- [ ] Integration tests is required.

**Comment by shuse2** [comment]
Closing superseded by #4043
