### ISSUE TITLE
Name of unsigned transactions queue is misleading

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk-sdk#3610]
### Expected behavior
The name should reflect actual behavior.
### Actual behavior
The queue contains all the transactions that require to be signed, doesn't matter if they are already signed or not.
API endpoints: `/node/status/`, `/node/transactions/unsigned`
### Steps to reproduce
N/A
### Which version(s) does this affect? (Environment, OS, etc...)
`2.0.0-alpha.0`

**Comment by pablitovicente** [comment]
@MaciejBaj @SargeKhan what name should I use for this?

**Comment by pablitovicente** [comment]
Changed to `pending` in #3620

**Comment by pablitovicente** [comment]
Changed to pending in #3625 closing.
