### ISSUE TITLE
Combine all the transaction related logic into one module and expose used functionality

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#3614]
### Expected behavior
Within transactions module, it should not have any external dependency, and only exposing the used function from other module

- init_transaction.js
- process_transaction.js
- check_transaction_against_exceptions.js
- broadcaster.js
- transaction_pool.js
- transactions.js
- process_transactions.js
- multisignatures.js

### Actual behavior
Transaction logic spread across the chain module

**Comment by pablitovicente** [comment]
Before starting work on this we should merge https://github.com/LiskHQ/lisk-sdk/pull/3501
