### ISSUE TITLE
Combine all the rounds related logic into one module and expose used functionality

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#3615]
### Expected behavior
Within round module, it should not have any external dependency, and only exposing the used function from other module

- round.js
- rounds_information.js
- rounds.js
- delegates.js

### Actual behavior
Round logic spread across the chain module

**Comment by MaciejBaj** [comment]
Don't introduce any changes to rounds! The parallel changes will be introduced to [Lisk SDK 3.0](https://github.com/LiskHQ/lisk-sdk/projects/7)
