### ISSUE TITLE
Process status shows undefined in Lisk Application 

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk-sdk#3621]
### Expected behavior
When running Lisk Core (binary) - is shouldn't appear as `undefined` in the processes list.
### Actual behavior
![Screen Shot 2019-05-15 at 09 29 54](https://user-images.githubusercontent.com/22824146/57756771-3ed8bc80-76f4-11e9-8dfe-a1a90cc0af3c.png)
### Steps to reproduce
Run Lisk Core from binary.
### Which version(s) does this affect? (Environment, OS, etc...)
`2.0.0-alpha.4`

**Comment by fchavant** [comment]
@4miners I believe this (changing the process name) is a [feature](https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/controller/application.js#L46) introduced by [@nazarhussain](https://github.com/LiskHQ/lisk-sdk/blame/7c31c9d4b12a72f18a35ead79198b2ba6d4bd091/framework/src/controller/application.js#L46). It's not specific to binary builds.
