### ISSUE TITLE
Add Round.apply function

### ISSUE THREAD

**Issue by yatki** [LiskHQ/lisk-sdk#3633]
### Expected behavior
We'll need to create a new Round module to support BFT consensus LIP.
### Actual behavior
The current rounds module is not compatible with the LIP
### Acceptance Criteria
- [x] If a new round is about to start, delegate list must be generated.
- [x] Increase producedBlocks on mem_accounts table
- [x] Apply votes to mem_accounts table
- [x] Update delegate ranks
- [ ] Continue publishing events in existing rounds module
- [x] If it's the end of the round, process rewards & missedBlocks information.
- [x] functions needs to be exported from `submodules/round/round.js` file for testing but only `apply` must be exported from `submodules/round/index.js`.

**Comment by MaciejBaj** [comment]
Open the corresponding issue for Round.undo

**Comment by shuse2** [comment]
@MaciejBaj I think if we implement correctly this way, we might not need `undo`
