### ISSUE TITLE
Add functional tests for validated queue

### ISSUE THREAD

**Issue by pablitovicente** [LiskHQ/lisk-sdk#3636]
### Expected behavior

/node/status now shows `validated` queue count and we should add tests to it.

### Actual behavior

Tests do not exists

### Steps to reproduce

Send 1000 transactions and call `GET api/node/status` the transactions are first buffered before showing add in the queue so there will be some timings to have into account for testing this.

**Comment by shuse2** [comment]
With #4841 , this issue is no longer relevant.
