### ISSUE TITLE
Remove redundant code in modules/transactions

### ISSUE THREAD

**Issue by lsilvs** [LiskHQ/lisk-sdk#3638]
The transactions module declares many functions which are just wrapper functions for transaction pool, hence can be replaced. Furthermore, the transactions module declares function getPooledTransactions whose definition uses unnecessary dynamic function calls. This function is difficult to understand and hard on the eye. Thus, it should be refactored as well.

_Originally posted by @SargeKhan in https://github.com/LiskHQ/lisk-sdk/issues/3524#issuecomment-490108645_

**Comment by shuse2** [comment]
Closed by #3614
