### ISSUE TITLE
Expose more util functions from `lisk-transactions`

### ISSUE THREAD

**Issue by mitsujutsu** [LiskHQ/lisk-sdk#3640]
### Expected behavior

`createBaseTransaction`, `validateTransferAmount` and `validateNonTransferAmount` can be useful when writing custom transactions for validation.

### Actual behavior

Currently not exposed from elements `lisk-transactions`

### Which version(s) does this affect? (Environment, OS, etc...)
2.0

**Comment by SargeKhan** [comment]
@mitsujutsu, we don't yet have an implementation of `createBaseTransaction`. Are you suggesting to implement this functionality as part of this issue?

**Comment by mitsujutsu** [comment]
@SargeKhan we already have one in `elements/lisk-transactions/src/utils/create_base_transaction`
