### ISSUE TITLE
Discovery is too reliant on seed peers

### ISSUE THREAD

**Issue by jondubois** [LiskHQ/lisk-sdk#3643]
### Expected behavior

The discovery should start with the seed peers but when the interval executes again, it should use some of the newly discovered peers as the new seeds.

### Actual behavior

There is a bug in the current discovery algorithm which means that our node always go back to the seed peers for discovery.

### Steps to reproduce

Check the code.

### Which version(s) does this affect? (Environment, OS, etc...)

`0.1.0-alpha.9`

**Comment by ishantiw** [comment]
@jondubois I think we need to use `triedPeers` and `newPeers` or just `triedPeers` when we start discovering in intervals, seems like we are just passing seed peers again and again, every time we do discovery,
https://github.com/LiskHQ/lisk-sdk/blob/development/elements/lisk-p2p/src/p2p.ts#L562
