### ISSUE TITLE
Difficulty in testing lisk-core with local versions of lisk-sdk and lisk-framework

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#3645]
### Expected behavior

Developers should be able to develop and test on lisk-core by linking to the local repo of `lisk-sdk` and `lisk-framework`.

### Actual behavior

`npm link` only works for `lisk-sdk` but `lisk-framework` points again to the npm version.

### Steps to reproduce

N/A

### Which version(s) does this affect? (Environment, OS, etc...)
`2.0.0`

**Comment by ishantiw** [comment]
For testing everything locally, 

1) At root of `lisk-sdk` repo,  run `npx lerna link`
2) At root of `lisk-core` repo, run `npm link lisk-sdk`

*Notes:*
1) If you have made changes in `elements` lib then make sure you run `npm run build` to see the changes
2) To clean up, install and build from scratch, `npm run clean:node_modules && rm -rf ./node_modules && npm ci && npm run bootstrap -- --ci && npm run build`

**Comment by shuse2** [comment]
@ishantiw Can we add this steps and general starting step such as (npm ci, npm run bootstrap, npm run build) to the readme?
