### ISSUE TITLE
P2P errors while syncing with testnet

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#3651]
### Expected behavior
While syncing with testnet or mainnet, the node shouldn't make too many disconnects or the other errors mentioned below.
### Actual behavior
Too many P2P errors while syncing with test network.

`14:46:17.406Z ERROR lisk-framework: Event 'rpc-request' was aborted due to a bad connection`
`14:46:13.092Z ERROR lisk-framework: Unable to match an address to the peer`
`14:46:13.073Z ERROR lisk-framework: Connection id does not match with corresponding peer`
### Steps to reproduce
Start `2.0.0-alpha.4` node with test network.
### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0

**Comment by ManuGowda** [comment]
This errors also occurring in isolated `2.0.0-alpha.x` network.
for debugging this use any of the nodes from network http://alpha7-seed-01.liskdev.net:6040/networkMonitor

**Comment by ManuGowda** [comment]
Move to the trace level log after classified as a regular behavior.

**Comment by ishantiw** [comment]
I was debugging and found out that these two errors are coming specifically from 1.6 versions,
`
Error: Unable to match an address to the peer

Verison of connected peer: '1.6.0-rc.3'


Error: Connection id does not match with corresponding peer

Verison of connected peer: '1.6.0-rc.4'
`

**Comment by ManuGowda** [comment]
closing this issue as the errors don't occur
```
14:46:13.092Z ERROR lisk-framework: Unable to match an address to the peer
14:46:13.073Z ERROR lisk-framework: Connection id does not match with corresponding peer
```
only `14:46:17.406Z ERROR lisk-framework: Event 'rpc-request' was aborted due to a bad connection
` occurs and its very less.

**Comment by 4miners** [comment]
In version `2.0.0-alpha.10` the node is still trying to connect to itself frequently:
```
09:24:35.855Z DEBUG lisk-framework: Peer disconnect event: Outbound connection of peer 134.209.90.103:5000 was closed with code 4101 and reason: Peer cannot connect to itself
09:24:35.856Z ERROR lisk-framework: Event 'rpc-request' was aborted due to a bad connection
```
This is not the correct behavior.

**Comment by jondubois** [comment]
@4miners This is because the node doesn't remember who it was so it keeps rediscovering itself through peers. This problem shouldn't lead to any negative side effects though and will fix itself once we have implemented the LIP partial view feature.

My view is that it would be better to just let the node to connect and interact with itself - This would lead to simpler more consistent logic with fewer states. At worst, it would be a very minor performance overhead (probably less than 1% in a network with 100 peers) to just let the node send itself a transaction/signature/block once in a while.

**Comment by ishantiw** [comment]
We can avoid this error occurring frequently by adding our public `ip` to blacklist in p2p in-memory, the first time we see it. In this way, it will always be discarded before even throwing these errors even if it comes from the peer list of other peers during the discovery. So we will only see this error one time.

**Comment by jondubois** [comment]
That said it's probably a pretty easy fix.

**Comment by jondubois** [comment]
@ishantiw Yes I think this is fine. We do something like this in the 0.x and 1.x versions; the node bans itself.
