### ISSUE TITLE
Invoke `applyPenalty` network actions in framework

### ISSUE THREAD

**Issue by mitsuaki-u** [LiskHQ/lisk-sdk#3672]
### Expected behavior

As per [Lip 0004](https://github.com/LiskHQ/lips/blob/master/proposals/lip-0004.md), we should apply penalties to peers for a list of bad behaviors on the framework level.

All of the banning type are described in https://github.com/LiskHQ/lips/blob/master/proposals/lip-0004.md#banning-mechanism-1

### Notes
- It is blocked by lazy push/eager push because this cannot be fully completed until they are implemented.

### Which version(s) does this affect? (Environment, OS, etc...)
2.3

### Acceptance Criteria
- For bad blocks and transaction, peer gets banned after a few transactions( As per Lips 004 )

**Comment by pablitovicente** [comment]
@mitsujutsu in https://github.com/LiskHQ/lisk-sdk/pull/4286/files#diff-14e7ab0521cfea25154c1e3fdbdbbb3bR76 I'm already exposing the method as I needed it so don't know if you need to take into account the BFT branch when doing this.
