### ISSUE TITLE
Update API /delegates/forgers endpoint to be BFT compliant

### ISSUE THREAD

**Issue by yatki** [LiskHQ/lisk-sdk#3684]
### Expected behavior
`/delegates/forgers` gives active list of delegates for the round. We need to update the endpoint to get the list for round `r - ROUND_DIFFERENCE`.
### Actual behavior
We are providing delegate list generated for the active round.

**Comment by shuse2** [comment]
This is not required anymore by the implementation.
The calling function `Dpos.getForgerPublicKeysForRound` takes care the offset
https://github.com/LiskHQ/lisk-sdk/pull/4445#pullrequestreview-309245726
