### ISSUE TITLE
Improve log level and log information

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#3703]
### Expected behavior
Improve log level and log information
### Actual behavior
Change the below mentioned logs to be `trace`, all the `MONITOR` logs to `trace`
```
10:24:31.508Z  INFO lisk-framework: Releasing enqueued broadcasts
10:24:31.508Z  INFO lisk-framework: Queue empty
10:27:22.237Z DEBUG lisk-framework: Block already forged for the current slot
10:27:30.222Z DEBUG lisk-framework:
    MONITOR: undefined -> network:event { event: 'postBlock',
```
### Steps to reproduce
Run the node `lisk-2.0.0-alpha.9` and tail for logs
### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0

**Comment by pablitovicente** [comment]
`MONITOR` already changed to `trace` by #3707
