### ISSUE TITLE
Log framework migration process

### ISSUE THREAD

**Issue by lsilvs** [LiskHQ/lisk-sdk#3714]
### Expected behavior
When the Controller loads the migrations in `_loadMigrations` method, it should log the process showing the migration and namespace as it runs.

### Actual behavior
There is no log

### Steps to reproduce
Start the application. Check the logs.

### Which version(s) does this affect? (Environment, OS, etc...)
2.2

**Comment by lsilvs** [comment]
REF.: https://github.com/LiskHQ/lisk-sdk/pull/3701#pullrequestreview-240674925

**Comment by shuse2** [comment]
Closing this in favor of https://github.com/LiskHQ/lisk-sdk/issues/5238
