### ISSUE TITLE
Transactions type 4 are not propagated through the network

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk-sdk#3728]
### Expected behavior
Transactions type 4 should be propagated to all nodes of the network.
### Actual behavior
There are issues with the propagation of those transactions. When we query `api/node/status` endpoint on the node that we're sending transactions to, we can see that amount of `pending` transactions is increasing. When we query other nodes of the network, `pending` stays at `0` - so looks like those transactions are not propagated correctly. This also leads to block beign not full:
<img width="900" alt="Screen Shot 2019-05-24 at 16 25 48" src="https://user-images.githubusercontent.com/22824146/58335151-40fff100-7e41-11e9-8749-1143ebc8bf9f.png">
### Steps to reproduce
Execute QA stress test.
### Which version(s) does this affect? (Environment, OS, etc...)
`2.0.0-alpha.10`

**Comment by SargeKhan** [comment]
@jondubois is there a different way in which multisignature transactions are being propagated?

**Comment by 4miners** [comment]
Closed in favor of https://github.com/LiskHQ/lisk-sdk/issues/3624
