### ISSUE TITLE
Implement create and sign any transaction functionality in Lisk Transactions

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk-sdk#3739]
### Expected behavior
There should be functionality in Lisk Transactions allowing to create and sing any transaction - passing that transaction as a parameter. The functionality should verify only the required properties of transactions (common for all of the transactions):
```
- receipientId/receipentPublicKey,
- fee
- passphrase 
```
For that property set, the function creates and signs a transaction, adds the following properties:
```
- receipientId (if receipentPublicKey was passed),
- signature
- senderPublicKey (derived
- senderId (derived from the senderPublicKey)
- timestamp
- amount (0 by default)
- type
```
The output is ready to send over the `POST /api/transactions` API.
### Actual behavior
Missing functionality.

### Which version(s) does this affect? (Environment, OS, etc...)
`2.0.0`

**Comment by sridharmeganathan** [comment]
@LucasIsasmendi Please estimate and see it is possible to do it in our current sprint.
