### ISSUE TITLE
Implement mechanism for finding commonBlock

### ISSUE THREAD

**Issue by michielmulders** [LiskHQ/lisk-sdk#3769]
### Expected behavior
~Peer should be able to send 202 block ids to a specific peer in the network in order to find a common block within this range. If no common block can be found, this means the node can not provide it and the BFT process should be aborted.~

~Also, add functionality for verifying the commonBlock.~

**Remarks:** This functionality can be reused by Block Sync Mechanism @limiaspasdaniel 

**Goal:** Implement functionality as a chain action.
~Requirements: @jondubois PR for targetting specific peer is needed for this to be able to work.~

### Which version(s) does this affect? (Environment, OS, etc...)
`feature/introduce-bft`

**Comment by limiaspasdaniel** [comment]
Closing. Done in #3816
