### ISSUE TITLE
Implement reverting to last common block step for Block Sync Mechanism

### ISSUE THREAD

**Issue by limiaspasdaniel** [LiskHQ/lisk-sdk#3770]
### Expected behavior
Implement reverting to last common block step for Block Sync Mechanism

a) The node requests the last common block `C` from `P` (Peer).
b) If `C.height<chainHeightFinalized`, then `P` is banned and the block synchronization is restarted from Step 1. BFT module will provide `chainHeightFinalized`

c) The node deletes all blocks of the current chain until block `C` is the tip of the chain. All these blocks are stored persistently so the previous chain can be restored in case synchronizing with `P` fails. This logic will not be implemented inside Block Synchronizer but instead shared with Fast Chain Switcher

### Which version(s) does this affect? (Environment, OS, etc...)
`feature/BFT`

**Comment by pablitovicente** [comment]
I think for item `c` in the list we might need to emit `p2p.EVENT_BAN_PEER`, @shuse2 ?

**Comment by shuse2** [comment]
It will need to call
`channel.invoke('network:applyPenalty', { peerId, penalty })`

**Comment by pablitovicente** [comment]
For item `a` after consulting `blocks.getHighestCommonBlock()` needs to be called

**Comment by pablitovicente** [comment]
To request data from an specific peer the method in the p2p lib is `requestFromPeer`
