### ISSUE TITLE
Network module should ignore peers for consensus while sycing to network

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#3786]
### Expected behavior
Network module should consider  <= `100` peers with matching broadhash for consensus calculation.
### Actual behavior
When a group of peers are syncing to network and not reached the network height, when a forging node takes these peers for consensus calculation it results in low consensus due to sycing and miss match braodhash, this results in delegate missing a block.
### Steps to reproduce

1. Deploy a network of 10 nodes
2. Enable 101 delegates forging on 10 nodes
3. After reaching certain height, Deploy 100 nodes, you can observe the delegates starts to miss forging blocks due to low consensus

### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0

**Comment by shuse2** [comment]
Consensus is calculated in the chain module, and also consensus calculation does support this scenario.
