### ISSUE TITLE
Create compontents/index.js in Chain Module

### ISSUE THREAD

**Issue by yatki** [LiskHQ/lisk-sdk#3787]
### Expected behavior
Components can be initalized and used through application with just requiring them. There is no need to put them into scope variable. 
### Actual behavior
We are passing components in scope variable.

**Comment by shuse2** [comment]
This will not work because in the close future, we want to move most of the logics into elements as separate packages. In that case, this we cannot use require

**Comment by yatki** [comment]
In that case, I agree.
