### ISSUE TITLE
Move BlockSlots class into Dpos Module

### ISSUE THREAD

**Issue by yatki** [LiskHQ/lisk-sdk#3789]
### Expected behavior
BlockSlots class is only used in Dpos module. Thus we can move it into dpos folder.
### Actual behavior
It's under blocks module at the moment.

**Comment by sridharmeganathan** [comment]
@yatki will do the analysis before the next sprint grooming meeting.

**Comment by sridharmeganathan** [comment]
STM has done and the team agreed to develop it in a specific way.

**Comment by yatki** [comment]
Also,

Remove -getTime function.
Rename class to Slots
Update tests
