### ISSUE TITLE
Lisk Core 2.0.0 API performance degrade

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#3800]
### Expected behavior
The API Average Performance should be under seconds
### Actual behavior
The following endpoint performance is degraded
```
get /accounts/{address}/multisignature_groups
get /voters
get /accounts
post /transactions
```

## Summary
<img width="1023" alt="Screen Shot 2019-06-07 at 14 32 30" src="https://user-images.githubusercontent.com/6449871/59104176-25144900-8931-11e9-8b1f-0c5c81df20d6.png">

### Steps to reproduce
1) Deploy `2.0.0-alpha.11` network with 110 nodes, ensure new relic is enabled.
2) Run stress test for all types of transaction
3) Monitor the stats in new relic.

### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0

**Comment by ManuGowda** [comment]
@limiaspasdaniel @fix Here is the performance metrics captured in 1.6.0 before the fix, but yeah this can give some reference how much the degrade happened.

<img width="1016" alt="Screen Shot 2019-06-07 at 14 46 54" src="https://user-images.githubusercontent.com/6449871/59105017-41b18080-8933-11e9-8234-461b9e4e616e.png">

**Comment by fchavant** [comment]
@ManuGowda looks like `post /transactions` actually improved?

**Comment by ManuGowda** [comment]
> @ManuGowda looks like `post /transactions` actually improved?

Yes, maybe we can improve further if possible. but it is not a blocker.

**Comment by ManuGowda** [comment]
@limiaspasdaniel after running stress test for `1.6.0` and re-running stress test for `2.0.0`, the following stats observed in newrelic.

it looks like the performace has improved for some endpoints and there was no degrade, so i am gonna close this issue.
## 1.6.0
<img width="888" alt="Screen Shot 2019-06-11 at 13 50 29" src="https://user-images.githubusercontent.com/6449871/59269724-0626f700-8c50-11e9-89ad-aa4c3a8a534e.png">

# 2.0.0
<img width="834" alt="Screen Shot 2019-06-11 at 13 50 20" src="https://user-images.githubusercontent.com/6449871/59269755-13dc7c80-8c50-11e9-80fc-57e486ee8644.png">

**Comment by limiaspasdaniel** [comment]
That's great then. Thanks @ManuGowda :)
