### ISSUE TITLE
Remove bus from chain module

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#3813]
### Expected behavior
 Since we introduced the new architecture supporting the inter-module communication through the channels, we should use them to facilitate the interactions within the chain modules itself.  

### Actual behavior
To communicate between modules we use the bus (as a helper).

### Steps to reproduce
- the bus helper is removed
- the bus usages are replaced by channel.invoke calls
### Which version(s) does this affect? (Environment, OS, etc...)
`*`

**Comment by lsilvs** [comment]
Also, consider replacing the use of `EventEmitter` as extended class.

Current extended by:
```
framework/src/modules/chain/blocks/blocks.js
framework/src/modules/chain/transaction_pool/transaction_pool.js
```
