### ISSUE TITLE
No longer need to prevent adding ourself as a peer

### ISSUE THREAD

**Issue by jondubois** [LiskHQ/lisk-sdk#3820]
### Expected behavior

Since we have implemented partial view, the probability of adding ourself as a peer is low. Moreover, adding ourself as a peer was not a functionality issue but a performance issue.

### Actual behavior

The current behaviour to prevent adding ourself as a peer creates edge cases in the code which add unnecessary complexity.

### Which version(s) does this affect? (Environment, OS, etc...)
2.3

**Comment by jondubois** [comment]
Upon further analysis, this issue is risky to implement if not done correctly.

Potential risk:

- We need to ignore loopback addresses, otherwise a malicious peer could poison our peer list with loopback addresses and then our node may end up connecting with itself and use up all outbound and inbound slots.

**Comment by shuse2** [comment]
Closing this because it is prevented already, and doesn't have much benefit to remove the code now
