### ISSUE TITLE
Remove registerTransaction check for extending BaseTransaction

### ISSUE THREAD

**Issue by mitsujutsu** [LiskHQ/lisk-sdk#3821]
### Expected behavior

Any custom transaction should not be required to explicitly extend `BaseTransaction` as long as it implements all the required functionality.

### Actual behavior

Currently requires transactions to extend `BaseTransaction` class. 

### Which version(s) does this affect? (Environment, OS, etc...)
2.1

**Comment by shuse2** [comment]
#3877 will introduce enhanced validation
