### ISSUE TITLE
Use channel instead of event emitter

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#3827]
### Expected behavior
Within module, it should consistently use channel instead of event emitter.
Event emitter can handle internal events within modules too.

### Actual behavior
Event emitter was used when removing `bus`

### Which version(s) does this affect? (Environment, OS, etc...)
2.2-

**Comment by shuse2** [comment]
This issue need to consider future impact on the modules which will be in the elements

**Comment by limiaspasdaniel** [comment]
@shuse2, regarding the ongoing BFT implementation, the way events are currently emitted is not consistent, for example EVENT_NEW_BLOCK is not emitted when receiving a block from the network passively and applying it. 

I have an idea in mind to unify this behavior for example by emitting this in `processBlock` or similar, but using channels.

This is what it currently looks like on 2.0:

![image](https://user-images.githubusercontent.com/7485885/60080406-28c90d80-9730-11e9-958d-3a553edbf8cb.png)

We also have to take into account EVENT_NEW_BROADHASH in the new BFT impl.

**Comment by pablitovicente** [comment]
Let's remember to have into account potential cases described in https://github.com/LiskHQ/lisk-sdk/issues/3539

**Comment by shuse2** [comment]
Closing because channel is now consistently use for external communication from the framework, and internally eventEmitter is used.
