### ISSUE TITLE
Add Accounts asset data to the API

### ISSUE THREAD

**Issue by lsilvs** [LiskHQ/lisk-sdk#3847]
### Expected behavior
Expect to get account asset data when requesting accounts from API (`/api/accounts`)

### Actual behavior
No account asset data returned by API

### Steps to reproduce
Run the application.
Access `/api/accounts`

### Which version(s) does this affect? (Environment, OS, etc...)
`2.0`

**Comment by pablitovicente** [comment]
Solution discussed in chat:

- in the controller use `extended: true`
- asset only to be returned for regular accounts
