### ISSUE TITLE
/api/node/status/forging returns "Access Denied"

### ISSUE THREAD

**Issue by TheGoldenEye** [LiskHQ/lisk-sdk#3856]
### Expected behavior
/api/node/status/forging endpoint is running

### Actual behavior
After the update to testnet 2.0.0-rc.0 the "getforging" endpoint is not running anymore.
It returns a {"message":"Access Denied"} error.
The ip of the querying server is in the forging whitelist.

### Steps to reproduce
http://<node_ip>:7000/api/node/status/forging?publicKey=<pub_key>

### Which version(s) does this affect? (Environment, OS, etc...)
testnet 2.0.0-rc.0

**Comment by TheGoldenEye** [comment]
ok found it
the reason is the changed config structure and the migration script did not handle this

The following config.json works for me:
{
  "modules": {
    "http_api": {
      "access": {
        "public": false,
        "whiteList": [
          "127.0.0.1"
        ]
      },
      "ssl": {
        "enabled": true,
        "options": {
          "port": 12345,
          "key": "/etc/letsencrypt/live/current/privkey.pem",
          "cert": "/etc/letsencrypt/live/current/fullchain.pem"
        }
      },
      "forging": {
        "access": {
          "whiteList": [
            "127.0.0.1"
          ]
        }
      }
    },
    "chain": {
      "forging": {
        "delegates": [
          {
            "encryptedPassphrase": "xxxxxxxxxxxxxxx",
            "publicKey": "xxxxxxxxxxxxxxxxxxxxx"
          }
        ]
      }
    }
  }
}

**Comment by shuse2** [comment]
This issue is related to the `update_config` tool in Core. Therefore, I'm moving this issue to the repository.
