### ISSUE TITLE
Follow common developer approach for error handling in transactions

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#3862]
From start we are targeting and speaking about our Lisk SDK, is the first of its kind in JavaScript that will make blockchain accessible to everyone. 

With that said, we should keep in mind that developers with different experience levels and even very beginners will also work with our SDK. So we should keep in mind the common developer approach to write program. 

Or easy to say we should not neglect basic language patterns which every one is familiar of. One of that is `if you have error throw it`. This is very common for developers and they must be familiar and doing this a lot in other projects, which is the user of `throw`. 

Current transaction processing logic does not allow you to throw error, rather we enforce a pattern to collect errors and return as array object from transaction steps `apply` and `undo`. Which could be an additional behaviour for our transaction processing, but we should not neglect the user of `throw` as its very basic language struct. 

We should refactor the processing logic to handle all of below given scenarios; 

```js
apply(store) {
  if(some_condition) {
     throw new Error('Some error in validation.') ;
  }
}
```

```js
apply(store) {
  if(some_condition) {
     return new Error('Some error in validation.') ;
  }
}
```

```js
apply(store) {
  const errors = [];
  if(some_condition) {
     errors.push(new Error('Some error in validation.')); 
  }
  return errors; 
}
```

This also relates to the fact that `enforcing a return value even empty array`, is also against the Javascript paradigm. Yes its an integral concept of functional programming, but our SDK is not here to enforce people to learn functional programming. They should be able to use the Javascript the way they are already doing.  

### Which version(s) does this affect? (Environment, OS, etc...)
2.1.0

**Comment by shuse2** [comment]
This is not possible or makes it user harder to implement what they want consistently.

For returning error vs array of error, it should be only one type.
As coding standard, we have consistent return type, and thats the example we are setting for users.

For throw vs returning error, users can throw error if the error is unhandleable/development error.
However, we have 2 cases that needs to be handled even though it has errors
 - Genesis block
 - Exceptions
Assuming user will have those two cases, we should provide the consistent approach.

@SargeKhan @mitsujutsu whats your take on this issue?

**Comment by nazarhussain** [comment]
Nothing is impossible 😄 It may be harder for implementation on our side as SDK developers. But on SDK user side is more convenient. They got a an error, they throw the error, that approach all had been using for years. 

Returning error as single object or array of objects is an enhanced feature should came along our SDK. If user want to use it, but must be forced to "not use throw".

**Comment by mitsujutsu** [comment]
@shuse2 I see @nazarhussain 's point that throwing is easier to understand and intuitive for developers of custom transactions. However I feel most custom transaction users will benefit from seeing all the validation errors at once, as opposed to one-by-one. Enforcing returned error array at the end ensures we won't have this bad user experience.

**Comment by shuse2** [comment]
With #5603 , this is no longer relevant
