### ISSUE TITLE
Revisit all events and action names in the code base

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#3863]
### Expected behavior
The event names and constants must be very well defined and follow same naming convention. 

### Actual behavior

Currently there is a mix of convention used in the code. 

```js
const EVENT_NEW_BLOCK = 'EVENT_NEW_BLOCK';
const EVENT_DELETE_BLOCK = 'EVENT_DELETE_BLOCK';
const EVENT_BROADCAST_BLOCK = 'EVENT_BROADCAST_BLOCK';
const EVENT_NEW_BROADHASH = 'EVENT_NEW_BROADHASH';

export const EVENT_ADDED_TRANSACTIONS = 'transactionsAdded';
export const EVENT_REMOVED_TRANSACTIONS = 'transactionsRemoved';
export const EVENT_VERIFIED_TRANSACTION_ONCE = 'transactionVerifiedOnce';
export const ACTION_ADD_VERIFIED_REMOVED_TRANSACTIONS = 'addVerifiedRemovedTransactions';
export const ACTION_REMOVE_CONFIRMED_TRANSACTIONS = 'removeConfirmedTransactions';
export const ACTION_ADD_TRANSACTIONS = 'addTransactions';
export const ACTION_EXPIRE_TRANSACTIONS = 'expireTransactions';
export const ACTION_PROCESS_VERIFIED_TRANSACTIONS = 'processVerifiedTransactions';
export const ACTION_VALIDATE_RECEIVED_TRANSACTIONS = 'validateReceivedTransactions';
export const ACTION_VERIFY_VALIDATED_TRANSACTIONS = 'verifyValidatedTransactions';
export const ACTION_ADD_VERIFIED_TRANSACTIONS = 'addVerifiedTransactions';
export const ACTION_ADD_PENDING_TRANSACTIONS = 'addPendingTransactions';
```

I would suggest following pattern `{EVENT|ACTION}_{ENTITY}_{ACTIVITY}`. Where every event/action prefix with `EVENT` or `ACTION` and the entity on which event happens e.g. block, transaction, signature and then actual activity which happens e.g. new, delete. 

### Which version(s) does this affect? (Environment, OS, etc...)
2.1.0

**Comment by michielmulders** [comment]
For consistency, I would also suggest creating a fixed list of terminology for the `{ACTIVITY}`:
- `CREATE`
- `ADD`
- `UPDATE`
- `DELETE`
- `READ`
- `VERIFY`
- `PROCESS`
- `EXPIRE`

**Comment by limiaspasdaniel** [comment]
Thanks, @nazarhussain. I think this is a good improvement proposal and will ease further development/improve consistency in the codebase. 
Extending what @michielmulders has commented, it might be also positive to add a third component: `{STATUS}`. Maybe not for the scope of this issue but it can be taken into account.

For example: `blocks:process:succeeded`.

`{STATUS}` could be one of the following: `STARTED|FAILED|SUCCEEDED`.

Note that if we are using the `channel` we don't necessarily need to prefix event names with `event` as there is a known interface for receiving only events, you can't subscribe for actions by mistake. If we decide to keep using EventEmitter then it's a different scenario.

Improving the naming convention for consistency could open the door for use cases like the following, where not only Chain module would benefit but also other modules developed by the community:

![image](https://user-images.githubusercontent.com/7485885/60164137-5334cc80-97fd-11e9-9a96-ccf0d7443896.png)

**Comment by shuse2** [comment]
This issue has been fixed in `v4`
