### ISSUE TITLE
Transaction must encapsulate its domain "fully"

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#3866]
Each transaction must encapsulate all its logic fully. There should not be any business logic related to a particular transaction defined outside transaction scope.

Currently there are few code mentioned outside their particular domain;

```js
const transactionResponse = transaction.apply(stateStore);
votes.apply(stateStore, transaction, this.exceptions);
stateStore.transaction.add(transaction);
```
In this example it seems vote logic is outside vote transaction. If its not the vote logic, then we should refactor and rename it properly. 

```js
public addMultisignature(
store: StateStore,
signatureObject: SignatureObject,
): TransactionResponse {

public addVerifiedMultisignature(signature: string): TransactionResponse
```
These methods available in base transaction, but actually belongs to the "MultiSignature" transaction. We need to come up with more elegant solution for:

1. If a custom transaction need to change behaviour of `BaseTransaction`, how to define it. 
2. The interface specification or hooks which can be used to hook in or modify base transaction behaviour. 
3. Do we or how we should expose similar functionality for this custom transaction developer 
4. Improve documentation for this behaviour in the SDK

### Which version(s) does this affect? (Environment, OS, etc...)
2.1.0

**Comment by shuse2** [comment]
With the new multisignature #4836 , and vote transaction #4915 , this should be resolved.
