### ISSUE TITLE
Refactor and clean the interfaces for BaseTransaction

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#3867]
The `BaseTransaction` will come under spotlight after SDK release. Everyone will look into it to understand our transaction processing and extend it to create custom transaction. Currently it have a lot of interfaces, which I think can be refactored. Particularly:

1. `fromSync` in `BaseTransaction` is confusing. If its necessary for serialization/deserialization then it should have a clear counterpart `forSync`. 
2. `assetFromSync` seems redundant and confusing in reference to `fromSync`
2. `isExpired` seems to be very specific to transaction pool. I am not sure if its extended in custom transaction, what impact it will have. We may remove it from `BaseTransaction`
3. `verifyAgainstOtherTransactions` is confusing as the reference is not clear. What are "Other transactions", it may be splitted in two `verifyAgainstChain` and `verifyAgainstTransactionPool`.

<img width="911" alt="base_transaction" src="https://user-images.githubusercontent.com/112468/60164194-6ba4e700-97fd-11e9-86bf-40584a40882e.png">

### Which version(s) does this affect? (Environment, OS, etc...)
2.1.0

**Comment by shuse2** [comment]
Although some functions are removed, with #4841 , `verifyAgainstOtherTransactions` and `isExpired` can be removed.
