### ISSUE TITLE
Refactor the interface for state store for better developer experience

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#3868]
Currently we have following interfaces for the state_store. 

1. async cache(filter)
2. createSnapshot()
3. restoreSnapshot()
4. get(primaryValue)
5. getOrDefault(primaryValue)
6. find(fn)
7. set(primaryValue, updatedElement)
8. finalize()

Here is some feedback we can improve; 

1. This store is exposed to transaction with mindset that user will only use `cache `, `get`, `getOrDefault`, `set` and `find`. So we must make all other interfaces private (only by convention) so people know they can't call `finalize` or other. 
2. We should rename `cache` to `getAndStoreToCache` or similar to match its behaviour. Original name `cache` is confusing which refers to get data from cache. 
3. `finalize` meant to return a Promise, it can be declared as `async` to make it clear. 

### Which version(s) does this affect? (Environment, OS, etc...)
2.1.0

**Comment by pablitovicente** [comment]
I think this is a good idea but I would invest more time in framework and then tackle this. I think we can still improve framework more by doing a similar analysis on it.

**Comment by shuse2** [comment]
Definitely good idea. We need to follow the convention. All the "private" one should have the `_` by convention.
Also, `finalize` should be async.

@pablitovicente what's the reason you think it should be investigated more?

**Comment by pablitovicente** [comment]
> Definitely good idea. We need to follow the convention. All the "private" one should have the `_` by convention.
> Also, `finalize` should be async.
> 
> @pablitovicente what's the reason you think it should be investigated more?

I didn't mean about this issue specifically I was thinking about maybe invest more time in revisiting framework and check what we can improve there before moving to elements.

**Comment by nazarhussain** [comment]
The state_store and the issue itself refers to the framework not the elements. If you identity similar problems no matter in framework or element, please create issues for those so we can plan to improve those.

**Comment by shuse2** [comment]
Closing because with #5238, StateStore has been simplified
