### ISSUE TITLE
Split block processing steps into separate functions and expose them from module/blocks

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk-sdk#3869]
### Expected behavior
Block processing includes block and transactions validation, verification and applying into the blockchain. Each step is an expensive operation and should be called only once for each block. As part of BFT, we execute these steps at different stages, and block processing should allow calling these functions independently.
### Actual behavior
process.js file only exports applyBlock and processBlock functions which encapsulate all the work related to validating, verifying and applying a block. It does not allow executing these steps separately. 

### Which version(s) does this affect? (Environment, OS, etc...)
feature/introduce_bft_consensus

**Comment by limiaspasdaniel** [comment]
This could be a way of implementing this based on the steps defined in the section `Processing Blocks` of [LIP-0014](https://github.com/LiskHQ/lips/blob/master/proposals/lip-0014.md#processing-blocks):

```javascript
async _validateAndVerifyInMemory(block, lastBlock, broadcast) {
		const enhancedBlock = !broadcast
			? blocksUtils.addBlockProperties(block)
			: block;
		const normalizedBlock = blocksLogic.objectNormalize(
			enhancedBlock,
			this.exceptions
		);
		const { verified, errors } = this.blocksVerify.verifyBlock(
			normalizedBlock,
			lastBlock
		);
		await this.blocksVerify.validateBlockSlot(normalizedBlock);
	}

	async _verifyBlockAgainsState() {
		await this.blocksVerify.checkExists(normalizedBlock); // Step 4
		await this.blocksVerify.checkTransactions(normalizedBlock); // Step 4
	}

	async processValidatedBlock(block, lastBlock, broadcast) {
		this.BFTConsensusManager.validateBlockHeader(block); //Step 2

		if (typeof broadcast === 'function') {
			broadcast(normalizedBlock); // Step3
		}

		await this.verifyBlockAgainsState(); // Step4
		await this.blocksChain.applyBlock(normalizedBlock, true); // Step 5

		this.BFTConsensusManager.addBlockHeader(
			normalizedBlock
		); // Step 6: Compute prevotes and precommits

		this.channel.publish('chain:blocks:processing:succeeded', {
			block: {
				id: block.id,
				height: block.height,
				heightPrevoted: block.heightPrevoted
			}
		});

		return normalizedBlock;
	}

	async processBlock(block, lastBlock, broadcast) {
		const validatedVerifiedBlock = this._validateAndVerifyInMemory(block, lastBlock); // Step 1
		this.processValidatedBlock(validatedVerifiedBlock, lastBlock, broadcast);
	}
```

**Comment by pablitovicente** [comment]
While at this I would also encapsulate this methods in different objects so we can switch between different processing models on the fly.

**Comment by limiaspasdaniel** [comment]
Absolutely, something like `blocks processing v2` having processV2.js or similar to achieve what Pablo said.

**Comment by pablitovicente** [comment]
> Absolutely, something like `blocks processing v2` having processV2.js or similar to achieve what Pablo said.

Check this out https://github.com/pablitovicente/random_experiments/tree/master/strategy_test (gist does not support folders so I just created a repo but we can move somewhere else :) )

**Comment by yatki** [comment]
https://github.com/LiskHQ/lisk-sdk/blob/4797f8d7c4a4d245e69c8531139b00018da4fc20/framework/src/modules/chain/blocks/process.js#L46-L89 

`processBlocks` funciton does everything that `applyBlock` function does. So, can we get rid of `applyBlock` @SargeKhan ?
