### ISSUE TITLE
Create ip prefix calculation function for peer bucket

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#3874]
### Description

In order to create peer bucket within new/tried peer list we need to calculate /16 IPv4 prefix of peer's IP address.

```
group = /16 IPv4 prefix of peer's IP address
k = Hash(random_secret, IP) % 4
b = Hash(random_secret, group, k) % 64
```

**Comment by mitsujutsu** [comment]
IP prefixing will also be required as part of banning mechanism "netgrouping".
