### ISSUE TITLE
networkHeight in /api/node/status unreliable

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk-sdk#3885]
### Expected behavior
/api/node/status should return "networkHeight" which is the currently valid height in the network. This height could be used to verify if the own node is on the correct height.

### Actual behavior
networkHeight only rarely contains the correct height in the network. Most often it is 0.

### Steps to reproduce
call /api/node/status mutiple times and check "networkHeight" in the returned data. Most often it is 0. Only rarely it returns the correct height.

### Which version(s) does this affect? (Environment, OS, etc...)
core 2.0.0-rc.0 on testnet

**Comment by shuse2** [comment]
Possibly related to #3881
