### ISSUE TITLE
Lisk Hub / Lisk Mobile should always connect

### ISSUE THREAD

**Issue by punkr0ck** [LiskHQ/lisk-sdk#3886]
If you choose "Mainnet" or "Testnet" in Lisk Hub it should always connect. In the past days several users claimed that nodes were offline. Lisk Hub should always pick only nodes that are online, so users never see "failed to connect" again. The current "lottery"-system is bad.

I was told that this seem to be a problem with Lisk Elements.

**Comment by shuse2** [comment]
APIClient is updated, and only connect to specified node now
