### ISSUE TITLE
httpPort and wsPort can not change using Lisk Commander 2.2.0

### ISSUE THREAD

**Issue by hitobb** [LiskHQ/lisk-sdk#3889]
### Expected behavior

1. Install [lisk commander 2.2.0]
2. Install Lisk 2.2.0-rc0 on testnet using the following command
```
lisk core:install -n testnet lisk-testnet
```
3. Execute the following command.
httpPort : 7002, wsPort   : 7003
```
lisk core:status lisk-testnet
```
![lisk-commander-port](https://user-images.githubusercontent.com/14948578/60334568-cc3b4c00-99d6-11e9-8b78-8d92b5309677.png)

4. The default value of testnet is
httpPort : 7000, wsPort   : 7001

  **so,I want to change those value to default one.**

5.  lisk config:set command not support [http_api.httpPort] and [network.wsPort]

```
test@lisk99:~/.lisk/instances/lisk-testnet/config/testnet$ lisk config:set --help
USAGE
  $ lisk config:set VARIABLE [VALUES]

OPTIONS
  -j, --[no-]json  Prints output in JSON format. You can change the default behaviour in your config.json file.

  --[no-]pretty    Prints JSON in pretty format rather than condensed. Has no effect if the output is set to table. You can change the default
                   behaviour in your config.json file.

DESCRIPTION
  Sets configuration.
                ...
                Variables available: api.nodes, api.network, json, pretty.

EXAMPLES
  config:set json true
  config:set api.network main
  config:set api.nodes https://127.0.0.1:4000,http://mynode.com:7000

test@lisk99:~/.lisk/instances/lisk-testnet/config/testnet$
```

### Actual behavior

I want to change those value to default one.

---
It seems to need fix for two problems.

 - [lisk config:set] command should be support [http_api.httpPort] and [network.wsPort]
 - Change the default value to [httpPort7000,wsPort7001] when installing lisk core with lisk commander.

### Steps to reproduce

Same the Expected behavior

### Which version(s) does this affect? (Environment, OS, etc...)

Lisk core : Testnet Lisk 2.0.0-RC0 
Lisk commander : 2.2.0

**Comment by shuse2** [comment]
Command to run core is moved to `lisk-core` since lisk-core v3, so im closing this issue
