### ISSUE TITLE
Introduce error codes to act and debug easily through out the system

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#3899]
### Actual behavior

Currently we are using different error constructors to identify the right error occurred in the system. That helps to not just identify error but also helps in debugging. 

But with growing system we may end up in huge list of such error constructors, which will decrease on boarding to message. 

https://github.com/LiskHQ/lisk-sdk/blob/fa29121e93e5369cfeaf671480d740e3e78824ef/framework/src/errors.js#L34

https://github.com/LiskHQ/lisk-sdk/blob/fa29121e93e5369cfeaf671480d740e3e78824ef/framework/src/errors.js#L50

https://github.com/LiskHQ/lisk-sdk/blob/fa29121e93e5369cfeaf671480d740e3e78824ef/framework/src/errors.js#L69

https://github.com/LiskHQ/lisk-sdk/blob/fa29121e93e5369cfeaf671480d740e3e78824ef/framework/src/modules/chain/bft/errors.js#L29

https://github.com/LiskHQ/lisk-sdk/blob/fa29121e93e5369cfeaf671480d740e3e78824ef/framework/src/modules/chain/bft/errors.js#L37

### Expected behavior
So we need to reduce the error constructors and have few very generic ones. And also we don't want to handle all cases by long error messages, that usually end up in regular expression matching on error messages if you want to check of couple of cases. 

I suggest to introduce error codes with generic error constructors. That would be easy to know small set of generic error constructors as well extensible to define different error codes to pin point the right error case. 

### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0

**Comment by shuse2** [comment]
Error code has been introduced in the framework errors
