### ISSUE TITLE
Misleading validation function name

### ISSUE THREAD

**Issue by lsilvs** [LiskHQ/lisk-sdk#3902]
### Expected behavior
Expect the `isValidNumber` function inside `lisk-transactions` to return `true` when `isValidNumber('-1')`

Also expect to have tests for `isValidNumber` function.

### Actual behavior
Currently it returns `true` for `isValidNumber(-1)` but returns `false` for `isValidNumber('-1')`.
This is happening because `isValidNumber` uses `isNumberString` which has a regex allowing only `0-9` numbers.

### Steps to reproduce
```
const { isValidNumber } = require('./validation.ts');

isValidNumber('-1'); //? false
```

### Which version(s) does this affect? (Environment, OS, etc...)
2.*

### Addional Information
- isValidNumber is used to check only the positive number now, so the naming should be isValidPositiveNumber

**Comment by shuse2** [comment]
Closing becuase `isValidNumber` is removed along with codec issues
