### ISSUE TITLE
Modules should not extend EventEmitter class

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk-sdk#3904]
### Expected behavior
General purpose classes which trigger events should declare a variable `emitter` which fires events from this class.
### Actual behavior
Classes inherit EventEmitter class which should not happen because these classes include behavior which extends much more than to simply emitting events. See: https://github.com/LiskHQ/lisk-sdk/pull/3853#discussion_r299462427

**Comment by shuse2** [comment]
Superseded by #4825
