### ISSUE TITLE
Configuration parameter broadcastLimit is no longer used

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk-sdk#3905]
### Expected behavior
Breaking changes should be documented and reflected in tests.
### Actual behavior
Looks like `modules.chain.broadcasts.broadcastLimit` (previously used only for blocks broadcasts) was changed to `modules.network.emitPeerLimit` and behavior is now different (it's used for other things also).
- 🚫 Documentations is outdated
https://github.com/LiskHQ/lisk-docs/blob/dev-sdk-2.0.0/configuration.md
https://github.com/LiskHQ/lisk-docs/blob/dev-core-2.0.0/configuration.md
- 🚫 Changes are not reflected in tests
https://github.com/LiskHQ/lisk-sdk/blob/88e88a452523e5644cade105485c441470e39c0c/framework/test/mocha/unit/modules/chain/transport/broadcaster.js#L45 https://github.com/LiskHQ/lisk-sdk/blob/a153a03a04278ca393e7aebd67194195ab49cdbb/framework/test/jest/unit/specs/controller/__snapshots__/application.spec.js.snap#L65
- ✅ Changes are reflected in `update_config.js`
https://github.com/LiskHQ/lisk-core/blob/master/scripts/update_config.js
### Steps to reproduce
N/A
### Which version(s) does this affect? (Environment, OS, etc...)
`2.0.0-rc.0`

**Comment by ishantiw** [comment]
Resolved different parts of this issue in different PRs,

- PR LiskHQ/lisk-docs#292 🚫 Documentations is outdated-> https://github.com/LiskHQ/lisk-docs/blob/dev-sdk-2.0.0/configuration.md

- PR LiskHQ/lisk-docs#294 🚫 Documentations is outdated-> https://github.com/LiskHQ/lisk-docs/blob/dev-core-2.0.0/configuration.md

- PR #3909 🚫 Changes are not reflected in tests in Framework
