### ISSUE TITLE
Validate each transaction property with its own method

### ISSUE THREAD

**Issue by pablitovicente** [LiskHQ/lisk-sdk#3912]
### Expected behavior

Each transaction property has its own validator (this was a suggestion by Lucas/Nazar in #3893)

### Actual behavior

We have a single validate method that uses some methods for some properties

### Steps to reproduce

Check the `validate()` method in baseTransaction.

### Which version(s) does this affect? (Environment, OS, etc...)
2.1

**Comment by shuse2** [comment]
Although it's not the case right now, I think I prefer to keep the base transaction property not exposable and we use them as minimal requirement for any transaction and behaive the same.

For example, if custom transaction starts to allow fee or senderPublicKey not mandatory, the core processing will not work.

**Comment by lsilvs** [comment]
Currently we have the following validations inside `BaseTransaction.validate()`:
```
validateSchema()
validateAsset()
validateSignature()
validateTransactionId()
validateFee()
```
Being able to overwrite a particular one is a nice feature imo

**Comment by shuse2** [comment]
Closing because it is outdated
