### ISSUE TITLE
Target specific peers in Block Sync Mechanism

### ISSUE THREAD

**Issue by limiaspasdaniel** [LiskHQ/lisk-sdk#3916]
### Expected behavior
In Block Sync Mechanism we need to target specific peers when finding a common block, requesting blocks or banning in Block Sync Mechanism (`block_sync_mechanism.js`)

This issue is a part of #3771

This feature will be merged from P2P branch once completed, then this issue can be tackled.
### Actual behavior
We are not
### Which version(s) does this affect? (Environment, OS, etc...)
`feature/introduce_bft_consensus`

**Comment by shuse2** [comment]
Superseded by #3565
