### ISSUE TITLE
Use transaction not transactions in lisk-client readme

### ISSUE THREAD

**Issue by RachBLondon** [LiskHQ/lisk-sdk#3925]
### Expected behavior
Instructions to import transaction should work correctly in readme

### Actual behavior
There is no `transactions object`  `lisk-client`, `transaction` is available instead

### Steps to reproduce
`import { APIClient, transactions } from '@liskhq/lisk-client';`

### Which version(s) does this affect? (Environment, OS, etc...)
OS, imported `@liskhq/lisk-client` in to a create-react-web-app, should this be fixed at the readme or codebase level?

**Comment by shuse2** [comment]
This should be `transactions` for consistency with other packages, but for historical reason that's not the case.
However, doing so will be a breaking change.
Let's export `transactions` and `transaction` until the next major release.
