### ISSUE TITLE
Introduce semantic versioning for custom transaction compatibility check

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#3935]
### Expected behavior
There must be a well defined pattern to communicate, document and explain to users about the interface for the custom transaction. And to distinguish between different breaking changes. This should also cover the scenario if user is using `lisk-transactions` package directly to create their transaction and not using `lisk-sdk` or `lis-framework`. 

So the suggestion is to add a static versioning number to the `BaseTransaction` which can be accessed by `BaseTransaction.version`. So once you register a particular transaction with the app through `app.registerTransaction`, framework can identity the version and match agains the version compatible to the framework. This `version` must follow semantic versioning, then it will be easy to identify and communicate the breaking changes. 

We can or not link this version to the package version of `lisk-transactions`, based on the definition of what is exported from the `lisk-transactions`. If there are utility functions then its not possible and we have to introduce different version for BaseTransaction. 

This will also help us to document the custom transaction interface in our docs and also communicate on different developer forums. And when we introduce any breaking change, we can refer back/forth to those documentations. 

### Actual behavior
Currently we are just matching public functions names on the transaction class and there is no way to communicate to users about breaking changes in that interface for future. 

### Which version(s) does this affect? (Environment, OS, etc...)

**Comment by shuse2** [comment]
We have decided not to use the version, but type field will be incremented
