### ISSUE TITLE
Improve the blocks and processing tests to have more declarative expectations

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#3949]
### Expected behavior

We introduced new integration test for blocks and transactions processing. `framework/test/mocha/integration/blocks/blocks_and_transactions.js`. 

These tests should be improved to have more declarative expectations.

```js
expect(bat.getTransactionsInLastBlock()).to.deep.equal(
					[valid_trs1, valid_trs2]
				);
```

### Actual behavior

Currently we are have a logic encapsulated in a helper which generates the valid expectations. on runtime. Which is good for given scenario, but if we can refactor and have more declarative expectations that will be great. 

```js
expect(bat.getTransactionsInLastBlock()).to.deep.equal(
					bat.getValidSortedTransactions()
				);
```

### Which version(s) does this affect? (Environment, OS, etc...)
2.x

**Comment by shuse2** [comment]
Closing because outdated, and the new jest test should have improvement from this
