### ISSUE TITLE
Add P2P QA test to verify that shuffling is working as expected in outbound

### ISSUE THREAD

**Issue by jondubois** [LiskHQ/lisk-sdk#3953]
### Expected behavior

There should be a QA test to verify that the network is not completely static and that nodes change peers from time to time. According to the LIP, for each node in the network, a random peer should be kicked out of its peer list (and disconnected) once every 5 minutes.

### Actual behavior

There are no QA tests to verify shuffling. This feature did not exist prior to v2.3.

### Which version(s) does this affect? (Environment, OS, etc...)

v2.3

**Comment by ishantiw** [comment]
After analyzing the logs in the alpha network, I have captured shuffling behavior which seems to remove a peer in every shuffling interval for outbound nodes. Below is some part of the logs. Since the behavior is working as expected, I will close this issue.

```js
BEFORE
[ '104.248.203.30',
  '104.248.205.28',
  '104.248.152.25',
  '167.71.78.28',
  '134.209.233.122',
  '104.248.197.223',
  '159.65.189.208',
  '167.71.237.151',
  '68.183.207.188' ]
AFTER
[ '104.248.203.30',
  '104.248.205.28',
  '104.248.152.25',
  '167.71.78.28',
  '134.209.233.122',
  '104.248.197.223',
  '159.65.189.208',
  '167.71.237.151' ]
```
```js
BEFORE
[ '104.248.203.30',
  '104.248.205.28',
  '104.248.152.25',
  '167.71.78.28',
  '134.209.233.122',
  '104.248.197.223',
  '159.65.189.208',
  '167.71.237.151',
  '134.209.62.221',
  '165.22.137.10',
  '104.248.146.160',
  '68.183.74.106',
  '167.71.233.61',
  '104.248.193.153',
  '165.22.192.207',
  '157.230.217.174',
  '68.183.204.124',
  '167.71.239.234',
  '134.209.25.221' ]
AFTER
[ '104.248.203.30',
  '104.248.152.25',
  '167.71.78.28',
  '134.209.233.122',
  '104.248.197.223',
  '159.65.189.208',
  '167.71.237.151',
  '134.209.62.221',
  '165.22.137.10',
  '104.248.146.160',
  '68.183.74.106',
  '167.71.233.61',
  '104.248.193.153',
  '165.22.192.207',
  '157.230.217.174',
  '68.183.204.124',
  '167.71.239.234',
  '134.209.25.221' ]
```
