### ISSUE TITLE
Isolate nextForge and nextSync implementation from registering logic

### ISSUE THREAD

**Issue by limiaspasdaniel** [LiskHQ/lisk-sdk#3958]
### Expected behavior
`nextForge` and `nextSync` tasks implementations should be defined outside of the logic responsible of registering the tasks.

For example:
`jobsQueue.register('taskName', implementation)`

instead of:
`jobsQueue.register('taskName', () => { // stuff })`

This simplifies code readability, isolation, and testing.

`nextForge` and `nextSync` are implemented in: 

**_startForging**: `framework/src/modules/chain/chain.js:501`
**_startLoader**:`framework/src/modules/chain/chain.js:459`

### Actual behavior
`nextForge` and `nextSync` are two tasks that are registered to the `jobsQueue` but their concrete implementation is too coupled to this logic.
### Which version(s) does this affect? (Environment, OS, etc...)
`release/2.2`

**Comment by yatki** [comment]
@limiaspasdaniel please don't forget to use `// Arrange & Act & Assert` comments to organise code blocks. Cheers,
