### ISSUE TITLE
Test to check if a node is choosing peers to connect consistently across the buckets

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#3967]
### Expected behavior

Add test to check if the peers consistently selected from different buckets to connect instead of giving preference to one or a few buckets that can be used by a local attacker to push its IP addresses.

This is to test the following feature from [LIP-0004- Introduce robust peer selection and banning mechanism](https://github.com/LiskHQ/lips/blob/master/proposals/lip-0004.md)
> peers are randomly selected from a collection with sufficient diversity because IP addresses from the same group only hash to 4 different buckets. This protects against a local attacker that has a lot of IP addresses only in one group

### Actual behavior

There are no QA tests to test peer buckets. This feature did not exist prior to `v3.0`.

### Which version(s) does this affect? (Environment, OS, etc...)
`v3.0`

**Comment by shuse2** [comment]
Closing since it's covered in the unit test
