### ISSUE TITLE
Update process tests

### ISSUE THREAD

**Issue by pablitovicente** [LiskHQ/lisk-sdk#3979]
### Expected behavior

Process tests are re-implemented

### Actual behavior

During refactors for 2.2 we removed the implementations of process.js tests 

### Steps to reproduce

Check `framework/test/mocha/integration/blocks/process/process.js`

### Which version(s) does this affect? (Environment, OS, etc...)

2.2.*

**Comment by shuse2** [comment]
Superseded by #4043
