### ISSUE TITLE
Enable ESLint rule to require usage of `use strict`

### ISSUE THREAD

**Issue by limiaspasdaniel** [LiskHQ/lisk-sdk#3989]
### Expected behavior
`ESLint` should require `use strict` to be written in the top of a file.

To achieve this, this ESLint rule has to be enabled: https://eslint.org/docs/rules/strict?origin_team=T3CBPJ17X

### Actual behavior
We are not checking whether files are making use of the `use strict` statement.
### Which version(s) does this affect? (Environment, OS, etc...)
`*`

**Comment by shuse2** [comment]
Closing because we have added the typescript setup for all the packages, and this is no longer relevant
