### ISSUE TITLE
Remove empty Jenkinsfile

### ISSUE THREAD

**Issue by fchavant** [LiskHQ/lisk-sdk#3993]
### Expected behavior
There are no Jenkinsfile in this repository doing nothing.

### Actual behavior
[framework/Jenkinsfile](https://github.com/LiskHQ/lisk-sdk/blob/release/2.2.0/framework/Jenkinsfile) is virtually empty.

**Comment by shuse2** [comment]
This issue needs to be done with 2.2 branch
