### ISSUE TITLE
Update Produce Block

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-sdk#4001]
### Description

When `undo` is called, it should update the produced block by decrementing 1 from the current value

### Motivation
In order to maintain the feature for the HTTP API and explorer, we need to maintain the produced block.

### Acceptance Criteria
- it should update the produced block when deleting the block from the end of the round

**Comment by pablitovicente** [comment]
Code seems to be completed for this. Tests need to be checked or implemented if they were not.
