### ISSUE TITLE
Update delegates ranks at the end of the round 

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-sdk#4006]
### Description

On `undo` step of the round calculation, if the undoing block is the beginning of the round, `rank` of the mem_account should be updated.

### Motivation
In order to maintain the http_api endpoint, we need to keep the `rank` property calculation up to date.

### Acceptance Criteria
- it should not change the rank if the block is not first block of the round
- it should update the rank if the block is first block of the round

### Additional Information

**Comment by nazarhussain** [comment]
> it should update the rank if the block is first block of the round 

@SargeKhan @yatki Why on first block of the round, why not last block of round? Which is existing behaviour?

**Comment by SargeKhan** [comment]
@nazarhussain, do we need this feature as part of the chain module implementatoin or can implement this functionality in http_api module?

**Comment by SargeKhan** [comment]
As for your question, we should replicate the existing behavior, and perform this at the end of the round. I agree.

**Comment by lsilvs** [comment]
@SargeKhan I like the idea of removing `rank` from Chain Module. It seems to be used only by HTTP API and we can achieve the same results by using `vote` attribute instead.

**Comment by nazarhussain** [comment]
@LucasIsasmendi It was previously been done through vote attribute and we added this rank column due to performance impact. Don't see any reason of going back to old approach and degrade the API performance. 

Once we plan to remove **rank** from the API then we can completely remove it from backend as well. Till then been part of chain module is ok.

**Comment by lsilvs** [comment]
Why we have performance issue when sorting by `vote` and not when sorting by `rank`?

**Comment by nazarhussain** [comment]
We have sort option by **rank**, we have to calculate it runtime for all delegates and then sort the results. That cause performance bottle neck. You can find details, existing implementation and all discussion on this issue. https://github.com/LiskHQ/lisk-sdk/issues/2351

**Comment by lsilvs** [comment]
The queries
`SELECT "publicKey" FROM mem_accounts WHERE "isDelegate" = 1 ORDER BY rank DESC;` and
`SELECT "publicKey" FROM mem_accounts WHERE "isDelegate" = 1 ORDER BY vote DESC;` should be equivalent, no?

**Comment by nazarhussain** [comment]
:) Not just vote but public key as well. See original query in the issue.

**Comment by yatki** [comment]
@nazarhussain this issue seems to be for "undo". It's unlikely but maybe @shuse2 meant the last block of the round but while undoing last block is the the first to undo :D @shuse2 could you clarify :D

**Comment by nazarhussain** [comment]
@4miners As discussed with @shuse2 please check with the community the current and possible usage of `rank` attribute in `/api/delegates` endpoint. So we can safely remove this attribute or come up with other solution for the use cases.

**Comment by 4miners** [comment]
I would recommend keeping the `rank` attribute. It's useful to know the position of a particular delegate without having to fetch all the delegates to calculate this - for example you can display the rank of your own delegate on the website, make a chart, etc. This property is also used in third-party tools.

**Comment by shuse2** [comment]
Since this will be confusing after the BFT changes, we decided to remove.
Reasoning:
- We can display one ranking, but which ranking should it show? Current delegate list ranking (2 rounds before), or current vote weight ranking or the last delegate list ranking
- For current vote weight ranking, it will be able to fetch with limit and offset with order
