### ISSUE TITLE
does lisk-framework need a fixed node version?

### ISSUE THREAD

**Issue by tobiaslins** [LiskHQ/lisk-sdk#4009]
Does `lisk-framework` really need a fixed node version? 
What about using `>=10.0 <=10.16` or something like that

### Actual behavior
While installing `lisk-sdk` with npm I'll get an error 
```
error lisk-framework@0.2.0: The engine "node" is incompatible with this module. Expected version "10.15.3". Got "10.5.0"
```

**Comment by shuse2** [comment]
Thank you for reporting the issue.
`lisk-framework` should allow the ranged node version, while `lisk-core` should have the fixed version.

**Comment by shuse2** [comment]
Minimum node version should be 10.4 to support Bigint in the future
