### ISSUE TITLE
Total supply not updated after custom, cashback, transaction

### ISSUE THREAD

**Issue by Korben3** [LiskHQ/lisk-sdk#4015]
### Description

After performing the custom cashback transaction from the provided SDK tutorials. It seems that the total supply has not been updated.

call after tx with 10% bonus was broadcasted: ```http://127.0.0.1:4000/api/node/constants```
result: ```
{
   .<snip>..
      "supply" : "10000000000000000",
      "milestone" : "0"
   },
   "links" : {}
}```

The transaction was broadcasted successfully. Balances of both accounts are updated. Since there are now more tokens on the network, just as when tokens are forged, the total supply should be updated as well.

**Comment by nazarhussain** [comment]
Its actually not possible or at least not possible in current structure. Total supply is calculated statically from some basic values. Which are genesis block value and rewards. Its not possible to change that value in case of cash back transaction. Even if we change it runtime, in case the application restart we will loose that. 

And its not possible to look into storage layer and find out which transactions generated extra supply. The only possibility left is to persist this value, even then finding that which transaction generated how much extra supply is not possible in current structure or not efficient. 

@shuse2 We may be able to calculate runtime value from storage, but with recent change in DPOS will restructure the rewards values. So I suggest to not address this issue at the moment and after we are done with BFT and new DPOS restructuring.

**Comment by shuse2** [comment]
@nazarhussain Thank you for looking into it, and agree with your points.
Let's schedule it later and think about the solution more carefully.

**Comment by karek314** [comment]
It could be solved quite simply by keeping track of added and deduced amount in total, in very simple field in db ?

**Comment by shuse2** [comment]
calculating the total reward is complex in the system, and it does not affect the protocol. Therefore, it should be done in the second layer in the future
