### ISSUE TITLE
DB layer + TypeScript heads-up

### ISSUE THREAD

**Issue by vitaly-t** [LiskHQ/lisk-sdk#4016]
For old-time-sake, this is just a heads-up on the database development, since I'm not on the Slack anymore.

The main drive toward the recent release of [pg-promise v9.0.0](https://github.com/vitaly-t/pg-promise/releases/tag/9.0.0) was going all-TypeScript, or at least as much as possible. I did have temptations to even start rewriting things natively in TypeScript, but it is normally all-or-nothing kind of architecture, so that part was left in JavaScript.

I have done some projects recently, for Node.js, of impressive size, and today I will say, I'm not touching bare JavaScript anymore. The amount of time and grief it saved me by writing everything in TypeScript, I cannot put a price on it.

I think that making Lisk 100% TypeScript will prove the best value for the project. And as far as [pg-promise] is concerned, it just got a bit more friendly toward TypeScript, which is the proper way of using it today. I also have updated [pg-monitor] and [pg-promise-demo] to keep up.

All the best!!!

[pg-promise-demo]:https://github.com/vitaly-t/pg-promise-demo
[pg-monitor]:https://github.com/vitaly-t/pg-monitor
[pg-promise]:https://github.com/vitaly-t/pg-promise

**Comment by shuse2** [comment]
@vitaly-t 
Thank you for the update! Totally agree with your points!
We are gradually making the Lisk-SDK and Lisk-Core to be fully TypeScript.

**Comment by vitaly-t** [comment]
@karmacoma Hi Oliver! In case your team needs help with anything like that, or database-related, I have some time available these days, can get on-board for a bit, if needed.
