### ISSUE TITLE
Don't use hardcode config options in the jest tests

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#4028]
In jest tests there re few places where `activeDelegates = 101` is hardcoded. We should use the unified configuration generated from application or configurator to get such values. 

https://github.com/LiskHQ/lisk-sdk/blob/3b34e29a99cf45f029b9bfc7abe4ee05bb825585/framework/test/jest/unit/specs/modules/chain/bft/bft.spec.js#L74

https://github.com/LiskHQ/lisk-sdk/blob/3b34e29a99cf45f029b9bfc7abe4ee05bb825585/framework/test/jest/unit/specs/modules/chain/bft/finality_manager.spec.js#L112

**Comment by shuse2** [comment]
I think for unit test it's a good practice to make it as deterministic as possible.
If number of active delegate is an input, then it should test against 101, and other values like 10 or 50 etc
