### ISSUE TITLE
Strongly-typed events

### ISSUE THREAD

**Issue by vitaly-t** [LiskHQ/lisk-sdk#4042]
In relation to #3908, #3904, #3827 and #3539, plus general TypeScript makeover...

I was recently struggling with events in my own project, and ended up writing [my own module](https://github.com/vitaly-t/sub-events) to handle events, in case it is of any interest here.

Since you are transforming into TypeScript, strongly-typed events is a must-have.

**Comment by vitaly-t** [comment]
Version [0.7.0.] added very useful [diagnostics], to help counter memory leaks and performance degradation.

[0.7.0]:https://github.com/vitaly-t/sub-events/releases/tag/0.7.0
[diagnostics]:https://github.com/vitaly-t/sub-events/wiki/Diagnostics

**Comment by shuse2** [comment]
Closing this issue since value added is small, and mostly already implemented
