### ISSUE TITLE
Block creation logic extension

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-sdk#4049]
### Description

Ability to extend block generation logic in similar fashion to custom transactions.

### Motivation

Execute specific code, each X blocks. For example dividend distribution in case of autonomous companies.

### Acceptance Criteria

Ability to extend block creation logic, modifying account balances should be doable from that scope.

### Additional Information
N/A

**Comment by nerdvibe** [comment]
+1 on this. In our case we would like to implement some custom logic on the block creation. An example would be to implement some custom rules on the way the inflation is spread. I'm not sure we are missing something on this and there is an alternative way, but a block creation logic module would be really helpful.

cheers,
🍝Carbonara team

**Comment by simonmorgenthaler** [comment]
I'd like to see that functionality too. I think it would allow a lot more use cases. One could be to run some code on every block creation. This would allow to execute automatic code (like a cronjob, executed every 10 sec) and would make the business logic independent from sent transactions (if needed). Such functionality is not present in other chains like for example Ethereum and could be a big advantage for Lisk

**Comment by shuse2** [comment]
Closing since this is now possible with new on-chain architecture #5603
