### ISSUE TITLE
Check the sync is working with closed inbound

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-sdk#4052]
Verify that the node can sync while the inbound `wsPort` is closed.

Scenarios to check:
1. Node can sync from genesis
2. Node can sync after reaching the max network height

**Comment by jondubois** [comment]
I tested the scenarios on devnet (running only v2.3 nodes).

I verified the first sync scenario by running the node on localhost with a fresh database and connecting to devnet. The node was able to sync from scratch.

To verify the second scenario, I ssh'ed into a node on devnet which was already at a good height. I also watched the HTTP API endpoint `/api/blocks` to monitor the current height and checked that it was receiving blocks passively from the network. Then I blocked the inbound `wsPort` (port `5000`) using firewall rules on Digital Ocean.

- The logs indicated that the node was still synching.
- The node height continued to increment every 10 seconds.
- Opening the port allowed the node to exit sync mode and return to receiving blocks passively.
