### ISSUE TITLE
Postgres default connection is too heigh

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#4062]
### Expected behavior
Postgresql default max number of connection is 100, so the SDK should comply with the max number of connection

### Actual behavior
Currently max connection is 95 * 3 modules, which is 275.
Therefore, for some case, it will hit the max number of connection.
```
07:11:24.880Z ERROR lisk-framework: remaining connection slots are reserved for non-replication superuser connections (err.code=53300)
    error: remaining connection slots are reserved for non-replication superuser connections
        at Connection.parseE (/Users/x/xxx/node_modules/pg/lib/connection.js:554:11)
        at Connection.parseMessage (/Users/x/xxx/node_modules/pg/lib/connection.js:379:19)
        at Socket.<anonymous> (/Users/x/xxx/node_modules/pg/lib/connection.js:119:22)
        at Socket.emit (events.js:189:13)
        at Socket.EventEmitter.emit (domain.js:441:20)
        at addChunk (_stream_readable.js:284:12)
        at readableAddChunk (_stream_readable.js:265:11)
        at Socket.Readable.push (_stream_readable.js:220:10)
        at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
07:11:24.883Z  INFO lisk-framework: Cleanup controller...
07:11:24.883Z ERROR lisk-framework: Reason: Error: DB Connection Error
```

### Steps to reproduce
Starting the application with default setup

### Which version(s) does this affect? (Environment, OS, etc...)
2.0-

**Comment by kplusq** [comment]
I had a same error in v2.2.0, but there was no trouble in v2.1.0.
There were three instance at v2.1.0. however from v2.2.0, there are four since controller has own connection.
It's just a guess but, is there a possibility that the change might have caused it?
.

**Comment by kplusq** [comment]
Sorry, that was my misunderstanding.
I suppose the problem has nothing to do with the number of instance, but a timing of `loadBlockChain` execution .
In v2.1.0, API module and Network module are loaded before loading Blockchain. 
However in v2.2.0, it seems loading those modules are called after loading Blockchain.
so in that case, if max setting is 95, full of connections are used by Chain module.

**Comment by nazarhussain** [comment]
I agree, that default value was carry forward when every thing was using single db object. Now since load been splitted between modules so default max connection can be reduced.
