### ISSUE TITLE
Commander core commands for remote node(s) 

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk-sdk#4066]
### Description
It would be nice if all the commander core commands (install, status, upgrade, etc...) could not only be used on the local node, but also for remote nodes. It would be even better if multiple nodes could be managed at the same time with one single command (eg lisk core:upgrade node1 node2 node3) 

### Motivation
It would be useful for delegates to manage their nodes, and also for developers who want to set up their own little testbed with multiple nodes. Tjey could install, upgrade and monitor multiple nodes from a single management machine.

**Comment by shuse2** [comment]
Closing this issue since this is no longer valid
