### ISSUE TITLE
Transaction pool logs redundant info logs

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#4072]
### Expected behavior
Instead of actively logging transaction pool data, the better approach would be to log the transaction pool info when we receive any transaction for processing, this way we can avoid redundantly logging `Transaction pool - received size: 0 validated size: 0 verified size: 0 pending size: 0 ready size: 1`  
### Actual behavior
Active logging of transaction pool makes the `info` logs redundant
### Steps to reproduce
- Deploy `2.3.0-alpha.1`
- Monitor logs
### Which version(s) does this affect? (Environment, OS, etc...)
2.3.0

**Comment by shuse2** [comment]
This message is only logged when a transaction is removed from transaction pool. https://github.com/LiskHQ/lisk-sdk/blob/release/2.3.0/framework/src/modules/chain/transaction_pool/transaction_pool.js#L197

Therefore, it only log when new block, expire block or invalid transactions filters remove the transaction from the pool passively
