### ISSUE TITLE
When a peer asks us for our peer list, we should not report the state property

### ISSUE THREAD

**Issue by jondubois** [LiskHQ/lisk-sdk#4073]
### Expected behavior

When a peer asks for our peer list, our node should not report the state property.
This will likely cause a hard fork with 1.x nodes so it should be implemented as a major release.

As for the `getPeerList` endpoint, it should only return ip:port as described in https://github.com/LiskHQ/lips/blob/master/proposals/lip-0004.md#peer-discovery-messages

### Actual behavior

Because old 1.x nodes expect the `state` property, we had to also add it in the new `2.x` versions of the SDK for compatibility reasons.

However, security-wise, it's not a good idea to tell peers about which other peers we are connected to; for this reason we hardcoded the value to always be `2`.

### Which version(s) does this affect? (Environment, OS, etc...)

2.x

**Comment by ishantiw** [comment]
- To move `consolidatePeers` and `filterByParams`  from the network module to `http_api` module
- use `state` value as `connected` & `disconnected`
- create separate actions, `getConnectedPeers` and `getDisconnectedPeers` on network module
