### ISSUE TITLE
Send back correct error message when action is private

### ISSUE THREAD

**Issue by michielmulders** [LiskHQ/lisk-sdk#4080]
### Expected behavior
Return proper error message when the action is not public.
--> [Referring to discussion leading up to this issue](https://github.com/LiskHQ/lisk-sdk/issues/4070#issuecomment-520894045).

Expected error message: `The action ACTION_NAME on module MODULE_NAME is not public`.

### Actual behavior
Not clear from error what has gone wrong.

### Steps to reproduce
Define an action as private and call the action.
`channel.invoke('chain:mytestaction', ...)`

### Which version(s) does this affect? (Environment, OS, etc...)
2.*

**Comment by pablitovicente** [comment]
Maybe we should discuss a little deeper about channels check for other issues we need to check/guard against https://github.com/LiskHQ/lisk-sdk/issues/3539
