### ISSUE TITLE
PeerPool removePeer should allow code or reason as parameter

### ISSUE THREAD

**Issue by mitsujutsu** [LiskHQ/lisk-sdk#4083]
### Expected behavior

`removePeer` should accept `reason` string for disconnect reason so logs are more descriptive.

### Actual behavior

Currently when inbound peer evicted it shows message: `INbound connection of peer 157.230.222.179:5000 was closed with code 1000 and reason: undefined`

### Steps to reproduce

SSH into alphanet 2.3.0 node and view logs. 

### Which version(s) does this affect? (Environment, OS, etc...)
2.3

**Comment by jondubois** [comment]
Also we should fix that typo with the capital `N` in `INbound connection of peer...`.
