### ISSUE TITLE
Superfluous use of promises

### ISSUE THREAD

**Issue by vitaly-t** [LiskHQ/lisk-sdk#4095]
https://github.com/LiskHQ/lisk-sdk/blob/a800c3217e50a94c5e865febd0240ddd834dfb3c/framework/src/modules/chain/blocks/blocks.js#L231

This entire piece:

```js
const { blocksCount, genesisBlock, memRounds } = await new Promise(
    (resolve, reject) => {
        this.storage.entities.Block.begin('loader:checkMemTables', async tx => {
            try {
                const result = await blocksUtils.loadMemTables(this.storage, tx);
                resolve(result);
            } catch (error) {
                reject(error);
            }
        });
    },
);
```

Can be just this:

```js
const { blocksCount, genesisBlock, memRounds } =
    await this.storage.entities.Block.begin('loader:checkMemTables', tx => blocksUtils.loadMemTables(this.storage, tx));
```

And the result will be identical.

**Comment by vitaly-t** [comment]
In addition to it, the code has tons of invalid use of `resolve` and `reject` calls...

Search for all of the following entries:

* `return resolve(`, `return Promise.resolve(`
* `return reject(`, `return Promise.reject`

and remove `return` everywhere, because methods `resolve` and `reject` never return anything. That's the promise spec, and is a known error when working with promises.

**Comment by shuse2** [comment]
@vitaly-t For the second part, we are aware of the callback not returning anything.
It's more for stopping the execution at point.
so instead of doing,
```
resolve(x);
return;
```
it's doing
```
return resolve(x);
```
It's misleading so definitely better to do in the first approach.

**Comment by vitaly-t** [comment]
@shuse2 I was mostly talking about where it is not the case. Here's just a few such cases:

* https://github.com/LiskHQ/lisk-sdk/blob/a800c3217e50a94c5e865febd0240ddd834dfb3c/framework/test/mocha/network/network.js#L75
* https://github.com/LiskHQ/lisk-sdk/blob/a800c3217e50a94c5e865febd0240ddd834dfb3c/framework/test/mocha/network/network.js#L88
* https://github.com/LiskHQ/lisk-sdk/blob/280ac4e9c8daf459e297a54aa547404d6d7b3971/framework/test/jest/unit/specs/modules/chain/utils/sequence.spec.js#L85
* https://github.com/LiskHQ/lisk-sdk/blob/a800c3217e50a94c5e865febd0240ddd834dfb3c/framework/test/mocha/integration/transactions/exceptions/duplicate_signatures.js#L143
* https://github.com/LiskHQ/lisk-sdk/blob/a800c3217e50a94c5e865febd0240ddd834dfb3c/framework/src/modules/network/lookup_peers_ips.js#L27

Cases like these are too many to list here.

**Comment by shuse2** [comment]
@vitaly-t It is returning the `new Promise` and expecting the value from `resolve` or `reject`. Syntax was it's misleading and not good, but it should be ok.

Also, the reason is consistent return from eslint (where if we use `return` for `reject`, `resolve` should return too`

**Comment by shuse2** [comment]
This issue has been addressed while migrating to typescript
