### ISSUE TITLE
StateStore only allows for account and transaction data to be loaded

### ISSUE THREAD

**Issue by michielmulders** [LiskHQ/lisk-sdk#4114]
### Expected behavior
Currently, we can only load transaction and account data into the StateStore: `elements/lisk-transactions/src/base_transaction.ts:79`.
It would be nice if we could also load block data to be used inside custom transactions. 

However, we should not allow to `.set()` blocks data as that would mean you can change blockchain data. We only want to implement `.get()` for blocks.

### Actual behavior
Only account and transaction data can be cached.

### Which version(s) does this affect? (Environment, OS, etc...)
2.*

**Comment by shuse2** [comment]
We are not planning to extend the state store for other entities than account and chain state.
Transaction state store was mainly for the backward compatibility for previous protocol.
