### ISSUE TITLE
Lisk Commander create custom transaction

### ISSUE THREAD

**Issue by JesusTheHun** [LiskHQ/lisk-sdk#4115]
Currently the CLI allow us to create core transactions.
It would be great if not mandatory to create custom transactions from CLI, mostly for dev purpose.

It would require an extra method such as :

```js
getCliArguments() {
    return [ ...super.getCliArguments(), 'myOption1', 'myOption2'] // Each argument is then mapped to the transaction asset object
}
```

Then 

`$ lisk transaction:create --type=42 0 myOption1Value myOption2Value 13356260975429434553L`

**Comment by shuse2** [comment]
Closing because creating any registered transaction is possible with the `transaction:create` command in core now with lisk-core v3
