### ISSUE TITLE
Lisk Commander aliases

### ISSUE THREAD

**Issue by JesusTheHun** [LiskHQ/lisk-sdk#4116]
When you want to manually test some scenario during the dev process, it would be great to be able to replace addresses by aliases.

Those aliases would be set in a `.lisk-commander` file for exemple.

```js
{
    account1: { /* account data, copy/paste from the lisk account:create command */},
    account2: { /* another account */ },
   "@default": { /* this is the default account, if I press enter without any input */ }
}
```

Then you can use them into more interactive modes :

```bash
$ lisk transaction:create:transfer 100 @account1
```

The prompt will ask for the passphrase, you write `@account2`, select from a list, or simply press enter to use the default account.

You could also make an extra param for `lisk account:create --save myAlias`which would save the account into `.lisk-commander`

**Comment by shuse2** [comment]
Closing this issue since value added is small, and this can be achieved in the host machine
