### ISSUE TITLE
/api/accounts performance is too low

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#4122]
### Expected behavior
/api/accounts endpoint should be less than 100ms

### Actual behavior
Each accounts request takes around 300ms
`/api/accounts?address=xxxL` should be less than 

### Steps to reproduce
call
`http://localhost:8000/api/accounts?address=xxxL`

### Which version(s) does this affect? (Environment, OS, etc...)
hotfix/2.3.1

**Comment by michielmulders** [comment]
Add the `asset` field to the non-extended query and change `extended:true` to `false` by default.

**Comment by michielmulders** [comment]
WIP on `fix-account-performance`
