### ISSUE TITLE
Unable to understand the use and relevance of reloadRequired function in blocks/verify.js file

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk-sdk#4130]
### Expected behavior
The function `reloadRequired` should check the integrity of the blockchain.
### Actual behavior
The definition of the function is quite rudimentary. It only checks the blocks count with the mem_rounds table and validates that at least one delegate exists in the database. These checks maybe irrelevant after 3.0.0
### Steps to reproduce
Look at the code here: https://github.com/LiskHQ/lisk-sdk/blame/bdeabd6fef197bd8ba63d760eb90b06cefd5f6fd/framework/src/modules/chain/blocks/verify.js#L139
### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0

**Task List**

- [ ] Verify the genesis block is loaded before reloadRequired() function is executed.

**Comment by shuse2** [comment]
This data inconsistency will never occur because we have atomic block write.
we only write in the processor using database transaction.
Therefore, this check is no longer required
