### ISSUE TITLE
Merge child tables of mem_accounts

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#4139]
### Description
Remove `mem_accounts2delegates` and `mem_accounts2multisignatures` and merge into `mem_accounts` table

### Motivation

Child table is not required since we started to use JSON field in postgres.

### Acceptance Criteria

- Update the storage classes and remove the `extended` options
- Storage tests need to be updated
- All the usages of extended need to be removed
- Check the HTTP API performance

For **mem_account2delegates**: 
- [x] benchmark `/api/accounts?limit=100` and add results to this issue
- [x] create migration to create field `votedDelegatesPublicKeys`
- [x] create migration to migrate `mem_accounts2delegates` to the new field `votedDelegatesPublicKeys`
- [x] create migration to drop the table `mem_accounts2delegates`
- [x] delete `framework/src/components/storage/sql/accounts/get_extended.sql` and move fields to `framework/src/components/storage/sql/accounts/get.sql`
- [x] update usages of removed table in `framework/src/modules/chain/components/storage/entities/account.js` (this includes at least  filter `votedDelegatesPublicKeys_in` and methods `update`, `_updateDependentRecord`, `updateDependentRecords`)
- [x] analyse the impact of the changes in account entity methods `create()` and `update()` and refactor accordingly 
- [x] update `framework/src/modules/chain/components/storage/sql/accounts/reset_mem_tables.sql` to not include `mem_accounts2delegates`
- [x] remove all usages of `get({extended: true})` and replace with regular `get()`
- [ ] after all changes are done benchmark `/api/accounts?limit=100` and add results to this issue

For **mem_accounts2multisignatures**: 
- [x] benchmark `/api/accounts?limit=100` and add results to this issue
- [x] create migration to create field `membersPublicKeys`
- [x] create migration to migrate `mem_accounts2multisignatures` to the new field `membersPublicKeys`
- [x] create migration to drop the table `mem_accounts2multisignatures `
- [x] delete `framework/src/components/storage/sql/accounts/get_extended.sql` and move fields to `framework/src/components/storage/sql/accounts/get.sql` (this might already be done by removing mem_accounts2delegates)
- [x] update usages of removed table in `framework/src/components/storage/entities/account.js`
- [x] update usages of removed table in `framework/src/modules/chain/components/storage/entities/account.js`
- [x] analyse the impact of the changes in account entity methods `create()` and `update()` and refactor accordingly
- [x] update `framework/src/modules/chain/components/storage/sql/accounts/reset_mem_tables.sql` to not include `mem_accounts2multisignatures`
- [x] remove all usages of `get({extended: true})` and replace with regular `get()`
- [x] after all changes are done benchmark `/api/accounts?limit=100` and add results to this issue

**Comment by pablitovicente** [comment]
Benchmark results before changes: 

```
While load testing before changes PSQL load was 43.5%
While load testing before changes Node load was 19.0% and memory 200 MB


Transactions:		         850 hits
Availability:		      100.00 %
Elapsed time:		       59.49 secs
Data transferred:	        4.28 MB
Response time:		        1.73 secs
Transaction rate:	       14.29 trans/sec
Throughput:		        0.07 MB/sec
Concurrency:		       24.66
Successful transactions:         850
Failed transactions:	           0
Longest transaction:	        2.14
Shortest transaction:	        1.22
```

**Comment by pablitovicente** [comment]
Benchmark results after changes:
command used: siege -c25 -t60s http://localhost:8000/api/accounts?limit=100
computer: MacBook Pro, 16GB Ram, 12 Cores.

Take into account that the branch this is built upon is under heavy development currently and not stable so this needs to be checked again after branch stabilises .
```
While load testing before changes PSQL load was 43.5%
While load testing before changes Node load was 19.0% and memory 200 MB

Transactions:		         825 hits
Availability:		      100.00 %
Elapsed time:		       59.91 secs
Data transferred:	        4.15 MB
Response time:		        1.79 secs
Transaction rate:	       13.77 trans/sec
Throughput:		        0.07 MB/sec
Concurrency:		       24.67
Successful transactions:         825
Failed transactions:	           0
Longest transaction:	        2.19
Shortest transaction:	        1.20
```
