### ISSUE TITLE
Lisk Client for browser

### ISSUE THREAD

**Issue by JesusTheHun** [LiskHQ/lisk-sdk#4163]
Currently the Lisk Client export a version for NodeJS and for browsers. This causes a lot of problems while developing into a browser, the main reason being the default version is the NodeJS one, so we have to suffix `/dist-browser`, but even doing this we end up with errors.

One of the error I get :

`The package at "node_modules/cipher-base/index.js" attempted to import the Node standard library module "stream". It failed because React Native does not include the Node standard library.`

So please make a browser only package so we can import stuff safely.

**Comment by shuse2** [comment]
This issue is related to #3348
