### ISSUE TITLE
Update unit tests for delegates/api

### ISSUE THREAD

**Issue by michielmulders** [LiskHQ/lisk-sdk#4173]
### Expected behavior
We should follow the new testing guidelines and make sure to test public interfaces instead of privately defined methods. Currently, only private methods are tested which is quite pointless.

File affected: `framework/test/mocha/unit/modules/http_api/controllers/delegates.js`
This file still uses rewire and Mocha, would be nice to avoid rewire and rewrite with Jest.

### Which version(s) does this affect? (Environment, OS, etc...)
`feature/improve-bft` or `development`

**Comment by shuse2** [comment]
Closing this in favor of #5213
