### ISSUE TITLE
APIError: Transaction was rejected with errors

### ISSUE THREAD

**Issue by rohitsahu21** [LiskHQ/lisk-sdk#4176]
### Expected behavior
Transaction Hash or Success Message

### Actual behavior
APIError: Transaction was rejected with errors

node_modules/@liskhq/lisk-api-client/dist-node/api_resource.js:40:27

### Which version(s) does this affect? (Environment, OS, etc...)
lisk-element version ^2.3.0
OS Linux Ubuntu

**Comment by shuse2** [comment]
Would you be able to give us the transaction object?
Without transaction object, and with the description above, it will be hard to tell if the transaction object was actually valid or not

**Comment by rohitsahu21** [comment]
Here is code it work fine with testnet, but error in mainnet

`const lisk = require('lisk-elements');

const transaction = lisk.transaction.transfer({
    amount: '2000000',
    recipientId: '2098227419519214458L',
    passphrase: 'xxxx xxxx xxxx xxxx candy calm defy xxxx gasp oak used xxxx',
});

// const client = lisk.APIClient.createTestnetAPIClient();
const client = lisk.APIClient.createMainnetAPIClient();

(async () => {
    const result = await client.transactions.broadcast(transaction);
    console.log(result);
})();
`

**Comment by shuse2** [comment]
Transaction can be valid or invalid depending on the state of the network.
Did u haver the balance on mainnet for the account?

**Comment by rohitsahu21** [comment]
Got it, its my mistake  available amount is 0.01, and its consume in transaction fee, that's why   it give an error,, but its not show properly error like insufficient fund. 

anyway Thank You for replying.
