### ISSUE TITLE
Transaction count wasn't cached Error: Cache Disabled

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-sdk#4177]
### Expected behavior
Lisk core shouldn't stuck because of an error

### Actual behavior
Lisk core stucked and did not process further blocks

### Steps to reproduce
Unknown

### Error log
This log occurs many times during stuck.
`{"name":"lisk-framework","hostname":"XXXXXXXXX","pid":14810,"level":40,"msg":"Transaction count wasn't cached Error: Cache Disabled\n    at Cache.setJsonForKey (/home/lisk/lisk-main/node_modules/lisk-framework/src/components/cache/cache.js:132:10)\n    at updateConfirmedCountToCache (/home/lisk/lisk-main/node_modules/lisk-framework/src/modules/chain/submodules/transactions.js:659:9)\n    at nextTask (/home/lisk/lisk-main/node_modules/async/dist/async.js:5324:14)\n    at Immediate.next (/home/lisk/lisk-main/node_modules/async/dist/async.js:5331:9)\n    at Immediate.<anonymous> (/home/lisk/lisk-main/node_modules/async/dist/async.js:969:16)\n    at runCallback (timers.js:706:11)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)\n    at process.topLevelDomainCallback (domain.js:120:23)","time":"2019-08-30T11:23:49.531Z","v":0}`

### Which version(s) does this affect? (Environment, OS, etc...)
Ubuntu 18.04

**Comment by karek314** [comment]
Happened again, on the same node. reloading resolved issue.

**Comment by shuse2** [comment]
It was solved by #4206
