### ISSUE TITLE
Zero vote delegate issue on testnet

### ISSUE THREAD

**Issue by lsilvs** [LiskHQ/lisk-sdk#4194]
### Expected behavior
Expect to only accept the correct forger public key for blocks produced during the rounds listed on `exceptions.ignoreDelegateListCacheForRounds`

**It only affects testnet as `exceptions.ignoreDelegateListCacheForRounds` is not defined on mainnet**

### Actual behavior
The previous Rounds module implementation used to use `account.vote` attribute in order to get the list of active delegates. This `account.vote` attribute was only updated in the **end of the round** making it possible to generate the same active delegate list at any slot of the round.

The new Dpos module implementation uses `account.voteWeight` attribute in order to get the list of active delegate. This `account.voteWeight` attribute is updated **every new block** making it unreliable to generate the same active delegate list at any slot of the round.

During implementation of https://github.com/LiskHQ/lisk-sdk/issues/2421, `exceptions.ignoreDelegateListCacheForRounds` was introduced to cater for the `zero vote delegate` issue https://github.com/LiskHQ/lisk-sdk/pull/2543#pullrequestreview-178505587 on testnet but now that Dpos rely on the list generated in the beginning of the round because the list generated in the middle of the round is affected by `account.voteWeight`, we can't just ignore the cache and make a new query to the database as it will return a list affected not only by the `zero vote delegate` issue but also by `account.voteWeight` that is now potentially updated every new block.

A workaround during Dpos module implementation was to accept any forger for any block produced during the rounds defined in `exceptions.ignoreDelegateListCacheForRounds`. This ensures sync/rebuild still work for testnet but shouldn't be the ultimate solution.

### Steps to reproduce
Undo the commit https://github.com/LiskHQ/lisk-sdk/commit/be30cb5001a00aa4ec6bea1fd68282efedc673b6 and try to sync/rebuild testnet.
It should fail in the round 19

### Which version(s) does this affect? (Environment, OS, etc...)
`feature/introduce_bft_consensus`

**Comment by shuse2** [comment]
This issue will be resolved with #4915
