### ISSUE TITLE
Improve syncing logging

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#4195]
#### Suggestion
- When the node is in sync and not reached the network height, it should log, for example
`lisk-framework: Syncing in progress with the network, current height: 10000`
- When the node sync up to the network it should log accordingly, for example
`lisk-framework: Finished syncing with the network, current height: 9164697`

When are at the tip of blockchain or when we synced with the network and we are the highest height use `lisk-framework: Finished syncing with the network, current height: 9164697`, otherwise use format `lisk-framework: Syncing in progress with the network, current height: 10000`
### Actual behavior
Due to the way we handle syncing, every time a few seconds we see `Starting sync` and `Finished sync`. with this log information its harder to know if the node actually finished syncing with the network.

### Steps to reproduce
- Sync to a network from scratch
- Observe info logs

**Comment by lsilvs** [comment]
Similar log message should be used during rebuilding imo

**Comment by ManuGowda** [comment]
After discussing with @shuse2, I am closing this issue.
Reason:
`
loader will be removed, and network height is not indicator anymore (because we sync with specific node in the BFT)
`
