### ISSUE TITLE
API endpoint for pending txs bug

### ISSUE THREAD

**Issue by Gr33nDrag0n69** [LiskHQ/lisk-sdk#4241]
### Expected behavior
On

/api/node/transactions/pending?offset=0&limit=100

correct .meta.count value is returned

### Actual behavior

.meta.count doesn't return correct value

it return random values

only the meta look affected since when i count myself the number of items (txs info object) in my array i always get the correct number.

this was tested on all v2.0 public nodes of mainnet by me and corsaro

### Steps to reproduce

send multisig pending txs and fetch the list from api

### Which version(s) does this affect? (Environment, OS, etc...)

2.x

**Comment by shuse2** [comment]
With #4836 and #4841 , this issue no longer exists
