### ISSUE TITLE
Move stub definitions and expectations to a common place for unit & integration tests

### ISSUE THREAD

**Issue by yatki** [LiskHQ/lisk-sdk#4270]
### Description

Unit tests should import and use arguments and return values for `whenCalledWith`, `mockReturnValue`, `mockResolveValue` functions from a central folder.

Integration tests should also use the same arguments and expectations to make sure all protocols for I/O connectors were tested.

### Motivation

With the new testing strategy, we are only mocking the I/O connectors. But since unit tests and integration tests are structured separately, It's hard to keep track of what's being mocked and what was integration tested. 

So, by moving expectations into a single folder and by adding that folder to code coverage reports we can keep track of which mocks were integration tested.
### Acceptance Criteria
- unit tests stub definitions must come from a central folder
- integration test expectations must come from that central folder as well.
- central folder must be added to the coverage report for unit & integration test.
- Address these comments: https://github.com/LiskHQ/lisk-sdk/pull/4269#discussion_r326185417, https://github.com/LiskHQ/lisk-sdk/pull/4269#discussion_r326176689

**Comment by shuse2** [comment]
Closing since unit test stubbing no longer have the same issue
