### ISSUE TITLE
Advanced test coverage related to PeerBook management and peer list poisoning

### ISSUE THREAD

**Issue by jondubois** [LiskHQ/lisk-sdk#4283]
### Description

More tests are needed to verify that PeerBook management is working under unusual scenarios.
Some things to check (note that this is not an exhaustive list):

- Verify that the total number of peers in the PeerBook is guaranteed to be limited to a maximum value (around 4k peers max according to the new bucket system).
- Verify that peers from the same IP group end up in the same buckets and cannot occupy large portions of the whole PeerBook.

Related issue: https://github.com/LiskHQ/lisk-sdk/issues/4279

### Motivation

PeerBook management is a complex feature which requires more thorough testing.

### Acceptance Criteria

- The test cases cover advanced or malicious scenarios like the ones described above.
- The goal of this issue is not to add test cases to verify obvious functionality. The tests should aim to uncover flaws. They need to focus on edge cases.

**Comment by ManuGowda** [comment]
Closing this issue as the tests are covered https://github.com/LiskHQ/lisk-sdk/blob/90372bbe6831249ceb7b1a97aa259de749964f2c/elements/lisk-p2p/test/unit/peer_book/new_list.ts#L131
