### ISSUE TITLE
Do not allow id property in PeerInfo provided by a peer

### ISSUE THREAD

**Issue by jondubois** [LiskHQ/lisk-sdk#4284]
### Expected behavior

PeerInfo from the network should not have an id property. If it does, it should be ignored.

### Actual behavior

The `validatePeerInfoSchema` function allows having an `id` field inside `PeerInfo` objects.

**Comment by ManuGowda** [comment]
This issue is no longer valid as its been addressed in different issue, and `id` property doesn't exists anymore in the `P2PPeerInfo`
```
export interface P2PPeerInfo {
	// String to uniquely identify each peer
	readonly peerId: string;
	readonly ipAddress: string;
	readonly wsPort: number;
	readonly sharedState?: P2PSharedState;
	readonly internalState?: P2PInternalState;
}
```
