### ISSUE TITLE
DPoS verifyBlockForger unit tests contains redundant stubs

### ISSUE THREAD

**Issue by yatki** [LiskHQ/lisk-sdk#4306]
### Expected behavior
There shouldn't be redundant stubs. We need to make sure if the tests are checking the right functionality or remove those stubs.
### Actual behavior
Tests are still passing after deleting `RoundDelegates.create` and `Account.get` stubs.
### Steps to reproduce
Please remove the lines below 
```js
					// @todo create was stubbed but never used, create an issue to remove it or add a test case
					create: jest.fn(),
				},
				Account: {
					get: jest.fn().mockReturnValue([]),
```
Then run:

`npm run jest:unit -- verify  `

**Comment by shuse2** [comment]
Superseded by #4749
