### ISSUE TITLE
Implement finding common block for FCS

### ISSUE THREAD

**Issue by michielmulders** [LiskHQ/lisk-sdk#4337]
### Expected behavior
Currently, we do have an implementation for finding the common block which is implemented at: `framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js:125` -> Function name: `_requestLastCommonBlock`

We need to *copy and modify* this functionality to make it compliant for FCS.
=> As we can maximum revert 202 blocks, we can only send 202 block IDs.
Function needs to be tuned to include this limit and the implementer can play with the number of block IDs that can be send (202 at once, chunks of 25 IDs, ...).

Also, this issue includes the following checks:
- `C.height<chainHeightFinalized` --> ban peer
- `A.height-C.height>202` --> Abort and restore blocks with `restoreBlocks` in `synchronizer/utils.js`
- `B.height-C.height>202` --> Abort and restore blocks with `restoreBlocks` in `synchronizer/utils.js`

### Implementation Details
Function should be created under: `framework/src/modules/chain/synchronizer/fast_chain_switching_mechanism.js`

### LIP Section
```
**1. Step: Query blocks**
Query the peer P that sent B for the last common block C of the chain with tip A and the chain with tip B. Afterwards the node requests the missing blocks up to block B from that peer. If C.height<chainHeightFinalized holds, the change to a different branch is aborted and P is banned, as a node never reverts a finalized block. If A.height-C.height>202 or B.height-C.height>202 holds (i.e., we need to delete or apply more than 202 blocks), the node aborts the process of moving to a different chain.
```

**Comment by michielmulders** [comment]
Send 202 block IDs at once.

**Comment by michielmulders** [comment]
Not sure if we should ban peer if diff is higher than 202

**Comment by shuse2** [comment]
Superseded by #4396
