### ISSUE TITLE
Query all blocks from common block for peer and validate for FCS

### ISSUE THREAD

**Issue by michielmulders** [LiskHQ/lisk-sdk#4338]
### Expected behavior
Per https://github.com/LiskHQ/lisk-sdk/issues/4337 we have found the common block and validated the block with the three checks outlined in the issue. 

When the checks pass, we request blocks from this peer from common block height up to the tip of the peer's chain. (separate function in `fast_chain_switching_mechanism.js` called `requestBlocksFromPeerFromHeight`?)

1. Each block is added to the validation pipeline in the processor.
2. If delegate slot check or processor validate pipeline fails, we ban the beer (not sure if banning can be called yet). + abort switching process -> call `restoreBlocks`

Note: Can be implemented independently from #4337 as we can assume a block ID will be passed as an argument. Functionality can be unit tested.

- Consider to to remove blocks after successful validation

**Comment by shuse2** [comment]
Superseded by #4396
