### ISSUE TITLE
Switch to Different Chain via FCS

### ISSUE THREAD

**Issue by michielmulders** [LiskHQ/lisk-sdk#4339]
### Expected behavior
1. Delete all blocks from current chain up to common block C we found (ref. https://github.com/LiskHQ/lisk-sdk/issues/4337 for finding common block) and put them in the `temp_block` table.

Call: `framework/src/modules/chain/blocks/blocks.js:306` ->
```
async remove({ block, tx }, saveToTemp)
```

2. Apply all blocks we received from the peer (ref. https://github.com/LiskHQ/lisk-sdk/issues/4338) using the processor `processValidated` pipeline by looping all blocks and trying to apply them. -> skip validation steps if there are.

3. If we receive an error from applying blocks or the node crashes, we should call `restoreBlocks` function to put back the old chain in place.

Note: Again can be started directly as we expect a block ID as input. Verified via unit tests.

#### Skip broadcast and validation?
FCS switching to different chain mechanism describes that we can skip step 1 (validation) and step 3 (broadcasting applied blocks) when applying the new blocks received from the peer. --> Skip validate

From LIP:
```
3. Step: Broadcast block B to peers using the mechanism provided by the P2P module.
```

I'm not sure if we should broadcast the block again as the chances are high that all other peers already have those blocks. Needs discussion to verify this point. Also if we can skip validation for the received blocks as they are already validated. --> Skip broadcast

#### Checks needed for restoring chain after crash
LIP states:
```
It is essential that even if a node crashes while performing this step, it is afterwards able to either restore the chain with tip A or the new chain with tip B.
```

```
b) If the node is not able to obtain all blocks up to block B from P, but synchronization stops at a block T (i.e., T is the tip of the current chain), then the node checks whether T has priority over A in terms of the fork choice rule (condition at the beginning of the section):

(A.heightPrevoted<T.heightPrevoted) || A.height<T.height && A.heightPrevoted==T.heightPrevoted)
```

**Comment by shuse2** [comment]
Superseded by #4396
