### ISSUE TITLE
Rename database table names

### ISSUE THREAD

**Issue by yatki** [LiskHQ/lisk-sdk#4345]
### Description
We should rename the tables to have more clear names.

Also, tables should not have prefix `temp`  if the data there is important for the node.

### Motivation

Some of the table names are misleading in the database.

### Acceptance Criteria

- `mem_accounts` to `accounts`
- `trs` to `transactions`
- Find a better name for `temp_block` table.

**Comment by shuse2** [comment]
Closing this in favor of https://github.com/LiskHQ/lisk-sdk/issues/5238
