### ISSUE TITLE
Result of computation in the transaction field

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-sdk#4346]
### Description
Ability to store results in the **asset** field of transaction, without invalidating signature check of base transaction.

### Motivation
There are use-cases where it would be beneficial to store result of computation directly in, let's say **asset_results** field, which would not be part of transaction body verification.

At this moment, anything set to the asset property of transaction will result in verification issue. Workaround for this, is to store, something like **transaction_results** in account asset and allocate objects to **tx_id** key, however I'm not sure that would be efficient with thousands of transactions.

**Comment by shuse2** [comment]
Closing because transaction are not part of the state, and it should be immutable during the block processing.
However, we will most likely provide the interface to store custom state from transaction
