### ISSUE TITLE
Add delegateMinHeightActive needs to be included in calculation of prevote and precommit

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#4349]
### Description
In the BFT module when we compute prevotes and precommits, an important variable [`delegateMinHeightActive`](https://github.com/LiskHQ/lips/blob/master/proposals/lip-0014.md#computing-prevotes-and-precommits) is currently hardcoded to `0`. Practically this is not breaking the code execution but of course, it leads to **miscalculated** precommits and prevotes.

As LIP states, `delegateMinHeightActive` is for a currently **active** delegate, the height of **first block of the round** when that delegate has been **continuously** __active__.`

So, a correct `delegateMinHeightActive` information must be provided to the BFT module.

For that, Dpos module should update the account states at the beginning of the rounds. Unfortunately, as LIP states `undo` requires to calculate this information from scratch. 

### Motivation
Delegates should **not** be able to precommit or prevote for blocks when they were not active in that round.

### Acceptance Criteria
-  `delegateMinHeightActive` must be updated once a delegate becomes active and should not be updated as long as that delegate remains active.
- Unit test for dpos module is updated for delegate becoming active
- Unit test for dpos module is updated for delegate going standby and coming back active
- Add unit test for bft module where delegateMinHeightActive is update according to the account state
- Add unit tests in case of  reverting a block.

### Additional Information
- https://github.com/LiskHQ/lips/blob/master/proposals/lip-0014.md#computing-prevotes-and-precommits

**How to choose the right `delegateMinHeightActive` value.**

Let's assume block A which has a height of 820 was received. That means block A is part of round 9. And if delegate was not active in the previous round (8), `delegateMinHeightActive` for that delegate will be updated to `809` (The first block height of the round 9). It doesn't matter which list was used or how the list was stored in the database. Also [`delegateListRoundOffset`](https://github.com/LiskHQ/lisk-sdk/pull/4397/files) variable is not important when calculating `delegateMinHeightActive`. delegateMinHeightActive is always calculated from the received block which gives us the active round. In this example active round is round 9.

**Comment by janhack** [comment]
Note that it is sufficient to check which delegates where active in the last 3 rounds and compute `delegateMinHeightActive` from there. The reason is that all prevotes and precommits by a block `B` are only for the last 303 blocks, i.e., if `delegateMinHeightActive<B.height-302`, then we can simply set `delegateMinHeightActive:=B.height-302` for computing the `prevotes` and `precommits`. See also the section referenced above.
