### ISSUE TITLE
Always allow fixed/whitelist incoming connections

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#4353]
### Expected behavior

Check on incoming connection if its a whitelist or fixed and remove a peer that is neither a whitelist nor a fixed peer. In any case, it should always make space for fixed/whitelist peers regardless of its reputation and productivity.

### Actual behavior

There is no check for incoming connections if it's coming from white or fixed list.

### Steps to reproduce

Try to make connection to a node that has selected you as fixed or white list and check if they always connection with you.

### Which version(s) does this affect? (Environment, OS, etc...)
`3.0`

**Comment by shuse2** [comment]
This issue is invalid since incoming connections are always allowed, and white/fixed list are protected by eviction
