### ISSUE TITLE
Error Plugin: lisk-commander: files attribute must be specified

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#4355]
### Expected behavior
Plugin error shouldn't occur while using any of the commander commands.
### Actual behavior
```
lisk@mainnet-sync-1vcpu-1gb-fra1-01:~$ lisk core:logs lisk-mainnet
(node:8265) Error Plugin: lisk-commander: files attribute must be specified in /usr/local/lib/node_modules/lisk-commander/package.json
module: @oclif/config@1.9.0
plugin: lisk-commander
root: /usr/local/lib/node_modules/lisk-commander
See more details with DEBUG=*
{"name":"lisk-framework","hostname":"mainnet-sync-1vcpu-1gb-fra1-01","pid":8028,"level":30,"msg":"Transaction pool - received size: 0 validated size: 0 verified size: 0 pending size: 0 ready size: 0","time":"2019-10-02T11:02:50.559Z","v":0}{"name":"lisk-framework","hostname":"mainnet-sync-1vcpu-1gb-fra1-01","pid":8028,"level":30,"id":"2177623880503325106","height":3209,"numberOfTransactions":2,"msg":"New block added to the chain","time":"2019-10-02T11:02:50.563Z","v":0}
```
### Steps to reproduce
- Create a droplet
- Install `NPM` globally
- Run `npm install --global --production lisk-commander`
- Run `lisk core:install --no-snapshot lisk-mainnet`
### Which version(s) does this affect? (Environment, OS, etc...)
2.2.3

**Comment by ManuGowda** [comment]
After investigation, this issue is happening with `npm` version `3.x.x`. After upgrading to the latest npm version, this issue is no longer reproducible.

**Comment by ManuGowda** [comment]
Commander throws error while using commander, steps to reproduce 

Env:
```
 nodejs is v14.5.0 and npm is 6.14.5
OS is ubuntu 16.04
```

1. `npm install --global --production lisk-commander@2.2.3`

Error
```
libtoolize:   error: Failed to create 'build-aux'
./configure: 5: ./configure: ./configure: not found
/usr/lib/node_modules/lisk-commander/node_modules/sodium-native/preinstall.js:119
    if (err) throw err
```

**Comment by seven010** [comment]
Thanks for updating the issue, Manu. I faced this issue today while installing Lisk Commander while setting up dakk's pool script. To check if the issue persists, I did the setup from scratch on a new server but still got the same issue mentioned above. However even with this error, at the end I was able to send the pool transactions successfully.
