### ISSUE TITLE
Improve network actions to expose connectedPeers and disconnectedPeers

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#4361]
### Description

Improve network actions to expose `connectedPeers` and `disconnectedPeers`

### Motivation

Right now we expose `getPeers` and `getUniqueOutboundPeers`
`getPeers` action returns a list of all the peers with `state` value `0` for disconnected and `1` for connected peers but other modules usually are interested in `connectedPeers` and we want to get rid of `state` value in the future.

Also, there was an extra overhead every time we call these actions as it was going through `consolidatePeers`  function that is used to assign `state` value based on connection state of peers.

### Acceptance Criteria

Other modules should be able to call `connectedPeer` or `disconnectedPeers` actions without passing `state` filter.

**Comment by shuse2** [comment]
Superseded by #4374
