### ISSUE TITLE
TRS table has too many indexes

### ISSUE THREAD

**Issue by pablitovicente** [LiskHQ/lisk-sdk#4370]
### Description

We have 16 indexes out of 22 columns for the table `trs`. We should analyse if we can potentially remove some of them. 

### Motivation

Many of the indexes are sorted ones probably to help HTTP API performance. We should check if other index types can provide similar performance. We should also study alternative options (e.g. have a different process store data emitted by the chain module in a different set of tables for exclusive HTTP API use)

We can most probably drop the duplicated indexes for ASC/DESC as the documentation for PSQL states: `An index stored in ascending order with nulls first can satisfy either ORDER BY x ASC NULLS FIRST or ORDER BY x DESC NULLS LAST depending on which direction it is scanned in.`
As they're not compound indexes I think it's safe to keep only ASC or DESC (see for complete explanation: https://www.postgresql.org/docs/10/indexes-ordering.html )

### Acceptance Criteria

- Report on the feasibility of removing some of the indexes by using different types of index
- Report on the feasibility of having a separate set of tables updated by a different process to provide HTTP API with data

**Comment by pablitovicente** [comment]
We could simplify the indexes but it will imply a change of behaviour in the HTTP API. We're currently forcing a sort by `rowId` in the transaction entity and the indexes are compound with the column `rowId`; due to this reason PSLQ can not simply use an index sorting by `<column> ASC|nulls first` and falls back to a scan of blocks which is not good. 

For being able to simplify the indexes we should:
- remove the forced order by `rowId` (this might slightly change the current order)
- change the index to be `<COLUMN> ASC | NULLS first` (this will also change the order for some columns sorting)

Currently I would say not to go for this change and plan for it accordingly or next time we update the HTTP API

**Comment by lsilvs** [comment]
For reference:
 - Inconsistent response for /transactions endpoint #1884
 - Low performance for transactions endpoint with sort param #2201
