### ISSUE TITLE
Audit SQL queries and SQL indexes

### ISSUE THREAD

**Issue by pablitovicente** [LiskHQ/lisk-sdk#4394]
### Description

- Audit all query files from storage to identify potential SQL optimisations
- Audit all indexes used by the SQL database

### Motivation

-  We've identified some cases where SQL queries could be optimised (for example some of the transaction queries are using subqueries and might be replaced with code reducing subqueries)
- ~~#4370 identified that we have unnecessary indexes that make insert/updates slower~~ (these indexes were find out to be required as we force extra filter on transactions for the return of the HTTP API to be deterministic)

### Acceptance Criteria

- List of queries that can potentially be optimised with proposed solution/replacement/optimisation
- List of indexes that are redundant or can be replaced by compound indexes
- Performance scripts with results before/after proposed changes
- After list exist a discussion should be held to decide the strategy to follow for implementing the changes

**Comment by michielmulders** [comment]
Blocks has an index on every column which slows down the performance when writing new blocks (refer: https://www.citusdata.com/blog/2017/10/11/index-all-the-things-in-postgres/)

**Comment by pablitovicente** [comment]
We decided to close this issue as we might change the storage layer completely in the coming months.
