### ISSUE TITLE
To many properties within Peer Class and redundant fields

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#4401]
### Expected behavior

Peer class constructor should be cleaner and should not have redundant properties

### Actual behavior

We have all the properties spread out from peer config and filling up the peer properties. We can have a peer config property that encapsulate all the config passed to the constructor (this._peerConfig = peerConfig) and also remove redundant properties like `peerId`, `ipAddress`, 
 and `wsPort`

### Steps to reproduce

N/A

### Which version(s) does this affect? (Environment, OS, etc...)
`3.0`

**Comment by shuse2** [comment]
Superseded by #4314
