### ISSUE TITLE
Network reward milestones are not respected

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-sdk#4409]
### Expected behavior
Network reward milestones should work as it is configurable

### Actual behavior
They are not, in case of rewards=0, after 2160 height, lisk-sdk ignores milestones and
2161 -> 4 reward
2162 -> 3 rewrad
2163 -> 2 rewrad
2164 -> 1 rewrad
and continue with 1.0

### Steps to reproduce
```
"genesisConfig": {
			"EPOCH_TIME": "2019-04-24T17:00:00.000Z",
			"BLOCK_TIME": 5,
			"MAX_TRANSACTIONS_PER_BLOCK": 25,
			"REWARDS": {
				"MILESTONES": [
					"0"
				],
				"OFFSET": 2160,
				"DISTANCE": 1
			}
		}
```

"OFFSET": 1000000000
Seems to resolve issue, but this is rather workaround.

### Which version(s) does this affect? (Environment, OS, etc...)
2.3.6

**Comment by Incede** [comment]
With lisk-sdk v5.10 (latest), the reward milestones are respected:

2161 -> 0 reward
2162 -> 0 reward
2163 -> 0 reward
2164 -> 0 reward

```
"genesisConfig": {
			"blockTime": 5,
			"maxPayloadLength": 15360,
			"rewards": {
				"milestones": [
					"0"
				],
				"offset": 2160,
				"distance": 1
			}
		}
```
