### ISSUE TITLE
Hide asset property in the Account entity

### ISSUE THREAD

**Issue by lsilvs** [LiskHQ/lisk-sdk#4417]
### Description
Adapt the Storage account entity interface in order to hide the `asset` field from the user.

### Motivation
Storage account entity exposes the property `asset` as an object that allows users to add any custom property that is required to its use case. This is confusing because users can modify not only the `asset` property but any other property in the account like `balance`, `voteWeight` or `username`.

My suggestion is to abstract the `asset` property hiding it from the user and allowing them to add any property to accounts directly - see example bellow.

**Current way:**
```js
account.asset.myProperty = 42
```

**Proposed way:**
```js
account.myProperty = 42
```

PS: Internally the Storage component would still save the custom property in the `asset` field to avoid the need of migrations.

### Acceptance Criteria
--

### Additional Information
--

**Comment by shuse2** [comment]
With https://github.com/LiskHQ/lips/blob/master/proposals/lip-0030.md, this issue is no longer relevant
