### ISSUE TITLE
Update to Node.js 10.17.0

### ISSUE THREAD

**Issue by fchavant** [LiskHQ/lisk-sdk#4420]
### Expected behavior
Use https://github.com/nodejs/node/releases/tag/v10.17.0

### Actual behavior
We're using https://github.com/nodejs/node/releases/tag/v10.16.3

### Steps to reproduce
`cat .nvmrc`

### Which version(s) does this affect? (Environment, OS, etc...)
`development`

**Comment by pablitovicente** [comment]
Node 12 went into LTS so probably we should just go to that version?

**Comment by fchavant** [comment]
We should use 12.x for the next version however we should make sure to use the latest 10.x if we have to release a patch version.

**Comment by ManuGowda** [comment]
Closing this issue as we upgraded to Node 12 LTS https://github.com/LiskHQ/lisk-sdk/issues/4392
