### ISSUE TITLE
Reject unnecessary messages and ban a peer

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#4424]
### Expected behavior

A node should not send internal messages to a lisk node as it's not needed which creates an extra overhead.

### Actual behavior

Its accepting messages that are internal and not related to `lisk-sdk` and should be rejected and a peer should be banned as its not suppose to send these messages.

### Which version(s) does this affect? (Environment, OS, etc...)
`3.0`

**Comment by shuse2** [comment]
Reverted #4426 since `test/mocha/functional/ws/transport/transport.js` was consistently failing.
In this test, the connection as disconnected with the below reason
```
20:43:42.397Z DEBUG lisk-framework: EVENT_CLOSE_INBOUND: Close inbound peer connection (module=network, ipAddress=127.0.0.1, wsPort=25403, code=4009, reason="Peer should not send invalid or internal messages")
```
