### ISSUE TITLE
Check all of the exceptions related tests are covered

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#4433]
### Description

All of the tests in this folder is outdated, because those transaction type will be disabled.
https://github.com/LiskHQ/lisk-sdk/tree/development/framework/test/mocha/integration/transactions/exceptions

However, check all of the relevant tests are covered in `lisk-transactions` library. Otherwise, move the same tests.

### Motivation

Although this case is covered in the source code, since this will be outdated, need to make sure if the test is covered.

### Acceptance Criteria

- All of the relevant tests are covered in the unit tests.

**Comment by nazarhussain** [comment]
@shuse2 @ManuGowda Do you have any idea about `those transaction type will be disabled` mentioned in the issue. I don't see such transactions like signature or multi-signature is going to be disabled.

**Comment by shuse2** [comment]
@nazarhussain
I meant type 1-7 are disabled, and now default is type 8-12 although it's similar transaction
