### ISSUE TITLE
Fix fragile max payload test in p2p

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#4447]
### Expected behavior
A peer should not send payload to other peers when the payload exceeds the configured `maxPayload` size in p2p
### Actual behavior
The test is fragile and the reason is unknown, it doesn't consistently stop the node from sending the payload 
### Steps to reproduce
- `npm run test` in `lisk-p2p` library
### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0

**Comment by ManuGowda** [comment]
The max payload issue existed because of the invalid configuration passed during SC server creation.
Bug
```
this._scServer = attach(this._httpServer, {
            wsEngineServerOptions: {
                maxPayload: config.wsMaxPayload
                    ? config.wsMaxPayload
                    : DEFAULT_WS_MAX_PAYLOAD,
            },
        }) as SCServerUpdated;
```
Solution
```
this._scServer = attach(this._httpServer, {
            maxPayload: config.wsMaxPayload
                    ? config.wsMaxPayload
                    : DEFAULT_WS_MAX_PAYLOAD
        }) as SCServerUpdated;
```

**Comment by ManuGowda** [comment]
@ishantiw what is the difference between `maxPayload` and `wsEngineServerOptions.maxPayload`?

**Comment by valamidev** [comment]
Solved in, https://github.com/LiskHQ/lisk-sdk/pull/4432
