### ISSUE TITLE
Revisit Peer discovery threshold test

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#4503]
### Expected behavior
Test should not be unstable.

### Actual behavior
Test is unstable, and locally it fails more than 50%.
Also the test is checking the `newPeers`, but the `MINIMUM_PEER_DISCOVERY_THRESHOLD`, should check the result of getPeers.
Same for `MAX_PEER_DISCOVERY_RESPONSE_LENGTH`, it should check the getPeers response. 

### Steps to reproduce
Run peer discovery threshold test.

**Comment by valamidev** [comment]
Functionality is already covered with[ test/unit/peer_book/peer_book.ts](https://github.com/LiskHQ/lisk-sdk/blob/development/elements/lisk-p2p/test/unit/peer_book/peer_book.ts#L365) and edge cases are covered with integration test.

**Comment by valamidev** [comment]
Solved in #4556
