### ISSUE TITLE
API peers should hide internal state information

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#4508]
### Expected behavior
API get peers endpoint should not show internal fields (`nonce`, `blockVersion`, `maxHeightPrevoted`, `lastBlockId`).
### Actual behavior
```
{
"ip": "82.196.5.152",
"height": 475,
"os": "linux4.15.0-70-generic",
"version": "3.0.0-alpha.1",
"httpPort": 4000,
"protocolVersion": "2.0",
"blockVersion": 2,
"maxHeightPrevoted": 407,
"lastBlockId": "6569507740839559794",
"state": 2,
"nonce": "9e7fb782da3019c5",
"wsPort": 5000
}
```
### Steps to reproduce
http://devnet-seed-01.liskdev.net:4000/api/peers
### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0-alpha.1

**Comment by pablitovicente** [comment]
As per offline discussion with Ishan and Shu a change in P2P will take care of this. We decided not to add extra check in the http controller for Peers.

**Comment by shuse2** [comment]
`advertiseAddress` should not be shown to the API.
However, `blockVersion`, `maxHeightPrevoted`, `lastBlockId` are shared state which can be exposed since everyone will know through the RPC, and `state` is HTTP API specific field after #4576 , so it is fine to be there
