### ISSUE TITLE
API transactions by default should display latest transactions

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#4510]
### Expected behavior
The transactions should be ordered by height descending.
### Actual behavior
- The transactions are ordered by height ascending.
- API delegates by default give random ordered results
### Steps to reproduce
http://byzantine-seed-01.liskdev.net:4000/api/transactions
http://byzantine-seed-01.liskdev.net:4000/api/delegates
### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0-alpha.1

**Comment by pablitovicente** [comment]
@ManuGowda this seems to contradict what https://github.com/LiskHQ/lisk-sdk/issues/1884 requested could you elaborate a bit more on the change ?

**Comment by ManuGowda** [comment]
closing this issue with reference to response from #1884
