### ISSUE TITLE
Elements library show throw informative errors

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#4512]
### Expected behavior
When a user miss a required information to a function, it should throw error with missing required argument rather than generic error.
### Actual behavior
Missing argument `networkIdentifier` to transfer function throws generic error `Argument must be a string.`
### Steps to reproduce
```
elements.transaction.transfer({
 recipientId: a.address,
 amount: TO_BEDDOWS(amount),
 passphrase,
})
```
### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0-alpha.1

**Comment by pablitovicente** [comment]
I added a tests in elements as the base class does throw a descriptive error.
the `transfer()` function is using an slightly different method for validating and what's throwing this error is the call to `cryptography.hexToBuffer(networkIdentifier)` in `validateNetworkIdentifier` this method seems to be generic for re-use in cryptography so should I go for adding an extra check in `validateNetworkIdentifier()` for empty string? @shuse2
