### ISSUE TITLE
Node 12.13 LTS support

### ISSUE THREAD

**Issue by magmel48** [LiskHQ/lisk-sdk#4527]
### Description

Add Node 12.13 LTS support

### Motivation

Because it's LTS now

### Acceptance Criteria

No error when installing the libraries from the repo on machine with Node 12.x

### Additional Information

Now it cannot be achieved since there is check for engine:node <= 10.

**Comment by valamidev** [comment]
Solved in, #4448

Small changes might help, add `-- --ci` flag to `npm run bootstrap`.
`
npm ci
npm run bootstrap -- --ci
npm run build
`
