### ISSUE TITLE
Finalized height is not being updated

### ISSUE THREAD

**Issue by limiaspasdaniel** [LiskHQ/lisk-sdk#4546]
### Expected behavior
- Finalized height should be updated
- Add info log when the finality is updated
### Actual behavior
The block finality is not updated
### Steps to reproduce
Run the node and check the `node/status` endpoint on the HTTP API
### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0-alpha.2

**Comment by shuse2** [comment]
Fixed by #4499
