### ISSUE TITLE
Schema validation error for tx type 7

### ISSUE THREAD

**Issue by lsilvs** [LiskHQ/lisk-sdk#4585]
### Expected behavior
Expect to validate transaction `id = 8742556801784407667` on mainnet

### Actual behavior
It fails with the following error:

```
err: [
      {
        "message": "'.amount' should be string",
        "name": "TransactionError",
        "id": "8742556801784407667",
        "dataPath": ".amount"
      }
    ]
```

### Steps to reproduce
Start syncing with mainnet and wait until block height `808831`

### Which version(s) does this affect? (Environment, OS, etc...)
`3.0.0-alpha.2`

**Comment by ManuGowda** [comment]
Issue moved to [LiskHQ/lisk-core #174](https://github.com/LiskHQ/lisk-core/issues/174) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ManuGowda** [comment]
Issue moved to [LiskHQ/lisk-core #175](https://github.com/LiskHQ/lisk-core/issues/175) via [**ZenHub**](https://www.zenhub.com/)
