### ISSUE TITLE
Cut thread when there is an error applying P2P node info

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk-sdk#4587]
### Expected behavior

If the node info is not valid, application must log an error and stop execution, not applying the erroneous node info.

### Actual behavior

`validateNodeInfo` is throwing an error that is not capture when applying node info in P2P: https://github.com/LiskHQ/lisk-sdk/blob/c312538277e17e0e0031d19bdab7aee0a92f7f8a/elements/lisk-p2p/src/p2p.ts#L522

### Which version(s) does this affect? (Environment, OS, etc...)
`3.0`

**Comment by ManuGowda** [comment]
The applyNodeInfo is handled in the framework 
https://github.com/LiskHQ/lisk-sdk/blob/90372bbe6831249ceb7b1a97aa259de749964f2c/framework/src/modules/network/network.js#L174
