### ISSUE TITLE
Backup and use complete tried peers data

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk-sdk#4607]
### Expected behavior

All the data from tried peers is saved into the database and reused after a restart.

### Actual behavior
- Internal state is not being saved.
- Shared state not being used.

### Steps to reproduce
Start two nodes, use one of them as seed, check `network_info` database after some time.

### Which version(s) does this affect? (Environment, OS, etc...)
`3.0`

**Comment by shuse2** [comment]
Original behavior of this issue seems to be expected behavior
- All the banning score etc should be removed when the node is restarted
- shared state is most likely outdated, so it should not be reused

**Comment by ManuGowda** [comment]
> Original behavior of this issue seems to be expected behavior
> 
> * All the banning score etc should be removed when the node is restarted
> * shared state is most likely outdated, so it should not be reused

Let's take an example to understand this scenario. Imagine an external malicious node was attacking the node which got crashed if the node goes down and when it restarts and if it doesn't restore reputation, ban score and other information related to that, that malicious peer will be allowed back know? as the information is lost?

**Comment by shuse2** [comment]
I thought there was a phrase saying we should not keep the ban score after restarting, but i cannot find it in the LIP now. Maybe, it came from previous discussion.

Currently per LIP, it doesn't save the information on exit, rather it saves every 10min.
Therefore, in the scenario, unless timing was perfect, it will not affect anything.
Also, we are saving tried peer (not connected peers), the shared information is outdated for 2008/2048 in the maximum size case. In other words, only 40 / 2048 has updated information, but all other information are not useful
