### ISSUE TITLE
Cleanup test utilities for framework

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#4626]
### Description

There are a lot of utilities created for test suits for framework. Over the time many of these been duplicated due to two tests frameworks as Mocha and Jest. We need to go over these utilities and remove the duplicate ones and put rest into a common directory. 

### Motivation

Everyone writing tests should be aware of utilities available to streamline testing. These utilities should be clear and not duplicated so one can't be confused which function or fixture to use. 

### Acceptance Criteria

There should be no duplicate function, file, fixture as named a utility for tests.

**Comment by karmacoma** [comment]
Closed by #4645
