### ISSUE TITLE
HTTP API whitelists do not always work as expected

### ISSUE THREAD

**Issue by fchavant** [LiskHQ/lisk-sdk#4629]
- Setting the `LISK_API_WHITELIST` environment variable (e.g by adding `export LISK_API_WHITELIST=127.0.0.1` to `env.sh`) breaks the whitelist: no IP whatsoever is allowed to connect (in the example `127.0.0.1` will not get an HTTP code `403`
- Similarly setting `LISK_FORGING_WHITELIST` breaks the "forging" whitelist
- Setting `.modules.http_api.forging.access.whiteList[0]` in a custom `config.json` also breaks the "forging" whitelist.

I strongly suspect this behaviour was introduced with `2.0` but I can only state with certainty that is is present in `2.0.2`, `2.1.3` and a recent build from the `development` branch. See this [spreadsheet](https://docs.google.com/spreadsheets/d/1CVndVU-1IWkUXq9hMAUfDRzTXpGLfAiXOEaYZTsh-C0/view) for details.

**Comment by nazarhussain** [comment]
Confirmed, Its because of wrong formatter:

https://github.com/LiskHQ/lisk-sdk/blob/090e5a011ecaff59034da6b66ff7ae0e19474b0d/framework/src/modules/http_api/defaults/config.js#L50

It converts environment variables to array of objects with `{ip: '', wsPort: ''}` definition.

**Comment by fchavant** [comment]
@nazarhussain that exlpains `LISK_API_WHITELIST` and `LISK_FORGING_WHITELIST` being unusable but what about `.modules.http_api.forging.access.whiteList=["<EXTERNAL_IP>"]` not working?

**Comment by nazarhussain** [comment]
@fchavant I tried this custom config file it works for me. 

```
{
  "modules": {
	"http_api": {
	  "access": {
		"whiteList": ["192.168.99.99"]
	  },
	  "forging": {
		"access": {
		 "whiteList": ["192.168.99.99"]
		}
	  }
	}
  }
}
```

So there may be some other issue, will debug further.

**Comment by fchavant** [comment]
@nazarhussain 
```
wget https://lisk-releases.ams3.digitaloceanspaces.com/lisk-core/lisk-3.0.0-alpha.2-090e5a011-bfe1e76-Linux-x86_64.tar.gz https://lisk-releases.ams3.digitaloceanspaces.com/lisk-core/lisk-3.0.0-alpha.2-090e5a011-bfe1e76-Linux-x86_64.tar.gz.SHA256
sha256sum -c lisk-3.0.0-alpha.2-090e5a011-bfe1e76-Linux-x86_64.tar.gz.SHA256
tar xf lisk-3.0.0-alpha.2-090e5a011-bfe1e76-Linux-x86_64.tar.gz.SHA256
cd lisk-3.0.0-alpha.2-090e5a011-bfe1e76-Linux-x86_64/
sed -i -r -e 's/^LISK_NETWORK=.*/LISK_NETWORK=testnet/' env.sh
./lisk.sh coldstart -0
curl http://127.0.0.1:7000/api/node/status  # 200
curl http://188.166.27.120:7000/api/node/status  # 403
echo {} >empty.json
jq '.modules.http_api.forging.access.whiteList=["188.166.27.120"]' empty.json >config.json
./lisk.sh reload
curl http://127.0.0.1:7000/api/node/status  # 200
curl http://188.166.27.120:7000/api/node/status  # 403
source env.sh
node scripts/generate_config.js -c config.json |jq .modules.http_api.access.whiteList  # ["127.0.0.1"]

**Comment by nazarhussain** [comment]
@fchavant 

custom.json
```
{
    "modules": {
        "http_api": {
            "access": {
                "whiteList": [
                    "192.168.9.0"
                ]
            },
            "forging": {
                "access": {
                    "whiteList": [
                        "192.168.9.1"
                    ]
                }
            }
        }
    }
}
```
Run the command

```
node scripts/generate_config.js -c custom.json | jq .modules.http_api
```

Here is the output:

```
{
  "access": {
    "public": true,
    "whiteList": [
      "192.168.9.0"
    ]
  },
  "forging": {
    "access": {
      "whiteList": [
        "192.168.9.1"
      ]
    }
  },
  "enabled": true,
  "httpPort": 4000,
  "address": "0.0.0.0",
  "trustProxy": false,
  "ssl": {
    "enabled": false,
    "options": {
      "port": 443,
      "address": "0.0.0.0",
      "key": "./ssl/lisk.key",
      "cert": "./ssl/lisk.crt"
    }
  },
  "options": {
    "limits": {
      "max": 0,
      "delayMs": 0,
      "delayAfter": 0,
      "windowMs": 60000,
      "headersTimeout": 5000,
      "serverSetTimeout": 20000
    },
    "cors": {
      "origin": "*",
      "methods": [
        "GET",
        "POST",
        "PUT"
      ]
    }
  }
}
```

So to me it seems works fine with the custom configuration file. For env variables I will fix it.

**Comment by fchavant** [comment]
@nazarhussain you're not testing with the (exact) same config.js; did you try the reproduction steps I posted above?
