### ISSUE TITLE
Use chalk package for coloured output in console

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#4650]
### Expected behavior

The usage of coloured output should semantically correct and known to developers. Currently the coloured out put is broken in the system and not known the reason. Even not known which library was used actually for that purpose. 

https://github.com/LiskHQ/lisk-sdk/blob/6b737b961ccf952bd44337b0adbe01d34e3b95e3/framework/test/utils/http/api.js#L61

https://github.com/LiskHQ/lisk-sdk/blob/6b737b961ccf952bd44337b0adbe01d34e3b95e3/framework/test/mocha/functional/ws/transport/transport.js#L249

Check the usage of `string`.grey, its broken right now and showing `undefined; 

### Actual behavior

We should use `chalk` package for such use case as its already in chain for dev dependencies. 

```js
const chalk = require('chalk');

console.log(chalk.grey('String output'));
```

### Steps to reproduce

Run the tests and notice the output. 

### Which version(s) does this affect? (Environment, OS, etc...)

2.0

**Comment by shuse2** [comment]
Closing because after migration to jest, we no longer have verbose output in the test
