### ISSUE TITLE
Fix all the fragile P2P test for consistant result

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#4651]
### Expected behavior
The p2p test suite should consistently pass on `development` and `release/3.0.0` branch
### Actual behavior
Few of the p2p tests are fragile, this leads to multiple build failures causing interruption for development and slowness and inconsistency with the test.
Following are the tests:
- `getBucketId: should return different buckets for same target address and source address but different peerType ` -> `test/unit/utils/misc.ts:356`
- `p2p.send: should send a message to peers; should reach peers with even distribution` -> `test/functional/actions/send.ts:75`
### Steps to reproduce
Looking to jenkins job, many PRs are failing due to these common tests failures
### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0, development

**Comment by valamidev** [comment]
Related to #4654

**Comment by shuse2** [comment]
Closed by #4654
