### ISSUE TITLE
lisk core stops, something about SSL

### ISSUE THREAD

**Issue by liberspirita-lisk** [LiskHQ/lisk-sdk#4655]
### Expected behavior
Just using lisk commander to send lisk : 
lisk@clovis:~/lisk-test$ lisk transaction:create:transfer 100 11237438676908077440L  --pretty
? Please enter your secret passphrase:  [hidden]
? Please re-enter your secret passphrase:  [hidden]
{
	"id": "11945506560372285320",
	"amount": "10000000000",
	"type": 0,
	"timestamp": 113861590,
	"senderPublicKey": "ab5146c3d62747f6372f5b35ca68ff85dccba9094526f84cd557133d395a8a7d",
	"senderId": "3897910504949673529L",
	"recipientId": "11237438676908077440L",
	"fee": "10000000",
	"signature": "5e09d5faf7caa6c8c5c6205ce7ad4e21e5fd32cb9bb2471bc6c14504ef0c8b9af49de05e71ce51c423a63df7d5d8b259aea26ad1028d4873b138f51c66143b02",
	"signatures": [],
	"asset": {}
}

lisk@clovis:~/lisk-test$ lisk transaction:get 11945506560372285320
 **›   Error: write EPROTO 139842222430016:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:**
 

### Actual behavior
Lisk core stops after few seconds, in logs this msg : 
  ✔ Start Lisk Core instance
lisk@clovis:~/lisk-test$ lisk core:logs lisk-testnet
{"name":"lisk-framework","hostname":"clovis","pid":12022,"level":50,"err":{"message":"there is no unique constraint matching given keys for referenced table \"trs\"","name":"error","stack":"error: there is no unique constraint matching given keys for referenced table \"trs\"\n    at Connection.parseE (/home/lisk/.lisk/instances/lisk-testnet/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/home/lisk/.lisk/instances/lisk-testnet/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/home/lisk/.lisk/instances/lisk-testnet/node_modules/pg/lib/connection.js:119:22)\n    at Socket.emit (events.js:198:13)\n    at Socket.EventEmitter.emit (domain.js:448:20)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)","code":"42830"},"msg":"there is no unique constraint matching given keys for referenced table \"trs\"","time":"2020-01-02T13:08:20.962Z","v":0}{"name":"lisk-framework","hostname":"clovis","pid":12022,"level":50,"msg":"App stopped with error there is no unique constraint matching given keys for referenced table \"trs\"","time":"2020-01-02T13:08:20.965Z","v":0}
{"name":"lisk-framework","hostname":"clovis","pid":12041,"level":30,"msg":"Booting the application with Lisk Framework(0.1.0)","time":"2020-01-02T13:08:22.523Z","v":0}
{"name":"lisk-framework","hostname":"clovis","pid":12041,"level":30,"msg":"Starting the app - lisk-testnet-7004","time":"2020-01-02T13:08:22.524Z","v":0}
{"name":"lisk-framework","hostname":"clovis","pid":12041,"level":30,"msg":"Initializing controller","time":"2020-01-02T13:08:22.525Z","v":0}
{"name":"lisk-framework","hostname":"clovis","pid":12041,"level":30,"msg":"Loading controller","time":"2020-01-02T13:08:22.536Z","v":0}
{"name":"lisk-framework","hostname":"clovis","pid":12041,"level":30,"msg":"Old PID: 12022","time":"2020-01-02T13:08:22.586Z","v":0}
{"name":"lisk-framework","hostname":"clovis","pid":12041,"level":30,"msg":"Current PID: 12041","time":"2020-01-02T13:08:22.586Z","v":0}
{"name":"lisk-framework","hostname":"clovis","pid":12041,"level":50,"err":{"message":"there is no unique constraint matching given keys for referenced table \"trs\"","name":"error","stack":"error: there is no unique constraint matching given keys for referenced table \"trs\"\n    at Connection.parseE (/home/lisk/.lisk/instances/lisk-testnet/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/home/lisk/.lisk/instances/lisk-testnet/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/home/lisk/.lisk/instances/lisk-testnet/node_modules/pg/lib/connection.js:119:22)\n    at Socket.emit (events.js:198:13)\n    at Socket.EventEmitter.emit (domain.js:448:20)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)","code":"42830"},"msg":"there is no unique constraint matching given keys for referenced table \"trs\"","time":"2020-01-02T13:08:22.638Z","v":0}
{"name":"lisk-framework","hostname":"clovis","pid":12041,"level":50,"msg":"**App stopped with error there is no unique constraint matching given keys for referenced table \"trs\"","time":"2020-01-02T13:08:22.641Z","v":0}**

### Steps to reproduce
Nothing but installing new testnet node
+ few stuffs : python3, php7, sqlite, and many things that turn around

### Which version(s) does this affect? (Environment, OS, etc...)
Debian 9
lisk-testnet last version
nodejs v12.14.0
npm 6.13.4

**Comment by ManuGowda** [comment]
@liberspirita-lisk we tried to reproduce this issue with following steps
- Ensure the node we were installing the lisk-core testnet instance had enough space
- Install using commander `lisk core:install -n testnet test`
- Check the logs after install `lisk core:logs test`

Other info:
Commander version: `lisk-commander/2.2.3 linux-x64 node-v12.14.0`
Lisk core version: `2.1.3-rc.1`
Lisk blockchain snapshot checksum: `e4130aed0e0c6e83d33a235226ca72f08993e9ced7c32d24533c85c81f254f53`
Snapshot path in commander: `cd ~/.cache/lisk-commander/downloads.lisk.io/lisk/testnet/`

could you give us the detailed steps to reproduce this issue?

**Comment by liberspirita-lisk** [comment]
@ManuGowda  I have just reproduced the issue on a new machine (a laptop running Linux Mint 19), 
fresh creation of a lisk user, with nodejs 12.14, "lisk core:install lisk-mainnet"
and the logs finished like that ... :

> {"name":"lisk-framework","hostname":"liberspirita","pid":20663,"level":50,"msg":"App stopped with error there is no unique constraint matching given keys for referenced table \"trs\"","time":"2020-01-05T17:42:36.341Z","v":0}

**Comment by shuse2** [comment]
With the HTTP API plugin being development focus, SSL feature has been removed
