### ISSUE TITLE
Create lisk interfaces as an element

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#4658]
### Description
Add interface definitions as a separate element library and use the interfaces in the required element and framework.
### Motivation

As the `SDK` progress towards typescript, all of the interfaces will be scattered around and can have duplication and problems with usability.

### Acceptance Criteria
- Should have new element library `lisk-interfaces`? 
- Should include interface definitions for `TransactionPool, P2P, State Store` and the other libraries that we planned to move for example `Blocks, DPoS, etc...`

**Comment by shuse2** [comment]
Separating the interface will not make sense because each library will have distinct domain.
It should be separated as they are independent.
Also, it will be hard to manage the dependency.

**Comment by ManuGowda** [comment]
The separate was for reusability and ease of accessibility. We don't have to jump into it right away, we can discuss it with the team and close the issue if it's not valid. 
In the future, if somebody is implementing some library that needs the interface definitions they have to require the whole package for that, It is possible as you mentioned, but we can discuss it when everyone is here.

**Comment by shuse2** [comment]
They do not need to import the whole package.
Typescript use duck typing interface. This is already how transaction and transaction pool are implemented
