### ISSUE TITLE
Lisk Core with enabled HTTP API gets out of sync

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-sdk#4662]
### Expected behavior

Lisk Core keeps the same height as the whole network.

### Actual behavior

Lisk Core stops syncing and the API is unavailable.
It does not happen when the API access is disabled.

Important: the issue fixes itself after a while before reoccurring.

### Steps to reproduce

Spin up a single node connected to the testnet with the API enabled.
After some time, usually a few days, the node will not respond to the REST API requests.

### Which version(s) does this affect? (Environment, OS, etc...)

2.1.3-rc.1

**Comment by pablitovicente** [comment]
This might have been solved by #4714 @MichalTuleja please check and report back

**Comment by shuse2** [comment]
Solved in #4714
