### ISSUE TITLE
asset_contains and asset_exists filters for transaction entity

### ISSUE THREAD

**Issue by corbifex** [LiskHQ/lisk-sdk#4695]
### Description

Make filtering possible on transaction assets. The same filters as already exists in the account entity: `asset_contains` and `asset_exists`

### Motivation

To be able to select a more specific group of transactions.

### Acceptance Criteria

The transaction entity with `asset_contains` and `asset_exists` filters.

**Comment by shuse2** [comment]
We are not planning to extend the state store for transaction in the future for several reasons.
It was mainly for the backward compatibility for previous protocol.
1. Concept-wise, transaction is not a state
2. If transaction will have context of history other than account, which might make future protocol improvement harder
