### ISSUE TITLE
Remove swagger-node-runner dependency from the http-api module

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#4702]
### Description

We need to remove `swagger-node-runner` from `http-api` module and directly use the `sway` package. The runner itself is just a wrapper around sway with few extra usability features. 

### Motivation

We need to reduce the dependencies in the application, specially which are not maintained actively. With that spirit, we need to remove a very less maintained package `swagger-node-runner` from the dependencies. 

### Acceptance Criteria

There should not be any vulnerability after removing swagger-node-runner and directly moving integration to sway package.

**Comment by shuse2** [comment]
Closing this in favor of #5213 and we will not use swagger as runner
