### ISSUE TITLE
Add integration test for lisk-chain library

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#4791]
### Description
Add missing unit and integration test for lisk-blocks module
### Motivation
- Missing unit test for blocks cache module
- Missing integration test for chain module
### Acceptance Criteria
- Add missing unit test for the lisk-blocks module (blocks cache, data access module)
- Add Integration test for lisk-blocks module

**Comment by shuse2** [comment]
Superseded by #5257
