### ISSUE TITLE
Lisk Commander transaction type errors

### ISSUE THREAD

**Issue by Lemii** [LiskHQ/lisk-sdk#4801]
When I try to create a regular transfer transaction with Lisk Commander, it throws an error stating that the transaction type is incorrect. It seems there is an offset of 8:

```
lisk transaction:create --type=0 100 1L -p=pass:"word word word word word word word word word word word word"


 ›   Error: Expected --type=0 to be one of: 8, transfer, 9, second-passphrase, 10, delegate, 11, vote, 12, multisignature
 ›   See more help with --help
```

When I try to create the transaction with `--type=transfer` it generates a transaction with `"type: 8", in its body -- which gets rejected by the network as expected.

### Which version(s) does this affect? (Environment, OS, etc...)
- lisk-commander/3.0.1 linux-x64 node-v13.5.0
- Ubuntu 18.04

**Comment by Lemii** [comment]
This problem appears to be related to version `3.0.0` and up. I rolled back to `2.2.3` and that is working correctly.

**Comment by shuse2** [comment]
@Lemii Currently latest commander only supports lisk-sdk@3.0~.
If you want to use it for current testnet/mainnet, please use v2 version
