### ISSUE TITLE
Integrate new transaction pool implementation and cleanup

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#4856]
### Description
With the new transaction pool implementation, we need to clean up the existing transaction pool implementation which is no longer needed and integrate new transaction pool implementation.

### Motivation
Maintainability is the key motivation to clean up the existing transaction pool implementation which will be outdated after the new transaction pool implementation.

### Acceptance Criteria
- Remove logic related to `validated`, `verified` and `ready` (transaction-pool)
- Remove get actions related to signature processing, validated transactions, verified transactions, adding multi-sign transactions.
- Remove all the tests related to `validated`, `verified`, `ready` and the get actions.
- Integrate new transaction pool implementation
- Consolidate `processTransactions` and `verifyTransactions` into `applyTransactions`
- Update `addTransaction` and `removeTransaction` to `add` and `remove`
- Use `AddTransactionResponse` to respond for `addTransaction`
```
interface AddTransactionResponse {
	readonly status: Status;
	readonly errors: ReadonlyArray<TransactionError>;
}
```
- Test if transactions are accepted from API and Network
- Test if valid transactions are included in the block

### Related issues
#4841

**Comment by shuse2** [comment]
Superseded by #4864
