### ISSUE TITLE
 commander: lisk config:set api.network fails

### ISSUE THREAD

**Issue by biolypl** [LiskHQ/lisk-sdk#4872]
### Expected behavior
Command `lisk config:set api.network beta` should set network to betanet.
### Actual behavior
The command fails with error: 
```
 ›   Error: Value must be a hex string with 64 characters, or one of main or 
 ›   test.
```
### Steps to reproduce
Try to set beta network with lisk commander.
### Which version(s) does this affect? (Environment, OS, etc...)
lisk-commander/3.0.2 linux-x64 node-v12.14.1

**Comment by biolypl** [comment]
If this is correct behavior for the beta argument, then please fix the documentation [here](https://lisk.io/documentation/lisk-sdk/reference/lisk-commander/user-guide.html#_configure_the_network)  (worth to mention that _<NETWORK>_ can be the 64 bytes network identifier).

**Comment by shuse2** [comment]
With #5211 , this is no longer relevant
