### ISSUE TITLE
commander: creation transaction for custom network (betanet) return error

### ISSUE THREAD

**Issue by biolypl** [LiskHQ/lisk-sdk#4873]
With given lisk-commander config (for betanet):
```
{
	"json": true,
	"api": {
		"nodes": [
			"https://betanet.lisk.io"
		],
		"network": "7158c297294a540bc9ac6e474529c3da38d03ece056e3fa2d98141e6ec54132d"
	},
	"pretty": true,
	"default": {
...
	}
}
``` 
should be possible to create transactions with `lisk transaction:create` (e.g. `lisk transaction:create -t=8 100  3385439950339234343L`)
### Expected behavior

Create transaction.

### Actual behavior
Return error:  `Error: Invalid network identifier`. To create transaction user has to specify the network identifier again with flag --networkIdentifier, which isn't marked as required.
### Steps to reproduce
Config lisk-commander for betanet, try create any type of transaction. 
### Which version(s) does this affect? (Environment, OS, etc...)
lisk-commander/3.0.2 linux-x64 node-v12.14.1

**Comment by shuse2** [comment]
> To create transaction user has to specify the network identifier again with flag --networkIdentifier, which isn't marked as required.

This is expected behavior because the `betanet` itself is temporal network.
We only support aliasing on the mainnet and testnet
