### ISSUE TITLE
Update base transaction sign function

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#4906]
### Description
Update base transaction sign function to allow the transaction to be signed by multiple pass-phrases. 

### Motivation
After the removal of `signature` and `signSignature` from the base transaction, and with the. introduction of new multi-signature LIP changes, we need to allow accounts to sign for multi-signature accounts and regular accounts with single and multiple passphrases.

### Acceptance Criteria

- `sign` function in `base_transaction` should be updated to allow signing for 
   - a regular account with one passphrase
   - a regular account with multiple pass-phrases
   - multi-signature account
- At least happy path tests cases for all transaction types are added 
### Additional Information
- Commander `sign` function needs update?

### Related Issues
#4836

**Comment by pablitovicente** [comment]
- I'm 99% sure this is solved by https://github.com/LiskHQ/lisk-sdk/pull/4901
- Issue created for commander in https://github.com/LiskHQ/lisk-sdk/issues/4905
