### ISSUE TITLE
Add command to get fee estimation

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#4910]
### Description

`transaction:estimate` command should be implemented. 
It should call lisk-service endpoint and present the result

### Motivation

- With the new dynamic fee system, command to get fee estimation from the network is required.

### Acceptance Criteria

- It should show all low, medium and high priority estimation

### Related Issues
#4837

**Comment by sridharmeganathan** [comment]
This  issue is depended on lisk-Service

**Comment by ManuGowda** [comment]
Closing this issue as we do not integrate service to lisk-sdk.
