### ISSUE TITLE
Typesafe StateStorePrepare

### ISSUE THREAD

**Issue by JesusTheHun** [LiskHQ/lisk-sdk#4949]
Currently the type definition of the StateStorePrepare is as follow: 

```typescript
export interface StateStoreCache<T> {
	cache(
		filterArray: ReadonlyArray<{ readonly [key: string]: string }>,
	): Promise<ReadonlyArray<T>>;
}
```

Using type literal it is possible to provide an exhaustive list of available filters, allowing slick auto-completion and type safety, in following code : 

```typescript
class SomeTransaction {
	public async prepare(store: StateStorePrepare): Promise<void> {
		await store.account.cache([
			{
				address_in: ['1L', '2L'], // OK
				balance_in: 100, // Error
				balance_gte: 100, // OK
			},
		]);
	}
}
```

**Comment by shuse2** [comment]
Closing because `prepare` method was there for technical reason , and it will be removed
