### ISSUE TITLE
Remove network identifier from the constructor of transaction

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#4961]
### Description

Network identifier is not part of the transaction instance and it is only required during signature validation.
With the changes to #4951, it will be part of the chain state, so base transaction should get networkIdentifier from chain state to verify the signature.

### Acceptance Criteria

- Remove the network identifier while instantiating the transaction
- Use the network identifier in the chain state to validate signature
- Remove variable networkIdentifier in the base transaction

**Comment by ManuGowda** [comment]
@shuse2 I updated the issue, let me know if the details are correct, I will pick up the issue.
