### ISSUE TITLE
Do not log private information for blocks in the logger

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#5023]
### Expected behavior

It should not log information like private keys in the console/logger

### Actual behavior

When creating a new block it logs some sensitive information at trace level that needs to be removed

### Steps to reproduce

Run the application and check the logs at TRACE level

### Which version(s) does this affect? (Environment, OS, etc...)
`4.0.0`

**Comment by shuse2** [comment]
Closed By #5036
