### ISSUE TITLE
Add test for apply transactions in specific order

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#5040]
### Expected behavior
Test for transaction that is not independently valid, but as sequentially valid should be added.

### Actual behavior
There is no test specific to this scenairo

### Which version(s) does this affect? (Environment, OS, etc...)
4.0-

**Comment by MaximeGagnebin** [comment]
Starting from the initial-state: {A is a regular account with 100 tokens}

The following payloads should now be valid:

payload1: {A sends 2 to B; B sends 1 to C}
payload2: {A registers as delegate; A votes for themselves}
payload3: {A registers as delegate; A votes for themselves; A unvotes themselves}
payload4: {A registers as multisig; A sends 1 to B (with new multisig signatures)}
payload5: {A sends 10 to B; A registers as delegate; B votes for A}

The followings should still be invalid:

payload6: {A registers as multisig; A sends 1 to B (with old signature)}
payload7: {A sends 2 to B; B sends 3 to C; A sends 2 to B}
