### ISSUE TITLE
Update maxTransctionsPerBlock to maxPayloadSize

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#5071]
### Expected behavior

- genesis config should have `maxPayloadLength` and not `maxTransactionsPerBlock`
-  `delegateListRoundOffset` should be moved to constants_schema from application_config_schema
- `sdk/src/samples/config_devnet.json` should reflect the update.

### Actual behavior
It still has `maxTransactionsPerBlock` in `framework/src/application/schema/application_config_schema.js`.

### Which version(s) does this affect? (Environment, OS, etc...)
4.0-

**Comment by pablitovicente** [comment]
Took the size of a multi-signature registration with max number of public keys and it was 6260 bytes so I will set a safe minimum of 10KB for maxPayloadLength and a max of 30K in the schema.
