### ISSUE TITLE
Delegate should not punished by DPoS violation for first rounds 

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#5110]
### Expected behavior
Delegate for first rounds are punished for the DPoS violation

### Actual behavior
```
{
 "id": "7620152438571012831"
}
15:47:52 INFO lisk-framework: Punishing delegate for DPoS violation (module=lisk:app)
{
 "id": "17099278745515138981"
}
15:47:52 INFO lisk-framework: Punishing delegate for DPoS violation (module=lisk:app)
{
 "id": "10681471986634929949"
}
15:47:52 INFO lisk-framework: Punishing delegate for DPoS violation (module=lisk:app)
{
 "id": "17861655877572574378"
}
```

### Steps to reproduce
Run a node for several rounds, and try to sync with the node

### Which version(s) does this affect? (Environment, OS, etc...)
4.0-

**Comment by ManuGowda** [comment]
- Blocks cache needed to be sorted `desc`
- Used hash onion need to filtered including 3 rounds (103 * 3)

**Comment by shuse2** [comment]
For the hash-onion, it should leave at least one entry per account.
If there are more than 2 entries, the entries that are not the highest hight can be removed after finality.
