### ISSUE TITLE
Votes field in account is not clear about votes received or sent

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#5124]
### Expected behavior

Sent or casted votes should have a proper field name

### Actual behavior

As of now, sent or casted votes are coming under `votes` field which is a bit misleading as the user might get confused whether it's a sent or received or both kind of votes

### Steps to reproduce

Run a node and check http://localhost:4000/api/delegates?address={address} or  http://localhost:4000/api/accounts?address={address} endpoints to check for `votes` field

### Which version(s) does this affect? (Environment, OS, etc...)
`4.0.0`

**Comment by shuse2** [comment]
Superseded by #5264
