### ISSUE TITLE
Commander can't pass transaction JSON

### ISSUE THREAD

**Issue by LiskLabs** [LiskHQ/lisk-sdk#5143]
lisk transaction:verify '{"id":"13036533180773661471","type":8,"timestamp":122393758,"senderPublicKey":"da35dfe3875eefd2f9036b9c3044cc0bddc24b6f301afcb197ba2a74449ccce1","senderId":"4924831198491420106L","fee":"10000000","signature":"32fea76a7f9d9ae36586e34b4e76e8f41a0d3fffedb3b2297a230d3fa90cebf38c563f868b2cc3dd6e3a68d168616e6d91ae0e5a65feb54fc96dfacdfc76f503","signatures":[],"asset":{"amount":"1000000000","recipientId":"18252847109812530468L"}}'                

»   Error: Could not parse transaction JSON.

**Comment by shuse2** [comment]
I just tried with latest 3.0.2, but it seems it is parsing correctly
```
 ❯ lisk transaction:verify '{"id":"13036533180773661471","type":8,"timestamp":122393758,"senderPublicKey":"da35dfe3875eefd2f9036b9c3044cc0bddc24b6f301afcb197ba2a74449ccce1","senderId":"4924831198491420106L","fee":"10000000","signature":"32fea76a7f9d9ae36586e34b4e76e8f41a0d3fffedb3b2297a230d3fa90cebf38c563f868b2cc3dd6e3a68d168616e6d91ae0e5a65feb54fc96dfacdfc76f503","signatures":[],"asset":{"amount":"1000000000","recipientId":"18252847109812530468L"}}'
{
        "verified": false
}
```

**Comment by LiskLabs** [comment]
What am I dong wrong then ?  I am on a win cmd.

![Untitled](https://user-images.githubusercontent.com/63418527/78993868-6a079e00-7b47-11ea-924f-a34efa9b808f.png)

**Comment by shuse2** [comment]
That might be the reason, we havent supported the windows machines yet. 
I don't have windows machine right now that I can debug...let's see if someone can debug this

**Comment by LiskLabs** [comment]
Ok. I am looking to build .NET on top of Lisk. Is assuring to know at least is in the pipeline.

**Comment by LiskLabs** [comment]
`lisk transaction:broadcast '{"id":"17109110869242775824","type":8,"timestamp":122710352,"senderPublicKey":"fa5607ff84d3e82437a899074d1f718478213c854b830cee12929490f489ec62","senderId":"1829930269694993659L","fee":"10000000","signature":"4de4277eeade1b077375a24ca9c5924bc3ecca536c75227157a6d1147f4b4cf5de2e0a44b0c0f4eb9844a8727d35a2c9fc7619b29b3a52cae15326f688922704","signatures":[],"asset":{"amount":"100000000","recipientId":"18252847109812530468L"}}'`

What am I doing wrong here ? I m on a linux terminal.

![Untitled](https://user-images.githubusercontent.com/63418527/79172200-b3344800-7dfc-11ea-9fb5-91c30a420781.png)

**Comment by shuse2** [comment]
Commander and elements has the same time when it is used with corresponding version.
However, because current latest release is not used in the Lisk-Core mainnet, the latest elements and commander versions have transaction type greater than 8 while mainnet/testnet has 0-7

**Comment by LiskLabs** [comment]
Does dies work ? 

https://lisk.io/documentation/lisk-sdk/guides/broadcast.html

**Comment by shuse2** [comment]
@LiskLabs it works, but this documentation is for `Lisk SDK`, and Lisk Core currently does not support these default transactions yet

**Comment by LiskLabs** [comment]
How do I brodcast a transaction ?

**Comment by LiskLabs** [comment]
I don't understand. I just want to broadcast a transaction. It doesn't really mater what OS or language I use. 

So, can I broadcast a transaction with Lisk SDK ? ( or Lisk SDK goes throw the Lisk CORE and the answer is NO ?  )

**Comment by shuse2** [comment]
If you just need to broadcast a signed transaction,
you can either directly call http api endpoint to the server which they enabled the endpoint with
```
POST /api/transactions
```
or using APIClient
```
const api = new APIClient([url]);
await api.transactions.broadcast(tx.toJSON())
```

**Comment by LiskLabs** [comment]
Ok. Great.

And to create a valid signed transaction ? I understand Commander and Elements is a no.

**Comment by shuse2** [comment]
If you want to send it to testnet/mainnet now, then please use below version
```
"@liskhq/lisk-cryptography": "2.3.0",
"@liskhq/lisk-transactions": "2.3.1",
"lisk-commander": "2.2.3",
"lisk-sdk": "2.3.7",
```
or version up to this branch https://github.com/LiskHQ/lisk-sdk/tree/v2

**Comment by LiskLabs** [comment]
On your website it clearly states Ubuntu 16 & 18 ( 32b & 64b ). I have Ubuntu 16 32b and can't install the core :((

**Comment by LiskLabs** [comment]
Do I need to change the "networkIdentifier" for Mainnet? 

![Untitled](https://user-images.githubusercontent.com/63418527/79291638-d5e75f00-7ed7-11ea-87ce-b24954cfd870.png)

`#!/usr/bin/env node

const transactions = require('@liskhq/lisk-transactions');
const {getNetworkIdentifier} = require('@liskhq/lisk-cryptography');
const { APIClient } = require('@liskhq/lisk-api-client');

// Constants
const API_BASEURL = 'http://localhost:8000';
const networkIdentifier = getNetworkIdentifier(
    "23ce0366ef0a14a91e5fd4b1591fc880ffbef9d988ff8bebf8f3666b0c09597d",
    "Lisk",
);

// Initialize
const api = new APIClient([API_BASEURL]);

const tx = new transactions.TransferTransaction({
    asset: {
        amount: '0.00001',
        recipientId: ' 1071996747232285522L',
    },
    networkIdentifier: networkIdentifier,
});

tx.sign('creek own stem final gate scrub live shallow stage host concert they');

api.transactions.broadcast(tx.toJSON()).then(res => {
    console.log("++++++++++++++++ API Response +++++++++++++++++");
    console.log(res.data);
    console.log("++++++++++++++++ Transaction Payload +++++++++++++++++");
    console.log(tx.stringify());
    console.log("++++++++++++++++ End Script +++++++++++++++++");
}).catch(err => {
    console.log(JSON.stringify(err.errors, null, 2));
});`

**Comment by shuse2** [comment]
For the mainnet, network identifier is not required.
Also, `amount` and `recipientId` should be in the root level. (it was moved inside of asset only in the SDK 3.0-). Finally, `amount` should be integer (unit should be beddow) 1LSK = 10^8 Beddows
```
const tx = new transactions.TransferTransaction({
        amount: '0.00001',
        recipientId: ' 1071996747232285522L',
});
```
Please refer to the previous version of the documentation

https://lisk.io/documentation/lisk-sdk/2.3.7/index.html

**Comment by LiskLabs** [comment]
Thank you. The issue can be closed. I am also on Discord now.
