### ISSUE TITLE
Notification Events

### ISSUE THREAD

**Issue by pablitovicente** [LiskHQ/lisk-sdk#5162]
### Description

Node should emit channel events that notify the need of actions to be carried by the node operator. 

### Motivation

Messages for events such as hash onion empty, when a node stops forging for some reason, and other events that do not crash the node but are due to specific circumstances that require attention. Although this events can be detected by querying the API, greping the logs, etc. it would be nice for the node to provide a programatic way for operators to be aware of these types of events

### Acceptance Criteria

We should discuss this as it will use the existing channel functionality but introduces a new family of events.

**Comment by shuse2** [comment]
Closing this in favor of #5216
