### ISSUE TITLE
Unify all generated files to specific folder

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#5184]
### Description

Replace the application config property `tempPath` with `dataPath`, and store all generated files in the folder, like so:

```js
${dataFolder}/tmp // sock files etc
${dataFolder}/logs
${dataFolder}/data
${dataFolder}/configs
```

### Motivation

Currently, the generated files are in different folders, and we want to have a consistent approach.

### Acceptance Criteria

- All generated files are in one folder as specified above

**Comment by ManuGowda** [comment]
This issue is addressed by https://github.com/LiskHQ/lisk-sdk/issues/5243
