### ISSUE TITLE
Update to only use 1 IPC socket file

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#5187]
### Description

Currently to enable IPC communication with child process, we use 3 sock files, but the same feature should be achievable through one socket only.

### Motivation

We don't need to manage 3 sock files.

### Acceptance Criteria

- Only one sock should be created when IPC communication is enabled

### Additional Information

- Investigate the difficulty of updating `lisk-framework` to only use 1 socket, and decide whether to implement in this version or not

**Comment by nazarhussain** [comment]
Evaluated all the options within the current implementation we have. If we stick with the `axon` library that we are using then it's not possible. We have to keep the following socket files in **root sockets directory** `.lisk/<app>/tmp/sockets/`

File  | Description 
---|---
pub_socket.sock  | The event socket file where bush publishes the events and plugins subscribe to those events. This works as an axon `pub/sub` communication model. This should be the main socket file if a third party plugin wants to listen to all events.
sub_socket.sock | This event socket file where all plugins publish the events and bus listens to those. This works as an axon `push/pull` but in sink mode. This is required as `axon` does not support mutli-emitter with `pub/sub` model. 
bus_rpc_socket.sock | On this file `Bus` exposes all its RPC actions. This should be the main socket file, where any third party plugin has to connect to invoke RPC calls. For plugins, the bus will route those calls to respective RPC sockets. 
[plugin]_rpc_socket.sock | These will be multiple socket files for each plugin where these plugins will expose their actions. The bus has RPC connections to all those socket files and routes the requests to the respective plugin. 


As all the socket files are in one directory and contain `.sock` extension, so I feel it would not be difficult to maintain on sever. 

This is not an ideal structure, but remaining within current implementation without major refactoring this can't be changed. If we later move to some other implementation then we can revisit all socket files.
