### ISSUE TITLE
Application cleanup should be synchronous 

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#5202]
### Expected behavior
The `cleanup` interface should be `synchronous`, as the `process.once` handler is sync operation.

### Actual behavior
The modules and components `cleanup` interface is `async`.

### Steps to reproduce
https://github.com/LiskHQ/lisk-sdk/blob/aee6a924eae7797af909d7ef2ea955de01d692bb/framework/src/application/node/node.js#L316

### Which version(s) does this affect? (Environment, OS, etc...)
development

**Comment by shuse2** [comment]
Closing this issue since this is no longer valid
