### ISSUE TITLE
Create lisk-db package in elements

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#5241]
### Description

With the introduction of an `embedded` database system, a new elements package named `lisk-db` should be created.

### Acceptance Criteria

- Create `lisk-db` package from template
- Implement `KVStore` class exposing public interfaces
- Add unit tests

#### Interface

```
class KVStore {
	public constructor(filePath: string)

	public async get(key: string): Promise<any>

	public async put(key: string, val: Buffer): Promise<void>

	public async del(key: string): Promise<void>

	public async exists(key: string): Promise<boolean>

	public batch(): <T> # T -> {put, write, del}

	public createReadStream(options?: Options): ReadStream

	public async clear(): Promise<void>

        public async close(): Promise<void>
}
```

Related issues: #5238

**Comment by pcdinh** [comment]
What EmbeddedDB has been chosen? It is still a relational database (SQLite) or a key value store?

**Comment by ManuGowda** [comment]
> What EmbeddedDB has been chosen? It is still a relational database (SQLite) or a key value store?

We have done an initial evaluation of `LevelDB` and `RocksDB` after benchmarking and further evaluation we will choose either of the one based on this issue https://github.com/LiskHQ/lisk-sdk/issues/5261
