### ISSUE TITLE
Domain module is deprecated

### ISSUE THREAD

**Issue by LucasIsasmendi** [LiskHQ/lisk-sdk#525]
**app.js**
``` js
var d = require('domain').create();
d.run(function () {
	var modules = [];
	async.auto({....})
	...
}
```

>This module is pending deprecation. Once a replacement API has been finalized, this module will be fully deprecated. Most end users should not have cause to use this module. Users who absolutely must have the functionality that domains provide may rely on it for the time being but should expect to have to migrate to a different solution in the future.

https://nodejs.org/dist/latest-v6.x/docs/api/domain.html#domain_domain

**Comment by gnz00** [comment]
@karmacoma Noticed this as well, need any help refactoring?

**Comment by nazarhussain** [comment]
Currently the `domain` module is only used in the `app.js` on the startup. In new architecture design we are working there will be no `app.js` and we will rewrite that logic, so we will make sure not to use `domain` module in it. So I believe no need to work on this issue with current codebase. 

@MaciejBaj

**Comment by shuse2** [comment]
After removing dynamic require in lisk-sdk@2.2.0, domain module is removed
