### ISSUE TITLE
Update framework forger to store encoded data

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#5265]
### Description

- Define schema for `usedHashOnion`, `registeredHashOnionSeeds` and `forgedMap`
- Store encoded value and used decoded value

### Motivation

`lisk-codec` should be used consistently across the `lisk-sdk`

### Acceptance Criteria

- All data used in forger has schema defined
- Add integration test for those functions that uses database
- Update unit tests

### Additional Information

- `forgedMap` requires schema change from the current one since it uses dynamic key

Related issues: #5200

**Comment by pablitovicente** [comment]
Moving back to backlog as it might create too much conflicts with another ongoing PRs
