### ISSUE TITLE
Remove undo steps from everywhere

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#5274]
### Description

Remove undo steps from:

- Framework: processor / block processor / base block processor
- `lisk-chain`: undo
- `lisk-transactions`: BaseTransaction + each dependent transaction
- `lisk-dpos`: undo
- `lisk-bft`: deleteBlocks

### Motivation

Explicit undo steps are no longer required.

### Acceptance Criteria

- Remove tests for `undo` functionality

### Additional Information

Related issues: #5232

**Comment by ManuGowda** [comment]
- Remove reward field from asset for PoM transaction
