### ISSUE TITLE
Add event listers to keep track of registered forger information

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#5285]
### Description

- Expose `decodeBlock` from base plugin
- Expose fees: `NAME_FEE, MIN_FEE_PER_BYTE` through framework action
- Add listener for new block and delete block
- Decode the obtained information, and store calculated values in database on the event:
  - Votes Received [{ address, amount}]
  - Total Produced blocks
  - Total Received fees
  - Total Received rewards

### Motivation

In order to provide useful information with regard to the registered forger, the calculation of inferred values is required.

### Acceptance Criteria

- Add unit test for 
- Check if the calculated value is stored by registering to the framework

### Additional Information
- Get forging delegate information for particular node using action `getForgingStatusOfAllDelegates`

Related issues: #5215

**Comment by ManuGowda** [comment]
Missed blocks information will be captured in issue https://github.com/LiskHQ/lisk-sdk/issues/5552
