### ISSUE TITLE
buffer.readBigUint64BE is not a function

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#5305]
### Expected behavior
Transaction and Cryptography library should be able to use in the front-end application

### Actual behavior
buffer.readBigUint64BE is used to convert buffer into bigint in `lisk-cryptography:bufferToIntAsString`. 
which is used to calculate transactionId in the `lisk-transactions` and `getAddressFromPublicKey` in `lisk-cryptography`.

Currently Frontend is using https://www.npmjs.com/package/buffer, but this library does not support the new `readBigUint64BE` and `writeBigUint64BE` functions

### Steps to reproduce
Try to create transaction in the frontend

### Which version(s) does this affect? (Environment, OS, etc...)
4.0-

**Comment by shuse2** [comment]
Will be solved by https://github.com/feross/buffer/pull/247

**Comment by corbifex** [comment]
@shuse2 
> Will be solved by [feross/buffer#247](https://github.com/feross/buffer/pull/247)

Do you know any work around to make this work before the pull request is resolved? It looks like that pull request won't be resolved soon as I've seen the progress over there.

**Comment by dekadentno** [comment]
@corbifex did you manage to find a workaround? Seems like this issue is still unresolved in feross/buffer.

**Comment by shuse2** [comment]
@dekadentno
https://github.com/feross/buffer/pull/267

This issue was resolved in 6.0, and we use it here. https://github.com/LiskHQ/lisk-sdk/blob/development/elements/lisk-client/package.json#L66 
if you use `lisk-client` it shouldnt be a problem anymore
