### ISSUE TITLE
Add JSON decode and encode for the lisk-codec

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#5354]
### Description

For the JSON decode and encode,
`bytes` should be translated from/to base64 string.
`uint64/sint64` should be translated from/to number string.

interface should be same as encode, decode.

Add 
```
decodeJSON(schema: Schema, message: Buffer): JSONObject
encodeJSON(schema: Schema, message:JSONObject): Buffer
```

### Motivation

Although it will not be used in the protocol, it will be beneficial to have json decode and encode for debugging, using in HTTP plugin, or from the front end.

### Acceptance Criteria

- Test should be written using the protocol spec
- It should not be used in the framework

**Comment by pablitovicente** [comment]
Values should be mapped like:

```
CODED -> JSON
Uint64 -> string representation
Sint64 -> string representation
Int32 ->  number
Sint32 -> number
String -> string
Buffer -> Base64 string
Boolean -> boolean
```
