### ISSUE TITLE
Add extra protocol-spec and tests for lisk-codec

### ISSUE THREAD

**Issue by pablitovicente** [LiskHQ/lisk-sdk#5360]
### Description

Add more protocol-specs and tests using them to lisk-codec

### Motivation

Although we had protocol-specs for lisk-codec before implementing it we need to add more cases to make sure we cover several edge cases

### Acceptance Criteria

- Add protocol-spec/tests for objects with several nested objects
- Add protocol-spec/tests for objects with arrays with complex nested objects

**Comment by ManuGowda** [comment]
List of schema can be covered:
Blocks -> https://github.com/LiskHQ/lips/blob/master/proposals/lip-0029.md#appendix-a-block-schema-in-the-current-protocol
Accounts -> https://github.com/LiskHQ/lips/blob/master/proposals/lip-0030.md#appendix-serialization-example
Transactions -> https://github.com/LiskHQ/lips/blob/master/proposals/lip-0028.md#basetransaction-schema

**Comment by ManuGowda** [comment]
More generic:
```
{
   "order_id":"1234",
   "created_at":"2015-01-01 00:00:00",
   "customer_id":"100",
   "line_items":[                         // line item record begins
      {
         "product_id":"5008798",
         "price":"5.99",
         "quantity":"1",
         "tax_lines":[                    // tax line record begins
            {
               "price":"5.99",
               "rate":"0.06",
               "title":"State Tax"
            }
         ]                               // tax line record ends
      }
   ]                                    // line item record ends
}
```
