### ISSUE TITLE
Update the regex for application version to be flexible and just follow semantic versioning

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#5416]
### Description

The regular expression to validate the format of the application version should be flexible and match to semantic versioning. Currently, it is linked with the networks we have for `lisk-core`

### Motivation

Any application developed with Lisk SDK can follow an independent versioning scheme. Which could not be restricted to particular networks or release path we have for `lisk-core`. So on framework level, we should make it flexible to just validate any semantic versioning scheme. 

### Acceptance Criteria

- Application versioning scheme to be validated against a different set of semantic versions
- It should not be bound to release prefix we have currently  

### Additional Information

The specification or the application version can be found on https://github.com/LiskHQ/lips/blob/master/proposals/lip-0007.md#b-software-implementation-versioning

**Comment by ManuGowda** [comment]
Closing this issue as the current semver `semver.valid` validation implementation is working according to https://semver.org/
