### ISSUE TITLE
Update all regexpr to be valid and match valid data

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#5418]
### Expected behavior

All regular expressions used in `formats` the `lisk-validator` should be verified and tested properly. 

### Actual behavior

1.  Path regex has an Unescaped forward slash in this regex.
2. The path does not match forward slash at the end. e.g. `/nazar/alpha/beta/` which is quite common to use in paths

https://github.com/LiskHQ/lisk-sdk/blob/551ec555b1d9950845a004637be4255b52647173/elements/lisk-validator/src/formats.ts#L139-L142

3. Encrypted passphrase regex does not match values 
<img width="877" alt="84251684-fb769a80-ab0d-11ea-9155-a549d09f643c" src="https://user-images.githubusercontent.com/112468/84270662-5074d980-ab2b-11ea-823d-18ddb0ed5b1d.png">

https://github.com/LiskHQ/lisk-sdk/blob/551ec555b1d9950845a004637be4255b52647173/elements/lisk-validator/src/formats.ts#L151-L159

### Which version(s) does this affect? (Environment, OS, etc...)
5.0

**Comment by ManuGowda** [comment]
@nazarhussain regarding the passphrase regex.. it looks good to me
https://regexr.com/577h6
could you maybe give an example for unmatched values?

**Comment by ManuGowda** [comment]
Encrypted passphrase regex looks good
```
/^([a-zA-Z0-9]{2,15}=[a-f0-9]{1,256})(?:&([a-zA-Z0-9]{2,15}=[a-f0-9]{1,256})){0,10}$/gim.test('cipherText=abcd1234')
true
/^([a-zA-Z0-9]{2,15}=[a-f0-9]{1,256})(?:&([a-zA-Z0-9]{2,15}=[a-f0-9]{1,256})){0,10}$/gim.test('cipherText=abcd1234&iterations=10000&iv=ef012345')
true
```
