### ISSUE TITLE
Fix npm audit and deep scan issues

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#5433]
### Expected behavior

Both NPM and DeepScan feasible issues should be fixed.

### Actual behavior

Audit(NPM, DeepScan) against master branch shows errors
`NPM Audit`
```
found 981 vulnerabilities (980 low, 1 moderate) in 946 scanned packages
  run `npm audit fix` to fix 973 of them.
  8 vulnerabilities require manual review. See the full report for details.
```
`DeepScan`
https://deepscan.io/dashboard/#view=project&tid=6759&pid=8869&bid=187355&subview=issues&b=master

### Steps to reproduce
- `npm audit fix`

### Which version(s) does this affect? (Environment, OS, etc...)
master

**Comment by shuse2** [comment]
With latest master branch, audit is fixed
