### ISSUE TITLE
Redefine exposed actions from the framework

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#5440]
#### Expose actions
- getAccount: ({ address: bytes }) => bytes
- getAccounts: ({ address: bytes[] }) => bytes[]
- getLastBlock: () => bytes
- getBlockByID: ({ id: bytes }) => bytes;
- getBlocksByIDs: ({ ids: bytes[] }) => bytes[]
- getBlockByHeight: ({ height: number }) => bytes;
- getBlocksByHeightBetween: ({ from: number, to: number }) => bytes[];
- getTransactionByID: ({ id: bytes }) => bytes
- getTransactionsByIDs: ({ ids: bytes[]}) => bytes[]
- getConnectedPeers: () => bytes[]
- getDisconnectedPeers: () => bytes[]
- postTransactions: ({ transaction: bytes }) => void
- getTransactionsFromPool: () => bytes[]
- getNodeStatus: () => NodeStatus
  // This needs to be defined clearly
- getSchema: () => {
  account: {},
  baseBlockHeader: {},
  blockHeaders: { [version: number]: schema },
  baseTransaction: {},
  transactions: { [type: number}: schema },
}

where bytes are **base64 string**

#### Expose but change expected actions
- getForgerAddressesForRound: () => { addresses: bytes[], round: uint32, blocksPerRound: uint32, currentSlot: uint32 }
  // This endpoint needs update for removing calcSlotNumber and calcSlotRound
- updateForgingStatus
- getForgingStatusOfAllDelegates

Reason: Since forging is not particularly protocol, it could be moved to the forging plugin.
At that time, these functionality might be moved to the forging plugin or being updated to support.

#### Remove actions
- getApplicationState
- updateApplicationState
- sendToNetwork
- broadcastToNetwork
- requestFromNetwork
- requestFromPeer
- applyPenaltyOnPeer

Reason: Those actions were internally used when the network and chain module was the module.
However, we made them not to be module since if either of them does not work, the framework does not work. Those actions were necessary to communicate between the chain and network module, but no longer needed. Also, there is high possibility that if those actions are misused, then the node itself will be isolated by being banned.

- calculateSupply
- calculateMilestone
- calculateReward

Reason: This information can not be calculated properly anymore with the change of DPoS and BFT.
The reward will be different based on the DPoS and BFT violation and supply changes based on the burntFee, and new genesis block. If required this should be calculated in the plugin.

- calcSlotNumber
- calcSlotRound

Reason: It was used to calculate the forging time, but getForgerAddressesForRound should calculate and return calculated information.

#### Remove functions on `channel`
Remove functions on `channel` related to network actions `invokeFromNetwork`
 and `publishToNetwork` as these actions will no longer be available on `app`.

### Motivation

- Only expose the features which have valid use cases to decrease the breaking changes

### Acceptance Criteria

- Remove the actions without valid use cases
- Add functional tests for kept actions

### Additional Information
Created from #4894

**Comment by pablitovicente** [comment]
Maybe we could add versioning to reduce breaking changes as much as possible? 
Although versioning does not solve all problems related to incompatible changes it helps with the simpler cases.
