### ISSUE TITLE
Allow running node-inspector when using child processes

### ISSUE THREAD

**Issue by pablitovicente** [LiskHQ/lisk-sdk#5520]
### Description

When using child processes it's not possible to run the debugger

### Motivation

It will be useful for some developers to have the option of using the debugger to work on custom plugins

### Acceptance Criteria

It's possible to run plugins as child processes and use the Nodejs debugger

### Additional Information

This was fixed in the previous version of child process with https://github.com/LiskHQ/lisk-sdk/pull/3194/files so probably some ideas can be taken from it when fixing.

**Comment by shuse2** [comment]
https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/controller/controller.ts#L232-L240
it seems it is already implemented

**Comment by Incede** [comment]
It **is possible** to run node inspector & connect with child processes and run debugger with custom plugins.
The main process & child processes use different debugging ports.

Steps to test :

1. Start node & enable monitor plugin (child process) with flag to enable node inspector like
`NODE_DEBUG=true node --inspect ./bin/run start -n devnet --enable-monitor-plugin`

2. Observe the logs to find the UUI & ports of debugger for node (main process) & monitor plugin (child process)

Node Debugger :
`Debugger listening on ws://127.0.0.1:9229/574edc96-704c-411d-970e-17cd747a6921`

Monitor Plugin Debugger :
```
INFO lisk-framework: Event monitor:loading:finished was subscribed but not registered to the bus yet. (module=lisk:app)
Debugger listening on ws://127.0.0.1:18428/838a262b-d2f5-431f-9d51-dd1bf2e7a557
```
3. Use a inspector/debugger client to connect using the above paths.
Or use a script like :
```
const WebSocket = require('ws');
var ws = new WebSocket("ws://127.0.0.1:18428/838a262b-d2f5-431f-9d51-dd1bf2e7a557");
ws.onmessage = function(data){console.log(data);}
ws.onerror = function(data){console.log(data);}
```
4. Check the logs
