### ISSUE TITLE
Update transaction create, sign, signature functions

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#5571]
### Description
- Remove transaction specific creation functions
- Add below functions and expose from the index.ts
```
getSigningBytes: (assetSchema: object, transactionObject: Record<string, unknown>) => Buffer;
validateTransactionSchema: (assetSchema: object, transactionObject: Record<string, unknown>) => Error | undefined;
signTransaction: (assetSchema: object, transactionObject: Record<string, unknown>, networkIdentifier: Buffer, passphrase: string) => Record<string, unknown>;
signMultiSignatureTransaction: (assetSchema: object, transactionObject: Record<string, unknown>, networkIdentifier: Buffer, keys: MultisigKeys, includeSender = false) => Record<string, unknown>;
```
where `Record<string, unknown>` should be transaction in object format.

### Motivation

Creation of transaction is basically shaping the transaction object, which can be done in any format.
Therefore, specific tooling seems not required. Also, transaction specific creation functions are not generic enough to be used for custom transactions.
However, getting signing bytes, validating, signing or signing multi-signature transaction needs specific logic to do.

### Acceptance Criteria

- Update the tests for signMultiSignatureTransaction
- Create unit test for the new functions, getSigningBytes, validateTransaction, and signTransaction

**Comment by ManuGowda** [comment]
Extended test will be covered as part of this issue https://github.com/LiskHQ/lisk-sdk/issues/5593
