### ISSUE TITLE
Error: schema with key or id "/block/header"

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#5572]
### Expected behavior
There should be no schema related errors when running the app. 

### Actual behavior
If we `run` the same app twice in the sam process we get following error. 

```
 Trace: Error: schema with key or id "/block/header"
```

Currently, caching is disabled by `addUsedSchema: false,` in lisk-validator/lisk_validator.ts.
This affects also src code.

### Steps to reproduce
1. Create an app object 
2. Use `app.run` to start it 
3. Use `app.shutdown` to stop the app
4. Use `app.run` to start it again

### Which version(s) does this affect? (Environment, OS, etc...)
5.0.*

**Comment by nazarhussain** [comment]
Verified with the following script and this issue is no more valid. 

```typescript
import { Application, genesisBlockDevnet, configDevnet, utils } from 'lisk-sdk';

const app = Application.defaultApplication(
	genesisBlockDevnet,
	utils.objects.mergeDeep(configDevnet, {
		label: 'app1',
		network: { port: 5000 },
	})
);

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-expect-error
process.exit = () => {
	console.info('Process exit called...');
};

const sleep = async (time: number) =>
	new Promise((resolve) => setTimeout(resolve, time));

app
	.run()
	.then(async () => sleep(5000))
	.then(async () => app.shutdown(0, 'user shut down'))
	.then(async () => app.run())
	.catch(console.error);

```

**Comment by nazarhussain** [comment]
Its observed that the behaviour mentioned in above comment is because of following code. 

https://github.com/LiskHQ/lisk-sdk/blob/9de6a07215fa3544b1333968d26611065d8a1802/elements/lisk-validator/src/lisk_validator.ts#L36-L38

And removing this configuration is generating new error. 

```
schema with key or id "http://lisk.io/lisk-schema/schema" already exists
```

The brief is, when `addUsedSchema` is set to true, and we compile any schema which is pointing to meta schema that is cached to the instance. And in next attempt of any compiling ay other schema which is pointing to same meta schema throw above mentioned error. So we have to keep `addUsedSchema: false` for now.

We must observe the issue https://github.com/ajv-validator/ajv/issues/1221. When its released we should upgrade and try to remove `addUsedSchema` from our configuration. Till then we should keep the issue open.

**Comment by shuse2** [comment]
Closing this issue since this is no longer valid
