### ISSUE TITLE
Add transaction specific tests

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#5593]
### Description

With the introduction of issue #5571, we no longer have transaction specific util functions. These transaction specific functions will become modules eventually.

As part of the modules(token, keys, etc.) we need to cover transaction specific tests(protocol spec)

### Acceptance Criteria

- Update protocol spec related to keys module
- Add tests to cover keys scenario
  - https://github.com/LiskHQ/lisk-sdk/blob/64ec200080be3eef576046fe1586cd07d942ecff/elements/lisk-transactions/test/sign_multi_signature_transaction.spec.ts
  - https://github.com/LiskHQ/lisk-sdk/blob/64ec200080be3eef576046fe1586cd07d942ecff/elements/lisk-transactions/test/register_multisignature_account.spec.ts

### Additional Information
Refer PR https://github.com/LiskHQ/lisk-sdk/pull/5591 to get more details about removed tests

**Comment by shuse2** [comment]
This issue should be addressed in #5607

**Comment by shuse2** [comment]
This util function is tested in #5591 and the missing test is addressed in #5607
