### ISSUE TITLE
Fork / rollback events

### ISSUE THREAD

**Issue by JesusTheHun** [LiskHQ/lisk-sdk#5617]
### Description

Lisk SDK should emit an event upon transaction rollback, chain swap or anything related to chain lifecycle.

### Motivation

Since consumer level integration will be executed outside the blockchain itself, one need to be aware if some blocks & transactions have been rolled back so they can act accordingly.

**Comment by shuse2** [comment]
@JesusTheHun Thanks for creating the issue.
With v5, there is an event that you can listen to using action/events.
https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/application/application.ts#L362-L485

Specifically, on fork and block creation and deletion, it will have `app:chain:fork`, `app:block:new` and `app:block:delete`.
It will be documented properly when releasing SDK v5
