### ISSUE TITLE
HTTP server can not handle block and transaction id with front slash

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#5679]
### Expected behavior
Support `blocks` and `transactions` endpoint with id having `/` slash

### Actual behavior
- A transaction can have id with `/` slash as part of the id `jl4VaKMHEbqm/sRNu5yrnnpCda1pkO8Sp8MWoNhgiX4=`
- A block can have id with `/` slash as part of the id `jl4VaKMHEbqm/sRNu5yrnnpCda1pkO8Sp8MWoNhgiX4=`

### Steps to reproduce
- Create a transaction which can result in `/` slash
ex:
```
./bin/run transaction:create 46YmxX4GvkJp2587xWhkRRlMOEfvOS85Hn1itZFdsRU= 100000000 8 2 0 --asset='{"amount":100,"recipientAddress":"0EaZ5XxKOEbJiPPBUwZ5b46uXBw=","data":"send token"}' --passphrase='peanut hundred pen hawk invite exclude brain chunk gadget wait wrong ready'
```
### Which version(s) does this affect? (Environment, OS, etc...)
5.0.0

**Comment by shuse2** [comment]
Fixed with #5390
