### ISSUE TITLE
Endpoint /api/blocks returns invalid error message

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#5684]
### Expected behavior
```
{"errors":[{"message":"Block with height '10' was not found"}]}
```
### Actual behavior
http://127.0.0.1:4000/api/blocks?height=10
```
{"errors":[{"message":"Specified key blocks:height:\u0000\u0000\u0000\n does not exist"}]}
```
### Steps to reproduce
- Start a node with http api enabled
- Query endpoint `http://127.0.0.1:4000/api/blocks?height=10` before chain is grown beyond height 10

### Which version(s) does this affect? (Environment, OS, etc...)
5.0

**Comment by mitsuaki-u** [comment]
Queried endpoint and got correct result `"Block with height '1000' was not found"`. Closing issue.
