### ISSUE TITLE
HTTP Plugin validation rejects valid transaction

### ISSUE THREAD

**Issue by pablitovicente** [LiskHQ/lisk-sdk#5713]
### Expected behavior

When sending a transaction originating from a multi-signature account if a signature is empty string (i.e. one of the optional keys does not need to sign) the transaction should be accepted.

### Actual behavior

When sending a transaction originating from a multi-signature account if a signature is empty string (i.e. one of the optional keys does not need to sign) the transaction is rejected with: 

```
{"errors":[{"message":"Lisk validator found 1 error[s]:\nProperty '.signatures[3]' should match format \"base64\""}]}
```

Probably `isBase64String` needs to handle this case

### Steps to reproduce

Send a transaction from a multi-signature account configured with 2 mandatory, 2 optional and 3 signatures required thru HTTP API

### Which version(s) does this affect? (Environment, OS, etc...)

5.0

**Comment by pablitovicente** [comment]
Probably fixed with https://github.com/LiskHQ/lisk-sdk/pull/5711

**Comment by shuse2** [comment]
I think the problem is the schema which validates the request body specifies that signatures must be array of `base64` (after #5711, `hex`). However, here it should allow empty string also

**Comment by pablitovicente** [comment]
> I think the problem is the schema which validates the request body specifies that signatures must be array of `base64` (after #5711, `hex`). However, here it should allow empty string also

yes
