### ISSUE TITLE
PoM transaction for delegate with balance lower than block reward is not accepted

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#5758]
### Expected behavior

As per the specification mentioned on LIP https://github.com/LiskHQ/lips/blob/335a9ee963f65884e2ed4d44aa8ddb2dca823488/proposals/lip-0024.md#reward-of-pom

```
let A be the account of the misbehaving delegate

reward = min { A.balance , regular block reward }

reward is added to the balance of the sender of the PoM
reward is subtracted from A.balance
```

If delegate balance is lower than the block reward, it should transfer full remaining balance to the PoM sender. 

### Actual behavior

Due to contradicting requirement in `token` module any account must satisfy a minimum balance requirement. So any of such PoM transactions transferring full balance is rejected with following error. 

```
{
      errors: [ { message: 'Remaining balance must be greater than 5000000' } ]
}
```

### Steps to reproduce

1. Transfer 100LSK to a genesis delegate account
2. Check the last block reward which would e.g. 5LSK 
3. Transfer all amount in delegate account to some random account and keep only 4.5LSK in delegate account
3. Create a contradicting block for that genesis account
4. Send PoM Transaction for those contradicting blocks 

### Which version(s) does this affect? (Environment, OS, etc...)
5.0.0

**Comment by shuse2** [comment]
maybe we can add `getMinBalanceRequried` method to reducer in token module
