### ISSUE TITLE
Missing peer banning for a few scenarios

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#5761]
### Expected behavior

- `postNodeInfo` with >4 send a status message in a 10 s time window - `Should apply penalty of 10. The number of postNodeInfo messages by an honest peer in a 10 s time window is throttled at 3.`

- `getNodeInfo` with More than one node header message for one connection - `Should apply penalty of 10. There should only be one getNodeInfo message when the connection is established.`

- `getPeers` with More than one message after establishing a connection - Should apply penalty of 10. Honest peers should send a getPeers message only once directly after establishing a connection.

### Actual behavior

Missing banning in the above cases

### Steps to reproduce

Request `getPeers` 2 times after connecting or post nodeInfo 4 times in 10 seconds

### Which version(s) does this affect? (Environment, OS, etc...)

`5.0`

**Comment by mitsuaki-u** [comment]
This issue is more related to applying the penalty rather than the banning mechanism itself
