### ISSUE TITLE
rpc-secret protected API

### ISSUE THREAD

**Issue by wyh136** [LiskHQ/lisk-sdk#579]
can i visit the api with a rpc-secret not just white list the ip? because i can not watch my nodes through random ip.

**Comment by 4miners** [comment]
@wyh136 Do you mean protect forging enable/disable endpoint using password instead of IP whitelisting?

**Comment by Isabello** [comment]
They mean more than that. RPC secret would let the user access the node from any ip without any need for whitelisting.

setting another secret for the forging endpoint would be a good option as well.

**Comment by karek314** [comment]
I think one private key should be enough as only node operator will be able to access it.

This would be convenient to see it like:
Option in config to disable or enable whitelisting ip and disable or enable signing request to lisk node.
When signing will be enabled then all requests will require additional header like **"SIGNATURE"**, which should contain for instance result of **sha256_hmac(request_body,secret_key_set_in_lisk_config)**

**Comment by wyh136** [comment]
signing request is not necessary，i just want to use the API from random IP, the white list is hard to use in this case.

**Comment by shuse2** [comment]
Closing because this issue is no longer valid with the current architecture
