### ISSUE TITLE
Update updateForgerStatus to be more safe

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#5839]
### Description

Update application actions
* getForgingStatus to return corresponding forger info
```
{
	height: number;
	maxHeightPrevoted: number;
	maxHeightPreviouslyForged: number;
}
```
* updateForgingStatus to include properties `overwrite` as optional and `maxHeightPreviouslyForged` and `maxHeightPrevoted`, `height` as required
  - when overwrite is false and maxHeightPreviouslyForged, maxHeightPrevoted, height does not match, it should fail to enable forging
  - when overwrite is false and maxHeightPreviouslyForged, maxHeightPrevoted, height does match, it should enable forging
  - when overwrite is true, it should overwrite the maxHeightPreviouslyForged and maxHeightPrevoted, height to the input value and enable forging
* Update forging plugin to accept `maxHeightPreviouslyForged`, `maxHeightPrevoted`, `height` and `overwrite` parameters

#### Note
Only enable forging if the node is synced up to the tip of the chain where the provided forger info matches below condition. 

`(forgingInfo.heightPrevoted < B.heightPrevoted ) || ( forgingInfo.heightPrevoted == B.heightPrevoted && forgingInfo.height < B.height)`

where `B` is the block currently at the tip of the chain of the node.

### Motivation

Currently when enabling forging, it is enabling without any check on the forger info.
However, this can lead to misbehavior of BFT protocol.

https://github.com/LiskHQ/lips/blob/master/proposals/lip-0014.md#migrating-to-a-new-forging-node-with-data

### Acceptance Criteria

- Add unit test and functional test
  - when overwrite false and not matched maxHeightPreviouslyForged, maxHeightPrevoted, height
  - when overwrite false and matched maxHeightPreviouslyForged, maxHeightPrevoted, height
  - when overwrite false and data does not exist
  - when overwrite true

### Additional Info
- Update core command to support this change

**Comment by janhack** [comment]
The general approach looks good and should prevent node operators easily activating forging by mistake with the incorrect forger info. One question: How and when is the forger info initialized? We could only initialize it once someone calls `updateForgingStatus` with `force==true` and the chosen `maxHeightPreviouslyForged`. Cosmetic comment: We could rename `force` to `overwrite`, which would be more explicit.

**Comment by janhack** [comment]
Maybe we could still precisely say what synced up means, i.e., the `forgingInfo` provided for the delegate satisfies
```
(forgingInfo.heightPrevoted < B.heightPrevoted ) || ( forgingInfo.heightPrevoted == B.heightPrevoted && forgingInfo.height < B.height),
```
where `B` is the block currently at the tip of the chain of the node. So only if the above condition is satisfied, forging is activated.
