### ISSUE TITLE
Client PONG timeout disconnects node 

### ISSUE THREAD

**Issue by mitsuaki-u** [LiskHQ/lisk-sdk#5855]
### Expected behavior

Given a non-lisk node utilizing `lisk-p2p` which connects to a lisk-node and sends requests, penalty should be applied when necessary. 

### Actual behavior

Before the penalty, p2p node is disconnected due to a PONG timeout under certain specific circumstances. 

### Steps to reproduce

Request for script. 

### Which version(s) does this affect? (Environment, OS, etc...)
5.0

**Comment by shuse2** [comment]
Superseded by https://github.com/LiskHQ/lisk-sdk/issues/5761
