### ISSUE TITLE
Add functionality to find conflicting block for new blocks in PoM plugin

### ISSUE THREAD

**Issue by mitsuaki-u** [LiskHQ/lisk-sdk#5878]
### Description

For every new block detected in the PoM Plugin:

1. Check if it already exists in db.
2. Create pure function to find conflicting blockheaders from BFT 
3. Decode the blockheader returned from event and get the generatorPublicKey.
4. Search the last 260,000 blockheaders generated by this generatorPublicKey on all chains, forks included for the conflicting blockheader.

### Motivation

In order to submit a PoM transaction, the conflicting blockheaders `b1` and `b2` must be located. 

### Acceptance Criteria

- Plugin must detect conflicting blockheaders stored 
- Write relevant tests

**Comment by shuse2** [comment]
Extracted the refactoring of the BFT function to https://github.com/LiskHQ/lisk-sdk/issues/5894
