### ISSUE TITLE
Complete alpha testing for SDK 5.0

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-sdk#5957]
The goal of this epic is to complete alpha testing for SDK 5.1 which includes adding missed test cases, fixing bugs and refactor the code for improvement.

#### Sprint 32 (Round 1)

- Remove peers HTTP API functional test #5958 
- Wrong logic for nonce validation on transaction.create #5983
-  Add functional test for actions and events using APIClient #5979

#### Sprint 33 (Round 1 & 2)

- When action fails it doesn't return the actual error #5996
- Lisk Commander cannot find module 'globby' #5995
- Report misbehavior fails when delegate has zero balance #6027
- Unformatted JSON-RPC request crashes the application #6026
- Update lisk-sdk README #6032
- Lisk Commander build contains npm-shrinkwrap with dev dependencies #6030
- Update sodium native and buffer packages #6024
- APIClient event is outdated and type in incorrect #6021
- Update default nodejs version to 12.20.0 #6018 
- when using `app:network:event`, the content must be validated #6019 
- Update action and event handler to simplify the interface #6012
- Update forger plugin to use action and events  #5943
- Fix inconsistency in base32 address function #6014
- Update lisk-transaction readme #5997
- Framework readme has non-existing event information #5999
- lisk-api-client does not resolve asset name #6006 
- Timeout for action "monitor:getForkStats" in API Client when node is syncing #5986 
- Remove `ipc` property from config #5965
- Fix codec to be able to decode/encode empty object #6000
- Framework IPC channel action invoke missing check in error handling #6002
- Remove deprecated data access function #5946

**Comment by pcdinh** [comment]
I think that the title should be read as Complete alpha testing for SDK 5.0
