### ISSUE TITLE
delegates/forgers endpoint returns same Slot's for all next forgers

### ISSUE THREAD

**Issue by Korben3** [LiskHQ/lisk-sdk#5980]
### Expected behavior

Return incremented slots for each next forger.

### Actual behavior

Returns same slot for each next forger.

### Steps to reproduce

See: https://betanet.lisk.io/api/delegates/forgers?limit=4&offset=0

Returns:
`{"meta":{"lastBlock":32377,"lastBlockSlot":14132436,"currentSlot":14132436,"limit":4,"offset":0},"data":[{"username":"genesis_3","address":"8206462713258972713L","publicKey":"eebd615e51dfdaa9c244c298a79d5266320bd73b2f56e9117ddb4a165d68d850","nextSlot":14132436},{"username":"genesis_43","address":"703493689357525100L","publicKey":"88570b8a527dc2e6c55bfe8416e70d7053b7fbb131a8a53dd1a69a903226a54f","nextSlot":14132436},{"username":"genesis_100","address":"3511736717200493064L","publicKey":"b1b906be18107a0b502c2547ed430009f90594d45ae420cae800125a1a81bd26","nextSlot":14132436},{"username":"genesis_101","address":"17463235734272719462L","publicKey":"f825dffff62a51eb22cda368172ed5aafd4a6e272ec361173b33c3e1c118d558","nextSlot":14132436}],"links":{}}`

All with the same slot 14132436. Expected return is something like:

`{"meta":{"lastBlock":32377,"lastBlockSlot":14132436,"currentSlot":14132436,"limit":4,"offset":0},"data":[{"username":"genesis_3","address":"8206462713258972713L","publicKey":"eebd615e51dfdaa9c244c298a79d5266320bd73b2f56e9117ddb4a165d68d850","nextSlot":14132436},{"username":"genesis_43","address":"703493689357525100L","publicKey":"88570b8a527dc2e6c55bfe8416e70d7053b7fbb131a8a53dd1a69a903226a54f","nextSlot":14132437},{"username":"genesis_100","address":"3511736717200493064L","publicKey":"b1b906be18107a0b502c2547ed430009f90594d45ae420cae800125a1a81bd26","nextSlot":14132438},{"username":"genesis_101","address":"17463235734272719462L","publicKey":"f825dffff62a51eb22cda368172ed5aafd4a6e272ec361173b33c3e1c118d558","nextSlot":14132439}],"links":{}}`

As is the case here: https://node01.lisk.io/api/delegates/forgers?limit=3&offset=0

**Comment by ManuGowda** [comment]
This issue has been addressed in Lisk Core v3.0.0-beta.2, Lisk SDK 5.0.0 release https://betanet5.lisk.io/api/forgers
