### ISSUE TITLE
Update readme for lisk-client to include instructions for build tools

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#5994]
### Description

Lisk Client is supposed to be used with front-end tools and projects. Modern frontend projects use some kind of build tools. `lisk-client` should work out-of-box for all such build tools or we should provide steps and instructions how to use those. 

### Motivation

The documentation published in Readme format should be good enough for any SDK developer to use `lisk-client` in any frontend project. 

### Acceptance Criteria

- Readme must gave instructions to work with `Webpack >= 5` 

### Additional Information

A working example can be found here for reference 

https://github.com/nazarhussain/lisk-client-webpack-5

**Comment by shuse2** [comment]
With #6049, there is no specific setting required.
