### ISSUE TITLE
Use api-client in framework plugins

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#6016]
### Expected behavior

There should be a standard tool or way to interact with functional tests in plugin.

Consistently use lisk-api-client in the source code and for tests plugin's functional tests.

### Actual behavior

We are using `_channel` property on application directly in tests in plugins or sometimes we use api-client

### Which version(s) does this affect? (Environment, OS, etc...)

`5.0.1`

**Comment by shuse2** [comment]
Superseded by #6612
