### ISSUE TITLE
No limit to dpos_getAllDelegates endpoint

### ISSUE THREAD

**Issue by ghost** [LiskHQ/lisk-sdk#6053]
### Expected behavior

Receiving an error or result limited tot 101 or 103 delegates when setting the limit to a large number.

### Actual behavior

Endpoint seems to retrieve all registered delegates.

### Steps to reproduce

See: https://betanet5.lisk.io/api/delegates?limit=999

This retrieves a total of 127 delegates.

**Comment by shuse2** [comment]
Updating the issue title to reference `dpos_getAllDelegates` because in v6 this endpoint is under dpos

**Comment by shuse2** [comment]
Closing this issue since this is no longer valid
