### ISSUE TITLE
Add createTransaction in lisk-framework

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#6123]
### Description

- Add createTransaction to generate transaction based on a asset definition
```
const tx = createTransaction({ 
  moduleID: number,
  assetClass: Asset,
  asset: {},
  networkIdentifier: Buffer,
  passphrase?: string,
  nonce?: bigint,
  fee?: bigint,
});
```

### Motivation

When testing block processing or hooks, it requires a transaction. Therefore, there should be an easy way to generate any custom transaction for testing

### Acceptance Criteria

- Transaction should be statically valid if passphrase is provided
- If passphrase does not exist, it should not sign the transaction
- Multi-signature should not be considered (since it's module)

**Comment by mitsuaki-u** [comment]
Closing the issue due to already existing functionalities within the `lisk-transaction` library. To avoid duplicated functionality we will simply use the existing ones. Furthermore, the test writer can easily create transaction fixtures for unit tests with `commander`.
