### ISSUE TITLE
Add fundTokens action in faucet plugin

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#6138]
### Description

- Add fundTokens action in the faucet plugin
- Input should be
```
{
  address: 'binary address in hex format',
}
```
- Action should create a transaction using registered passphrase and send it to the running application

### Acceptance Criteria

- Add test to check if the getToken action create and send the token transfer transaction
- Add test to check if error is returned when input is invalid
- Add test to check if error is returned when passphrase is not set

**Comment by djiworks** [comment]
Hi, I've tried your faucet:fundTokens from Dashboard actions as shown in image using a new generated hex address <img width="628" alt="Capture d’écran 2022-02-14 à 20 07 56" src="https://user-images.githubusercontent.com/4953757/153900952-b89957e4-eb95-4f0b-b907-770a902d52d5.png">

But I always get error : "Captcha response was invalid." However doing the faucet action from Faucet UI on 4004 port, everything are ok.

**Comment by djiworks** [comment]
Yes I did it also. Anyway, thank you for your time.
