### ISSUE TITLE
Enable forging for multiple accounts with given file

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#6163]
### Description

During bootstrapping we generate a file `forging_info.json` which contains list of all delegates in `accounts.json` with their encrypted passphrases and hash onions. User can copy that file and put in the `config.json` under `forging.delegates`. 

We need to create new command `forging:enable:all` or update teh `forging:enable` command to accept `accounts.json` and enable forging on all delegate accounts. 

### Motivation

After copying the `forging_info.json` there is no intuitive way for user to enable forging for all accounts. Which is quite common use case for development environment. 

User should be able to see the blocks forging after one command, if he enables one or two accounts manually there will be a lot missed blocks and during that time application logs don't show anything. And user will be confused is app is working or not. 

### Acceptance Criteria

- Existing `forging:enable` with existing arguments and options should not have any change 
- The same behaviour should be reflected on `forging:disable` 

### Additional Information
5.0.x

**Comment by shuse2** [comment]
Closing this issue since this is no longer valid
