### ISSUE TITLE
Resolve DPoS module dependency for running application instance

### ISSUE THREAD

**Issue by Incede** [LiskHQ/lisk-sdk#6198]
### Description

* The `getApplicationEnv` function in `framework/testing/app_env.ts` accepts empty array of module class as input
* But with on-chain architecture minimum 1 initial delegate is required in genesis block & hence `DPoS` module needs to be registered to run an application instance
* To comply with this requirement the `DPoS` module is added artificially to `modules: ModuleClass[]` input parameter if it's not provided by the user input.

### Motivation
* `createGenesisBlock` in `testing` utility in framework currently allows to create `genesis-block` without any registered modules
* It should ideally be possible to use this `genesis-block` to run an application instance without further changes
* Currently, the `genesis-block` created without any `modules` or `intiDelegates` cannot be used to run an application instance.

### Acceptance Criteria
* There shouldn't be any artificial addition to input parameters to `getApplicationEnv` function in `framework/testing/app_env.ts`
* All functions in `testing` utility in framework should have similar input parameter requirement (empty modules)
* It should be possible to use `genesis-block` created by `createGenesisBlock` in `testing` utility in framework to run an application instance without further changes

### Additional Information
* It should be clear for the end-user (developer) from the application design if (some or all) of the default modules are necessary or optional for the application to work. 
* Distinction should be made whether to use `defaultApplication` or `new Application()` to create application instance in testing utility in framework.

**Comment by shuse2** [comment]
This issue is superseded by https://github.com/LiskHQ/lisk-sdk/issues/6211
