### ISSUE TITLE
[Commander] lisk-core blockchain:download points to wrong url

### ISSUE THREAD

**Issue by JesusTheHun** [LiskHQ/lisk-sdk#6208]
### Issue

```bash
$ lisk-core blockchain:download --network betanet
Downloading snapshot from https://downloads.lisk.io/lisk/betanet/blockchain.db.tar.gz
    Error: Request failed with status code 404
```
Apparently you changed the compression format, the correct url is `https://downloads.lisk.io/lisk/betanet/blockchain.db.gz`

### Which version(s) does this affect? (Environment, OS, etc...)

`lisk-core@3.0.0-beta.4`

**Comment by JesusTheHun** [comment]
Also importing the new archive leads to 

> Error: TAR_BAD_ARCHIVE: Unrecognized archive format
Code: TAR_BAD_ARCHIVE

**Comment by shuse2** [comment]
yes currently on the path, betanet v4 data is stored. and in the v5, database format is changed.
Once we move to the betanet v5 or testnet, it should work =)

**Comment by shuse2** [comment]
Related to https://github.com/LiskHQ/lisk-core/issues/481, we will update the URL to snapshot
