### ISSUE TITLE
Chain state iterator

### ISSUE THREAD

**Issue by JesusTheHun** [LiskHQ/lisk-sdk#6280]
### Description

Let's say you store data in the chain state with this key pattern : `foo:bar:<000000>-<999999>`. 
Example of keys : `foo:bar:000042-7777777`, `foo:bar:483950-873950`.
Not all keys in the range exist, only some.

Now what if you want to find all keys that exist, or all keys between `foo:bar:000000` and `foo:bar:100000` ?
Right now you can't. That's the purpose of the rocksdb iterator.

### Motivation

The only workaround to this problem is to store all existing key in a dedicated tuple. Then when you need it you fetch the tuple and filter it in JS. This is trivial at the beginning but as the dataset grows, the RAM used, the CPU consumption and the computation time will grow massively and become unpractical. 
On the other hand the iterator find the keys for you, load the data bit by bit, allowing you to reduce the data without high loads.

### Acceptance Criteria

- [ ] Key discovery with search criteria
- [ ] Data is loaded one tuple at a time

**Comment by shuse2** [comment]
Superseded by #6564
