### ISSUE TITLE
Scaffolding

### ISSUE THREAD

**Issue by JesusTheHun** [LiskHQ/lisk-sdk#6299]
### Description

```bash
lisk new sidechain --type typescript my-project
```
Should generate a base structure that can be started immediately, especially now we use embedded db.

### Motivation

Being able to get started in matters of second is a really good selling point for dev. It helps them try your product and get a good first opinion.

### Acceptance Criteria

* [ ] A sidechain is generated and can be started immediately with `npm start`
* [ ] A default module is generated with an example schema and asset
* [ ] A default plugin is generated 
* [ ] Basic module & asset tests are generated

### Additional Information

This kind of scaffolding makes developer adoption skyrocket.

**Comment by shuse2** [comment]
@JesusTheHun thanks for the issue. We have implemented this feature in the https://github.com/LiskHQ/lisk-sdk/issues/6066 which will be released in SDK 5.1 as a feature of lisk-commander.
Looking forward to your feedback on this feature once release
