### ISSUE TITLE
 Invalid application URL resolution outside development environment

### ISSUE THREAD

**Issue by mehmetegemen** [LiskHQ/lisk-sdk#6362]
### Expected behavior
Fetch to `/api/config` and access to `applicationUrl` within the `getApplicationUrl()` function in dashboard plugin utils should always return a definite value
### Actual behavior
Fetch to `/api/config` and access to `applicationUrl` within the `getApplicationUrl()` function in dashboard plugin utils doesn't return a definite value all the time due to a missing `await` of the fetch call.
### Steps to reproduce
Running dashboard plugin outside of development environment

### Which version(s) does this affect? (Environment, OS, etc...)
development

**Comment by shuse2** [comment]
Superseded by #6368
