### ISSUE TITLE
Rename BasePlugin.default to BasePlugin.options

### ISSUE THREAD

**Issue by JesusTheHun** [LiskHQ/lisk-sdk#6363]
### Description

`BasePlugin.default` hold the configuration schema of the plugin and default values of said configuration.
It should be renamed `BasePlugin.options`.

### Motivation

The name `default` is misleading, it does not say what it is the default of and it's not only the default values but also the schema of the options.
`BasePlugin.options` is a lot clearer on what it is about. A good TS type along with a good name will give a clear view of what is expected to be set here.

### Acceptance Criteria

* [ ] `BasePlugin.defaults` is renamed `BasePlugin.options`

**Comment by shuse2** [comment]
Superseded by #6623
