### ISSUE TITLE
Send transaction widget resolves passphrase input as string incorrectly

### ISSUE THREAD

**Issue by Incede** [LiskHQ/lisk-sdk#6388]
### Expected behavior
*A user will be accustomed to use strings in dashboard UI since most of the input fields are JSON.
So, for the passphrase field, either we should explicitly indicate to pass mnemonic as space separated words without double quotes or fail on string input. Otherwise if the user uses the correct passphrase with double quotes, with the current error message he couldn’t identify what went wrong

### Actual behavior
* Passphrase as mnemonic input resolves to correct address & tx. succeeds
* Same passphrase as string input (with double quotes) resolves to incorrect address & tx. fails

### Steps to reproduce
* Use `endless focus guilt bronze hold economy bulk parent soon tower cement venue` as input in passphrase field
* Use `"endless focus guilt bronze hold economy bulk parent soon tower cement venue"` as input in passphrase field

### Which version(s) does this affect? (Environment, OS, etc...)
development

**Comment by shuse2** [comment]
Closing this issue since this is no longer valid
