### ISSUE TITLE
Unnecessary options override in framework plugins 

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#6399]
### Expected behavior

The plugins options defined per config schema exported from `defaults` getter should be override from the framework only in `BasePlugin`. In the actual plugins we can safely use `this.options` 

https://github.com/LiskHQ/lisk-sdk/blob/91137f530cb31bef2aa30c7df47e22a865931dad/framework/src/plugins/base_plugin.ts#L209-L222

### Actual behavior

Plugins are repeating this logic in their implementation which is not necessary. 

https://github.com/LiskHQ/lisk-sdk/blob/91137f530cb31bef2aa30c7df47e22a865931dad/framework-plugins/lisk-framework-dashboard-plugin/src/plugin/dashboard_plugin.ts#L66-L70

https://github.com/LiskHQ/lisk-sdk/blob/91137f530cb31bef2aa30c7df47e22a865931dad/framework-plugins/lisk-framework-faucet-plugin/src/plugin/faucet_plugin.ts#L183-L187

In above cases we should declare plugin like this. 

```js
import {PluginOptionsWithAppConfig} from 'lisk-sdk';

interface DashboardPluginOptions extends PluginOptionsWithAppConfig {
	applicationUrl: string;
	port: number;
	host: string;
}

export class DashboardPlugin extends BasePlugin<PluginOptions> {

```

And later inside plugins its safe to access `this.options`. 

### Which version(s) does this affect? (Environment, OS, etc...)

development

**Comment by shuse2** [comment]
Superseded by #6612
