### ISSUE TITLE
Application running with `--api-ws` still enable the IPC

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#6400]
### Expected behavior

The `IPC` communication should be enabled only when `--api-ipc` flag is provided to the application. 

### Actual behavior

If we start an application with `--api-ws` only it still enables the IPC communication and all the commands e.g. `block:get` works as expected. 

### Steps to reproduce

```
lisk init /my/app
cd /my/app
./bin/run start --api-ws

# In other terminal 
./bin/run block:get 1
```

### Which version(s) does this affect? (Environment, OS, etc...)
development

**Comment by nazarhussain** [comment]
Starting app with options like throw error. 

```
> ./bin/run start --api-ws --api-ipc
 ›   Error: --api-ws= cannot also be provided when using --api-ipc=
```

Why `--api-ws` and `--api-ipc` to be exclusive to each other. Application can run both Websocket API and IPC. Which is a common use case, no matter onerunning websocket or not, he should be able to run command like `block:get` directly on the node.

**Comment by shuse2** [comment]
This change requires the change in config, and it will be breaking change

**Comment by ishantiw** [comment]
This will be tackled in the issue #6554

**Comment by shuse2** [comment]
superseded by #6612
