### ISSUE TITLE
What address version should be used for WIFs?

### ISSUE THREAD

**Issue by faustbrian** [LiskHQ/lisk-sdk#6499]
I'm trying to derive a WIF for LSK private keys with https://github.com/bitcoinjs/wif but I couldn't find a WIF address version anywhere for LSK. Do you guys already have a WIF version that you use which isn't documented or would I have to make up one myself?

**Comment by shuse2** [comment]
We dont exactly have WIF, but we use address format defined in https://github.com/LiskHQ/lips/blob/master/proposals/lip-0018.md.
And it's implemented at https://github.com/LiskHQ/lisk-sdk/blob/development/elements/lisk-cryptography/src/keys.ts
