### ISSUE TITLE
Invalid prevote calculation

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#6594]
### Expected behavior
`maxHeightPrevoted` should always equal or greater than the current last block `maxHeightPrevoted` as described in [LIP-0014](https://github.com/LiskHQ/lips/blob/master/proposals/lip-0014.md#computing-prevotes-and-precommits) with `computeChainMaxHeightPrevoted`.

### Actual behavior
When there are not enough `prevote` for more than 5 rounds (we keep the prevote record for last 5 rounds), the `maxHeightPrevoted`will be initialized to the `finalizedHeight`.
This is possible to make the `maxHeightPrevoted` lower than the current `maxHeightPrevoted` and also possible to introduce non-deterministic behavior because `finalizedHeight` might be different on each nodes.

### Steps to reproduce
Have a chain which has not enough prevote for more than 5 rounds, and try to forge a block.

### Which version(s) does this affect? (Environment, OS, etc...)
5.1.3

**Comment by ManuGowda** [comment]
```
The problem revealed itself when less than 68 delegates were active on Testnet. This means that new blocks cannot obtain at least 68 prevotes and the maxHeightPrevoted value does not further increase. The computation of the value of maxHeightPrevoted only takes into account the 309 most recent blocks. As in this specific scenario none of these blocks had at least 68 prevotes, the implementation was incorrectly using the finalized height, where instead it should be using the maxHeightPrevoted property of the most recent block. This issue led to delegates producing blocks that violated the Lisk-BFT protocol. These blocks were reported using the report delegate mishbehavior transaction and the respective delegates were banned.
```
