### ISSUE TITLE
Discover & optimize low performance operations for sparse Merkle Tree

### ISSUE THREAD

**Issue by Incede** [LiskHQ/lisk-sdk#6597]
### Description

* Discover & replace low performance operations like `array.map` `array.shift` with faster alternatives.
* Optimize this logic
```
				for (const i of siblingHashes) {
					if (i.equals(nodeHash)) {
						isPresentInSiblingHashes = true;
						break;
					}
				}
				for (const i of ancestorHashes) {
					if (i.equals(nodeHash)) {
						isPresentInAncestorHashes = true;
						break;
					}
				}
				if (!isPresentInSiblingHashes && !isPresentInAncestorHashes) {
					// TODO : optimize this
					siblingHashes.push(nodeHash);
				}
```

* Try to discover excessive db calls which can be avoided and optimize them
### Motivation
Tests for sparse Merkle tree take unexpected long times to finish

### Additional Information
PR #6584

**Comment by shuse2** [comment]
Closing this issue since this is no longer valid
