### ISSUE TITLE
Update Lisk SDK README with deep clean build command

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#6626]
### Description

Add deep clean and build command to lisk-sdk README, so that developers and community members can use the deep clean build to resolve build issue when required.

### Motivation

At times working with different branches are version we encounter issue with building lisk-sdk.

### Additional Information

`yarn clean:node_modules && rm -rf node_modules && yarn && yarn build`

**Comment by shuse2** [comment]
Maybe it's better to add it as a npm script?
