### ISSUE TITLE
Benchmark application rpc endpoints

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#6642]
### Description

Application endpoints should be benchmarked and all the endpoints should respond within a standard timeframe (100-500ms, we can also define the timings).

### Motivation

- Lisk Service receives lot of timeout errors of certain actions and endpoints on Lisk Core.
- This intern has impact on Lisk Service for 
   - Indexing
   - Timeouts at Lisk Desktop which leads to bad user experience.
- Also some of the exchanges and third party applications are using Lisk Core/Lisk Service, these timeouts can be a bottleneck for the users.

### Additional Information

- While benchmarking make sure we consider inter-process, intra-process, docker environments into consideration, as Lisk Service runs in docker container and Lisk Core might be running in a docker container or on a host machine
- Consider possibility to configure timeouts, so that one could increase when required
- Endpoints (we also have other actions in modules, take them into consideration too) : https://github.com/LiskHQ/lisk-sdk/blob/c9c94a4fc0faaf72193d9689df946b6a87511887/framework/src/application.ts#L399-L476

**Comment by sameersubudhi** [comment]
The endpoints most frequently resulting in timeouts at Lisk Service ​are:

- `legacyAccount:getUnregisteredAccount` (On concurrent requests)
- `app:getAccounts` (On concurrent requests)
- `app:getAccount` (On concurrent requests)
- `app:getLastBlock` (Occasionally)
- `app:getForgers` (Occasionally)
- `app:getTransactionsFromPool` (Occasionally)
- `app:getTransactionsByIDs` (On concurrent requests)
- `app:getNodeInfo` (Mostly likely when Core is under pressure and others are timing out)

**Comment by shuse2** [comment]
Closing this issue since this is no longer valid
