### ISSUE TITLE
posibility of a 0.6.1 release for @liskhq/lisk-validator with updated validator

### ISSUE THREAD

**Issue by evansrobert** [LiskHQ/lisk-sdk#6649]
Hi, @shuse2 @nazarhussain, there are several vulnerabilities introduced by package **validator@13.5.2**:
### Issue Description

   I noticed that four vulnerabilities are introduced in **_@liskhq/lisk-validator@0.6.0_**:
 Vulnerability [SNYK-JS-VALIDATOR-1090600](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090600), [SNYK-JS-VALIDATOR-1090599](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090599), [SNYK-JS-VALIDATOR-1090601](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090601) and [SNYK-JS-VALIDATOR-1090602](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090602) affect package **_validator_** (versions:<13.6.0). 
   The above vulnerable package is referenced by **_@liskhq/lisk-validator@0.6.0_** via:
`@liskhq/lisk-validator@0.6.0 ➔ validator@13.5.2`

Since **_@liskhq/lisk-validator@0.6.0_** ([2,049 downloads per week](https://www.npmjs.com/package/@liskhq/lisk-validator/v/0.6.0?activeTab=versions)) is referenced by **116** downstream projects (e.g., [@liskhq/lisk-transactions 5.1.1](https://www.npmjs.com/package/@liskhq/lisk-transactions) (latest version), [@liskhq/lisk-api-client 5.1.3](https://www.npmjs.com/package/@liskhq/lisk-api-client) (latest version), [@liskhq/lisk-client 5.1.3](https://www.npmjs.com/package/@liskhq/lisk-client) (latest version), [@liskhq/lisk-codec 0.2.0](https://www.npmjs.com/package/@liskhq/lisk-codec) (latest version), [lisk-elements 5.1.4](https://www.npmjs.com/package/lisk-elements) (latest version)), the above vulnerabilities can be propagated into these downstream projects and expose security threats to them via the following package dependency paths:
 (1)`@lemii/lisk-ipfs-plugin@0.3.0 ➔ lisk-sdk@5.1.4 ➔ @liskhq/lisk-api-client@5.1.3 ➔ @liskhq/lisk-codec@0.2.0 ➔ @liskhq/lisk-validator@0.6.0 ➔ validator@13.5.2`
(2)`@lisk-react/core@0.6.5 ➔ @liskhq/lisk-client@5.1.1 ➔ @liskhq/lisk-api-client@5.1.3 ➔ @liskhq/lisk-codec@0.2.0 ➔ @liskhq/lisk-validator@0.6.0 ➔ validator@13.5.2`
  **......**

If **_@liskhq/lisk-validator@0.6.\*_** removes the vulnerable package from the above version, then its fixed version can help downstream users decrease their pain.

**Given the large number of downstream users, could you help update your package to remove the vulnerability from @liskhq/lisk-validator@0.6.0 ?**

### Fixing suggestions

In **_@liskhq/lisk-validator@0.6.1_**, maybe you can kindly try to perform the following upgrade(not crossing major version) :
`validator 13.5.2 ➔ 13.6.0`; 

**Note:**
_**validator@13.6.0**(>=13.6.0) has fixed the vulnerability [SNYK-JS-VALIDATOR-1090600](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090600), [SNYK-JS-VALIDATOR-1090599](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090599), [SNYK-JS-VALIDATOR-1090601](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090601) and [SNYK-JS-VALIDATOR-1090602](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090602)._

Thank you for your attention to this issue and welcome to share other ways to resolve the issue.^_^

**Comment by shuse2** [comment]
Superseded by #7084
