### ISSUE TITLE
Cryptography.getLegacyAddressFromPublicKey(publicKey) doesn't work

### ISSUE THREAD

**Issue by adamant-al** [LiskHQ/lisk-sdk#6651]
Hi,

### Expected behavior
Returns old Lsik address like '123456789L'

### Actual behavior
`Uncaught TypeError: publicKeyTransform.readBigUInt64BE is not a function
    at Object.getLegacyAddressFromPublicKey (legacy_address.js?164d:11)`

### Steps to reproduce
`const addressLegacy = cryptography.getLegacyAddressFromPublicKey(publicKey)`
Where `publicKey` is
Hex: `dba4a0461872b876ad833fd68fa872fe078cf55850af9407ecd9718f395bd44a`
Bytes: `Uint8Array(32) [219, 164, 160, 70, 24, 114, 184, 118, 173, 131, 63, 214, 143, 168, 114, 254, 7, 140, 245, 88, 80, 175, 148, 7, 236, 217, 113, 143, 57, 91, 212, 74]`

### Which version(s) does this affect? (Environment, OS, etc...)
"@liskhq/lisk-cryptography": "3.1.0" (latest)

**Comment by shuse2** [comment]
If you are using in the browser, please use `@liskhq/lisk-client` package. the `Buffer` is replaced in the package

**Comment by adamant-al** [comment]
Still it be more comfortable with `@liskhq/lisk-cryptography`, I don't use `@liskhq/lisk-client`.

**Comment by shuse2** [comment]
if you want to use `@liskhq/lisk-cryptography` in the browser, you need to use https://www.npmjs.com/package/buffer and have global `Buffer` in the window

**Comment by adamant-al** [comment]
Thank you.
But it sees to be complicated.
