### ISSUE TITLE
keys broken unit tests?

### ISSUE THREAD

**Issue by roccomuso** [LiskHQ/lisk-sdk#6673]
### Expected behavior

publicKey to generate the expected address buffer.
https://github.com/LiskHQ/lisk-sdk/blob/development/elements/lisk-cryptography/test/keys.spec.ts#L46

### Actual behavior

When using this publicKey: `5d036a858ce89f844491762eb89e2bfbd50a4a0a0da658e4b2628b25b117ae09`
I do get this Buffer:

> <Buffer 3a 97 1f d0 2b 4a 07 fc 20 aa d1 93 6d 3c b1 d2 63 b9 6e 0f>

Instead of

> <Buffer 2b b8 0d 53 7b 1d a3 e3 8b d3 03 61 aa 85 56 86 bd e0 ea cd>

**Comment by shuse2** [comment]
Closing this issue since this is no longer valid
