### ISSUE TITLE
Update forging enable to be more strict

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#6674]
### Description

Forging enable should be strict for case
```
height: 0
maxHeightPrevoted: 0
maxHeightPreviouslyForged: 0
```

- case 1: Input is `0, 0, 0` and there is no previous forging data
  expected result: ok
- case 2: Input is `0, 0, 0` and there is non zero previous forging data
  expected result: fail
- case 3: Input is `0, 0, 0` and there is non zero previous forging data with overwrite flag
  expected result: ok
- case 4: Input is `x, y, z` and there is non zero previous forging data
  expected result: fail
- case 5: Input is `x, y, z` and there is non zero previous forging data with overwrite flag
  expected result: ok

### Acceptance Criteria

- All above cases are tested

**Comment by ManuGowda** [comment]
maybe we can also fix the order of fields to match forging:status command?

**Comment by shuse2** [comment]
which order are u referring to?

**Comment by ManuGowda** [comment]
```
[{"address":"xyz","forging":true,"height":0,"maxHeightPrevoted":0,"maxHeightPreviouslyForged":0}]
```
```
lisk-core forging:enable ADDRESS HEIGHT MAXHEIGHTPREVIOUSLYFORGED MAXHEIGHTPREVOTED
```

sometimes users run forgins:status to enable that time, copy paste could lead to errors, so if the order of `MAXHEIGHTPREVIOUSLYFORGED MAXHEIGHTPREVOTED` is same then its easy to copy and paste?

**Comment by shuse2** [comment]
JSON object key is `unordered`, therefore, we cannot guarantee that is will be in that order if we use JSON output.
If we change the output format, it will be breaking change

**Comment by ManuGowda** [comment]
no we dont have to change the forging:status output, we can just update the forging:enable input order to match it?

**Comment by dakk** [comment]
> no we dont have to change the forging:status output, we can just update the forging:enable input order to match it?

bad idea in my opinion, this will break existing tools

**Comment by shuse2** [comment]
@dakk what do you mean by `right` value? potentially `lisk-core forging:status` can return a valid value, if the data is migrated properly, but it's not possible to know if the data is migrated properly or not 😓

**Comment by dakk** [comment]
> @dakk what do you mean by `right` value? potentially `lisk-core forging:status` can return a valid value, if the data is migrated properly, but it's not possible to know if the data is migrated properly or not sweat

I mean, lisk-core forging:enable should be able to get automatically values from forging:status; not as default, but by passing an optional parameter. It's up to the delegate to check if he/she want to use that option, or if he/she want to provide the values.

Something like this:
```bash
lisk-core forging:enable --use-status-values
```

**Comment by JesusTheHun** [comment]
@shuse2 a responsible delegate will run `lisk-core forging:status` first to make sure the migration was successful, then use `lisk-core forging:enable --use-status-values`
