### ISSUE TITLE
Error API

### ISSUE THREAD

**Issue by roi35** [LiskHQ/lisk-sdk#6680]
Thanks, please delete

**Comment by shuse2** [comment]
I think you are using the old lisk-client which is not compatible with the current network v3.
Please upgrade the lisk-client. Example of creating and signing a transaction is https://lisk.com/documentation/lisk-sdk/guides/node-management/signing-transactions-offline.html#creating-and-signing-the-transaction

**Comment by roi35** [comment]
please help with this code what needs to be changed there
