### ISSUE TITLE
Update request id handling on JSONRPC

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#6698]
### Description

Currently when `request.id` is used, it is casted with `as string`. This casting needs to be removed.

https://github.com/LiskHQ/lisk-sdk/blob/feature/6554-improve-framework-architecture/framework/src/controller/request.ts#L28

`action.id` now called `request.id` is `string | null | number` to comply with JSONRPC 2.0, but we only expect string

### Acceptance Criteria

- Request must be compatible with JSONRPC 2.0
- All unit tests should pass
- All integration tests should pass
- All functional tests should pass

**Comment by shuse2** [comment]
Closing this issue since this is no longer valid
