### ISSUE TITLE
datapath can not start with dot

### ISSUE THREAD

**Issue by eden-wang** [LiskHQ/lisk-sdk#6729]
### Expected behavior
start lisk core successfully
### Actual behavior
```
Starting Lisk Core at /root/.lisk.
Genesis block from "mainnet" does not exists.
Downloading genesis block from https://downloads.lisk.io/lisk/mainnet/genesis_block.json.tar.gz
Downloaded to path: /root/.lisk/config/mainnet/genesis_block.json.tar.gz.
Verified checksum: a69fe85969ce8727b6490a07ced612bbc36a5c377a54f2b6fab58c058d1663b5.
Extracting genesis block file.
Removing downloaded genesis block
Download completed.
   /root/.lisk/config/mainnet/genesis_block.json
    Error: Lisk validator found 1 error[s]:
    must match pattern "^[a-zA-Z][0-9a-zA-Z_-]*$"
```
### Steps to reproduce
```
./bin/lisk-core start --network mainnet --data-path /root/.lisk
```
### Which version(s) does this affect? (Environment, OS, etc...)
OS: 
```
Linux iZj6ccyjfj56u010e4hb22Z 4.4.0-62-generic LiskHQ/lisk-core#83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
Environment:
```
lisk-core/3.0.0 linux-x64 node-v12.22.3
```
### Found
```
./bin/lisk-core  config:show --config /root/.lisk/config/mainnet/config.json --data-path /root/.lisk --pretty
{
  "networkVersion": "3.0",
  "label": ".lisk",
  ....
}
```
`label` is '.lisk', but `label` is [limited](https://github.com/LiskHQ/lisk-sdk/blob/b7e5d1638d4369ac1b27e0d1587757f8b719d2fc/framework/src/schema/application_config_schema.ts#L22) to `^[a-zA-Z][0-9a-zA-Z_-]*$`

**Comment by shuse2** [comment]
Label is used as node name as well in logging or process name. Therefore, for the v5, it would be good to have the validation.
To mitigate the problem, `./bin/lisk-core start --network mainnet --data-path /root/.lisk/lisk-core` unless you have specific requirement.
I will create another issue to improve the usage of root path and label since this will require breaking change

**Comment by shuse2** [comment]
#6768 is created to further discuss this topic
