### ISSUE TITLE
Wrong path in genesis-block:create output

### ISSUE THREAD

**Issue by ShineKami** [LiskHQ/lisk-sdk#6789]
### Expected behavior
    ./bin/run genesis-block:create -o /home/USERNAME/.lisk/hello_app/config/default
     /home/USERNAME/.lisk/hello_app/config/default
### Actual behavior
    ~/hello_app/home/USERNAME/.lisk/hello_app/config/default
### Steps to reproduce
I use tutorial https://lisk.com/documentation/lisk-sdk/guides/app-development/genesis-block.html
PS: I think the problem is in line 178: https://github.com/LiskHQ/lisk-sdk/blob/development/commander/src/bootstrapping/commands/genesis-block/create.ts
process.cwd() - takes the path depending on where I run ". / bin/run"
### Which version(s) does this affect? (Environment, OS, etc...)
lisk-commander/5.1.5

**Comment by shuse2** [comment]
Closing this issue since this is no longer valid
