### ISSUE TITLE
forger:block:missed event returns a wrong delegate

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-sdk#6827]
### Expected behavior

`forger:block:missed` should always return a correct delegate

### Actual behavior

Sometimes when the event is fired, `forger:block:missed` returns a wrong delegate that missed the block. It's probably when the missed block is the last block in the round and the forger list gets reshuffled after the miss. 

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk-SDK 5.1.4

**Comment by shuse2** [comment]
Closing this issue since this is no longer valid
