### ISSUE TITLE
Implement add/validate commit functions of CommitPool

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#6849]
### Description

- Implement `addCommit(commit)` function where it adds a commit to `_nonGossipedCommits` data structure
- Implement `validateCommit(commit)` function where it adds or rejects or throws validation error (for banning) if it fails. Refer to steps of validation provided in [LIP:SingleCommits:Gossip](https://research.lisk.com/t/introduce-certificate-generation-mechanism/296#single-commit-p2p-gossip-37)
- Implement `getCommitsByHeight (height: number)` where it returns commits from `_nonGossipedCommits` and `_gossipedCommits` for that height.

```ts
public getCommitsByHeight (height: number) {
		return [...this._nonGossipedCommits[height], ...this._gossipedCommits[height]];
	}
```

### Acceptance Criteria

- Add unit test for `addCommit`, `getCommitsByHeight` and `validateCommit`

**Comment by milenagojkovic** [comment]
Issue was closed 13 days ago, closing the issue.
