### ISSUE TITLE
Genesis block output parameter expects only relative path, should also expect absolute path

### ISSUE THREAD

**Issue by Tschakki** [LiskHQ/lisk-sdk#6898]
### Expected behavior
./bin/run genesis-block:create --output /home/user/config/default

creates the genesis block in the location `/home/user/config/default/` (under absolute path)

### Actual behavior
```
./bin/run genesis-block:create --output  /Users/mona/.lisk/genesis-test/config/default
  Creating genesis block [====================] 100% 0.0s

Configuration files saved at: /Users/mona/git/test-app2/genesis-test/Users/mona/.lisk/genesis-test/config/default
```

creates the genesis block in the location `${CURRENT_DIR}/home/user/config/default/`

### Steps to reproduce

```
lisk init
./bin/run genesis-block:create --output /home/user/config/default
```

### Which version(s) does this affect? (Environment, OS, etc...)
lisk-commander/5.1.7 darwin-x64 node-v12.22.3

**Comment by shuse2** [comment]
Closing this issue since this is no longer valid
