### ISSUE TITLE
Error when you are creating module with lisk generate:module

### ISSUE THREAD

**Issue by idntty** [LiskHQ/lisk-sdk#6909]
When you create new module with  lisk generate:module command, there is a line added:

`app.registerModule(HelloModule);`

But default code in modules.ts file:

`
import { Application } from 'lisk-sdk';
export const registerModules = (_app: Application): void => {};
`

So when you try to run your app you got a error: ReferenceError: app is not defined

Probably have to fix it either in the module that generates the application or module skeleton.

**Comment by shuse2** [comment]
Closing this issue since this is no longer valid
