### ISSUE TITLE
Possible to swap out `nacl` implementation?

### ISSUE THREAD

**Issue by faustbrian** [LiskHQ/lisk-sdk#6960]
Is there some way to swap out the `nacl` implementation to avoid loading the ones that are based on `tweetnacl` and `sodium-native`? The reason for that being wanting to use faster implementations and browser support.

**Comment by shuse2** [comment]
Currently it's not possible to swap the `nacl` implementation in the cryptography library. However, `tweetnacl` have the browser support.

Could you describe what library or implementation in mind? Also, what is the usecase behind?

**Comment by faustbrian** [comment]
The use-case would be an integration into https://github.com/PayvoHQ/sdk which has already been completed but I'm trying to keep external cryptography dependencies as low as possible which is somewhat easily doable because a lot of coins use https://github.com/bcoin-org/bcrypto or their own implementation that has no dependencies but with the Lisk SDK I'm pulling in some additional dependencies that I had hoped could be replaced with my own implementation using [bcrypto](https://github.com/bcoin-org/bcrypto).

Will close this since it isn't possible and based on the current implementation it would be quite an effort to rework it.
