### ISSUE TITLE
TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (14054)

### ISSUE THREAD

**Issue by fovanessians** [LiskHQ/lisk-sdk#6973]
### Expected behavior
run node, create genesis block
### Actual behavior
21:56:48 INFO lisk-framework: Application shutdown started (module=lisk:app)
{
 "errorCode": 2,
 "message": "process.exit"

### Steps to reproduce
hello_app$ ./bin/run start

### Which version(s) does this affect? (Environment, OS, etc...)
node -v
v17.3.0

Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

lisk-commander/5.1.7 linux-x64 node-v17.3.0
git version 2.20.1

**Comment by fovanessians** [comment]
TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (14054)
    Code: ERR_INVALID_ARG_TYPE

**Comment by przemerr** [comment]
Use the latest version of nodejs v12, higher versions will give you this kind of error.

**Comment by fovanessians** [comment]
Switching to nodejs v12 worked. thank you
