### ISSUE TITLE
Call Action on SDK Dashboard app:getAccount invalid schema

### ISSUE THREAD

**Issue by fovanessians** [LiskHQ/lisk-sdk#7002]
### Expected behavior
Success in verifying transaction 
### Actual behavior
using public address under call action app:getAccount 
ERROR:
Invalid schema property found. Path: address, 0
### Steps to reproduce
Call action -> app:getAccount  -> {"address": "<public address>"} 
### Which version(s) does this affect? (Environment, OS, etc...)
Distributor ID: Debian
Description: Debian GNU/Linux 10 (buster)
Release: 10
Codename: buster

lisk-commander/5.1.7 linux-x64 node-v12.22.7
git version 2.20.1

**Comment by przemerr** [comment]
I've answered you here https://dev.lisk.com/t/invalid-schema-property-found-path-address-0/628

> Hi @fovanessians not sure what modification you did to the hello_app but everytime you change schema, add modules, you need to regenerate the genesis block, see here Generating a genesis block - Lisk SDK Docs. If you did, try removing the application data here rm -r ~/.lisk/<YOUR_APP>
> Does it happen when you launch the app from scratch?
>
>Cheers.

**Comment by djiworks** [comment]
Hello, I got the same error as soon as I use this portion of code. Cf [Lisk SDK tutorial](https://lisk.com/documentation/lisk-sdk/guides/app-development/frontend.html#account-details)
```ts
export const getClient = async () => {
  if (!clientCache) {
    clientCache = await apiClient.createWSClient(process.env.REACT_APP_BC_ENDPOINT || '');
  }
  return clientCache;
};

const client = await getClient();
const account: any = await client.account.get(address);
console.log(client.account.toJSON(account))
```
