### ISSUE TITLE
Add javascript BigInt support for android

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#7005]
### Description

Enable React Native Android environment with encoding and decoding using non native BigInt (e.g using `bignumber/ big-integer`

### Motivation

Currently, on React Native Android, the native javascript BigInt is not supported. Due which the transaction encoding and decoding fails and users will be unable to sign the transactions.

### Additional Information

- The patched Lisk Mobile version with big-integer https://github.com/LiskHQ/lisk-mobile/pull/1260
- Open issue on react native https://github.com/facebook/react-native/issues/32820

**Comment by shuse2** [comment]
Resolved with https://reactnative.dev/blog/2022/09/05/version-070
