### ISSUE TITLE
getAddressFromBase32Address does not work with all addresses in the ledger. 

### ISSUE THREAD

**Issue by nerdvibe** [LiskHQ/lisk-sdk#7006]
### Expected behavior

On testnet we have addresses that do not respect the 41 chars length (eg `lskzzzzzz7gpn25`) and therefore when passing such address to `getHexAddressFromBase32` it throws an error: `Address length does not match requirements. Expected 41 characters.`

### Actual behavior

I guess, even if not entirely correct, `getHexAddressFromBase32` should return a value because those addresses are in the ledger.

### Steps to reproduce

```
import {
  getAddressFromBase32Address,
} from "@liskhq/lisk-cryptography";

getAddressFromBase32Address('lskzzzzzz7gpn25')
```

**Comment by shuse2** [comment]
The short address on testnet is actually invalid address because address must be  20 bytes.
We may need to think of mitigation of this problem for testnet specifically, but the error message is correct
