### ISSUE TITLE
Account data is not correctly decoded

### ISSUE THREAD

**Issue by djiworks** [LiskHQ/lisk-sdk#7009]
### Context
Let's say you have a module called `loan` that store a field `lend` in account state.
```js
{
address: // Buffer
// ....
loan: {
 lend: [ '' ] // Array of string
}
// ...
}
```

### Expected behavior
This works correctly by using  CLI : `./bin/run account:get <your address>`
Get an account object like this :
```js
{
address: // Buffer
// ....
loan: {
 lend: [ '' ] // Array of string
}
// ...
}
```

### Actual behavior
```js
{
address: // Buffer
// ....
loan: {
 lend: ["57,53,56,54,102,57,56,100,55,56,56,54,48,56,100,51…8,101,57,53,102,50,51,53,97,53,102,98,48,99,49,97"] // Kind of buffer ?
}
// ...
}
```

### Steps to reproduce

What we use to retrieve account on client side :
```ts
export const getClient = async () => {
  if (!clientCache) {
    clientCache = await apiClient.createWSClient(process.env.REACT_APP_BC_ENDPOINT || '');
  }
  return clientCache;
};

export const getAccountData = async (address: Buffer) => {
  const client = await getClient();
  const account: any = await client.account.get(address);
  console.log(account)
  
  return { lend: account.loan.lend}
}
```

### Which version(s) does this affect? (Environment, OS, etc...)
CRA : 4
@liskhq/lisk-client : 5.2.1,

### How to fix it ?
Downgrade to  @liskhq/lisk-client 5.1.3

**Comment by Lemii** [comment]
I can confirm this issue is present. The 'fix' was indeed to downgrade to 5.1.x.

**Comment by Tschakki** [comment]
This might be related to #7002

**Comment by shuse2** [comment]
account / account.get no longer exist in v6 so closing this issue
