### ISSUE TITLE
Transaction create command does not parse the boolean value

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#7067]
### Expected behavior

The `transaction:create` command should take input for the asset and parse the values correctly. 

### Actual behavior

For `boolean` value the below code consider input as `string` which caused failure for schema validation 

https://github.com/LiskHQ/lisk-sdk/blob/8467d5a9004eee2d55bdfb1497c99d397fe6a259/commander/src/utils/reader.ts#L329

### Steps to reproduce

1. Create asset which have a boolean field. 
2. Run following `> ./bin/run transaction:create 1024 0 1000`
3. When the input will be asked for a boolean value, it will fail on schema check.

### Which version(s) does this affect? (Environment, OS, etc...)
5.x

**Comment by shuse2** [comment]
Closing this issue since this is no longer valid
