### ISSUE TITLE
Use pre-hashing for signatures

### ISSUE THREAD

**Issue by mitsuaki-u** [LiskHQ/lisk-sdk#7105]
### LIP

- [Use pre-hashing for signatures](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0062.md)

### Description

This Epic provides technical specifications for `Use pre-hashing for signatures in Lisk`.  This includes transactions, block headers and certificate signatures. This allows signing to be performed on memory limited devices such as hardware wallets.

### Tasks

- [ ] #7102
- [ ] #7103
- [ ] #7104

**Comment by shuse2** [comment]
This is duplicate of #6949

**Comment by mitsuaki-u** [comment]
> This is duplicate of #6949

Why not just close the other one keep this open since it had all the info? 🤔

**Comment by shuse2** [comment]
@mitsuaki-u The link to the issue might have been used before, so I tried to keep the URL active 🙇
