### ISSUE TITLE
Failed to create genesis block from bootstrapped application

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#7113]
### Expected behavior

Fix all the genesis block creation issue

#### Incorrect output path

The output file path is incorrect `/Users/manu/workspace/lisk-core/Users/manu/workspace/lisk-core/test_GB`

```
./bin/run genesis-block:create --output /Users/manu/workspace/lisk-core/test_GB --accounts 10 --validators 101 --assets-file ./config/default/assets.json
BaseGenesisBlockCommand.BaseGenesisBlockCommand
BaseGenesisBlockCommand.BaseGenesisBlockCommand..... end
Genesis block files saved at: /Users/manu/workspace/lisk-core/Users/manu/workspace/lisk-core/test_GB
```

#### genesis block create should convert JSON to object

bootstrapping/commands/genesis-block/create.js `await app.generateGenesisBlock`

Fix required
```
const genesisBlock = await app.generateGenesisBlock({
                assets: assetsJSON.assets.map(asset => ({
                    ...asset,
                    data: codec.codec.fromJSON(asset.schema, asset.data),
                })),
            });
```

#### Fix genesis asset schema

In file `utils/genesis_creation.js` `genesisAssetsSchema`

Fix:
```
{
    $id: '/genesis/asset/0',
    type: 'object',
    required: ['assets'],
    properties: {
        assets: {
            type: 'array',
            items: {
                type: 'object',
                required: ['moduleID', 'data', 'schema'],
                properties: {
                    moduleID: {
                        type: 'integer',
                        format: 'uint32',
                    },
                    data: {
                        type: 'object',
                    },
                    schema: {
                        type: 'object',
                    },
                },
            },
        }

    },
}
```
#### Return after using asset file

In file bootstrapping/commands/genesis-block/create.js, After this line `this.log(`Genesis block files saved at: ${configPath}`);`
add `return`

### Steps to reproduce

- Bootstrap an application using commander
- Add modules
- Create genesis block using that new module

### Which version(s) does this affect? (Environment, OS, etc...)
development

**Comment by shuse2** [comment]
Genesis block creation is updated and with alpha.3, it is working now
