### ISSUE TITLE
Add block assets schema for the endpoint `app_getSchema`

### ISSUE THREAD

**Issue by nagdahimanshu** [LiskHQ/lisk-sdk#7144]
### Description
Include block assets schema in response of endpoint `app_getSchema`
```
assetSchema = {
  "type": "object",
  "required": ["moduleID", "data"],
  "properties": {
    "moduleID": {
      "dataType": "uint32",
      "fieldNumber": 1
    },
    "data": {
      "dataType": "bytes",
      "fieldNumber": 2
    }
  }
}
```

### Motivation
- It is necessary to include the block assets schema while retrieving all schemas from SDK
- It is required to decode the complete block

**Comment by shuse2** [comment]
Superseded by #7133 in https://github.com/LiskHQ/lisk-sdk/pull/7184/files#diff-c71ac364c3be2288c1052ba89418fb2af01430298b501ea76cf17804fc8b8005R82-R90
