### ISSUE TITLE
Not clear when a CCM fails whether to fail the whole CCU or continue processing

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#7185]
### Description

Need to clarify and update the CCU execute part where we terminate the chain when a ccm schema or validation fails, whether to exit CCU processing or continue processing

- Also we need to clarify whether to have this check or not, https://github.com/LiskHQ/lisk-sdk/pull/7165#discussion_r881673082

### Which version(s) does this affect? (Environment, OS, etc...)

`6.0`

**Comment by shuse2** [comment]
Resolved by #7724 and #7725
