### ISSUE TITLE
Update modules with events and error handlings

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#7211]
### Motivation

With introduction of on-chain events and failing transaction, all existing modules should be updated to incorporate this features to enhance the user experience.

### Tasks
- [x] #7287
- [x] #7289 
- [x] #7341
- [x] #7342
- [x] #7345
- [x] #7346
- [x] #7343
- [x] #7436
- [x] #7344
- [x] #7301
- [x] #7381 
- [x] #7384 
- [x] #7385 
- [x] #7440
- [x] #7441
- [x] #7442
- [x] #7436
- [x] #7561 
- [x] #7556
- [x] #7647
- [x] #7555
- [x] #7558 
- [x] #7559 
- [x] #7560 
- [x] #7565
- [x] #7562 
- [x] #7564
- [x] #7566
- [x] #7596
- [x] #7597 
- [x] #7599
- [x] #7623
- [x] #7656 
- [x] #7657 
- [x] #7658 
- [x] #7550
- [x] #7686 
- [x] #7687 
- [x] #7688 
- [x] #7689 
- [x] #7279
- [x] #7719 
- [x] #7723
- [x] #7722
- [x] #7600
- [x] #7764 
- [x] #7765 
- [x] #7702
- [x] #7785
- [x] #7557
- [x] #7724
- [x] #7725
- [x] #7726 
- [x] #7727 
- [x] #7185
- [x] #7748
- [x] #7766 
- [x] #7768 
- [x] #7769 
--------

- [x] #7571
- [x] #7572 
- [x] #7573 
- [x] #7574 
- [x] #7576 
- [x] #7577 
- [x] #7578 
- [x] #7609
- [x] #7575 
- [x] #7579 
- [x] #7646 
-------

- [x] #7798

**Comment by Adminsupportt** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam
https://direct.lc.chat/14201763/
