### ISSUE TITLE
Unable to create transactions from the command line

### ISSUE THREAD

**Issue by sameersubudhi** [LiskHQ/lisk-sdk#7232]
### Expected behavior
User should be able to create a transaction from the command line without any issue.

### Actual behavior
Creating transaction from the command line fails. Following are the errors encountered when attempting to create a transaction from the command line.

```
SameersMBPIntel:lisk-core sameer$ ./bin/run transaction:create 2 0 100000000 --params='{"amount":100000000,"recipientAddress":"302043c35275926cef60dbe1b90c35e5f9123e70","data":"send token"}'
    Error: IPC Socket client connection timeout. Please check if IPC server is running.

SameersMBPIntel:lisk-core sameer$ ./bin/run transaction:create 2 0 100000000 --params='{"amount":100000000,"recipientAddress":"302043c35275926cef60dbe1b90c35e5f9123e70","data":"send token"}' -d ~/.lisk
    Error: Application at data path /Users/sameer/.lisk is not running.

SameersMBPIntel:lisk-core sameer$ ./bin/run transaction:create 2 0 100000000 --params='{"amount":100000000,"recipientAddress":"302043c35275926cef60dbe1b90c35e5f9123e70","data":"send token"}' -d ~/.lisk/lisk-core
    Error: IPC Socket client connection timeout. Please check if IPC server is running.

SameersMBPIntel:lisk-core sameer$ ./bin/run transaction:create 2 0 100000000 --params='{"amount":100000000,"recipientAddress":"302043c35275926cef60dbe1b90c35e5f9123e70","data":"send token"}' -d ~/.lisk/lisk-core/socket
    Error: Application at data path /Users/sameer/.lisk/lisk-core/socket is not running.

SameersMBPIntel:lisk-core sameer$ ./bin/run transaction:create 2 0 100000000 --params='{"amount":100000000,"recipientAddress":"302043c35275926cef60dbe1b90c35e5f9123e70","data":"send token"}' -d ~/.lisk/lisk-core/socket/ipc
    Error: Application at data path /Users/sameer/.lisk/lisk-core/socket/ipc is not running.

SameersMBPIntel:lisk-core sameer$ ./bin/run transaction:create 2 0 100000000 --offline --network devnet --network-identifier 5f26c04c589119ec65eeb49ab0b0525498ee3601ad66cb7e7075fb1724dfd5e1 --nonce 0 --params='{"amount":100000000,"recipientAddress":"302043c35275926cef60dbe1b90c35e5f9123e70","data":"send token"}'
    TypeError: this.getApplication is not a function
```

### Steps to reproduce

- Clone `https://github.com/LiskHQ/lisk-core/tree/development`
- `npm install --registry https://lisk.npm.com`
- `npm run build`
- `rm -rf ~/.lisk && ./bin/run start --network devnet --api-ipc --console-log info`
- In a new terminal window run one of the six commands listed along with the errors in the previous section

### Which version(s) does this affect? (Environment, OS, etc...)

Lisk SDK: `6.0.0-alpha.0`

**Comment by ishantiw** [comment]
Able to create the transaction but the transaction cannot be posted as token module needs interoperability API to do the processing. So we need to wait for [Add and expose interoperability APIs  #7261](https://github.com/LiskHQ/lisk-sdk/issues/7261)

**Comment by ishantiw** [comment]
Since the transaction can be created successfully right now so we can close this issue and we can handle the post transaction in [Add and expose interoperability APIs  #7261](https://github.com/LiskHQ/lisk-sdk/issues/7261)
