### ISSUE TITLE
Add missing unit tests for `DPos` module

### ISSUE THREAD

**Issue by sitetester** [LiskHQ/lisk-sdk#7259]
**Description**

_Genesis Processing_
- When genesis block initDelegates contains more delegates than round length (Genesis block should be rejected)
- When genesis block initDelegates contains an address which is not a delegate account  (Genesis block should be rejected)
- When genesis block is accepted (It should update all registered usernames)

_After block apply_
- When block is forged and finalized height is changed (It should clear vote weight cache)
- During bootstrap period when its last block of round (It should create vote weight snapshot)
- After bootstrap period when its last block of round (It should update the 2 validators who are not participating in consensus)
- After bootstrap period when delegate missed the block (It should increment the consecutiveMissedBlocks)
- After bootstrap period when delegate forged a block (It should reset consecutiveMissedBlocks to zero)
- After bootstrap period when delegate forged a block (It should update lastForgedHeight to current height)

**Which version(s) does this affect? (Environment, OS, etc...)**
development

**Comment by has5aan** [comment]
# Genesis Processing
> - When genesis block initDelegates contains an address which is not a delegate account (Genesis block should be rejected)

The scenario Init validators includes non existing validator address covers the suggested scenario.

> - When genesis block initDelegates contains an address which is not a delegate account (Genesis block should be rejected)

A stricter check against number of active validators covers this suggestion.

# After Transaction Execute
> - During bootstrap period when its last block of round (It should create vote weight snapshot)
> - After bootstrap period when its last block of round (It should update the 2 validators who are not participating in consensus)
> - After bootstrap period when delegate missed the block (It should increment the consecutiveMissedBlocks)
> - After bootstrap period when delegate forged a block (It should update lastForgedHeight to current height)

The tests `should update validators` and `should create stake weight snapshot` covers the reported scenarios post restructuring.
