### ISSUE TITLE
Add missing unit tests for validators module [API section] getGeneratorsBetweenTimestamps

### ISSUE THREAD

**Issue by sitetester** [LiskHQ/lisk-sdk#7267]
***getGeneratorsBetweenTimestamps***

- all entries in generatorList are pairwise distinct - startTimestamp == genesisData.timestamp - endTimestamp == genesisData.timestamp + 3 * BLOCK_TIME" (return {generatorList[1]:1, generatorList[2]:1})

<hr>
- Let a:=slot(startTimestamp) and b:=slot(endTimestamp)  
- all entries in generatorList are equal but the length of the list is larger than 1 
- startTimestamp < endTimestamp 
- b = a + n, where n > 1 

Expectation:
"return {generatorList[0]: n-1}
The returned object has only one entry.
The sum of all values is n-1."
<hr>

"Let a:=slot(startTimestamp), b:=slot(endTimestamp) and L:=length(generatorList).
- all entries in generatorList are pairwise distinct
- startTimestamp < endTimestamp
- b = a + n, where 1 < n < L
- a % L < b % L"

Expectation: 
"for the generators with index a%L  < j < b%L the count is 1, and for all other generators, the count is 0.
The returned object has n-1 entries.
The sum of all values is n-1."
<hr>

"Let a:=slot(startTimestamp), b:=slot(endTimestamp) and L:=length(generatorList).
- all entries in generatorList are pairwise distinct
- startTimestamp < endTimestamp
- b = a + n, where n > L; n = k* L + n', with k >= 1; n' < L
- a % L < b % L "

Expectation: 
"for the generators with index a%L  < j < b%L the count is k+1, and for all other generators, the count is k.
The returned object has L entries.
The sum of all values is n-1."
<hr>
"Let a:=slot(startTimestamp), b:=slot(endTimestamp) and L:=length(generatorList).
- all entries in generatorList are pairwise distinct
- startTimestamp < endTimestamp
- b = a + n, where 1 < n < L
- a % L > b % L" 

Expectation: 
"for the generators with index b%L <= j <= a%L the count is 0, and for all other generators, the count is 1.
The returned object has n-1 entries.
The sum of all values is n-1."
<hr>

"Let a:=slot(startTimestamp), b:=slot(endTimestamp) and L:=length(generatorList).
- all entries in generatorList are pairwise distinct
- startTimestamp < endTimestamp
- b = a + n, where n > L; n = k* L + n', with k >= 1; n' < L
- a % L > b % L "  

Expectation: 
"for the generators with index b%L <= j <= a%L the count is k, and for all other generators, the count is k+1.
The returned object has L entries.
The sum of all values is n-1."
<hr>

"Let a:=slot(startTimestamp), b:=slot(endTimestamp) and L:=length(generatorList).
- all entries in generatorList are pairwise distinct
- startTimestamp < endTimestamp
- b = a + L; basically set n=L
- ==> a % L == b % L " 

Expectation: 
"for the generators with index  j==a%L==b%L the count is 0, and for all other generators, the count is 1.
The returned object has L-1 entries.
The sum of all values is L-1."
<hr>

"Let a:=slot(startTimestamp), b:=slot(endTimestamp) and L:=length(generatorList).
- all entries in generatorList are pairwise distinct
- startTimestamp < endTimestamp
- b = a + k* L; basically set n= k*L
- ==> a % L == b % L " 

Expectation: 
"for the generators with index  j==a%L==b%L the count is k-1, and for all other generators, the count is k.
The returned object has L entries.
The sum of all values is n-1 = k*L-1."
<hr>

"Repeat all tests from 76 to 81 but:
- remove the condition: all entries in generatorList are pairwise distinct.
- add the condition: all entries are pairwise distinct but the first one is repeated at the end." 

Expectation: 
we expect the same results as in tests 76-81 if we understand all slots assigned to the last entry of the generatorList to be assigned to the first entry (so that this entry gets the sum of the two values)
<hr>

**Which version(s) does this affect? (Environment, OS, etc...)**
Lisk SDK `development` branch

**Comment by has5aan** [comment]
Suggested improvements have been made under issue #8115.
