### ISSUE TITLE
Add missing unit tests for validators module [Endpoints]

### ISSUE THREAD

**Issue by sitetester** [LiskHQ/lisk-sdk#7268]
**Description**

***getGeneratorList***

- Generator list substore is not initialized (?) Check latest spreadsheet for expected value
- Generator list substore has an entry (return the entry)
- Entry in generator list substore is the empty array (return empty array)
- Entry in generator list substore has length 199 (return the entry (array of length 199))
- Entry in generator list substore has length > 199 (return the entry (array of length > 199))

**verifyBLSKey**

- BLSKey is shorter than 48 bytes - proof of possession has valid length (- returns False)
- BLSKey is longer than 48 bytes - proof of possession has valid length (- returns False)

**Which version(s) does this affect? (Environment, OS, etc...)**
Lisk SDK `development` branch

**Comment by Incede** [comment]
Superseded by #7850
