### ISSUE TITLE
Invalid transaction state is not rolled back

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#7271]
### Expected behavior

When a transaction is executed, the state should be rolled back if it fails

### Actual behavior

The state is not rolled back when the transaction fails during execution

https://github.com/LiskHQ/lisk-sdk/blob/7090-id/framework/src/engine/generator/generator.ts#L717

### Steps to reproduce

- Run test `npm run test:integration test/integration/node/processor/report_misbehavior_transaction.spec.ts`

### Which version(s) does this affect? (Environment, OS, etc...)

`6.0.0-alpha.0`

**Comment by shuse2** [comment]
With https://github.com/LiskHQ/lisk-sdk/issues/7149, this should no longer problem
