### ISSUE TITLE
Use consistent approach for assigning ID as Buffer in the modules and commands

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#7280]
### Description

Follow the approach where we will only use `moduleID` as `number` in the following places for better user experience,
- When declare in `constants const MODULE_ID_FEE = 14`
- when assign it to the `id` of a module `public id = getIDBuffer(MODULE_ID_FEE)`

### Acceptance Criteria

- Should pass all the existing tests in the framework, commander, elements and plugins

**Comment by shuse2** [comment]
`id` is removed from module and command, so this issue is no longer valid
