### ISSUE TITLE
List of issues with latest canary version

### ISSUE THREAD

**Issue by nagdahimanshu** [LiskHQ/lisk-sdk#7309]
### Expected behavior

- Transaction should be successfully included in the block
- Able to connect via IPC client on Service side
- Able to subscribe to events when using WS client

### Actual behavior

- Able to create and post transaction to the node, but block execution of that particular block is failed with the error
```

21:30:30 INFO lisk-framework: Added transaction to pool (module=engine)
{
 "id": "827f444a59d723c95bd6638f4cf74a5de142e0d9ef83e587e47742e0720285ab",
 "nonce": "0",
 "senderPublicKey": "44c3cb523c0a069e3f2dcb2d5994b6ba8ff9f73cac9ae746922aac4bc22f95b1"
} 
21:30:37 INFO lisk-framework: Generated new block (module=engine)
{
 "id": "445d59cd8e0ef5cc4c3bf7ad8df9dd9b3568c8a4458dd776b4eafd4782987815",
 "height": 11,
 "generatorAddress": "0afb9cb0b91b11a583f219eec0d4abafe9b903d0"
} 
21:30:37 ERROR lisk-framework: Fail to respond (module=lisk:app)
Message: Invalid state root `Not matching with expected` 
 Trace: Error: Invalid state root `Not matching with expected` 
{
 "method": "commit"
} 
21:30:37 ERROR lisk-framework: Fail to execute block. (module=engine)
Message: Invalid state root `Not matching with expected` 
 Trace: Error: Invalid state root `Not matching with expected`
    at ABIClient._listenToRPCResponse (/Users/himanshu/Documents/lisk/lisk-core/node_modules/lisk-framework/dist-node/abi_handler/abi_client.js:141:33) 
21:30:38 INFO lisk-framework: Generated new block (module=engine)
{
 "id": "ec0d7c5f9618672fcfd7a3466b72e69911cd9da06eb8a3cff4579ae8194f079a",
 "height": 11,
 "generatorAddress": "0afb9cb0b91b11a583f219eec0d4abafe9b903d0"
} 
```
- Not able to connect via IPC client
- Able to connect to WS client but not able to subscribe to events

### Steps to reproduce

- Run Node with IPC client enabled: `./bin/run start -n devnet --api-ipc` and create IPC client using the method `createIPCClient `
- Run Node with WS client enabled and subscribe to events: `./bin/run start -n devnet --api-ws` and create WS client using the method `createWSClient `
- Run a node, create a valid transaction and send the transaction to the node

### Which version(s) does this affect? (Environment, OS, etc...)
6.0.0-alpha.31866

**Comment by nagdahimanshu** [comment]
> For
> 
> > Not able to connect via IPC client
> > Able to connect to WS client but not able to subscribe to events
> 
> these points, could you describe how you are trying to connect to the node? Also, are you using `--api-ws` and `--api-ipc` flags?

Hi @shuse2 ,yes I am using the flag `--api-ipc` to enable IPC client: 
Command: `./bin/run start -n devnet --api-ipc` and on `service` side, creating IPC client: ` await createIPCClient('~/.lisk/lisk-core');` 

And, in case WSClient, all endpoints works fine but not able to subscribe to events only.  I am using the flag `--api-ws` to enable WS client and creating WSClient: ` await createWSClient(`ws://localhost:7887/rpc-ws`);`

**Comment by ishantiw** [comment]
@nagdahimanshu 
I am able to connect using IPC when I create an API Client and run a node with `examples/dpos-mainchain`

```ts
const ipcClient = await createIPCClient('~/.lisk/dpos-mainchain');
```

For WS Client, I see the problem that it doesn't work for events.

**Comment by ishantiw** [comment]
Closing this issue as for the reported issues we already have other issues,

- Able to create and post transaction to the node, but block execution of that particular block is failed with the error https://github.com/LiskHQ/lisk-sdk/issues/7258
- Not able to connect via IPC client (does not exist, works fine)
- Able to connect to WS client but not able to subscribe to events https://github.com/LiskHQ/lisk-sdk/issues/7311
