### ISSUE TITLE
Update module endpoint context to have access to module.db

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#7312]
### Description

- Update module endpoint to have access to `module.db`
When handling endpoint in [in-memory channel](https://github.dev/LiskHQ/lisk-sdk/blob/development/framework/src/controller/channels/in_memory_channel.ts#L104-L105), it should add access to `module.db` as `StateStore`. For [IPC channel](https://github.dev/LiskHQ/lisk-sdk/blob/development/framework/src/controller/channels/ipc_channel.ts#L209-L210), it should add interface, but throw error because other process cannot have access to this DB.
- Update function name for the endpoint and insertAsset context to get module.db to be `getOffchainStore` from `getGeneratorStore`

### Acceptance Criteria
- Add unit test for in-memory and ipc channels to make sure `getOffchainStore` is accessible

### Additional Information
- There might be better function name instead of `getOffchainStore`

**Comment by mosmartin** [comment]
Hi @shuse2, for the second point in the description (`Update function name for the endpoint and insertAsset context...`), does;

- function name for the endpoint refer to [this](https://github.dev/LiskHQ/lisk-sdk/blob/ef942e74ea55f44db1af3a720093969d6a42194b/framework/src/engine/generator/generator_store.ts#L31) method definition?
- insertAsset context refer to [this](https://github.dev/LiskHQ/lisk-sdk/blob/ef942e74ea55f44db1af3a720093969d6a42194b/framework/src/state_machine/types.ts#L184) interface?

**Comment by shuse2** [comment]
For the rename, the main name change is [here](https://github.dev/LiskHQ/lisk-sdk/blob/ef942e74ea55f44db1af3a720093969d6a42194b/framework/src/state_machine/generator_context.ts#L61-L62).

which should return `getOffchainStore`. At the same time, probably we can make it consistent to have the same interface as getStore. ie) add `storePrefix` as second parameter.

the 2 places you mentioned will also need to be updated once you update the above
