### ISSUE TITLE
decryptPassphraseWithPassword does nothing when a provided password is wrong

### ISSUE THREAD

**Issue by eniolam1000752** [LiskHQ/lisk-sdk#7331]
### Description

When there is a need to decrypt an encrypted passphrase, the  `decryptPassphraseWithPassword` function from SDK is used which takes in the encypted passphrase and password.

When an incorrect password is provided, SDK doesn't throw an exception nor returns a value. It seems as though it goes into a loop.

### Motivation
`decryptPassphraseWithPassword` needs to be able to throw an error or return a value that can help tell a third-party consumer that the provided parameters are incorrect.

### Additional Information
`decryptPassphraseWithPassword` was consumed this way as seen below;
<img width="531" alt="image" src="https://user-images.githubusercontent.com/32064769/180770439-a61fbf48-e0d3-477a-bc74-b5928245bc7d.png">

When a wrong password is provided, `--- end ---` doesn't get logged nor is an error thrown

**Comment by shuse2** [comment]
Added test in #7335 https://github.com/LiskHQ/lisk-sdk/pull/7335/files#diff-e1e750e23824e1c8ff8baff38b41d04395865de3a37455a187dcc9104660e263R239-R243

However, it seems like it is properly rejecting
