### ISSUE TITLE
Lisk desktop tests fail when lisk-client is updated to v6

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#7338]
### Expected behavior

Configure Lisk desktop tests environment to handle `buffer` for both browser and nodejs

### Actual behavior

- When we update `lisk-client` dependency to its latest version the tests starts to fail
- The root cause of failing tests are due to the changes in the way lisk-client is being shipped from version >= v6
  - The global buffer is an instance of browser buffer https://github.com/LiskHQ/lisk-sdk/commit/f0c25ef51a69f232dcd95782306e78f2edf7316e
  - Since the jest setup is configured to work with nodejs buffer, if we update lisk-client to its latest version the lisk-client functions starts to fail
  
### Steps to reproduce

- Checkout development branch
- Update `lisk-client` to latest version `v6`
- Run `npm install`
- Run `npm run test`

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk Desktop v3

**Comment by shuse2** [comment]
The main reason why `browser` became default is we use the `browser` version in faucet and dashboard plugins and they are working.
`exports` field is currently not working well in [TypeScript](https://github.com/microsoft/TypeScript/issues/33079).

If we change the default back
* Make sure faucet/dashboard plugin UI works as it is. (maybe we just need bundler to resolve)
