### ISSUE TITLE
Commander command blockchain:reset needs to be updated 

### ISSUE THREAD

**Issue by mitsuaki-u** [LiskHQ/lisk-sdk#7349]
### Expected behavior

Should clear all dbs and allow to re-rerun the node.

### Actual behavior

Error when re-rerunning the node:
```
Message: Invalid validator key.
 Trace: Error: Invalid validator key
```

### Steps to reproduce

Run node for few blocks. Run blockchain:reset. Then run the node again.

### Which version(s) does this affect? (Environment, OS, etc...)
development

**Comment by milenagojkovic** [comment]
Reopened as it was PR https://github.com/LiskHQ/lisk-sdk/pull/7350 was linked to the correct issue that closes this issue. Adding into milestone 75.
