### ISSUE TITLE
Use max CCU size to collect CCM

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#7458]
### Description

Add a mechanism to check for max CCU size that is accepted by the network and based on that we create a CCU with number of CCMs it can hold making sure it respects the overall size of CCU transaction.
- we need to calculate the max CCU size ~15kb and determine the number of CCMs that can be included in a sequence. For ex, `ccm1, ccm2, ccm3, ccm4, ccm5,..ccm(n)` where ccm2 is at the certified height, then we chose from ccm3 to ccm(n) in a way that we can fit into max CCU size, `sizeOf[ccm3....ccm(m)] < MAX_CCU_SIZE` taking rest of the properties of CCU transaction into account.

- In the `newBlockHandler`, before calling [`createCCU`](https://github.com/LiskHQ/lisk-sdk/blob/3795e3d60b1883e0243267922f70530c6507ac76/framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts#L359). We call the function `getListOfCCM(ccm []) => list of ccm` where `getListOfCCM` implements the above logic and returns a list of CCMs that can be included in a CCU respecting max size. 

### Acceptance Criteria

- A CCU with size under max size is created including sufficiently large CCMs

### Additional Information

- Discussion: https://github.com/LiskHQ/lisk-sdk/pull/7438#discussion_r957450935
- Related function https://github.com/LiskHQ/lisk-sdk/blob/3795e3d60b1883e0243267922f70530c6507ac76/framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts#L422

**Comment by shuse2** [comment]
Max size of CCMs which can be included into the CCU is
```
export const MAX_CCM_SIZE = 10240
```
This is based on the maximum size of CCU which can be included into the mainchain block.
