### ISSUE TITLE
Jenkins test fails at random

### ISSUE THREAD

**Issue by sitetester** [LiskHQ/lisk-sdk#7475]
There is an unreliable test which sometimes pass & sometimes fail.

### Expected behavior
Test should pass like this - https://jenkins.lisk.com/blue/organizations/jenkins/lisk-sdk%2Flisk-sdk/detail/PR-7471/4/pipeline/#step-193-log-381

### Actual behavior
Failed test - https://jenkins.lisk.com/blue/organizations/jenkins/lisk-sdk%2Flisk-sdk/detail/PR-7471/3/pipeline/

```
FAIL test/integration/node/genesis_block.spec.ts (30.468 s)
[2022-09-02T11:12:26.317Z]   ● genesis block › given the application has not been initialized › when chain module is bootstrapped › should have correct delegate list
```

### Steps to reproduce
Build is auto run upon `git commit`

### Which version(s) does this affect? (Environment, OS, etc...)
V6

**Comment by shuse2** [comment]
Jenkins job is removed once PR is merged. It is not possible to see the problem.
Since we cannot check what was the problem, we will close this issue for now
