### ISSUE TITLE
[Lisk commander] Descriptions need to be updated to give more info

### ISSUE THREAD

**Issue by sitetester** [LiskHQ/lisk-sdk#7511]
### Description

./bin/run start
- By default, it starts server in `ipc` mode. Equivalent to `./bin/run start --api-ipc`
- We can add `./bin/run start --api-http` in EXAMPLES

 -d, --data-path=data-path Directory path to specify where node data is stored. Environment variable "LISK_DATA_PATH" can also be used.

- It should include "os.homedir() .lisk, application name" path

-n, --network=network    [default: default] Default network config to use. Environment variable "LISK_NETWORK" can also be used.

- `mainnet, devnet, testnet` options could be be added here

./bin/run transaction:create --offline Specify whether to connect to a local node or not.
- Need little clarification here, what's the difference to be `online` or `offline`
- We can provide sample value for `passphrase` `lorem ipsum dolor sit amet consectetur adipiscing elit donec eget eros eu`
- We can provide sample value for `tokenID` `0000000000000000`

./bin/run console --api-ipc=/path/to/server
- Need proper example here with path

./bin/run account:create --help
- We can provide short description about each of these in EXAMPLES
```
{
  "passphrase": "become anxiety bundle quality stove fetch wave chief remain away welcome erupt",
  "privateKey": "2676edf26b62baee3081a5d8f66f28ef6e084935a9ea29a472f89c1d22b6dac57f7f8f6dbc2720f2f6c238f5da754d2d0c789014aa85acc926d797e8609238d1",
  "publicKey": "7f7f8f6dbc2720f2f6c238f5da754d2d0c789014aa85acc926d797e8609238d1",
  "blsPrivateKey": "424574101f251cd457a57551b6a7fd92d8ae5f618bd2126d53468dca1155d185",
  "blsPublicKey": "9131a673dd3e0d515ba6be2613fb0f2c80e88e9fcc28335a04c1177d0b9245bce7b8bb13674dac643132e7b37f6d0dd6",
  "address": "lsky79wjt465smncdtdhwmk2c323yhcxjuvhs2xju"
 }
 ```
 
account:validate  Validate lisk32 address
- We can add blog link to lisk32 address in description - https://lisk.com/blog/research/new-lisk-id-system

./bin/run blskey:create
- We can add, this is same `blsPrivateKey` & `blsPublicKey` what we see in output of `./bin/run account:create` (corresponding to some `passphrase`)

### Motivation
To give more info to user

### Additional Information
- https://github.com/LiskHQ/lisk-docs/pull/1621
- https://lisk.com/documentation/integrate-blockchain/create-user-interface.html#new-account
- https://lisk.com/documentation/lisk-sdk/references/lisk-commander/commands.html#create_account

**Comment by mosmartin** [comment]
As discussed with @shuse2 , this is an old issue and will not be added to v6.1.0. The recommendations however, have been noted.
