### ISSUE TITLE
`./bin/run blockchain:hash` doesn't hash for default path

### ISSUE THREAD

**Issue by sitetester** [LiskHQ/lisk-sdk#7514]
### Expected behavior
It should work for default path also (configured in `getDefaultPath(this.config.pjson.name);`

### Actual behavior
It gives error

### Steps to reproduce
- cd /lisk-sdk/examples/dpos-mainchain
```
$ ./bin/run blockchain:hash                                                                            
Error: An exception occurred while executing a `neon::event::Channel::send` callback
```

### Which version(s) does this affect? (Environment, OS, etc...)
6.0.0

**Comment by Incede** [comment]
`./bin/run blockchain:hash` under  lisk-sdk/examples/pos-mainchain sucessfully returns output hash as e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
