### ISSUE TITLE
Inconsistency in vote

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-sdk#756]
Referencing issue from Lisk-js
https://github.com/LiskHQ/lisk-js/issues/335

**Comment by Tosch110** [comment]
`recipientId` should be `null` in vote transactions

**Comment by karek314** [comment]
Issue in lisk-js has been closed, as it's related to lisk core, here it is
Why does [voting](https://github.com/LiskHQ/lisk-js/blob/development/src/transactions/vote.js#L41) require address to be specified while [second signature creation](https://github.com/LiskHQ/lisk-js/blob/development/src/transactions/signature.js#L53) or [delegate registration](https://github.com/LiskHQ/lisk-js/blob/development/src/transactions/delegate.js#L41) not?

**Comment by willclarktech** [comment]
This is making things awkward in lisk-js where type 3 transactions have to be given special treatment. It would be much cleaner if `recipientId` could be `null` for all transactions where no balance is received.

Relevant lines are here:
https://github.com/LiskHQ/lisk/blob/7b5d1fa2c557913a244c191df5d2aa7e9cdb8ecd/logic/vote.js#L64-L66

**Comment by MaciejBaj** [comment]
As the change is breaking, we cannot implement it without introducing a hard fork. The issue is included in our [Roadmap](https://lisk.io/roadmap) as part of "Security and Reliability". Suspended for now.

**Comment by shuse2** [comment]
Closing because https://github.com/LiskHQ/lips/blob/master/proposals/lip-0012.md will solve this issue
