### ISSUE TITLE
Inconsistency in transaction vote asset

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-sdk#757]
Related to core, referencing from lisk-js
https://github.com/LiskHQ/lisk-js/issues/334

**Comment by karek314** [comment]
Issue on lisk-js has been closed. As it's core related, here it is
Taking look at [second signature asset calculation](https://github.com/LiskHQ/lisk-js/blob/development/src/transactions/crypto.js#L54) we see that byte buffer is being allocated from hex string public key.

However, when it comes to votes. In my opinion there is inconsistency. Asset byte buffer is allocated as string, not from hex string.

Example - vote addition to delegate `b002f58531c074c7190714523eec08c48db8c7cfc0c943097db1a2e82ed87f84`
produce asset, "votes" with one element array
`"+b002f58531c074c7190714523eec08c48db8c7cfc0c943097db1a2e82ed87f84"`
[here](https://github.com/LiskHQ/lisk-js/blob/development/src/transactions/crypto.js#L87) it's allocated directly into asset buffer as string producing buffer size of 65.

But we simply can create asset buffer from hex string by replacing "+" with "2B" and "-" with "2D" and then assign it same way we assign [here](https://github.com/LiskHQ/lisk-js/blob/development/src/transactions/crypto.js#L54). Not only it will be consistent but smaller, in this case 33 instead 65 (actually size doesn't really matter much in this case as it's used for signature calculation, but still signature body can be smaller).

**Comment by MaciejBaj** [comment]
As the change is breaking, we cannot implement it without introducing a hard fork. The issue is included in our [Roadmap](https://lisk.io/roadmap) as part of "Security and Reliability". Suspended for now.

**Comment by shuse2** [comment]
Vote transaction will be addressed with [LIP-0023](https://github.com/LiskHQ/lips/blob/master/proposals/lip-0023.md)
