### ISSUE TITLE
Update cross chain commands

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#7575]
### Description

- Remove `CCForwardCommand`
- Update `CrossChainTransferCommand` as specified in the [PR](https://github.com/LiskHQ/lips/blob/08935fbff959dd14f1fc0c2b1b64890f904d5eae/proposals/lip-0051.md#cross-chain-token-transfer-messages)

### Acceptance Criteria

- CCForwardCommand src and tests are removed
- Updated CrossChainTransferCommand is unit tested

### Additional Information
- This change requires #7571 and #7572

**Comment by mosmartin** [comment]
@shuse2 `CCForwardCommand` is a class right? (`framework/src/modules/token/cc_commands/cc_forward.ts`)

**Comment by shuse2** [comment]
yes that is a class
