### ISSUE TITLE
Lisk tree `size` needs to be `bigint`

### ISSUE THREAD

**Issue by sitetester** [LiskHQ/lisk-sdk#7608]
### Description

1. While updating schema for interoperability module, I found that we also need to be update `size` field from `number` to `bigint`

- framework/src/modules/interoperability/base_interoperability_store.ts
```
public async appendToInboxTree(chainID: Buffer, appendData: Buffer) {
	const channelSubstore = this.stores.get(ChannelDataStore);
	const channel = await channelSubstore.get(this.context, chainID);
	const updatedInbox = regularMerkleTree.calculateMerkleRoot({
		value: utils.hash(appendData),
		appendPath: channel.inbox.appendPath,
		size: channel.inbox.size, // *
	});
	await channelSubstore.set(this.context as StoreGetter, chainID, {
		...channel,
		inbox: updatedInbox,
	});
}
```

Here `channel.inbox.size` is of type `bigint`, but `size` is of `number` type
- elements/lisk-tree/src/merkle_tree/types.ts
```
export interface MerkleRootInfo {
	readonly value: Buffer;
	readonly appendPath: Buffer[];
	readonly size: number;
}
```

2. We also need to keep in mind that there is `Math.log2(size)` call which accepts only Number
- elements/lisk-tree/src/merkle_tree/utils.ts
```
// 2. Update the append path
let subTreeIndex;
const treeHeight = Math.ceil(Math.log2(size)) + 1;
```

```
  /**
   * Returns the base 2 logarithm of a number.
   * @param x A numeric expression.
   */
  log2(x: number): number;
```

### Motivation
Since schema is updated in `lip-0045.md`, any calls from interoperability module & lisk-tree should be compatible with each other

### Additional Information
- https://github.com/LiskHQ/lips/blob/main/proposals/lip-0045.md#json-schema-2
- https://github.com/LiskHQ/lisk-sdk/issues/7555

**Comment by shuse2** [comment]
We have concluded that we will use tree size as `uint32` so the definition of the LIP will be updated to use `uint32` for the size as well.
This will support the CCM up to 4B, and it will be rather simple upgrade if we need to update to uint64 in the future
