### ISSUE TITLE
Expose testing functionality for command execute()

### ISSUE THREAD

**Issue by emiliolisk** [LiskHQ/lisk-sdk#7632]
### Description

Expose all available testing functionality used for command execute(). 
So far we have identified these as missing: 
- InMemoryPrefixedStateDB
- createGenesisBlockContext
- createBlockHeaderWithDefaults
- createBlockContext

### Acceptance Criteria

- Should have unit tests

**Comment by has5aan** [comment]
`InMemoryPrefixedStateDB` is going to be available through `testing` in `lisk-sdk` upon approval of [PR 7676](https://github.com/LiskHQ/lisk-sdk/pull/7676).

The functions;

- createGenesisBlockContext
- createBlockHeaderWithDefaults
- createBlockContext

are already exported through `testing` object in `lisk-sdk`.
