### ISSUE TITLE
Move repeated tests in mainchain & sidechain endpoint to a common file

### ISSUE THREAD

**Issue by sitetester** [LiskHQ/lisk-sdk#7685]
### Description

Currently we have duplicated test cases in `mainchain/endpoint.spec.ts` & `sidechain/endpoint.spec.ts`
What we need to do is to move them to a common file e.g. base_interoperability_endpoint.spec.ts & test those endpoints either using mainchain or sidechain, since both are extending from single `base_interoperability_endpoint.ts`

### Motivation

Both tests are simply copy past with the only part changing is `sidechainInteroperabilityEndpoint` & `mainchainInteroperabilityEndpoint`

### Additional Information
- lisk-sdk/framework/src/modules/interoperability/base_interoperability_endpoint.ts
- framework/test/unit/modules/interoperability/mainchain/endpoint.spec.ts
- framework/test/unit/modules/interoperability/sidechain/endpoint.spec.ts

**Comment by ishantiw** [comment]
Fixed in #7700
