### ISSUE TITLE
Generator config exist in type and expected in some cases

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#7710]
### Expected behavior
Generator config should be removed

### Actual behavior
https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/state_machine/state_machine.ts#L42-L43
Module `init` should not expect generator config

### Which version(s) does this affect? (Environment, OS, etc...)
6.0.0-alpha.5-

**Comment by ishantiw** [comment]
Related to https://github.com/LiskHQ/lisk-sdk/issues/7728
