### ISSUE TITLE
Inconsistent naming in `forward` method signature

### ISSUE THREAD

**Issue by sitetester** [LiskHQ/lisk-sdk#7721]
### Description

```
public async forward(ccmForwardContext: CCMForwardContext): Promise<ForwardCCMsgResult>
```

1. `CCMForward` & `ForwardCCMsg` don't seem like consistent naming
2. We should avoid `Msg`, since `CCM` is already understood term from LIPs 

### Motivation

All codebase should have consistent naming

### Additional Information
- framework/src/modules/interoperability/mainchain/store.ts

**Comment by shuse2** [comment]
Resolved by #7754
