### ISSUE TITLE
Error: Fail to start controller

### ISSUE THREAD

**Issue by TalhaMaliktz** [LiskHQ/lisk-sdk#7760]
### Expected behavior
After registering the plugin and its related code to the project, the controller should start and the plugin's code should be executed as well.

### Actual behavior
On my branch [191-hello-plugin-v6](https://github.com/LiskHQ/lisk-sdk-examples/tree/191-hello-plugin-v6), After registering the plugin and its related code to the project, the controller fails to start and as a result, the plugin's code becomes inaccessible. The Plugin code works individually on a local project which doesn't have any module.

### Steps to reproduce
Pull branch: [191-hello-plugin-v6](https://github.com/LiskHQ/lisk-sdk-examples/tree/191-hello-plugin-v6)

- `rm -r ~/.lisk/hello_client`  (in case already present on system)

- `npm install --registry https://npm.lisk.com/`

- Update line 84 in`node_modules/lisk-framework/dist-node/plugins/base_plugin.js` to

    -  `this._apiClient = await lisk_api_client_1.createIPCClient(this.appConfig.system.dataPath);`

- ` npm run build`

- `./bin/run start --config config/custom_config.json`

**Result: Controller doesn't start**
```
$ application 3965 hello Loading in-memory plugin
$ application 3965 [err=Channel for module hello is already registered.] Fail to start controller
```

### Which version(s) does this affect? (Environment, OS, etc...)
LiskSDK: `lisk-commander/6.0.0-alpha.5 darwin-arm64 node-v16.18.0`
Project-based on: `6.0.0-alpha.5`
macOS Venture 13

**Comment by shuse2** [comment]
Problem was name duplication on plugin and module.
Application should check the name conflict across module and plugins
