### ISSUE TITLE
Return pomHeights as an object

### ISSUE THREAD

**Issue by sameersubudhi** [LiskHQ/lisk-sdk#7807]
### Description

Currently the response for `pos_getValidator`, `pos_getAllValidators` and `pos_getValidatorsByStake` return `pomHeights: number[];`.
It would be nice if `pomHeights` were of type `{ start: number, end: number }[];` instead.

### Motivation

This information will be used by the wallets to display the users (when trying to stake) if and when their chosen validator gets unbanned.

### Additional Information
- report misbehavior command uses the constant to check the end value, so `end` property should use the same constant to compute the end height

**Comment by bobanm** [comment]
@sameersubudhi, after considering different options with @shuse2, we have decided to leave `pomHeights` property as it is, but introduce a new property `punishmentPeriods`, which contains the array of objects with start and end block heights, as you requested.

This solution does not introduce breaking changes, and it doesn't require us to modify the type of `pomHeights` property, which would be a dirty hack.
