### ISSUE TITLE
validator.validate throws error`TS2775`

### ISSUE THREAD

**Issue by Tschakki** [LiskHQ/lisk-sdk#7809]
### Expected behavior
`validator.validate()` works without error.

### Actual behavior
`validator.validate()` displays error:

 `TS2775: Assertions require every name in the call target to be declared with an explicit type annotation.`

, when the package is imported from the`lisk-sdk` package.
If it is imported from separate package `@liskhq/lisk-validator`, it doesn't display the error for me.

### Steps to reproduce
<img width="922" alt="image" src="https://user-images.githubusercontent.com/1993505/203317290-2340ad0e-ba2b-46e7-93e4-9f4610f06d15.png">

### Which version(s) does this affect? (Environment, OS, etc...)
sdkv6.0.0-alpha.6

**Comment by Incede** [comment]
Tested with `lisk-sdk` versions `v6.0.0-alpha.6` & `v6.0.0-alpha.10` and works fine with both while importing directly from `lisk-sdk` or  `@liskhq/lisk-validator`. 

Apparently the issue was local probably due to an old repository with mis-configured package versions.
