### ISSUE TITLE
Web assembly issue with React-Native

### ISSUE THREAD

**Issue by Balanced02** [LiskHQ/lisk-sdk#7816]
### Expected behavior
- Should encrypt a message with password successfully

### Actual behavior
- Throws an error while calling `Lisk.cryptography.encrypt.encryptMessageWithPassword` function with right arguments

![Screenshot 2022-11-23 at 14 41 20](https://user-images.githubusercontent.com/28750984/203561325-c58cf2b0-473b-443e-a239-86b501a142a3.png)

### Steps to reproduce
- Try encrypting a message on a react-native project

I've tried using these modules to add webassembly to global object on react-native
- [webassemblyjs](https://www.npmjs.com/package/webassemblyjs)
- [react-native-wasm](https://www.npmjs.com/package/react-native-wasm).

**Comment by bobanm** [comment]
Could you please provide more context to help us look into it?
What were the right arguments that you have passed to the function?

**Comment by ishantiw** [comment]
Related issue created on React Native https://github.com/Daninet/hash-wasm/issues/41

**Comment by shuse2** [comment]
Try building https://github.com/Balanced02/BufferIssue, but failed with 
```
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening BufferProject.xcworkspace.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace BufferProject.xcworkspace -configuration Debug -scheme BufferProject -destination id=D0C9D1C4-0C87-4AA6-95DF-2CA8062F2B8C

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES
The following build commands failed:
        Ld /Library/Developer/Xcode/DerivedData/BufferProject-dgbyrlfypdgtqkeskbtqabxqpoov/Build/Products/Debug-iphonesimulator/BufferProject.app/BufferProject normal (in target 'BufferProject' from project 'BufferProject')
(1 failure)

```

Also, it shows some version requirement while doing `yarn`
@Balanced02 could you check the installation process for the sample project?

Also, it would be nice to detail out the error on the issue https://github.com/Daninet/hash-wasm/issues/41 so we can get the help from author as well

**Comment by ClementeSerrano** [comment]
> Related issue created on Hash wasm [Daninet/hash-wasm#41](https://github.com/Daninet/hash-wasm/issues/41)

was already solved on RN 0.70.0 release. we need to debug what's happening with SDK internally

**Comment by ManuGowda** [comment]
@shuse2 the [README](https://github.com/Balanced02/BufferIssue/blob/main/README.md) is up to date now, we tried with @ishantiw to setup and it worked for him.

**Comment by shuse2** [comment]
There were no JavaScript library available which can work in React Native (Android). Therefore, the solution was to use native binding for Android
