### ISSUE TITLE
Error when bootstrapping a new blockchain application with Lisk Commander using `lisk-commander@6.0.0-alpha.7`

### ISSUE THREAD

**Issue by mosmartin** [LiskHQ/lisk-sdk#7848]
### Expected behavior

Successful creation of a Lisk Blockchain App

### Actual behavior

An `Error: Command failed with exit code 127: npm run build` is thrown and the initialization process exits.

### Steps to reproduce

1. install `lisk-commander@6.0.0-alpha.7`
2. `mkdir hello_app && cd hello_app && lisk init`
3. View error stack

### Which version(s) does this affect? (Environment, OS, etc...)

- Node `v16.17.1`
- `lisk-commander@6.0.0-alpha.7`
- MacBook Pro
  - 16-inch, 2021
  - Apple M1 Pro
  - 32 GB Mem
  - OS: Ventura 13.0 (22A380)

**Comment by shuse2** [comment]
Closing, superseded by #7532
