### ISSUE TITLE
Add missing unit tests for the `PoS Module` Validator Registration Command

### ISSUE THREAD

**Issue by mosmartin** [LiskHQ/lisk-sdk#7873]
### Description

Based on the defined test cases, the following tests are missing from the implemented unit tests.

  - `verify()`
      - _params.validatorRegistrationFee != VALIDATOR_REGISTRATION_FEE_
        - Expectation: `Invalid transaction. Throw error at verify step.`
      - _name is longer than MAX_LENGTH_NAME characters long_
        - Expectation: `Invalid transaction. Throw error at verify step.`
      - _name is empty_
        - Expectation: `Invalid transaction. Throw error at verify step.`
      - _There exists already an entry in the name substore with store key trs.params.name_
        - Expectation: `Invalid transaction. Throw error at verify step.`
          
  - `execute()`
    - _Transaction passes verification and registerValidatorKeys function from the Validators module does not throw_

### Motivation

These test will align with defined test cases and ensure complete coverage of the scenarios.

**Comment by shuse2** [comment]
Looking at the [LIP](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0057.md), `name is longer than MAX_LENGTH_NAME characters long` requirement does not exist anymore, but other cases seems still valid

**Comment by mosmartin** [comment]
For the first test `params.validatorRegistrationFee != VALIDATOR_REGISTRATION_FEE` it's been covered by the `should return error if transaction does not have enough balance for the registration fee` test on L302.

For the second test `name is longer than MAX_LENGTH_NAME characters long,` the impl does not exist and I have created an issue [here](https://github.com/LiskHQ/lisk-sdk/issues/8407).

For the fourth test `There exists already an entry in the name substore with store key trs.params.name`, it's been covered by the `should return error if store key name already exists in name store` test on L256
