### ISSUE TITLE
Expose validation for derivation path

### ISSUE THREAD

**Issue by oskarleonard** [LiskHQ/lisk-sdk#7877]
### Description

Expose the validation logic used inside [this function](https://github.com/LiskHQ/lisk-sdk/blob/4cbb44a008699e3169208706f830864d88e38297/elements/lisk-cryptography/src/utils.ts#L49) publicly. 

### Motivation

The derivation path is customisable the FE so it would be great if we could use the same validation as the SDK to determine if it is correct. Right now i have copy pasted that logic from the SDK which means that we have the same validation in two places. 

### Other information

FE issue: https://github.com/LiskHQ/lisk-desktop/pull/4658/files#diff-2172141c00513d409f8b5aab55e0dbf23c2ca9f883cb7bf5c1cef2887d4671bd

**Comment by shuse2** [comment]
the parse function is already exposed, and it can be accessed by `utils` in `cryptography`
