### ISSUE TITLE
Fix `ModuleMetadata` export issue

### ISSUE THREAD

**Issue by nagdahimanshu** [LiskHQ/lisk-sdk#7878]
### Expected behavior

`ModuleMetadata` should be exported correctly from framework.

### Actual behavior
Currently `RootModuleMetadata ` is exported as `ModuleMetadata`

### Which version(s) does this affect? (Environment, OS, etc...)
6.0.0-alpha.7

**Comment by shuse2** [comment]
when UI (app.getMetadata or endpoint system_getMetadata) request the metadata, it will always come with `name` but when developer defines module, they don't need to define `name` for the metadata
