### ISSUE TITLE
Unit test review: Fee module

### ISSUE THREAD

**Issue by ricott1** [LiskHQ/lisk-sdk#7902]
### [module.spec.ts](https://github.com/LiskHQ/lisk-sdk/blob/development/framework/test/unit/modules/fee/module.spec.ts)

- **Missing**: Add 2 tests for verifying that user balance is larger than transaction fee.

### [method.spec.ts](https://github.com/LiskHQ/lisk-sdk/blob/development/framework/test/unit/modules/fee/method.spec.ts)

- **Test case**: `"should fail and log event when ccm is not processing and available fee is less than amount"`: improve description: "[...] when ccm is not processing and available fee is [...]" -> "[...] when ccm is not processing and _transaction_ available fee is [...]".
- **Test case**: `"should deduct amount from available fee when ccm is not processing and available fee is sufficient for amount"`: improve description: "[...] when ccm is not processing and available fee is [...]" -> "[...] when ccm is not processing and _transaction_ available fee is [...]".
- **Missing**: Not sure about this, but should we test with: `methodContext.contextStore.set(CONTEXT_STORE_KEY_CCM_PROCESSING, false);` as well, rather than just the entry not present in the store? (so basically duplicate the last two tests). This depends on how you decide to handle the property in the store, if it can be present with `true` value and not present, or also rpesent with `false` value.

### [cc_method.spec.ts](https://github.com/LiskHQ/lisk-sdk/blob/development/framework/test/unit/modules/fee/cc_method.spec.ts)

- **Missing**: Add test for assign remaining ccm fee to relayer
- **Test case**: `"should unlock transaction fee from sender"`: improve description 'should unlock transaction fee from sender' -> 'should unlock _ccm_ fee from sender'

**Comment by mitsuaki-u** [comment]
This missing test case: "Add test for assign remaining ccm fee to relayer" is not required since the remaining fee is already in the relayer account after unlock and burn. Can you confirm @ricott1 ?
