### ISSUE TITLE
Endpoint `pos_getStaker` throws error on invoke

### ISSUE THREAD

**Issue by nagdahimanshu** [LiskHQ/lisk-sdk#7924]
### Expected behavior

- `pos_getStaker` should work and return stakes for the account with stakes.

### Actual behavior

- when `pos_getStaker` is called, it throws error even for account with stakes
```
Key 7160f868386ff306bfac002e6e2c74b7d4720303f80094dfaeac does not exist
```
### Steps to reproduce

- Run `pos-mainchain`
- Create `pos:stake` transactions 
- Retrieve stakes for the account using `pos_getStaker` endpoint

### Which version(s) does this affect? (Environment, OS, etc...)
6.0.0-alpha.8

**Comment by shuse2** [comment]
```
./bin/run transaction:create pos stake 10000000
 lskffxs3orv2au2juwa69hqtrmpcg9vq78cqbdjr4,1000000000
./bin/run transaction:send 0a03706f7312057374616b6518002080ade2042a20a3f96c50d0446220ef2f98240898515cbba8155730679ca35326d98dcfb680f0321e0a1c0a14f783b43242c6618e42f9537b59c8a41fda2ab9e31080a8d6b9073a40dce55f64e321f7b69ecc0e8944a96194822ef627b0a810a535ca246053f5c2ccaccdadb9212e90a16ce17a592fa3c0603d5d125612a93671fa7a5f95d7938009
./bin/run endpoint:invoke pos_getStaker '{"address": "lske5sqed53fdcs4m9et28f2k7u9fk6hno9bauday"}' 
{"sentStakes":[{"validatorAddress":"lskffxs3orv2au2juwa69hqtrmpcg9vq78cqbdjr4","amount":"1000000000","stakeSharingCoefficients":[]}],"pendingUnlocks":[]}
```

I checked the behavior with above steps, and it seems it is working as expected

**Comment by mosmartin** [comment]
I've tested this on me end and works as well.
