### ISSUE TITLE
Fix `mainchainValidators` length checks in mainchain registration command

### ISSUE THREAD

**Issue by mitsuaki-u** [LiskHQ/lisk-sdk#7947]
### Expected behavior

`mainchainValidators` should have minimum length 1 and maximum length `MAX_NUM_VALIDATORS`

See: https://github.com/LiskHQ/lips/pull/187/commits/3626723611098bc2dfb72059ea27fffd02869c40

### Actual behavior

Currently the schema only allows exact `101` length

### Steps to reproduce

Check mainchain registration command schema

### Which version(s) does this affect? (Environment, OS, etc...)

development

**Comment by ishantiw** [comment]
It will be resolved in #8009
