### ISSUE TITLE
Add check if mainchain ID already exists in chain account store for mainchain registration command

### ISSUE THREAD

**Issue by mitsuaki-u** [LiskHQ/lisk-sdk#7948]
### Expected behavior

For mainchain registration command there should be a check to see if the mainchain ID already exists in chain account data. If it does it should throw an error. 

### Actual behavior

Currently it does not check

### Steps to reproduce

See mainchain registration execute step

### Which version(s) does this affect? (Environment, OS, etc...)

development

**Comment by ishantiw** [comment]
It will be resolved in https://github.com/LiskHQ/lisk-sdk/issues/8009
