### ISSUE TITLE
Verify step in state recovery initialization command is missing params validation

### ISSUE THREAD

**Issue by mitsuaki-u** [LiskHQ/lisk-sdk#7969]
### Expected behavior

We should validate command parameters against the command schema.

### Actual behavior

Schema check is missing in verify step. 

### Steps to reproduce

Check verify logic for state recov. init command

### Which version(s) does this affect? (Environment, OS, etc...)

development

**Comment by ishantiw** [comment]
When creating command context we decode params of a command

Check if the related encode test is available on state machine
https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/state_machine/state_machine.ts

https://github.com/LiskHQ/lisk-sdk/blob/b5dd5bfd6ed2b36eae284ca60a44622168a47adc/framework/src/state_machine/transaction_context.ts#L120-L122
