### ISSUE TITLE
Check for empty cert and inboxUpdate in sidechain CCU update command

### ISSUE THREAD

**Issue by mitsuaki-u** [LiskHQ/lisk-sdk#7979]
### Expected behavior

The following check is missing in the sidechain CCU update command verify hook:

```
certificateBytes = ccu.params.certificate  
   if len(certificateBytes) == 0 and ccu.params.inboxUpdate is empty: # An empty object has all properties set to their default values.
raise  Exception("A cross-chain update must contain a non-empty certificate and/or a non-empty inbox update.")
```

### Actual behavior

This check is missing in verify hook

### Steps to reproduce

Check CCU update logic

### Which version(s) does this affect? (Environment, OS, etc...)

development

**Comment by ishantiw** [comment]
Superseded by #8019
