### ISSUE TITLE
Check if mainchain account exists in sidechain CCU update command

### ISSUE THREAD

**Issue by mitsuaki-u** [LiskHQ/lisk-sdk#7980]
### Expected behavior

The following check is missing in the sidechain CCU update command verify hook:

``
 # The  mainchain account must exist.
	if chainAccount(ccu.params.sendingChainID) does not exist:
	     raise Exception("The mainchain is not registered.")
```

### Actual behavior

This check is missing in verify hook

### Steps to reproduce

Check CCU update logic

### Which version(s) does this affect? (Environment, OS, etc...)

development

**Comment by ishantiw** [comment]
Superseded by #8019
