### ISSUE TITLE
Update `executeCommon` logic used in sidechain CCU update command

### ISSUE THREAD

**Issue by mitsuaki-u** [LiskHQ/lisk-sdk#7982]
### Expected behavior

The `executeCommon` function in the sidechain CCU update command verify hook should contain the following logic:

``
def execute(ccu: Transaction) -> None:
    # Verify certificate signature. We do it here because if it fails, the transaction fails rather than being invalid.
    verifyCertificateSignature(ccu)

    if ccu.params.inboxUpdate is not empty:
        # Initialize the relayer account for the message fee token.
        # This is necessary to ensure that the relayer can receive the CCM fees
        # If the account already exists, nothing is done.
        relayerAddress = sha256(ccu.senderPublicKey)[:ADDRESS_LENGTH]
        messageFeeTokenID = getMessageFeeTokenID(ccu.params.sendingChainID)
        Token.initializeUserAccount(relayerAddress, messageFeeTokenID)

    # Process cross-chain messages in inbox update.
    crossChainMessages = ccu.params.inboxUpdate.crossChainMessages

    # First process basic checks for all CCMs.
    for ccmBytes in crossChainMessages:
        ccmID = sha256(ccmBytes)
        # Set ccmID (instead of the transaction ID) as default topic of this event.
        defaultEventsTopic = ccmID
        # Verify general format. Past this point, we can access ccm root properties.
        try:
            ccm = decode(crossChainMessageSchema, ccmBytes)
        except:
            terminateChain(ccu.params.sendingChainID)
            emitEvent(
                module = MODULE_NAME_INTEROPERABILITY,
                name = EVENT_NAME_CCM_PROCESSED,
                data = {"ccm": EMPTY_CCM, "result": CCM_PROCESSED_RESULT_DISCARDED, "code": CCM_PROCESSED_CODE_INVALID_CCM_DECODING_EXCEPTION},
                topics = [ccu.params.sendingChainID, OWN_CHAIN_ID]
            )
            # In this case, we do not even update the chain account with the new certificate.
            return
        try:
            validateFormat(ccm)
        except:
            terminateChain(ccu.params.sendingChainID)
            ccm.params = EMPTY_BYTES
            emitEvent(
                module = MODULE_NAME_INTEROPERABILITY,
                name = EVENT_NAME_CCM_PROCESSED,
                data = {"ccm": ccm, "result": CCM_PROCESSED_RESULT_DISCARDED, "code": CCM_PROCESSED_CODE_INVALID_CCM_VALIDATION_EXCEPTION},
                topics = [ccm.sendingChainID, ccm.receivingChainID]
            )
            # In this case, we do not even update the chain account with the new certificate.
            return
        try:
            # The CCM must come be directed to the sidechain, unless it was bounced on the mainchain.
            if ownChainAccount.chainID != ccm.receivingChainID:
                raise Exception("CCM is not directed to the sidechain.")
            # Sending and receiving chains must differ.
            if ccm.receivingChainID == ccm.sendingChainID:
                raise Exception("Sending and receiving chains must differ.")
        except:
            terminateChain(ccu.params.sendingChainID)
            emitEvent(
                module = MODULE_NAME_INTEROPERABILITY,
                name = EVENT_NAME_CCM_PROCESSED,
                data = {"ccm": ccm, "result": CCM_PROCESSED_RESULT_DISCARDED, "code": CCM_PROCESSED_CODE_INVALID_CCM_ROUTING_EXCEPTION},
                topics = [ccm.sendingChainID, ccm.receivingChainID]
            )
            # In this case, we do not even update the chain account with the new certificate.
            return

    # Update the context to indicate that now we start the CCM processing.
    ctx.ccmProcessing = True
    for ccmBytes in crossChainMessages:
        ccmID = sha256(ccmBytes)
        # Set ccmID (instead of the transaction ID) as default topic to all events emitted in apply
        defaultEventsTopic = ccmID
        ccm = decode(crossChainMessageSchema, ccmBytes)
        apply(ccu, ccm)
        # We append at the very end. This implies that if the message leads to a chain termination,
        # it is still possible to recover it (because the channel terminated message
        # would refer to an inbox where the message has not been appended yet).
        appendToInboxTree(ccu.params.sendingChainID, ccmBytes)
    # Update the context to indicate that now we stop the CCM processing.
    ctx.ccmProcessing = False

    # Update sidechain validators.
    validatorsUpdate = ccu.params.activeValidatorsUpdate
    if len(validatorsUpdate.blsKeysUpdate) > 0 or len(validatorsUpdate.bftWeightsUpdate) > 0 or validatorsUpdate.bftWeightsUpdateBitmap != EMPTY_BYTES or ccu.params.certificateThreshold != validators(ccu.params.sendingChainID).certificateThreshold:
        updateValidators(ccu)

    # Update last certificate.
    if len(ccu.params.certificate) > 0:
        updateCertificate(ccu)

    # Update partner chain outbox root.
    if ccu.params.inboxUpdate is not empty: # An empty object has all properties set to their default values.
        updatePartnerChainOutboxRoot(ccu)
```

### Actual behavior

The existing logic is missing some checks.

### Steps to reproduce

Check CCU update logic

### Which version(s) does this affect? (Environment, OS, etc...)

development

**Comment by ishantiw** [comment]
Superseded by https://github.com/LiskHQ/lisk-sdk/issues/8017 https://github.com/LiskHQ/lisk-sdk/issues/8018
