### ISSUE TITLE
Terminology change should be applied on `logs` and command's `help`

### ISSUE THREAD

**Issue by TalhaMaliktz** [LiskHQ/lisk-sdk#7994]
### Expected behavior
Based on the recent terminology update in documentation and Lips, `logs` and `help` of commands across SDK should also be checked and updated to the latest terminologies as well. 

### Actual behavior
- The create genesis block command has the term **DPoS** in it which should be updated to PoS.
- Other terminologies to look at are available here: https://github.com/LiskHQ/lips/pull/197

### Which version(s) does this affect? (Environment, OS, etc...)
`lisk-sdk`

**Comment by Incede** [comment]
Checked with `v6.0.0-alpha.11` `logs` and `help` output of `genesis-block:create` command in commander but couldn't find any outdated terminology. Other commands also look up to date in terms of terminology.
