### ISSUE TITLE
Missing implementation in `submit sidechain cross chain update command`

### ISSUE THREAD

**Issue by Phanco** [LiskHQ/lisk-sdk#8008]
### Expected behavior
Implementation of `verify` and `execute` in `SubmitSidechainCrossChainUpdateCommand` should match [LIP-53#SidechainCrossChainUpdate
](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0053.md#sidechaincrosschainupdate)

### Actual behavior
Missing the following checks
```
len(ccu.params.certificate) equals to 0 and ccu.params.inboxUpdate is empty
chainAccount(ccu.params.sendingChainID) not exist
chainAccount(ccu.params.sendingChainID).status equals to CHAIN_STATUS_REGISTERED and len(certificateBytes) equals 0
runs: verifyCertificate(ccu)
runs: verifyValidatorsUpdate(ccu)
runs: verifyPartnerChainOutboxRoot(ccu)
```

### Which version(s) does this affect? (Environment, OS, etc...)
`development`

**Comment by ishantiw** [comment]
Superseded by #8019 #8018
