### ISSUE TITLE
Potential wrong implementation on chain connector plugin

### ISSUE THREAD

**Issue by ricott1** [LiskHQ/lisk-sdk#8022]
- In function `calculateInboxUpdate`: https://github.com/LiskHQ/lisk-sdk/blob/6b5bd088647147905a5781ca1b66a4f6a51ef5ce/framework-plugins/lisk-framework-chain-connector-plugin/src/inbox_update.ts#L37 I am not sure why this works. The ccms to  be included could in general have height smaller than `lastCertificate.height` if the last CCU only contained a partial (or no) inbox update. 
- I don't understand why the `outboxRootWitness` is given by the last ccm to be included https://github.com/LiskHQ/lisk-sdk/blob/6b5bd088647147905a5781ca1b66a4f6a51ef5ce/framework-plugins/lisk-framework-chain-connector-plugin/src/inbox_update.ts#L43

**Comment by ishantiw** [comment]
Fixed in https://github.com/LiskHQ/lisk-sdk/pull/8112
