### ISSUE TITLE
Fix `pos_getValidatorsByStake` endpoint

### ISSUE THREAD

**Issue by nagdahimanshu** [LiskHQ/lisk-sdk#8057]
### Expected behavior
Endpoint `pos_getValidatorsByStake` should return proper response
It should return all validators when called with limit -1

### Actual behavior
Endpoint returns empty validators set.
```
  { "validators": [] }
```
### Steps to reproduce

- Run `pos-mainchain` app
- Retrieve validators using `pos_getValidatorsByStake` endpoint

### Which version(s) does this affect? (Environment, OS, etc...)
6.0.0-alpha.11

**Comment by shuse2** [comment]
After investigating, with the current version i get below result.

```
❯ ./bin/run endpoint:invoke pos_getValidatorsByStake '{"limit": -1}'
{"validators":[{"name":"genesis_69","totalStake":"100000000000","selfStake":"100000000000","lastGeneratedHeight":0,"isBanned":false,"reportMisbehaviorHeights":[],"consecutiveMissedBlocks":364,"commission":0,"lastCommissionIncreaseHeight":0,"sharingCoefficients":[],"address":"lske5sqed53fdcs4m9et28f2k7u9fk6hno9bauday","punishmentPeriods":[]}]}

```

However, condition is `validator must be eligible to be selected`. Therefore, with default config,
* it needs to have weight at least 1000 * 10^8. (this takes the self stake)
* it should not be banned

**Comment by bobanm** [comment]
To give more accurate context, this doesn't seem to be an issue with the endpoint, but some other component.

The endpoint fetches data from `EligibleValidatorsStore`, which is empty. That's why the endpoint response is empty.
