### ISSUE TITLE
Commander's transaction:create without parameters results in TypeError

### ISSUE THREAD

**Issue by has5aan** [LiskHQ/lisk-sdk#8088]
### Expected behavior
Calling `transaction:create` for transactions without parameters should result in transaction creation after inquiring passphrase.

### Actual behavior
Calling `transaction:create` for transactions without parameters result in `TypeError: Cannot read properties of undefined (reading 'properties')` after inquiring passpharse.

### Steps to reproduce
Calling `transaction:create` for transactions without parameters; `unlock` and `claimRewards` on `pos` module are a couple of valid examples.
 
### Which version(s) does this affect? (Environment, OS, etc...)
6.0.0-alpha.12

**Comment by bobanm** [comment]
Perhaps it will help while debugging: Using `--params '{}'` works without throwing an error.
