### ISSUE TITLE
Expose an endpoint to calculate minimumFee for CCM

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#8114]
### Description

- Expose an endpoint to calculate minimumFee for CCM

create endpoint `getMinimumMessageFee` that takes ccm as params
```
return getMinReturnFeePerByte(ccm.sendingChainID) * len(encode(crossChainMessageSchema, ccm))
```
 
### Motivation

- Users should be able to compute message fee required to transfer token cross chain

### Additional Information

Inputs from research team

#### For message fees:

i ) there is no strict *necessary* minimum; so, in general, it can be any value, indeed, even a ccm with message fee set to 0 might be valid, unless there is some "special" fee.

ii)  Special fees are same as in transactions: in particular for token transfer, in case a user account has to be initialized in the receiving chain, the message fee should be at least  USER_ACCOUNT_INITIALIZATION_FEE .

iii) In case something goes wrong in the ccm processing, there is the minimumFee set by bounce
[function](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0045.md#bounce) in order to send the ccm back. This is calculated as minimumFee = getMinReturnFeePerByte(ccm.sendingChainID) * len(encode(crossChainMessageSchema, ccm)) . However this is not mandatory to include, a user might not care about receiving the message back in case of errors.
So from UI perpspective, for transfer crosschain, I guess you want to check in the receiving chain if the recipient account exists and if not ccm.fee should be checked to be at least USER_ACCOUNT_INITIALIZATION_FEE . For the minimumFee required for bounce, I guess this could be shown to the user as "recommended", but having a value smaller than this will not result to failure.

### Additional Information

- https://github.com/LiskHQ/discussions/discussions/18
- https://github.com/LiskHQ/discussions/discussions/25

**Comment by shuse2** [comment]
I think it

> in case a user account has to be initialized in the receiving chain

This cannot be done in one chain. `hasUserAccount` needs to be called in the receiving chain
