### ISSUE TITLE
Unit tests review for validators module (LIP 0044)

### ISSUE THREAD

**Issue by AndreasKendziorra** [LiskHQ/lisk-sdk#8115]
The tests in [this folder](https://github.com/LiskHQ/lisk-sdk/tree/development/framework/test/unit/modules/validators) were reviewed.

# Endpoints

## validateBLSKey

- for the test for [existing BLS key](https://github.com/LiskHQ/lisk-sdk/blob/5e6afb58f4655ac19ca832a2c203bd5418679540/framework/test/unit/modules/validators/endpoint.spec.ts#L44), a valid proof of possession should be used for the given BLS key. Otherwise, the function may return `false` due to invalid proof of possession and not because the key exists already

# Methods

## registerValidatorKeys

- For some tests for which the function is expected to fail, it is tested that the substores does not contain the corresponding entries afterwards. For example [here](https://github.com/LiskHQ/lisk-sdk/blob/5e6afb58f4655ac19ca832a2c203bd5418679540/framework/test/unit/modules/validators/method.spec.ts#L239-L240). For some other tests, (for example [here](https://github.com/LiskHQ/lisk-sdk/blob/5e6afb58f4655ac19ca832a2c203bd5418679540/framework/test/unit/modules/validators/method.spec.ts#L147)) it is not done. It would be good to do it for every test where it is expected to fail.

## setValidatorBLSKey

- [This test](https://github.com/LiskHQ/lisk-sdk/blob/5e6afb58f4655ac19ca832a2c203bd5418679540/framework/test/unit/modules/validators/method.spec.ts#L378) should be improved by using a different BLS key in the [validator account](https://github.com/LiskHQ/lisk-sdk/blob/5e6afb58f4655ac19ca832a2c203bd5418679540/framework/test/unit/modules/validators/method.spec.ts#L386). Otherwise, it is not clear if the test should fail because the BLS key exists in the corresponding validator account in the validators substore or in the registered bls keys substore.
- We should have a test where a validator account with a valid BLS key is already stored in the validators substore, and `setValidatorBLSKey` is called for this account. In contrast to an old version of the LIP, this should NOT fail.
- For tests where the BLS keys have [incorrect length](https://github.com/LiskHQ/lisk-sdk/blob/5e6afb58f4655ac19ca832a2c203bd5418679540/framework/test/unit/modules/validators/method.spec.ts#L463-L485), it would be good to set up a validator account with the given address in the validators substore. Otherwise, it may just fail because the account does not exist.

## setValidatorGeneratorKey

- It would be good to have a test like [this one](https://github.com/LiskHQ/lisk-sdk/blob/5e6afb58f4655ac19ca832a2c203bd5418679540/framework/test/unit/modules/validators/method.spec.ts#L493), but where the new generator key is different from the existing one. And then it should be tested that the generator key in the substore was indeed updated. The existing test, where the new and the old generator key are equal, should be kept though.
- For the [tests where the generator key has an incorrect length](https://github.com/LiskHQ/lisk-sdk/blob/5e6afb58f4655ac19ca832a2c203bd5418679540/framework/test/unit/modules/validators/method.spec.ts#L564-L584), it would be good to set up the validator account with corresponding address before. Otherwise, it may just fail because the account does not exist.

## getGeneratorsBetweenTimestamps

- For [this test](https://github.com/LiskHQ/lisk-sdk/blob/5e6afb58f4655ac19ca832a2c203bd5418679540/framework/test/unit/modules/validators/method.spec.ts#L634):
  - It must also work for even stricter inputs, e.g. lowering the [endTimestamp](https://github.com/LiskHQ/lisk-sdk/blob/5e6afb58f4655ac19ca832a2c203bd5418679540/framework/test/unit/modules/validators/method.spec.ts#L641) to `timePerRound + 2 * blockTime`.
  - The desciption "if ... difference between input timestamps is greater than one round" is not correct. It must be "if difference between timestamps is larger than or equal to the length of one round plus two block slots."
- For [this test](https://github.com/LiskHQ/lisk-sdk/blob/5e6afb58f4655ac19ca832a2c203bd5418679540/framework/test/unit/modules/validators/method.spec.ts#L653):
  - It must also work for even stricter inputs, e.g. lowering the [endTimestamp](https://github.com/LiskHQ/lisk-sdk/blob/5e6afb58f4655ac19ca832a2c203bd5418679540/framework/test/unit/modules/validators/method.spec.ts#L660) to `timePerRound * 2 + 2 * blockTime`.
  - The desciption "if ... difference between input timestamps is greater than 2 rounds" is not correct. It must be "if difference between timestamps is larger than or equal to the length of two rounds plus two block slots."
- The description of [this test](https://github.com/LiskHQ/lisk-sdk/blob/5e6afb58f4655ac19ca832a2c203bd5418679540/framework/test/unit/modules/validators/method.spec.ts#L723) is wrong because the timestamps are equal but not `startSlotNumber` and `endSlotNumber`
- it would be nice to have an additional test that checks which subset of validators is counted and which one is not. For example:
  - `startTimestamp = 99 * blockTime`
  - `endTimestamp = 103 * blockTime`
  - expected result:  the result contains the 3 entries `generatorList[99]`, `generatorList[100]` and `generatorList[0]` with count 1 for each entry
  
## getValidatorKeys

- Maybe not relevant for the tests, but the generator key should have 32 bytes and the BLS key 48 bytes, and not the [other way around](https://github.com/LiskHQ/lisk-sdk/blob/5e6afb58f4655ac19ca832a2c203bd5418679540/framework/test/unit/modules/validators/method.spec.ts#L737-L738). 
  
## registerValidatorWithoutBLSKey

- in [this test](https://github.com/LiskHQ/lisk-sdk/blob/5e6afb58f4655ac19ca832a2c203bd5418679540/framework/test/unit/modules/validators/method.spec.ts#L802), it should also be checked that `setValidatorAccount.blsKey` equals `INVALID_BLS_KEY`

## setValidatorParams

There are no tests yet for this function. It should at least be tested that
-  the _validators params substore_ is updated correctly, and that
- the params are forwarded to the consensus domain

**Comment by has5aan** [comment]
# setValidatorBLSKey

> [This test](https://github.com/LiskHQ/lisk-sdk/blob/5e6afb58f4655ac19ca832a2c203bd5418679540/framework/test/unit/modules/validators/method.spec.ts#L378) should be improved by using a different BLS key in the [validator account](https://github.com/LiskHQ/lisk-sdk/blob/5e6afb58f4655ac19ca832a2c203bd5418679540/framework/test/unit/modules/validators/method.spec.ts#L386). Otherwise, it is not clear if the test should fail because the BLS key exists in the corresponding validator account in the validators substore or in the registered bls keys substore.

The test description `should not be able to set bls key for validator if address exists but bls key is already registered` intends to target duplicate BLS key insertion scenario and usage of a different BLS key would not be correct setup for the scenario.

> For tests where the BLS keys have [incorrect length](https://github.com/LiskHQ/lisk-sdk/blob/5e6afb58f4655ac19ca832a2c203bd5418679540/framework/test/unit/modules/validators/method.spec.ts#L463-L485), it would be good to set up a validator account with the given address in the validators substore. Otherwise, it may just fail because the account does not exist.

The test cases explicitly test for a validation error to be thrown to be thorough.

# setValidatorGeneratorKey
> For the [tests where the generator key has an incorrect length](https://github.com/LiskHQ/lisk-sdk/blob/5e6afb58f4655ac19ca832a2c203bd5418679540/framework/test/unit/modules/validators/method.spec.ts#L564-L584), it would be good to set up the validator account with corresponding address before. Otherwise, it may just fail because the account does not exist.

The test cases explicitly test for a validation error to be thrown to be thorough.
# getValidatorKeys
> Maybe not relevant for the tests, but the generator key should have 32 bytes and the BLS key 48 bytes, and not the [other way around](https://github.com/LiskHQ/lisk-sdk/blob/5e6afb58f4655ac19ca832a2c203bd5418679540/framework/test/unit/modules/validators/method.spec.ts#L737-L738).

This has been updated in a previous commit.

**Comment by AndreasKendziorra** [comment]
>The test description should not be able to set bls key for validator if address exists but bls key is already registered intends to target duplicate BLS key insertion scenario and usage of a different BLS key would not be correct setup for the scenario.

My interpretation of the scenario was that the BLS key is used already by another account, and therefore it should fail. But if this test is about the scenario that this account uses the provided BLS key, then it is correct. But then I would say another test is needed for the scenario I described.
