### ISSUE TITLE
Transaction with command claimRewards fails on execution

### ISSUE THREAD

**Issue by Incede** [LiskHQ/lisk-sdk#8118]
### Expected behavior
Command `claimRewards` should transfer claimable rewards to a staker.

### Actual behavior
Fails on `commandExecution`

### Steps to reproduce
Submit a transaction with command `claimRewards` from a staker with non-zero claimable rewards.
Check event data for `commandExecutionResult` for the block where transaction is included

### Which version(s) does this affect? (Environment, OS, etc...)
development

**Comment by shuse2** [comment]
- internalMethod.addDependencies is not called in the module
- `RewardsAssignedEvent` is not registered in the module

Also, there was edge case locked token for the reward and computed reward had difference by 1 beddow and fail

**Comment by shuse2** [comment]
Initialization is resolved in https://github.com/LiskHQ/lisk-sdk/pull/8123.

However, the computation seems to be off in some cases.

* locked amount for reward and claimable reward hard 1 difference and resulted in error as mentioned above
* staked sharing coefficient becomes bigger than voter sharing coefficient in some case
