### ISSUE TITLE
Endpoints not registered to the bus

### ISSUE THREAD

**Issue by sameersubudhi** [LiskHQ/lisk-sdk#8129]
### Expected behavior
The following endpoints should be registered to the bus and must be invocable:

```
dynamicReward_getInflationRate
generator_getForgingStatus
generator_updateForgingStatus
```

### Actual behavior
Invoking them results in error:

```
{"error":{"message":"Request 'dynamicReward_getInflationRate' is not registered to bus."}}
```

### Steps to reproduce
- Start Lisk Core v4.0.0-alpha.11
  - rm -rf ~/.lisk; ./bin/run start -n devnet --api-ipc -l info
- On a separate terminal, run:
  - ./bin/run endpoint:invoke dynamicReward_getInflationRate

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk SDK v6.0.0-alpha.14

**Comment by shuse2** [comment]
@sameersubudhi 
the name is changed to 
* `dynamicReward_getInflationRate` => `dynamicReward_getAnnualInflation`
* `generator_getForgingStatus` => `generator_getStatus`
* generator_updateForgingStatus => `generator_updateStatus`

**Comment by sameersubudhi** [comment]
Based on the comment, we created the following issue to update the endpoints in Lisk Service: https://github.com/LiskHQ/lisk-service/issues/1502.

Closing this issue as it is not valid anymore.
