### ISSUE TITLE
Unit test Review: Token module

### ISSUE THREAD

**Issue by gkoumout** [LiskHQ/lisk-sdk#8134]
**NOTE:** The review was done on Feb 9, therefore for each file it considers the version at that time (mainly while specifying line numbers). Since several modifications happened since then, a link to the version considered at the time of review is added. Nevertheless, I might have missed some versions, so I suggest being careful to consider the corresponding version while addressing the unit test reviews. 

### [commands/transfer.spec.ts](https://github.com/LiskHQ/lisk-sdk/blob/development/framework/test/unit/modules/token/commands/transfer.spec.ts) 

 - Tests of line 164 and 217 look equivalent to me, not sure if they are intended to cover different cases

### [commands/transfer_cross_chain.spec.ts](https://github.com/LiskHQ/lisk-sdk/blob/development/framework/test/unit/modules/token/commands/transfer_cross_chain.spec.ts)

[Version at time of review](https://github.com/LiskHQ/lisk-sdk/blob/9784630c994c883ee7fd8035348d8ea91fe8fa1a/framework/test/unit/modules/token/commands/transfer_cross_chain.spec.ts)

 - In the `verify` function, add check for the length of `messageFeeTokenID`, to make sure that it is a valid tokenID (e.g., in line 251 after other schema checks)
 - Another missing case in `verify` is about balances. Need to check the case where `messageFeeTokenID = tokenID` and the following holds: `availableBalance > amount`, `availableBalance > messageFee`, but `availableBalance < amount + messageFee`. 
 - Line 333: I am not sure that this test works as intended and that it will fail given this input.
 - Line 461: `interoperability.send()` does not have a parameter `status` anymore, needs to be updated (same holds for line 526, need to update also the implementation).
 
### [cc_commands/cc_transfer.spec.ts](https://github.com/LiskHQ/lisk-sdk/blob/development/framework/test/unit/modules/token/cc_commands/cc_transfer.spec.ts)

[Version at time of review](https://github.com/LiskHQ/lisk-sdk/blob/9784630c994c883ee7fd8035348d8ea91fe8fa1a/framework/test/unit/modules/token/cc_commands/cc_transfer.spec.ts)

- Line 127: More cases for validation failure: `senderAddress`, `recipientAddress`, length of `data`.
- line 279: I would include overall 3 cases in cases token is native to own chain: i) escrow does not exist ii) escrow exists but amount is not enough iii) escrow exists and amount is enough (success).
- In `verify()` missing check for `ccm.status > MAX_RESERVED_ERROR_STATUS`. 
- test of line 330 seems the same as the one of `verify`, not sure is needed.
- line 487 - 536: I am not sure that this test indeed checks that sender and recipient are swapped.
- line 730: This case is checked in the fee module, I guess this test is outdated and should be removed.

### [stores/supported_tokens.spec.ts](https://github.com/LiskHQ/lisk-sdk/blob/development/framework/test/unit/modules/token/stores/supported_tokens.spec.ts)

[Version at time of review](https://github.com/LiskHQ/lisk-sdk/blob/edddfc74785aee42e918d48cdae3c7073c97e68a/framework/test/unit/modules/token/stores/supported_tokens.spec.ts)

 - line 53: Missing test for `isSupported()`: add check that it returns True if all tokens are supported.
 - line 126: Not clear what "chain ID is LSK" means.
 - line 148: Could add explicit check that the entry in the store corresponding to this chain is the empty list.
 - line 192: Missing test: in case the token is already supported, the execution succeeds with no state change.
 - line 238: Add check that in case token is LSK then an error is thrown.
 - line 269: In case multiple tokens from a chain are supported, there are two cases (not clear which one is tested here, but we should test both): i) if `tokenID` is not supported, then no change occurs ii) if `tokenID` is supported then the entry is removed from the substore (e.g., if 3 tokens from this chain were supported before, now should be 2).
 - line 289: In case support does not exist, there is no failure, just no state change happens.
 - line 305: seems to be the exact same test as in line 259. Make sure that there was no intention to cover separate cases, otherwise remove this test.

###  [stores/user.spec.ts](https://github.com/LiskHQ/lisk-sdk/blob/development/framework/test/unit/modules/token/stores/user.spec.ts)

[Version at time of review](https://github.com/LiskHQ/lisk-sdk/blob/380ecb39218945f0ca35547f9a2aa79be831e649/framework/test/unit/modules/token/stores/user.spec.ts)

 - I guess the function `addAvailableBalanceWithCreate` and corresponding tests should be removed. 

### [cc_method.spec.ts](https://github.com/LiskHQ/lisk-sdk/blob/development/framework/test/unit/modules/token/cc_method.spec.ts)

[Version at time of review](https://github.com/LiskHQ/lisk-sdk/blob/9784630c994c883ee7fd8035348d8ea91fe8fa1a/framework/test/unit/modules/token/cc_method.spec.ts)

- line 304: In this test I think there is a typo.  I guess for this test you need in the `ccm` to set `module: Interoperability`, since this the module containing `CROSS_CHAIN_COMMAND_NAME_REGISTRATION`
- line 304: ccm command `transfer` is not special and same behavior should be expected for all Cross-Chain commands. I suggest adding a similar test with `crossChainCommand: CROSS_CHAIN_COMMAND_NAME_TRANSFER` and `module: tokenModule.name` and expect the exact same behavior on escrows.

### [endpoint.spec.ts](https://github.com/LiskHQ/lisk-sdk/blob/development/framework/test/unit/modules/token/endpoint.spec.ts)

[Version at time of review](https://github.com/LiskHQ/lisk-sdk/blob/308f100217ee6f72efbb2ba558e2f57d3ffce9af/framework/test/unit/modules/token/endpoint.spec.ts)

- line 235: check also that an error is thrown if the token is non-native.
- line 317: Missing cases to check explicitly: i) non-native token, but all tokens from its native chain are supported (return `True`) ii) native token (return `True`) iii) LSK (return `True`).
- Line 442: Missing test: `hasEscrowAccount` returns always False if tokenID is native to own_chain.

### [init_genesis_state_fixture.ts](https://github.com/LiskHQ/lisk-sdk/blob/development/framework/test/unit/modules/token/init_genesis_state_fixture.ts)

[Version at time of review](https://github.com/LiskHQ/lisk-sdk/blob/dee896c3dcb5484406a41bbf2a311c2130c6fe06/framework/test/unit/modules/token/init_genesis_state_fixture.ts)

- Missing checks: entries of all arrays are according to schema
- Missing check: In `userSubstore` there should not be duplicate values for pairs `(address, tokenID)`.
- Missing check: for entries with the same `address`,  `userSubstore` is sorted by lexicographic order of `tokenID` .
- line 347,364: Those two tests are the same, I guess in the one we should be checking uniqueness and the second lexicographic order, so one of the two should contain two different tokenIDs, placed in the wrong order. 

### [method.spec.ts](https://github.com/LiskHQ/lisk-sdk/blob/development/framework/test/unit/modules/token/method.spec.ts)

[Version at time of review](https://github.com/LiskHQ/lisk-sdk/blob/9784630c994c883ee7fd8035348d8ea91fe8fa1a/framework/test/unit/modules/token/method.spec.ts)

- line 230: For initializeToken() function it would be good to check the case where tokenID has invalid size but the chainID part is correct (e.g., size 7 instead of 8 but first 4 correspond correctly to the chainID, so it looks like a native token). Same for the next test for mint function (starting line 259).
- line 754: Token should be native either in sending or receiving chain. Make sure that if LSK gets transferred between sidechains, an error is thrown.

**Comment by has5aan** [comment]
### method.spec.ts

> line 230: For initializeToken() function it would be good to check the case where tokenID has invalid size but the chainID part is correct (e.g., size 7 instead of 8 but first 4 correspond correctly to the chainID, so it looks like a native token). Same for the next test for mint function (starting line 259).

Added the issue #8424.

**Comment by shuse2** [comment]
> > Line 442: Missing test: hasEscrowAccount returns always False if tokenID is native to own_chain.
> 
> Perhaps, a new issue is necessary to add the check to throw for native token and relevant test, current implementation has all the relevant tests? @shuse2

For this, I think relevant test is there. the native tokens will never be in the escrow account, so it will always return false
