### ISSUE TITLE
Unit test review genesis block processing (LIP 0060)

### ISSUE THREAD

**Issue by AndreasKendziorra** [LiskHQ/lisk-sdk#8136]
## Header

- Test for [`signature` property](https://github.com/LiskHQ/lisk-sdk/blob/de09b745a369c0970db7a8db2e5980534a1a036a/elements/lisk-chain/test/unit/block_header.spec.ts#L287): The requirement is NOT that the property is empty. Instead, the property should not even exist. So, this test should fail **due the existence** of the `signature` property. Moreover, genesis block validation should also fail if it has a signature property set to empty bytes.
- A test is missing where `generatorAddress` is NOT equal to `0x00..00` in which case the processing is expected to fail.
- Tests for the property `impliesMaxPrevotes` are missing (for both values `True` and `False`).
- Test for invalid `maxHeightGenerated` is missing.
- Tests for invalid `aggregateCommit.height`, `aggregateCommit.aggregationBits` and `aggregateCommit.certificateSignature` are missing.
- There is no test for the `stateRoot` property. In particular, there is no test that expects that genesis block processing fails if the value of `header.stateRoot` in incorrect.
- If [these tests](https://github.com/LiskHQ/lisk-sdk/blob/de09b745a369c0970db7a8db2e5980534a1a036a/framework/test/unit/engine/consensus/consensus.spec.ts#L1019-L1041) do not cover the `eventRoot` for genesis blocks (I'm not sure about it), then the tests for `eventRoot` are missing.
- If [these tests](https://github.com/LiskHQ/lisk-sdk/blob/de09b745a369c0970db7a8db2e5980534a1a036a/framework/test/unit/engine/consensus/consensus.spec.ts#L933-L980) do not cover the `validatorsHash` for genesis blocks (I'm not sure about it), then the tests for `validatorsHash ` are missing.

## Assets

- There seems to be no test to ensure that block processing fails if `asset.module` does not refer to a registered module for any asset `asset` in the block.

**Comment by shuse2** [comment]
> Test for [signature property](https://github.com/LiskHQ/lisk-sdk/blob/de09b745a369c0970db7a8db2e5980534a1a036a/elements/lisk-chain/test/unit/block_header.spec.ts#L287): The requirement is NOT that the property is empty. Instead, the property should not even exist. So, this test should fail due the existence of the signature property. Moreover, genesis block validation should also fail if it has a signature property set to empty bytes.

I think the decoding is for block header, so the signature property should exist but empty bytes?

> Tests for invalid aggregateCommit.height, aggregateCommit.aggregationBits and aggregateCommit.certificateSignature are missing.

https://github.com/LiskHQ/lisk-sdk/blob/de09b745a369c0970db7a8db2e5980534a1a036a/elements/lisk-chain/test/unit/block_header.spec.ts#L248-L285

> If [these tests](https://github.com/LiskHQ/lisk-sdk/blob/de09b745a369c0970db7a8db2e5980534a1a036a/framework/test/unit/engine/consensus/consensus.spec.ts#L1019-L1041) do not cover the eventRoot for genesis blocks (I'm not sure about it), then the tests for eventRoot are missing.

The same function is called both on normal block and genesis block, so it should cover both scenarios

**Comment by AndreasKendziorra** [comment]
> I think the decoding is for block header, so the signature property should exist but empty bytes?

In the [LIP](https://github.com/LiskHQ/lips/blob/db2b893f2d062cbc4bec06391f0ebc9c56102356/proposals/lip-0060.md?plain=1#L123), we say that the schema for _unsigned block header_ must be used.


> https://github.com/LiskHQ/lisk-sdk/blob/de09b745a369c0970db7a8db2e5980534a1a036a/elements/lisk-chain/test/unit/block_header.spec.ts#L248-L285

True. I'm not sure how I could miss them.

> The same function is called both on normal block and genesis block, so it should cover both scenarios

OK, sounds good.

**Comment by shuse2** [comment]
> > I think the decoding is for block header, so the signature property should exist but empty bytes?
> 
> In the [LIP](https://github.com/LiskHQ/lips/blob/db2b893f2d062cbc4bec06391f0ebc9c56102356/proposals/lip-0060.md?plain=1#L123), we say that the schema for unsigned block header must be used.

Ah ok, then maybe in this case adjusting the LIP maybe better. Otherwise, we will need to have different `Block` definition for genesis block specifically.

**Comment by AndreasKendziorra** [comment]
> > > I think the decoding is for block header, so the signature property should exist but empty bytes?
> > 
> > 
> > In the [LIP](https://github.com/LiskHQ/lips/blob/db2b893f2d062cbc4bec06391f0ebc9c56102356/proposals/lip-0060.md?plain=1#L123), we say that the schema for unsigned block header must be used.
> 
> Ah ok, then maybe in this case adjusting the LIP maybe better. Otherwise, we will need to have different `Block` definition for genesis block specifically.

Ok. I create the issue and will create the PR next Monday.
