### ISSUE TITLE
Create exception for mainchain registration command in transaction

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#8152]
### Description

According to [LIP0043:mainchainRegistrationCommand](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0043.md#mainchain-registration-command), we need to create an exception where mainchain registration doesn't require fee and should be prioritized by a validator to include it in the block. 

### Acceptance Criteria

- Should pass relevant unit tests
- Should include a `mainchainRegistration` transaction without fee

**Comment by shuse2** [comment]
Closing this issue since this is no longer valid
