### ISSUE TITLE
Inconsistent names for store, endpoint and schema in interoperability module

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#8153]
### Description

- ChainAccount is updated to ChainData and also relevant schema, store and endpoint name
- ChannelData should have relevant schema, store and endpoint name

### Which version(s) does this affect? (Environment, OS, etc...)

`v6.0.0-alpha.14`

**Comment by shuse2** [comment]
Closing this issue since this is no longer valid
