### ISSUE TITLE
Unit Test Review: Random Module

### ISSUE THREAD

**Issue by gkoumout** [LiskHQ/lisk-sdk#8154]
**NOTE:** The review was done on Feb 15, therefore in case the file gets updated after that, plz make sure that you are checking the appropriate version (so that line numbers are valid..).

### [method.spec.ts](https://github.com/LiskHQ/lisk-sdk/blob/development/framework/test/unit/modules/random/method.spec.ts)

- Line 295: I don't know where value 1000 came from. I guess it should be bounded by the maximum size of `validatorReveals` array (I guess implementation needs also to be updated [here](https://github.com/LiskHQ/lisk-sdk/blob/f45f5fa24858b133841953cbe61286531391e7ff/framework/src/modules/random/utils.ts#L76)).
- Tests of lines 322, 344, 366, 388: There was a [PR](https://github.com/LiskHQ/lips/commit/345afc86e79806d48d869a5af5386dd644e91787) fixing a logic error in `getRandomBytes` function which does not seem to have been incorporated neither in the implementation nor in unit tests. For the implementation, [line 87 of random/utils.ts](https://github.com/LiskHQ/lisk-sdk/blob/f45f5fa24858b133841953cbe61286531391e7ff/framework/src/modules/random/utils.ts#L87) should be modified to replace "<=" by "<" (also I think it could be implemented more efficiently given that validatorsReveal array is sorted by height..). If this change is done, then for all aforementioned tests cases, `numberOfSeeds` should be increased by 1 in order to expect the same outcome. 
- Tests of lines 322, 344, 366, 388 assume that function [bitwiseXOR](https://github.com/LiskHQ/lisk-sdk/blob/f45f5fa24858b133841953cbe61286531391e7ff/framework/src/modules/random/utils.ts#L106) is correctly implemented. Although it is simple, it would be good to check that it works as intended.
- line 426: I don't see where function `generateRandomSeeds` is implemented.

### Other Comments

[getSeedRevealValidity](https://github.com/LiskHQ/lisk-sdk/blob/f45f5fa24858b133841953cbe61286531391e7ff/framework/src/modules/random/utils.ts#L41) could be implemented more efficiently by making use of the fact that `validatorsReveal` is ordered according to height (same as in [the implementation of `isSeedValidInput`](https://github.com/LiskHQ/lisk-sdk/blob/f45f5fa24858b133841953cbe61286531391e7ff/framework/src/modules/random/utils.ts#L20)).

**Comment by bobanm** [comment]
To make PRs more focused, this issue will focus only on updating the protocol change logic. The changes are covered by PR #8570.

> line 426: I don't see where function generateRandomSeeds is implemented.

Indeed, the `generateRandomSeeds` as the name of test suite is inconsistent, as there is no function with that name. I have renamed the test suite into `getRandomBytes from protocol specs`.

I've created separate issues for the remaining points from this issue:

> Line 295: I don't know where value 1000 came from. I guess it should be bounded by the maximum size of validatorReveals array (I guess implementation needs also to be updated [here](https://github.com/LiskHQ/lisk-sdk/blob/f45f5fa24858b133841953cbe61286531391e7ff/framework/src/modules/random/utils.ts#L76)).

Remove limit check for `numberOfSeeds` in `getRandomSeed()` #8574 

> Tests of lines 322, 344, 366, 388 assume that function [bitwiseXOR](https://github.com/LiskHQ/lisk-sdk/blob/f45f5fa24858b133841953cbe61286531391e7ff/framework/src/modules/random/utils.ts#L106) is correctly implemented. Although it is simple, it would be good to check that it works as intended.

Add unit test for Random module `bitwiseXOR()` #8568 

> [getSeedRevealValidity](https://github.com/LiskHQ/lisk-sdk/blob/f45f5fa24858b133841953cbe61286531391e7ff/framework/src/modules/random/utils.ts#L41) could be implemented more efficiently by making use of the fact that validatorsReveal is ordered according to height (same as in [the implementation of isSeedValidInput](https://github.com/LiskHQ/lisk-sdk/blob/f45f5fa24858b133841953cbe61286531391e7ff/framework/src/modules/random/utils.ts#L20)).

Improve performance of Random module `getSeedRevealValidity()` function #8578
