### ISSUE TITLE
Create sending and receiving chain client classes in chain connector

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#8175]
### Description

Create sending and receiving chain client classes in chain connector that can encapsulate certain functions and RPC names that can improve usability of these clients and simplify it in the plugin class.
 
We can have a class SendingChainClient and ReceivingChainClient where we can encapsulate certain functions and simply use them like,
`receivingChainClient.getLastCertificate()`
`sendingChainClient.getOwnAccount()`

### Acceptance Criteria

 - Should have all the unit tests and passing

### Additional Information

- https://github.com/LiskHQ/lisk-sdk/pull/8112#discussion_r1114326220

**Comment by shuse2** [comment]
Closing this issue since this is no longer valid
