### ISSUE TITLE
Unit test review: Interoperability cross-chain commands

### ISSUE THREAD

**Issue by ricott1** [LiskHQ/lisk-sdk#8178]
### [Registration CCM](https://github.com/LiskHQ/lisk-sdk/tree/development/framework/test/unit/modules/interoperability/base_cc_commands/registration.spec.ts)
- The `minReturnFeePerByte` property is missing from the ccm. The relative checks in the verification are missing.

### [Sidechain terminated CCM](https://github.com/LiskHQ/lisk-sdk/blob/development/framework/test/unit/modules/interoperability/sidechain/cc_commands/sidechain_terminated.spec.ts)

- In general, the implementation does not follow the LIP, so the execution tests are a bit off. They should be more similar to those of channel terminated.
- Verification is tested properly.

**Comment by mitsuaki-u** [comment]
After review of code the tests required are already implemented.
