### ISSUE TITLE
Add proper calculation for ccm fee for the bounce function unit tests

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#8195]
### Description

- Relating to the [comment](https://github.com/LiskHQ/lisk-sdk/pull/8170#discussion_r1117043402), we have not added a calculation of ccm fee after we call the bounce function in the tests.
- Add something like `(context.ccm.fee - (MIN_FEE_PER_BYTE * CCM_BYTES_LENGTH))`to explain why addToOutbox was called with the expected ccm fee.

### Which version(s) does this affect? (Environment, OS, etc...)

`v6.0.0-alpha.14`

**Comment by Phanco** [comment]
Digging down into this issue.

After the LIP update [LIP#405](https://github.com/LiskHQ/lips/pull/405) and the corresponding code update https://github.com/LiskHQ/lisk-sdk/pull/8765, the fee is currently 0. 

@ishantiw I think this issue can be closed.

**Comment by ishantiw** [comment]
@Phanco Event after the LIP update, I think the tests are still prone to allow a bug.
The problem is that there is no explanation of message fee, that why `fee: BigInt(100000000000)` should pass and why `fee: BigInt(1)` should fail, by just giving unreasonably high and low values. These values should be calculated from the sample CCM used in the test in order to have these tests completely automated. For ex, if we have incorrect `const minFee = minReturnFeePerByte * BigInt(ccmSize) - randomValue;` code in source but in test it will still pass assertion for values `fee: BigInt(100000000000)` and `fee: BigInt(1)`

In test https://github.com/LiskHQ/lisk-sdk/blob/dc47a3f92ae7f30e3db8982f3fffb8f2ec481836/framework/test/unit/modules/interoperability/base_cross_chain_update_command.spec.ts#L1537, we simply give the lowest fee but without any explanation of this magic value 
https://github.com/LiskHQ/lisk-sdk/blob/dc47a3f92ae7f30e3db8982f3fffb8f2ec481836/framework/test/unit/modules/interoperability/base_cross_chain_update_command.spec.ts#L1539-L1543

Here, we can possibly calculate minFee for a CCM, have it in general for all the test and only for this test we can do something like `minFee - BigInt(1)` and it should fail and log event discarded.

**Comment by Phanco** [comment]
> @Phanco Event after the LIP update, I think the tests are still prone to allow a bug. The problem is that there is no explanation of message fee, that why `fee: BigInt(100000000000)` should pass and why `fee: BigInt(1)` should fail, by just giving unreasonably high and low values. These values should be calculated from the sample CCM used in the test in order to have these tests completely automated. For ex, if we have incorrect `const minFee = minReturnFeePerByte * BigInt(ccmSize) - randomValue;` code in source but in test it will still pass assertion for values `fee: BigInt(100000000000)` and `fee: BigInt(1)`
> 
> In test
> 
> https://github.com/LiskHQ/lisk-sdk/blob/dc47a3f92ae7f30e3db8982f3fffb8f2ec481836/framework/test/unit/modules/interoperability/base_cross_chain_update_command.spec.ts#L1537
> 
> , we simply give the lowest fee but without any explanation of this magic value
> https://github.com/LiskHQ/lisk-sdk/blob/dc47a3f92ae7f30e3db8982f3fffb8f2ec481836/framework/test/unit/modules/interoperability/base_cross_chain_update_command.spec.ts#L1539-L1543
> 
> Here, we can possibly calculate minFee for a CCM, have it in general for all the test and only for this test we can do something like `minFee - BigInt(1)` and it should fail and log event discarded.

Make sense, will work in it 👍 Thank you
