### ISSUE TITLE
Sidechain client CLI has depreciated terminology.

### ISSUE THREAD

**Issue by TalhaMaliktz** [LiskHQ/lisk-sdk#8196]
### Expected behavior
The CLI should have `system` instead of `node` 
![pos](https://user-images.githubusercontent.com/13951043/221502576-b26e6c6b-b462-4e5f-8eed-271ba0447872.jpg)

### Actual behavior
The CLI has `node` instead of `system`
![hc](https://user-images.githubusercontent.com/13951043/221502715-606e2642-0996-434f-9e12-39e067a7c8c3.jpg)

### Steps to reproduce

- Create a sidechain client based on `alpha.14`
- `./bin/run `

### Which version(s) does this affect? (Environment, OS, etc...)
 `alpha.14`

**Comment by Incede** [comment]
The terminology in `lisk-sdk` follows the expected beahviour. Apparently the issue seems to be coming from a [different](https://github.com/LiskHQ/lisk-sdk-examples) repository, which is also indicative from the screenshot in `Actual behaviour`.
