### ISSUE TITLE
CCU sending fails when a cross chain transfer is sent from sidechain to another sidechain with blockTime 10 secs

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#8386]
### Expected behavior

CCU should be sent when a crossChainTransfer is done from one sidechain to another for different blockTimes

### Actual behavior

CCU sending fails when a cross chain transfer is sent from sidechain to another sidechain with blockTime 10 secs but works when blockTime is 5 secs

### Steps to reproduce

`Send a ccTransfer from sidechain1 to sidechain2`

### Which version(s) does this affect? (Environment, OS, etc...)

`v6.0.0-beta.0`

**Comment by shuse2** [comment]
Resolved by #8387
