### ISSUE TITLE
lisk-client not usable in a React Typescript application (v6.beta)

### ISSUE THREAD

**Issue by tomploem** [LiskHQ/lisk-sdk#8438]
### Expected behavior

In the [example documentation](https://lisk.com/documentation/beta/integrate-blockchain/integrate-ui/index.html) it is mentioned that `@liskhq/lisk-client/browser` can be used to integrate a SDK project into your frontend.  

### Actual behavior

When using Typescript, this import does not work and can't be resolved to the dist-browser folder 

### Steps to reproduce

1. Install the [hello_world demo app](https://github.com/LiskHQ/lisk-sdk-examples/tree/development/tutorials/hello)
2. Change the `"@liskhq/lisk-client": "^6.0.0-alpha.14"` to the latest beta flag
3. Add Typescript to the project (tsconfig.json & dependencies)
4. Run the application

### Which version(s) does this affect? (Environment, OS, etc...)

- OS Venture 13.1

**Comment by tomploem** [comment]
While the import `@liskhq/lisk-client` works, the import `@liskhq/lisk-client/browser` used in the frontend examples is still not possible for typescript projects

**Comment by mosmartin** [comment]
Hi @tomploem, I've tried to reproduce the issue using the steps you provided and it is working. I 

1. updated the `lisk-client` lib to `"@liskhq/lisk-client": "^6.0.0-beta.1"`
2. installed `ts` and other dependencies
3. initialized `tsconfig`

and tested the demo app and is working as expected.

I'd be happy to assist further on this issue.
