### ISSUE TITLE
Invalid Argon2id memory parameter

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#8450]
### Expected behavior
default memory size should be `2097152` instead of `2024`. However, if the value cannot be used with the [issue](https://github.com/Daninet/hash-wasm/issues/40), `2097121` should be used instead

### Actual behavior
https://github.com/LiskHQ/lisk-sdk/blob/89e7504ef5eb6183aefe576a93be3d6052e56038/elements/lisk-cryptography/src/encrypt.ts#L27-L29

* 2 GiB should be 2048
* Input to the argon2id for hash-wasm should be in kB

### Which version(s) does this affect? (Environment, OS, etc...)
6.0.0-beta.0-

**Comment by mosmartin** [comment]
The mem value that worked during testing is `2097023`. Any value greater than this failed.

Env
`Apple M1 Pro` | `32 GB`
