### ISSUE TITLE
Message verification command fails on verification

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#8495]
### Expected behavior

MessageRecoveryCommand's verification of inclusion proof on outboxRoot is using incorrect parameters. Query data should not be pre-hashed.

### Actual behavior

MessageRecoveryCommand's verify parameters are pre-hashed.

### Steps to reproduce

Submit messageRecovery transaction and it will fail with `Message recovery proof of inclusion is not valid`

### Which version(s) does this affect? (Environment, OS, etc...)

`6.0.0-beta.1`

**Comment by mitsuaki-u** [comment]
Investigation showed that `verifyDataBlock` is correct as according to the LIP and there was no problem with pre-hashing the inputs to the function. Furthermore the logic for `appendToOutbox` was checked with no errors. Further QA reproduction of this issue is required.

**Comment by mitsuaki-u** [comment]
The function used `verifyDataBlock` was found to be correct as per LIP

**Comment by mitsuaki-u** [comment]
Verification working in unit tests. Further testing required on running network.
