### ISSUE TITLE
validator.validate has type void

### ISSUE THREAD

**Issue by tomploem** [LiskHQ/lisk-sdk#8526]
### Expected behavior

In the docs under section [creating transactions](https://lisk.com/documentation/integrate-blockchain/create-tx-offline.html#creating-and-signing-the-transaction) **transactionErrors** should be typed so that **length** and the spread operation is available with Typescript

### Actual behavior

<img width="1052" alt="image" src="https://github.com/LiskHQ/lisk-sdk/assets/12698415/bf9a0227-3cc3-4a9d-bd6e-eb674f3f476b">

### Steps to reproduce

Create a local project with Typescript and import the code given in the Lisk docs

**Comment by shuse2** [comment]
This is problem in the documentation than Lisk SDK.
the new usage should be
```
validator.validate<SomeExpectedType>(schema, object)
```
and if it does not match the schema, it will throw. and the object will be typed as `SomeExpectedType` after this call
