### ISSUE TITLE
Lack of schema validation in certificate schema in multiple places

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#8551]
### Description

The certificate schema is decoded but not validated in several locations. Note that the LIP in most cases specify that this validation should be present, but not in all cases. This means that both the code and the LIP should be updated to reflect each other. The problematic locations are,

- https://github.com/LiskHQ/lisk-sdk/blob/89e7504ef5eb6183aefe576a93be3d6052e56038/framework/src/modules/interoperability/mainchain/commands/submit_mainchain_cross_chain_update.ts#L270
- https://github.com/LiskHQ/lisk-sdk/blob/89e7504ef5eb6183aefe576a93be3d6052e56038/framework/src/modules/interoperability/utils.ts#L268
- https://github.com/LiskHQ/lisk-sdk/blob/89e7504ef5eb6183aefe576a93be3d6052e56038/framework/src/modules/interoperability/utils.ts#L216
- https://github.com/LiskHQ/lisk-sdk/blob/89e7504ef5eb6183aefe576a93be3d6052e56038/framework/src/modules/interoperability/utils.ts#L162
- https://github.com/LiskHQ/lisk-sdk/blob/89e7504ef5eb6183aefe576a93be3d6052e56038/framework/src/modules/interoperability/base_interoperability_internal_methods.ts#L636
- https://github.com/LiskHQ/lisk-sdk/blob/89e7504ef5eb6183aefe576a93be3d6052e56038/framework/src/modules/interoperability/base_interoperability_internal_methods.ts#L407
- https://github.com/LiskHQ/lisk-sdk/blob/89e7504ef5eb6183aefe576a93be3d6052e56038/framework/src/modules/interoperability/base_interoperability_internal_methods.ts#L373
- https://github.com/LiskHQ/lisk-sdk/blob/89e7504ef5eb6183aefe576a93be3d6052e56038/framework/src/modules/interoperability/base_interoperability_internal_methods.ts#L361
- https://github.com/LiskHQ/lisk-sdk/blob/89e7504ef5eb6183aefe576a93be3d6052e56038/framework/src/modules/interoperability/base_interoperability_internal_methods.ts#L272

### Which version(s) does this affect? (Environment, OS, etc...)

`v6.0.0-beta.1`

**Comment by Phanco** [comment]
Just a footnote, Certificate in ccm are parsed as bytes, thus it would not be validated by the fix at issue #8475.
