### ISSUE TITLE
`registerValidatorKeys` implementation in Validator module returns boolean

### ISSUE THREAD

**Issue by mitsuaki-u** [LiskHQ/lisk-sdk#8564]
### Expected behavior

`registerValidatorKeys` implementation in Validator module differs slightly from LIP. 

See comment: https://github.com/LiskHQ/lisk-sdk/pull/8525#discussion_r1222745376

### Actual behavior

returns `true` for success and `false` when invalid key. in the LIP it merely throws an error for anything besides success. 

### Steps to reproduce

Check Validators module `registerValidatorKeys`  versus LIP 

### Which version(s) does this affect? (Environment, OS, etc...)

6.0

**Comment by mitsuaki-u** [comment]
CC: @sergeyshemyakov

**Comment by mosmartin** [comment]
@mitsuaki-u would you kindly add a link to the LIP (part that it should align with)? 🙏
