### ISSUE TITLE
Failed asset validation during forging of next block does not reject the transaction

### ISSUE THREAD

**Issue by tezhm** [LiskHQ/lisk-sdk#8576]
### Expected behavior

Transaction is rejected from pool.

### Actual behavior

Node gets stuck in loop re-validating the already failed transaction when forging next block.

### Steps to reproduce

```ts
export interface ExampleAssetPayload{
    blockHeight: number;
}

export class ExampleAsset extends BaseAsset<ExampleAssetPayload> {
    ...

    public validate(context: ValidateAssetContext<ExampleAssetPayload>): void {
        const { header } = context;

        if (asset.blockHeight < header.height)
        {
            throw new Error("Block height cannot be in the past");
        }
    }
```

Let's say the current block height is 10. If I submit a transaction with above asset and set `blockHeight` to 10, the transaction will successfully submit to the pool because `10 < 10 == false`. But when the next block is forged, the header for that block is passed into the validation method with new height of 11 which results in `10 < 11 == true` thus failing validation.

### Which version(s) does this affect? (Environment, OS, etc...)

Debian buster, lisk-sdk 5.2.2

**Comment by shuse2** [comment]
On v5 of SDK, `validate` function should be used for the check which doesn't depend on the state.
This behavior is changed on v6 with name change to `verify`. Please use v6 which is currently on `beta` and if there is still a problem, feel free to open a new issue 🙇
