### ISSUE TITLE
Plugin is not properly loading in child process

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#8629]
### Expected behavior

When a plugin is loaded as childProcess it should be able to expose the registered endpoints.

### Actual behavior

When a plugin is loaded as childProcess it is not able to expose its registered endpoint.

### Steps to reproduce

- Load a plugin as a child process and check registered endpoints from the plugin, you will see error like `Request 'chainConnector_getSentCCUs' is not registered to bus.`

### Which version(s) does this affect? (Environment, OS, etc...)

`v6.0.0-beta.2`

Could be related to https://github.com/LiskHQ/lisk-sdk/pull/8513

**Comment by mosmartin** [comment]
@ishantiw How does one load a plugin to a child process?

**Comment by ishantiw** [comment]
When we call `app.registerPlugin` we can specify it whether to load it as child process or not. For example, https://github.com/LiskHQ/lisk-sdk/blob/4931464581afa4c0c712f312e217e8fb51452d93/examples/pos-mainchain/src/commands/start.ts#L123
