### ISSUE TITLE
Transactions stuck in the transaction pool

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-sdk#8634]
### Expected behavior
Transactions with a proper nonce should be included in a block
### Actual behavior
Currently if you send a transaction with a nonce higher than your account nonce it's marked as pending which is correct. However if you send a transaction with a nonce that is equal to your account nonce, while the higher nonce transaction is still in the pool, the transaction doesn't get included in a block. The way to unstuck the proper nonce transaction is to send it again with a higher fee.
### Steps to reproduce

- create a fresh account, send a transaction from that account with `nonce = 1`
- send a second transaction with `nonce = 0` 
- observe the pending transactions.
- send a transaction with `nonce = 0`, but with a higher fee, to unstuck

### Which version(s) does this affect? (Environment, OS, etc...)

SDK 6.0.0-beta.1

**Comment by mosmartin** [comment]
Hi @przemerr I have followed the defined steps to reproduce the issue with no success (good thing 😉). I created both txns (please see below) and a few seconds later, both had been successfully processed. When I checked the txn pool, it was empty and did not have to send another txn to `unstuck` any pending/stuck txn.
```bash
./bin/run endpoint invoke txpool_getTransactionsFromPool | jq .
[
  {
    "module": "token",
    "command": "transfer",
    "params": "0a0804000000000000001080c2d72f1a14b2f75b6968f687b495b69e1fec51d06fa8ae9d8d220a73656e6420746f6b656e",
    "nonce": "1",
    "fee": "100000000",
    "senderPublicKey": "308df5902f1a88c6d4eb8ddbe5e60a1bac043bb936832ec2d7edc314d2320be2",
    "signatures": [
      "bf50785effd42496f12bd68a5fa9a0b92ecc64bd7c151224955c29ac86611f0fbc30995af4d6ff616934fe92731f92f0a00325a9b1cb33fbecaef2db8a735108"
    ],
    "id": "f568be30a4e8820416ba9fef5f0bb64a052acf857302ca327bfab509719b10fa"
  },
  {
    "module": "token",
    "command": "transfer",
    "params": "0a0804000000000000001080c2d72f1a14b2f75b6968f687b495b69e1fec51d06fa8ae9d8d220a73656e6420746f6b656e",
    "nonce": "0",
    "fee": "100000000",
    "senderPublicKey": "308df5902f1a88c6d4eb8ddbe5e60a1bac043bb936832ec2d7edc314d2320be2",
    "signatures": [
      "81d3000031ec2b3d5062d71c4c731f9d1a29637db5d84b989de440e4efcbad95d5aa89a8307c64b7d48d116930b05921bac42dfe97e3a6f905b7e44253e0d00d"
    ],
    "id": "e30c9ecf9c9a31ddee3c20ff68c871d6df4be4d51bd38206cee2eb3d98f995fd"
  }
]

# few moments later, no pending/stuck txn
./bin/run endpoint invoke txpool_getTransactionsFromPool | jq .
[]
```

Is it possible to have another look and let me know. Will be glad to have another look if this persists.

**Comment by przemerr** [comment]
Hi @mosmartin thanks for taking a look :) , I'll test the behaviour once the new betanet is live, since I was testing it on a live network.. and also there were changes to the TX pool between beta.1 -> beta.4

**Comment by przemerr** [comment]
@mosmartin could not reproduce it with the current betanet 👍 You can close the issue 😇

**Comment by mosmartin** [comment]
Thanks @przemerr for the feedback. Super appreciated 🌝
