### ISSUE TITLE
Duplicate constants for Lisk32 charset

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#8653]
### Description

The [`CHARSET`](https://github.com/LiskHQ/lisk-sdk/blob/89e7504ef5eb6183aefe576a93be3d6052e56038/elements/lisk-cryptography/src/address.ts#L19) and [`LISK32_CHARSET`](https://github.com/LiskHQ/lisk-sdk/blob/89e7504ef5eb6183aefe576a93be3d6052e56038/elements/lisk-cryptography/src/address.ts#L121) constants are equivalent and are both used in the same set of functions for validation and encoding/decoding Lisk32 addresses. The code should be simplified to define and use only one constant for the valid set of characters.

### Which version(s) does this affect? (Environment, OS, etc...)

`v6.0.0-beta.2`

**Comment by bobanm** [comment]
I have addressed this on my own initiative in draft PR #7928 

Can we close this issue as a duplicate of #7927, and assign that issue to sprint?
