### ISSUE TITLE
Update message recovery command verification

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#8721]
### Description

Update message recovery init command verification and execution based on LIP PR https://github.com/LiskHQ/lips/pull/399

**Verification:** Add additional cheap check in verification of message recovery command to ensure that the indices of all provides messages are in the `range [0, ..., outboxSize -1]`
**Execution:** Emit `EVENT_NAME_INVALID_SMT_VERIFICATION`

### Acceptance Criteria

- Should have all the unit tests

### Additional Information

- Related LIP https://github.com/LiskHQ/lips/blob/main/proposals/lip-0054.md#message-recovery-command

**Comment by AndreasKendziorra** [comment]
> **Execution**: Emit `EVENT_NAME_INVALID_SMT_VERIFICATION`

Maybe it's clear from the first sentence, but also `SMTVerify` must be moved from verification to execution.

**Comment by Phanco** [comment]
For the `Execution` part, it has been well implemented by @mitsuaki-u 's PR 
https://github.com/LiskHQ/lisk-sdk/pull/8816
