### ISSUE TITLE
Fix a bug in state recovery initialization command 

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#8722]
### Description

- Fix a bug in state recovery initialization command as it was accepting a chain account with status "registered" which should not be the case.
- emit `EVENT_NAME_INVALID_SMT_VERIFICATION` in execution on failure
- Move SMTVerify from verification to execution

Related LIP PR https://github.com/LiskHQ/lips/pull/399

### Which version(s) does this affect? (Environment, OS, etc...)

`v6.0.0-beta.4`

**Comment by AndreasKendziorra** [comment]
The two related commits in the LIPs repository are these ones:

- https://github.com/LiskHQ/lips/pull/399/commits/ace427cd8a7f712091f569a5d0241369dd1a9cdc
- https://github.com/LiskHQ/lips/pull/399/commits/8f431e0344134034d7f2e3e158c26ab3ce4a9c8b
