### ISSUE TITLE
`_verifyLivenessConditionForRegisteredChains` & `verifyLivenessConditionForRegisteredChains` have duplicated code

### ISSUE THREAD

**Issue by sitetester** [LiskHQ/lisk-sdk#8731]
### Description

// framework/src/modules/interoperability/mainchain/commands/submit_mainchain_cross_chain_update.ts
```
private _verifyLivenessConditionForRegisteredChains(
	context: CommandVerifyContext<CrossChainUpdateTransactionParams>,
): void {
	const certificate = codec.decode<Certificate>(certificateSchema, context.params.certificate);
	validateCertificate(certificate);

	if (context.header.timestamp - certificate.timestamp > LIVENESS_LIMIT / 2) {
		throw new Error(
			`The first CCU with a non-empty inbox update cannot contain a certificate older than ${
				LIVENESS_LIMIT / 2
			} seconds.`,
		);
	}
}
```

vs

// framework/src/modules/interoperability/utils.ts
```
export const verifyLivenessConditionForRegisteredChains = (
	ccu: CrossChainUpdateTransactionParams,
	blockTimestamp: number,
) => {
	const certificate = codec.decode<Certificate>(certificateSchema, ccu.certificate);
	validateCertificate(certificate);

	const limitSecond = LIVENESS_LIMIT / 2;
	if (blockTimestamp - certificate.timestamp > limitSecond) {
		throw new Error(
			`The first CCU with a non-empty inbox update cannot contain a certificate older than ${limitSecond} seconds.`,
		);
	}
};
```

These two functions have same logic in their bodies. We can merge them together with a modified signature like this: 

```
export const verifyLivenessConditionForRegisteredChains = (
	blockTimestamp: number,
        certificate: Buffer)
) => {
```

### Motivation
- There is no point to have separate functions for same logic. If we need to change something, either we will do it at both places or it would result in inconsistency. 
- Separate functions means separate test cases (along with preparing their fixtures). It's a waste of time & requires extra effort on behalf of author & reviewer to manage things.

### Additional Information
[Already mentioned](https://github.com/LiskHQ/lisk-sdk/pull/8726)

**Comment by Phanco** [comment]
Duplicate issue, https://github.com/LiskHQ/lisk-sdk/issues/8552.

Can close this issue
