### ISSUE TITLE
Update generic message signing

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#8775]
### Description

- Update `signMessageWithPrivateKey` and `verifyMessageWithPublicKey` with the protocol defined in the [LIP PR](https://github.com/LiskHQ/lips/pull/429)

### Acceptance Criteria
- Check commander `message:sign` and `message:verify` commands
- Update unit tests and remove unnecessary functions from cryptography

### Additional Information

Related PR: https://github.com/LiskHQ/lips/pull/429

**Comment by bobanm** [comment]
Resolved in PR #8805
