### ISSUE TITLE
Unable to decode generatorFeeProcessed event data

### ISSUE THREAD

**Issue by sameersubudhi** [LiskHQ/lisk-sdk#8779]
### Expected behavior

`codec.decode` should be able to decode the event data when the correct schema is supplied.

### Actual behavior

`codec.decode` fails to decode data for `generatorFeeProcessed` event from the `fee` module.

### Steps to reproduce

Execute the script attached below.

### Which version(s) does this affect? (Environment, OS, etc...)

v6.0.0-beta.5

### Additional Information

Execute the following script.

```js
const events = [
	{
		data: '0a14fc18da54f6ce01bf31195548460361dfdb83c20512142d297229e6c4f5285c8aed63aa27c706bebd50af18a0810a20a0',
		index: 4,
		module: 'fee',
		name: 'generatorFeeProcessed',
		topics: [
			'3753eb313e365972702c2d3501c2a8e58a380e93280433d1dfe9d3e0dc5340b3',
			'fc18da54f6ce01bf31195548460361dfdb83c205',
			'2d297229e6c4f5285c8aed63aa27c706bebd50af',
		],
		height: 78788,
	},
];

const schemas = {
	fee_generatorFeeProcessed: {
		$id: '/fee/events/generatorFeeProcessed',
		type: 'object',
		required: ['senderAddress', 'generatorAddress', 'burntAmount', 'generatorAmount'],
		properties: {
			senderAddress: {
				dataType: 'bytes',
				format: 'lisk32',
				fieldNumber: 1,
			},
			generatorAddress: {
				dataType: 'bytes',
				format: 'lisk32',
				fieldNumber: 2,
			},
			burntAmount: {
				dataType: 'uint64',
				fieldNumber: 3,
			},
			generatorAmount: {
				dataType: 'uint64',
				fieldNumber: 4,
			},
		},
	},
};

const { codec } = require('@liskhq/lisk-codec');

events.forEach(event => {
	try {
		const eventDataSchema = schemas[`${event.module}_${event.name}`];
		codec.decodeJSON(eventDataSchema, Buffer.from(event.data, 'hex'));
	} catch (error) {
		console.error(error.stack);
		console.log(JSON.stringify(event, null, 2));
	}
});
```

**Comment by bobanm** [comment]
This issue only happens in dry run, when in non-strict mode, and when provided transaction fee is insufficient. This very unique use case is not something we would ever see in production. I would say that the system is working as expected, but a user here is abusing the system by doing a type of dry run which doesn't make sense.

Nevertheless, we don't want to confuse users by providing non-decodable event data. As agreed with @shuse2, I pushed a PR #8822 which makes non-strict dry run a little bit more strict, so now it rejects transactions with insufficient fees.
