### ISSUE TITLE
Throw error from getAuthAccount when account doesn't exist

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#8843]
### Description

The getAuthAccount method [implementation](https://github.com/LiskHQ/lisk-sdk/blob/89e7504ef5eb6183aefe576a93be3d6052e56038/framework/src/modules/auth/method.ts#L19-L28) differs from [LIP-0041](https://github.com/LiskHQ/lips/blob/be768c4fda2df6c46caefe710688314f47d8ceb8/proposals/lip-0041.md#getauthaccount). The LIP says the implementation should raise an exception when no account exists. The implementation returns a default account when no account exists.

### Which version(s) does this affect? (Environment, OS, etc...)

`v6.0.0-beta.6`

**Comment by bobanm** [comment]
As agreed with @shuse2, in this case it makes more sense to keep the implementation as it is, and align the LIP. That would align behavior of `getAuthAccount()` with behavior of [`getAvailableBalance()`](https://github.com/LiskHQ/lips/blob/be768c4fda2df6c46caefe710688314f47d8ceb8/proposals/lip-0051.md#getavailablebalance) and [`getEscrowedAmount()`](https://github.com/LiskHQ/lips/blob/be768c4fda2df6c46caefe710688314f47d8ceb8/proposals/lip-0051.md#getescrowedamount), where LIP-0051 specifies that for a non-existing key the system should return `0` as the default value.

I opened the [issue in LIP repo](https://github.com/LiskHQ/lips/issues/452).
