### ISSUE TITLE
Error: Specified key *** does not exist

### ISSUE THREAD

**Issue by EtherForge** [LiskHQ/lisk-sdk#8882]
![2023-08-19_11-19-56](https://github.com/LiskHQ/lisk-sdk/assets/142614303/d960b857-41f5-4741-b503-922e63dd8238)

**Comment by EtherForge** [comment]
I have blurr some points just in case.

**Comment by EtherForge** [comment]
I think, something wrong with ChainID. What can be wrong, if it's true?

**Comment by przemerr** [comment]
@EtherForge Try installing the latest version of the commander, the issue you're facing should be resolved
`npm install lisk-commander@6.0.0-beta.7 -g`
