### ISSUE TITLE
Error: Stored total supply conflicts with computed supply.

### ISSUE THREAD

**Issue by EtherForge** [LiskHQ/lisk-sdk#8884]
![2023-08-19_22-08-07](https://github.com/LiskHQ/lisk-sdk/assets/142614303/aa57f488-e85b-41ea-9d9e-a4f9fd25a235)

**Comment by przemerr** [comment]
@EtherForge you have some old blockchain data in the `.lisk/EtherForge`
delete the `EtherForge` folder

**Comment by EtherForge** [comment]
> @EtherForge you have some old blockchain data in the `.lisk/EtherForge` delete the `EtherForge` folder

Thanks!
