### ISSUE TITLE
Is it possible to change the lsk... in the wallet address to something else?

### ISSUE THREAD

**Issue by EtherForge** [LiskHQ/lisk-sdk#8885]
Hello! How can I (and can I at all) change the prefix of the Lisk wallet address? That is, wallet addresses start with lsk..., and can I replace lsk with my own letters? Thank you.

**Comment by EtherForge** [comment]
@przemerr

**Comment by przemerr** [comment]
Yes, it's possible, it's just a prefix, but i don't currently see an easy way to bootstrap with a different prefix.
