### ISSUE TITLE
BLS operations involving secret data are not constant time

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#8911]
### Description
Partially resolved in PR #8487, PR #8829, PR #8877, and PR #8881. 
However, the code still has calls to SecretKey.fromBytes, which, as specified in the issue, is vulnerable to timing attacks as specified in the original issue https://github.com/LiskHQ/lisk-sdk/issues/8449

### Which version(s) does this affect? (Environment, OS, etc...)
6.0.0-beta.7

**Comment by Madhulearn** [comment]
PR on external repo.
[[fix: SecretKey.fromBytes perform constant time comparison to zero bytes by has5aan · Pull Request #108 · ChainSafe/blst-ts](https://github.com/ChainSafe/blst-ts/pull/108)](https://github.com/ChainSafe/blst-ts/pull/108)
