### ISSUE TITLE
Update supportAllNFTs method of NFT module

### ISSUE THREAD

**Issue by Incede** [LiskHQ/lisk-sdk#8972]
### Description

The supportAllNFTs method of NFT module should first check if ALL_SUPPORTED_NFTS_KEY key is already present in the supported NFTs substore per [LIP PR](https://github.com/LiskHQ/lips/pull/477)

### Acceptance Criteria
- All the relevant changes from the LIP PR must be incorporated
- Relevant unit tests should be updated

### Additional Information
[LIP PR](https://github.com/LiskHQ/lips/pull/477)

**Comment by has5aan** [comment]
The suggested change is already aligned with [current implementation](https://github.com/LiskHQ/lisk-sdk/blob/2d04e23b5b172a7b84cdad2669b985a51156e671/framework/src/modules/nft/method.ts#L690-L694).
