### ISSUE TITLE
Dynamic Block Reward Computation incorrect in case validators number is small

### ISSUE THREAD

**Issue by gkoumout** [LiskHQ/lisk-sdk#9024]
The dynamic block rewards module calculates the block rewards assumming that the number of active validators in each round is *exactly* `NUMBER_ACTIVE_VALIDATORS` (e.g., 101 in the mainchain). 

### Expected behavior

We should take care of the case that in current round the number of eligible validators are less than  `NUMBER_ACTIVE_VALIDATORS` (e.g., 101 in the mainchain). This might very well happen after the next hard-fork since initially old validators will be banned until they register a BLS key. So a given round, might have much fewer validators. 

### Actual behavior

In[ `getStakeRewardActiveValidators` function](https://github.com/LiskHQ/lisk-sdk/blob/2d04e23b5b172a7b84cdad2669b985a51156e671/framework/src/modules/dynamic_rewards/utils.ts#L26), we define 

`	const numberOfActiveValidators = posMethod.getNumberOfActiveValidators(context);`

This always returns `NUMBER_ACTIVE_VALIDATORS` (e.g., 101 in the mainchain), even if the number of validators in current round is smaller, since PoS module state store is agnostic to the number of current active validators. Instead, the number of active validators should be get from the validators module

### Suggested modification

- Make the number of active validators an argument for `getStakeRewardActiveValidators`. The function would look like:

```
export const getStakeRewardActiveValidators = (
	context: ImmutableMethodContext,
	numberOfActiveValidators: bigint,
	defaultReward: bigint,
	minimalRewardActiveValidators: bigint,
) => {
	return (
		BigInt(numberOfActiveValidators) * (defaultReward - minimalRewardActiveValidators)
	);
};
```

(In fact, even the context does not seem to be needed as an argument in this case).

 - Modify the call to `getStakeRewardActiveValidators` from [`getDefaultBlockReward` function](https://github.com/LiskHQ/lisk-sdk/blob/2d04e23b5b172a7b84cdad2669b985a51156e671/framework/src/modules/dynamic_rewards/module.ts#L248) as follows:

Replace [here](https://github.com/LiskHQ/lisk-sdk/blob/2d04e23b5b172a7b84cdad2669b985a51156e671/framework/src/modules/dynamic_rewards/module.ts#L283C39-L283C69)

```
		const stakeRewardActiveValidators = getStakeRewardActiveValidators(
			context,
			this._posMethod,
			defaultReward,
			minimalRewardActiveValidators,
		);
```

by 

```
                numberActiveValidators = len([item for item in validatorParams.validators if item.bftWeight > 0])
		const stakeRewardActiveValidators = getStakeRewardActiveValidators(
			context,
			numberActiveValidators,
			defaultReward,
			minimalRewardActiveValidators,
		);
```

(here I am using pythonic syntax, but hopefully you get the point).

- Add unit tests to check the calculated rewards in case of small set of active validators (e.g., only 8 active) where it is easy to caluclate values at hand and verify results.

**Comment by przemerr** [comment]
so i was right in the end? 😝https://github.com/LiskHQ/lisk-sdk/issues/8502

**Comment by shuse2** [comment]
Could be 😓  Maybe current behavior is logically correct, but not something we wanted...

**Comment by gkoumout** [comment]
Indeed the inflation should not depend on the number of eligible validators. So total rewards per round (of length 103) should be 103 (assumming no missed blocks) no matter how many eligible validators we have.. Thanks @przemerr!
