### ISSUE TITLE
Fix --output flag in commander

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#9035]
### Expected behavior

`--output` should work with absolute or relative path from the user.

### Actual behavior

When using `keys:create` command with `output` flag with absolute path, it doesn't work, similar to the issue https://github.com/LiskHQ/lisk-sdk/issues/9013

**Note:** Check other commands also if this bug exists

### Steps to reproduce

- Run `keys:create` with `--output` flag

### Which version(s) does this affect? (Environment, OS, etc...)

`6.0.0-rc.2`

**Comment by Incede** [comment]
Works both for relative and absolute path, also with tilde `~`.
