### ISSUE TITLE
Increase the IPC timeout

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#9049]
### Description

Increase the IPC timeout to potentially 30s after checking on recommended machine spec

### Motivation

Some operation through the IPC takes longer than 3s in the mid spec machine (like decrypt/hash onion), and we want to be able to return proper response

### Additional Information
* We should test in the remote node what time is most suitable
* Check on api-cilent and server/client on the framework

**Comment by przemerr** [comment]
@shuse2 if I may add, there's also the same problem with launching plugins for example the PoM plugin, to make it load I had to increace this value
https://github.com/LiskHQ/lisk-sdk/blob/0f1296c62585f26f3291f3e1a01aa757801f93f0/framework/src/controller/controller.ts#L332-L335

and to authorize it i had to increase this
https://github.com/LiskHQ/lisk-sdk/blob/2d04e23b5b172a7b84cdad2669b985a51156e671/framework/src/controller/constants.ts#L15-L20

 please check on a fairly low speced machine

**Comment by bobanm** [comment]
To decrease the time required for hash onion calculations by orders of magnitude, we need to implement improvement from #8332
