### ISSUE TITLE
Validator consecutiveMissedBlock return value 1 (false positive)

### ISSUE THREAD

**Issue by Gr33nDrag0n69** [LiskHQ/lisk-sdk#9080]
### Expected behavior

Validator consecutiveMissedBlock return value 1 only when it's true.

### Actual behavior

It doesn't.

### Steps to reproduce

Poll the value of current list of active validator actively to see the bug appear and dissapear randomly.

### Which version(s) does this affect? (Environment, OS, etc...)

OS: Ubuntu 20.04
Version: Lisk-Core 4.0.0-rc.6

### Notes

* przemer had point me out to this [issue](https://github.com/LiskHQ/lisk-sdk/issues/9040) as possibly linked. 
* I created this issue on this repo (lisk-sdk) but I'm not sure if it would belong to [https://github.com/LiskHQ/lisk-core/issues](https://github.com/LiskHQ/lisk-core/issues) instead.

**Comment by bobanm** [comment]
Yes, the behavior you observed is a consequence of the same bug which caused #9040 and #9075.

This will be resolved once #9088 is merged.

Thanks for reporting 👍🏻
