### ISSUE TITLE
Lisk commander transaction schema doesn't allow an array to be the last field

### ISSUE THREAD

**Issue by corbifex** [LiskHQ/lisk-sdk#9130]
### Expected behavior
In Lisk Commander, the ability to create a transaction with an array field should not be restricted to any specific position.
The expected behavior is for an array to be accepted in any position in a command schema.

### Actual behavior
Currently, an array is only accepted when it is the first field.

### Steps to reproduce
In the NFT example, run the following command:

`./bin/run transaction create testNft mintNft 10000000`

![image](https://github.com/LiskHQ/lisk-sdk/assets/7694695/ac743eca-16d0-4e76-86a5-efdcce24bc2a)

**Comment by przemerr** [comment]
isn't this related?
https://github.com/LiskHQ/lisk-sdk/issues/9105

**Comment by corbifex** [comment]
Probably, I now see it's possibly fixed by #9118 😅

**Comment by shuse2** [comment]
Fixed by #9118
